BOINC/boinc

- .travis.yml
- Makefile.am
- configure.ac
- samples/Makefile.am
- samples/vboxmonitor/Makefile
- By default apps won't be built. In order to build the example apps use --enable-apps as option to ./configure. Not all apps are supported as some need further external libraries.
- Also fix a copy/paste error in the vboxmonitor Makefile
> BUILD: add example apps into the build process

- lib/gui_rpc_client.cpp
boinccmd now gives the correct error message (unauthorized) when not authorized, instead of saying 'Error -1'.
> Fixed error message in boinccmd

- samples/vboxwrapper/vboxwrapper.cpp
Typo where vboxwrapper was accepting `--ncpus` instead of `--nthreads` like it should.
> vboxwrapper ncpus -> nthreads bug

- py/Boinc/setup_project.py
- tools/make_project
I added two new options to `tools/make_project`:
```
--no_db              don't create the database
--project_host       default: $HOSTNAME
```
These allow one to build the project on a different system than the one which will ultimately run it. In this case the build system doesn't need to be connected to the mysql database nor does it need to have the same hostname. One example use-case (mine) is to allow creating a BOINC server Docker image where the build happens in a different container than the one running the project.
> new `make_project` options which allow building and running project on different systems

- clientgui/BOINCGUIApp.cpp
- clientgui/BOINCGUIApp.h
- clientgui/DlgOptions.cpp
- clientgui/DlgOptions.h
- clientgui/MainDocument.cpp
- New commanline option -nd (short) and --no-daemon (long).
- New option in Preferences Dialog "Run daemon?"
So after Manager start daemon will be run only if commandline option --no-daemon is off and option "Run daemon?" is on. Otherwise daemon will not be run.
> Fix issue #79: Optionally not start the daemon

- html/inc/prefs.inc
* tra() is defined in translation.inc
* prefs.inc didn't yet include it in any way
> Add missing include

- clientgui/browser.cpp
[clientgui/browser.cpp:375]: (error) Width 4096 given in format string (no. 1) is larger than destination buffer 'cookie_value[4096]', use %4095s to prevent overflowing it.
[clientgui/browser.cpp:575]: (error) Width 4096 given in format string (no. 1) is larger than destination buffer 'cookie_value[4096]', use %4095s to prevent overflowing it.
> cppcheck: fix 2 reports

- dcapi/condor/condor_utils.c
- dcapi/condor/tc.c
- dcapi/local/local_utils.c
(warning) Storing fgetc() return value in char variable and then comparing with EOF
+ optimize a bit by moving the instruction "buf[i]= '\0';" inside the loop, outside from it.
(only non example files have been changed)
> cppcheck: fix 1 kind of reports

- html/inc/account.inc
- html/inc/util.inc
- html/user/create_profile.php
When also including an older recaptchalib.php this function gets redefined. Since it is only a wrapper function and only used within BOINC, renaming it is safe.
> Web: rename recaptcha_get_html() because of a conflict with Drupal

- lib/sched_msgs.cpp
- lib/sched_msgs.h
- sched/file_upload_handler.cpp
Add logging to the code introduced in ce00365 to eventually get to know the frequency and cause of reuploads. Also check if the file upload handler can write into the upload_dir at startup. This should more clearly detect permission issues.
> file upload handler: add logging and error checking

- sched/assimilate_handler.h
- sched/assimilator.cpp
- sched/sample_assimilator.cpp
- sched/sample_dummy_assimilator.cpp
- sched/script_assimilator.cpp
- sched/single_job_assimilator.cpp
The assimilator handler can now pass unknown arguments to the project specific handler and display usage information for those custom options.
Projects that have there own assimilators need to implement the assimilate_handler_init() and assimilate_handler_usage() function. For examples see sample_assimilator.cpp or script_assimilator.cpp
I also added some checks for missing arguments and clarified some error messages.
I'm merging this myself when I'm done with it.
> Daemons: enhance assimilator framework

- sched/start
If the command of a task or daemon wants to use shell features like |, > or < the start script uses a shell encapsulation (sh -c) to start the process.
This had two problems:
1. It also started a shell if the command contained ' or " and didn't check if |, > or < where escaped or used within quotes (e.g. as part of a regular expression). The new mechanism uses the python module shlex to prepare the arguments for the execvp() call. It also detects if a shell encapsulation is needed and informs the user about it.
2. The actual daemon or task is a subprocess of the shell and was not terminated with the parent. The new signal propagation mechanism properly kills the daemon or task if the shell receives a signal to do so (e.g. by stop).
> Server: fix behaviour of start script

- html/inc/boinc_db.inc
Specify a $fallback_mode that is used for read-only DB connections:
0: default, use db_user if no replica_db_user is specified,
first try replica_db_host (if specified) then db_host
1: only use replica_db_user, first try replica_db_host then db_host
2: only use replica_db_user, only try replica_db_host
can be set projectwide using <replica_fallback_mode> in config.xml
> Web: introduce fallback_mode when using a replica DB

- html/inc/user.inc
The simplexml_load_file() call fails if allow_url_fopen is set to false and does not retrieve the statistics for the user. Curl is assumed to be available instead, if not, no information is shown to the user.
> Web: use curl in get_other_projects() if fopen() is disallowed

- INSTALL
Fixed the typo in INSTALL when using the ./configure command. This caused an
error when trying to configure BOINC.
> [1153] typo in file INSTALL

- client/hostinfo_unix.cpp
Previous merged PR: https://github.com/BOINC/boinc/pull/1453
Apologies. My initial code didn't close the connections to the X
displays after opening them. I had thought that falling out of scope
would close the connection automatically. However, thanks to a bug
report by Dan Merillat that I was able to replicate, I now know better:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812835
This simple adjustment closes the connection to the display (if a
connection succeeded in the first place; if XOpenDisplay() failed, it
returns NULL and there is no connection). Testing on my end shows that
this resolves the issue of the boinc client piling up new connections to
X servers.
> XSS Idle Detection Bugfix (XCloseDisplay)

- samples/vboxwrapper/vboxwrapper.cpp
Prior to this if you dumped an error code in `completion_trigger_file` it was always reported to BOINC as exit status = 1. 
Should be straight forward but someone should double check this as I've neither compiled nor tested this fix.
> VBOX: fixed error code not being reported

- clientgui/AdvancedFrame.cpp
The updated version of the shortcut for "select computer", users with multiple machines running boinc may like it.
Line 741: removed to be the same indent as the `#ifdef` it belongs to
> added a shortcut for "select computer", try 2

- configure.ac
Since curl is needed for the libraries and the libraries are needed for everything else check for libcurl by default.
> BUILD: fix curl detection

- generate_svn_version.sh
If building from detached head (eg. checkout a tag), remote branch name detection will fail. In this case, use `origin` as hard coded default.
> Fixed generate_svn_version.sh when building on detached head

- _autosetup
_autosetup claims that you can set `LIBTOOLIZE` to libtoolize's path, but this is not implemented. As homebrew use `glibtoolize` instead of `libtoolize`, this make it impossible to build on OS X.
This patch implements that support, and also changed mixed tab/space indentation to spaces.
> Add environment variable detection support to _autosetup

- _autosetup
Continued from #1498 
This PR is made by applying @f8l's patch in the original PR. I also removed gmake detection as it is expected that the user should set MAKE to its path instead. The `echo >/dev/null` is also removed and replaced by inverting the if conditions instead.
From my testing, it seems that in my original PR user can specify application name in `$PATH` but this one an absolute path is required. As the error messages already specified that the variables should be set to its path I consider this behavior to be correct as well.
> Use sh to detect applications in _autosetup

- py/Boinc/boincxml.py
- tools/make_project
- tools/project.xml
Currently even if you don't give the `--test_app` option to `make_project`, you still get `example_app` in your `project.xml`, which means it goes in the database and is displayed under "Applications" on the website. This makes it so it only goes in `project.xml` if you actually requested it.
> Don't add example_app to project.xml unless requested

- samples/wrapper/wrapper.cpp
* add a feature to use the phrase "boinc_resolve(filename)" in the <command_line> option of job.xml this gets passed through boinc_resolve_filename(filename)
* fix macro substitution which was broken after a reshuffle of boinc_init_options()
* fix do_zip_outputs() by resolving the filename before checking for existence; it's possible it is a softlink
* add a feature to rename/move output files; use this when output files are large and softlinked so they are not copied within the project directory
* recognize the DEBUG flag and print debug output
> Wrapper improvements

- client/gpu_nvidia.cpp
On Debian only the versioned object can be opened. It usually is a symlink to the actual file.
Please review and merge into the 7.6 branch.
> Client: fix nvidia_driver_version dlopen()

- client/acct_mgr.cpp
- client/log_flags.cpp
- lib/parse.cpp
Ironically, should the user specify an invalid XML tag in configuration, BOINC will write a log message containing that tag unescaped and unclosed. Needless to say, it breaks XML parsing instantly. This patch auto-closes such tags in the log messages.
> Work around invalid XML in logs

- clientgui/BOINCBaseView.cpp
- clientgui/BOINCBaseView.h
- clientgui/BOINCGUIApp.cpp
- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
When building BOINC with `wxUSE_STL=1` there are compiler errors (#1515) because the implicit conversion to `const char*` and `const wxChar*` is deactivated. The solution was to replace `char*` or `wxChar*` by `wxString`. At some point in the stack, the `wxChar*` were implicitly converted to `wxString` again, so this seems like the obvious best way.
One advantage is that `wxString` owns the memory, so we know it always points to valid memory.
> Use wxString where necessary

- lib/parse.cpp
If `realloc` fails, the old pointer is not freed. We should not overwrite the old pointer in this case, otherwise we have a memory leak.
We also have to free previously allocated memory in the case of reallocation failure.
> Prevent memory leak on reallocation failure

- drupal/sites/default/boinc/modules/boincimport/boincimport.module
If no users are ignored then the dbquery for users fails. Changed array initialization to array(0), which fixes the dbquery and the bug.
BOINC user import module has a bug where if there are no ignored users, the subsequent database query will fail. To fix this, the ignored_user_list array is initialized to zero.
> Drupal: Fixed bug in boinc user import module. 

- clientgui/res/virtualboxicon.xpm
to avoid a warning when transforming into a string.
I remember to have contributed these kind of compile-time-optics patches a lot some long time ago :) The Debian build demons all publish their runs here:
https://buildd.debian.org/status/fetch.php?pkg=boinc&arch=amd64&ver=7.6.31%2Bdfsg-6&stamp=1460045578
> virtualbox icon should be const char*

- py/Boinc/setup_project.py
- tools/make_project
There is a bug when creating a project, In create_project_dirs(), if a directory cannot be created due to permissions or any other reason, then the original code simply uses a try-except block with "pass". This means even if the base project directory cannot be created, the code continues. The result is that a bit later when the the program tries to [chmod 02770 some directories](https://github.com/BOINC/boinc/blob/master/py/Boinc/setup_project.py#L291), create_project_dirs() will fail in an ungraceful way. The chmod lambda-map() is not set in a try-except block.
My solution is to re-write the mkdir2 function to be smarter. Now it tries to create the directory. And then it checks if the directory already exists. Finally, it raises an SystemExit exception if both fail. This means the …
> bug in make_project and additional help for enduser

- lib/network.cpp
As described in PR #1531 the original error message does not provide enough information. This also fixes that no unrelated error message is shown.
> Lib: tweak error messages

- drupal/sites/default/boinc/themes/boinc/templates/views-view-field--boinc-account-tasks-all--id.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/views-view-field--boinc-host-tasks-all--id.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/views-view-field--boinc-workunit-tasks-all--id.tpl.php
Drupal: Replaced span tags with div tags to fix firefox not word-wrapping. Fixes DBOINCP-244
> Drupal: bug fix-firefox word wrapping of task names

- samples/vboxwrapper/vbox_mscom_impl.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vboxjob.cpp
- samples/vboxwrapper/vboxjob.h
- samples/vboxwrapper/vboxwrapper.cpp
Added an option `<boot_iso/>` to `vbox_job.xml` which puts the ISO first in the boot order in the case where you are attaching both a disk and an ISO. The default remains to boot from disk as before. Resolves https://github.com/BOINC/boinc/issues/1573. 
I did not add a command line option (I could though), since it seems like the options which have made it as command line options are ones which would need to be controlled on a per-job (rather than per-appversion) basis, and this doesn't seem to me to be one of them.
> VBOX: added boot_iso option

- samples/condor/boinc_gahp.cpp
- If there can't be found a Condor output file with a matching name in the output template, use the position of the file in the lists of output files to identify it.
- Prepare for the (rare) case where a Condor output file path contains blanks
- Append to an existing stderr / error file instead of overwriting it (Condor-style instead of BOINC style)
> Boinc gahp fixes

- android/BOINC/res/values-ca/strings.xml
- android/BOINC/res/values-cs/strings.xml
- android/BOINC/res/values-da/strings.xml
- android/BOINC/res/values-de/strings.xml
- android/BOINC/res/values-en/strings.xml
- android/BOINC/res/values-es/strings.xml
- android/BOINC/res/values-fr/strings.xml
- android/BOINC/res/values-hu/strings.xml
- android/BOINC/res/values-it-rIT/strings.xml
- android/BOINC/res/values-ja/strings.xml
- android/BOINC/res/values-ka/strings.xml
- android/BOINC/res/values-ko/strings.xml
- android/BOINC/res/values-nl/strings.xml
- android/BOINC/res/values-pl/strings.xml
- android/BOINC/res/values-pt-rBR/strings.xml
- android/BOINC/res/values-pt-rPT/strings.xml
- android/BOINC/res/values-ro/strings.xml
- android/BOINC/res/values-ru-rRU/strings.xml
- android/BOINC/res/values-ru/strings.xml
- android/BOINC/res/values-sk/strings.xml
- android/BOINC/res/values-tr/strings.xml
- android/BOINC/res/values-uk/strings.xml
- android/BOINC/res/values-zh-rCN/strings.xml
- android/BOINC/res/values-zh-rTW/strings.xml
- android/BOINC/res/values/strings.xml
- android/BOINC/src/edu/berkeley/boinc/client/NoticeNotification.java
See https://developer.android.com/guide/topics/resources/string-resource.html#Plurals for details.
As to #1595, in the next commit [```notice_notification_single_header```](https://github.com/BOINC/boinc/compare/master...GITNE:plurals#diff-f4e361a555c3a8b78cf2d29ffe035cb2L375) and [```notice_notification_multiple_header```](https://github.com/BOINC/boinc/compare/master...GITNE:plurals#diff-f4e361a555c3a8b78cf2d29ffe035cb2L376) would get removed in all other languages so that Transifex would inform translators about the new [```notice_notification```](https://github.com/BOINC/boinc/compare/master...GITNE:plurals#diff-f4e361a555c3a8b78cf2d29ffe035cb2R375) string resource. Translators will not have to bother about the obsolete string resources and will also not forget (or if nobody cares) to …
> AndroidBOINC: Fix plurals issue in notification messages

- lib/crypt.cpp
- lib/crypt.h
- lib/crypt_prog.cpp
The upcoming OpenSSL version introduces some API changes (https://wiki.openssl.org/index.php/1.1_API_Changes). This is so far a backwards compatible change that works with the old and the new API. I checked by signing files with both versions and verifying with the other.
Fixes #1565
> Openssl api change

- drupal/sites/default/boinc/modules/boincwork/boincwork.admin.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
The wording of preferences now mostly match those used on the regular BOINC website so volunteers are not confused about the meanings.
Special note: The preferences run_on_batteries, run_if_user_active and run_gpu_if_user_active are now shown inverse to how they are stored because of the changed description.
> Update Drupal preference wording

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
Added link in community preferences to allow users to view and edit their ignored users.
https://dev.gridrepublic.org/browse/DBOINCP-256
> Drupal: add ignore users to community preferences

- drupal/sites/all/features/news/news.views_default.inc
1. Main News page
- Changed link from DISCUSS to MORE to match front-page news box.
- Removed comment count if number of comments is zero, to match front-page news box.
2. Front-page news box
- Added PHP code to determine if the node has comments enabled. If yes, then a DISCUSS link will appear after the news item.
- Removed comment count if number of comments is zero. By definition nodes with read-only/disabled comments will have zero comments.
Fixes:
https://dev.gridrepublic.org/browse/DBOINCP-262
https://dev.gridrepublic.org/browse/DBOINCP-289
> Drupal: Changed news views display-

- samples/condor/boinc_gahp.cpp
This fixes an issue which causes the Gridmanager to log about 10K entries every second that look like:
08/05/16 23:10:38 [105816] GAHP[105817] -> 'S' '0'
08/05/16 23:10:38 [105816] GAHP[105817] <- 'RESULTS'
08/05/16 23:10:38 [105816] GAHP[105817] -> 'S' '0'
08/05/16 23:10:38 [105816] GAHP[105817] <- 'RESULTS'
> Fixing Gridmanager fast looping issue

- lib/stackwalker_win.cpp
- lib/util.cpp
- lib/win_util.cpp
These are some minor fixes (all regarding *lib/str_replace.h* and *lib/str_util.h*) I had to apply when building *libboinc_staticcrt* and *libboincapi_staticcrt* for Windows while porting my application — there may be other fixes needed by other projects.
> Fix Windows build by including needed headers.

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
The additional preset attribute in the venue tag is breaking preference parsing in the scheduler. We now use a tag instead of an attribute and clear any old attributes.
This is only a problem with generalprefs because they get propagated to other projects that do not have a scheduler which ignores the attribute. The Einstein@Home scheduler (only project to use the Drupal webcode right now) was patched to handle extra attributes so we don't need to strip the attribute from projectprefs.
> Drupal: convert preset attribute to tag

- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
Fixed bug where users who choose forum preference "Newest Post First" had an error in how a new forum post was previewed. Added a if conditional where if the number of comments is zero, the forum topic template does not try to create an additional set of div-tags. As a result the Preview link now works.
https://dev.gridrepublic.org/browse/DBOINCP-300
> Drupal: fix preview box bug

- drupal/sites/default/boinc/modules/contrib/bbcode/bbcode.module
BBCode link now opens in new window/tab.
Fixes: https://dev.gridrepublic.org/browse/DBOINCP-280
> Drupal: BBCode link now opens in new window/tab.

- drupal/sites/all/features/teams/teams.views_default.inc
Changed view boinc_team_members, Team member list sub-view. Added row number column as Rank, added Joined column to list when member joined BOINC (not the team).
https://dev.gridrepublic.org/browse/DBOINCP-290
> Drupal: Add row number of team member list

- drupal/sites/default/boinc/modules/boincwork/boincwork.module
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
New behavior: when the user loads the general or project preferences page, Drupal will display a message saying there are no preferences set. No longer auto-saves preferences upon visiting the page.
https://dev.gridrepublic.org/browse/DBOINCP-296
> Drupal: Removed autosave from prefrences page

- drupal/sites/default/boinc/themes/boinc/css/views-styles.css
Fixed CSS style so sticky-header has same CSS as main table header.
https://dev.gridrepublic.org/browse/DBOINCP-313
> Drupal: Fixed CSS style for stick-header

- drupal/sites/default/boinc/modules/boincteam/boincteam_forum.module
On main forum page, the team forum Last post field was wrong. I fixed the DB query to return the correct timestamp.
https://dev.gridrepublic.org/browse/DBOINCP-321
> Drupal: Fixed bug where team forum Last post was incorrect.

- drupal/sites/default/boinc/modules/boincwork/boincwork.admin.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
The default preference set when a user visits the accounts preference page is (now) 'standard'.
Added form submit for BOINC: preferences preset admin interface. Admin may now Save configuration with the disk usage settings from config.xml. In this way, those XML settings will be loaded into the database as the default preferences presets. These presets are in turn used by drupal when the user visits the preferences page. The form on that page will be filled with the preferences from the drupal database.
If there are no preference preset loaded in the drupal database, then the standard preset will be filled in with the disk usage settings from config.xml. Once it is save into the drupal database, the admin must use the Save configuration with disk usage settings from config.xml button in …
> Drupal: default preference set is now 'standard'.

- drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
- drupal/sites/default/boinc/themes/boinc/templates/views-view--boinc-workunit--page.tpl.php
Suppress output if app is using adaptive replication
Fixed wrong variable name in view.
Added additional conditional logic using a) error_mask and b) config.xml `<dontsupressoutput>` setting to match BOINC code. This is to suppress output if the app uses adaptive replication.
(b) is obtained through a new field in the fiew which loads the setting from config.xml into a variable.
Changed workunit view template. Variables from view used to determine if task list is output.
https://dev.gridrepublic.org/browse/DBOINCP-255
> Drupal: Fix workunit view for adaptive replication

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
... were not being displayed in the Web form correctly.
Other BOINC projects may not use the <preset> tag, which we introduced recently.
https://dev.gridrepublic.org/browse/DBOINCP-325
> Drupal: Fix bug where custom preferences from other projects

- drupal/sites/default/boinc/themes/boinc/templates/views-view-table--boinc-account-computers--panel-pane-1.tpl.php
Was: account/computers/all
Now: account/computers
https://dev.gridrepublic.org/browse/DBOINCP-326
> Drupal: Changed More (computers) link on Account Dashboard.

- drupal/sites/default/boinc/modules/boincwork/boincwork.module
function `venue_update()` no longer exists in BOINC code. Changed to boincwork's `boincwork_set_default_venue()` function.
https://dev.gridrepublic.org/browse/DBOINCP-311
> Drupal: Fixed udpate venue issue.

- drupal/sites/default/boinc/modules/boincteam/boincteam_forum.module
- drupal/sites/default/boinc/themes/boinc/templates/views-view--boinc-team-forum-topics.tpl.php
Fixed bug, now user can edit own team forum topics.
Fixed bug, now only team members see the Post New Topic link in team forum topic list.
https://dev.gridrepublic.org/browse/DBOINCP-319
> Drupal: Fixed bug, user can edit own team forum topic

- drupal/sites/default/boinc/modules/boincwork/boincwork.module
The view page for preferences is obsolete. These two commits remove the pages, one for the computing (general) and the second for the project preferences page.
If the user tries to reach this view page, s/he will be directed to the default edit page.
https://dev.gridrepublic.org/browse/DBOINCP-327
> Drupal: Removed view page/option from the computing and project preferences page

- sched/sched_types.cpp
The xp.element_contents() functions strips the linebreak before the closing tag. But the closing tag needs to be on it's own line because of the limitations of BOINC XML parsing.
> Scheduler: fix global preference parsing

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.admin.inc
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.css
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.info
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.install
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.module
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.node.inc
- drupal/sites/default/boinc/themes/boinc/template.php
Made changes to `forum_access` module and its corresponding database table to include a separate permission for `comment_create`, which grants users the ability to create comments in a particular forum.
Moved link generation from boinc template into `boinccore` module, so `forum_access` module may alter the links based on a user's permissions.
https://dev.gridrepublic.org/browse/DBOINCP-316
`forum_access` module install modified to use type unsigned int on field `rid` (instead of int).
https://dev.gridrepublic.org/browse/DBOINCP-324
> Drupal: Added comment_create permission to forum_access module.

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
Also fix bug where user can have <preset> tag set from another project. Upon initial loading of the preferences form, the preferences are filled from the user's database entry.
https://dev.gridrepublic.org/browse/DBOINCP-325
> Drupal: Fixed bug where user cannot select preset radio button.

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
...resulting in wrong page loading.
Changed cancel link from current URL to a pre-defined URL, the computing preference edit page.
https://dev.gridrepublic.org/browse/DBOINCP-307
> Drupal: Fix bug where Cancel link in AHAH form 

- drupal/sites/default/boinc/themes/boinc/css/comments.css
- drupal/sites/default/boinc/themes/boinc/template.php
When no $links are generated, the function _boinc_create_moderator_links() should exit without doing anything.
https://dev.gridrepublic.org/browse/DBOINCP-316
> Drupal: Fix bug- handle case where no $links generator

- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.module
Modified forum_access module to allow for the link "community/forum/0/read" which is necessary for the mark forum as read link.
https://dev.gridrepublic.org/browse/DBOINCP-332
> Drupal: Fix bug where "Mark forums as read" link led to Access Denied.

- drupal/sites/default/boinc/themes/boinc/template.php
Commit f64e644f inadvertently removed a crucial line that prevents signatures from being shown. I also got rid of the commented out comment that gave the impression that this function is not used.
> Drupal: show signatures in comments again

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
Make sure only numeric arguments are accepted to avoid misuse.
> Drupal: harden team email list RPC wrapper

- drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Site home page message is now an option that is set in the admin interface, BOINC Other.
The message is placed on the home page and is labeled as a project-specific string.
https://dev.gridrepublic.org/browse/DBOINCP-317
> Drupal: Site home page message translation set as project-specific.

- drupal/sites/default/boinc/modules/boincwork/boincwork.module
Home string should be have additional context.
> Drupal: Add project-specific context to Home string, part of preference set

- clientgui/DlgDiagnosticLogFlags.cpp
- clientgui/DlgDiagnosticLogFlags.h
Activates 'Apply' button when the checkboxes change their state or 'Defaults' button is pressed. 
As requested in issue #1689.
> Manager: add 'Apply' button to Event Log options dialog

- .gitignore
- lib/str_util.cpp
- lib/str_util.h
- sched/makefile_validator_test
- sched/sample_bitwise_validator.cpp
- sched/sample_substr_validator.cpp
- sched/sample_trivial_validator.cpp
- sched/script_validator.cpp
- sched/validate_util.cpp
- sched/validate_util.h
- sched/validator.cpp
- sched/validator.h
- sched/validator_test.cpp
The validator handler can now pass unknown arguments to the project specific handler.
Projects that have their own validator need to implement the validate_handler_init() function and handle project specific arguments there. They also need to supply a validate_handler_usage() function that printf()'s a description of the custom options. For examples see sample_substr_validator.cpp or script_validator.cpp
The validator test harness was also adopted to use this new functions.
This brings the implementation of the validator framework on the same level as the assimilator framework where similar changes where made in 0038d275c and dd004404a.
> Daemons: enhance validator framework

- client/scripts/Makefile.am
Adjusted `client/scripts/Makefile.am` to support out-of-tree builds, because `make install` was trying to find `boinc-client` in its source directory rather than in build workspace.
> Fix installation of `boinc-client` service script.

- html/user/job_file.php
- html/user/submit_rpc_handler.php
When a file is specified as `<remote_submisson_log>` in config.xml, the requests to submit_rpc_handler.php and job_file.php are logged to that file before being processed.
If a `<log_dir>` is specified in config_xml, the filename is taken relative to that directory.
Useful for debugging.
> remote submission: log xml requests to file specified as <remote_submisson_log>

- html/ops/test_job_file.php
- html/user/job_file.php
The upload_files function did not do a good job on error reporting. It now can handle and report several more problems.
- Loop over the uploaded files not the supplied md5 values so we can detect a discrepancy between the two
- Check upload error value provided by PHP (catches filesize limit problems, permission problems and partial uploads)
- Calculate md5 of uploaded file and check with supplied values (The size of uploaded files is typical small enough so this is not a problem)
- Report any error condition in the response and delete the uploaded files (especially if they are in the PHP temp directory)
- Added script to debug upload problems
> Web: fix job file upload error reporting

- client/gui_rpc_server_ops.cpp
The dont_detach_when_done RPC does not work as expected, it does not reset the flag. Looks like no one has noticed since the bug was introduced 5 years ago in c61103ac26bff4a40023dbc6a92781247e8801d8. This should fix it.
> Make project_dont_detach_when_done RPC work correctly

- samples/wrapper/wrapper.cpp
Android wrapper had an execution time error because de env variable $PWD was not found. Changing getenv("$PWD") for getcwd() fixes the issue.
> Fixed wrapper execution time error in android 

- drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
which causes PHP errors in Drupal's log.
> Drupal: Fixed wrong function declaration 

- drupal/sites/default/boinc/themes/boinc/css/layout-fixed.css
- drupal/sites/default/boinc/themes/boinc/css/tabs.css
* Adds page-wrapper min-width: ~~960px;~~ changed to 980px;
* ~~Fixes navigation bar width, should be width: 960px;~~ removed, navigation bar remains at 980px.
https://dev.gridrepublic.org/browse/DBOINCP-345
> Drupal: Fixed fixed-width CSS for smaller browser windows.

- clientgui/sg_BoincSimpleFrame.cpp
'Advance view' item is enabled always even if Manager doesn't connected to client.
As requested in issue 1748.
> MGR: Enable always 'Advance View' menu item in Simple mode.

- drupal/sites/all/features/news/news.views_default.inc
Fixes issue where Drupal would add extra <span> tag to the menu link.
https://dev.gridrepublic.org/browse/DBOINCP-348
> Drupal: Changed news view menu type to "Normal Menu".

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/themes/boinc/templates/search-result.tpl.php
- Fixed search result template to get NID from search result directly.
- Added to boincuser module hook into Apache Solr index to use user account creation date instead of the node creation date.
https://dev.gridrepublic.org/browse/DBOINCP-287
> Drupal: Fixes profile search result issue regarding 'Joined' date.

- html/user/edit_forum_preferences_action.php
This fixes the list of warnings shown below when submitting forum preferences and if you have PHP warnings on. 
This was due to the fact that unchecked checkboxes do not set POST data, so I had to insert several `isset`'s accordingly. 
I have only the most basic knowledge of PHP so while this seems to solve the problem, someone should verify this solution is a good one. 
```
Notice: Undefined index: forum_images_as_links in /root/project/html/user/edit_forum_preferences_action.php on line 110
Notice: Undefined index: forum_link_popup in /root/project/html/user/edit_forum_preferences_action.php on line 111
Notice: Undefined index: forum_hide_avatars in /root/project/html/user/edit_forum_preferences_action.php on line 112
Notice: Undefined index: forum_hide_signatures in …
```
> fixed PHP warnings when submitting forum preferences

- drupal/sites/all/features/teams/teams.views_default.inc
- drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
Changed users, teams, and hosts views to show 100, 100, and 50 results without a pager.
> Drupal: Change top host, user, and team views

- sched/validate_util2.cpp
- sched/validate_util2.h
A validator now has the possibility to mark a single result as "suspicious" by making init_result() return VAL_RESULT_SUSPICIOUS. If this is the single quorum result of an adaptive replication, this will trigger another task to be generated for validation.
> Validator: implement "suspicious" results

- client/gui_rpc_server_ops.cpp
This fixes #1709 by removing the XML declaration from lookup_account_poll and get_all_projects_list replies as it is already done for get_project_config_poll. Also, any error messages are now retained in the responses.
> Fix issue #1709: Malformed XML in RPC replies for lookup_account_poll and get_all_projects_list

- client/client_state.h
- client/current_version.cpp
- client/gui_rpc_server_ops.cpp
- clientgui/AdvancedFrame.cpp
- clientgui/AdvancedFrame.h
- clientgui/Events.h
- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientgui/sg_BoincSimpleFrame.cpp
- clientgui/sg_BoincSimpleFrame.h
- lib/gui_rpc_client_ops.cpp
Reused existing mechanism of version check.
Manager will check for new version during connection to the client.
Default message about new version will be shown in notices tab.
Added menu to check new version manually. In this case user will see the message with check result.
Fixed issue with new version response parse.
> MGR: Client version check

- client/hostinfo_unix.cpp
- client/hostinfo_win.cpp
- lib/str_util.cpp
- lib/str_util.h
This was already done for Mac but not Linux and Windows. It collapses multiple consecutive blanks into one blank which is then send to the server.
> Client: normalize whitespace in p_model and p_vendor entries

- configure.ac
- lib/diagnostics.cpp
Currently, execinfo.h is included in lib/diagnostics.cpp if `__GLIBC__` is
defined. However, this does not work when cross-compiling boinc with
uclibc-ng. So, instead, check the presence of execinfo.h in configure.ac
and update lib/diagnostics.cpp accordingly.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Check execinfo.h availability in configure.ac

- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
Either both email and password must be changed, or just the password.
https://dev.gridrepublic.org/browse/DBOINCP-355
> Drupal: Added error message- admin cannot change only a user's email.

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/themes/boinc/templates/search-result.tpl.php
Changed bundle name from "Profile" to "User".
Boinc username is used in Solr index (replaces drupal username).
Search template updated to use bundle name "User" and to use boinc username.
https://dev.gridrepublic.org/browse/DBOINCP-357
> Drupal: Use boinc username in Solr searches.

- lib/boinc_win.h
- lib/str_replace.h
I was cross compiling from ubuntu xenial with mingw for windows.
A few error occurred because current code failed to recognize mingw.
There might be better ways(that I don't know) to fix it.
> Fix cross-compile from ubuntu with mingw

- clientgui/AdvancedFrame.cpp
- clientgui/DlgSelectComputer.cpp
The hostname "localhost" was recognized as a special name which always prompted the Manager to try to read contents of gui_rpc_auth.cfg. The Manager used an empty password if the file is not readable but then can't connect because the Client actually uses a password. Any user supplied password was overwritten which made the dialog not work when using "localhost" but work when used with "127.0.0.1".
Now the dialog checks if the user has entered an empty password which prompts reading gui_rpc_auth.cfg and uses the user supplied password otherwise.
Fixes #1306
> Manager: Fix select computer dialog

- android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.java
1. Replaced some String `==` comparisons with `equals`
This is just a simple fix.
2. Simplified power source prefs dialog code by adding `ID` field to `SelectionDialogOption`
Now IDs are used to identify power source options, instead of translated strings.
> Android: Fixed and reduced string comparisons

- drupal/sites/all/features/user_profiles/user_profiles.features.menu_links.inc
Drupal: Removed alter=>TRUE from user_profile menu_links, which was causing a permanent override.
part of https://dev.gridrepublic.org/browse/DBOINCP-274
> Drupal: Fix user_profiles Feature to eliminate Feature override

- drupal/sites/all/features/user_profiles/user_profiles.features.menu_links.inc
- drupal/sites/default/boinc/themes/boinc/css/html-reset.css
- drupal/sites/default/boinc/themes/boinc/css/responsive-jswidth.css
Renamed the Moderation menu child item 'Moderation Menu' as 'Queue'.
Also, fixed BOINC theme CSS that was breaking mobile menu placement/layout.
> Drupal: Renamed moderation queue menu item as 'Queue'

- drupal/sites/default/boinc/themes/boinc/template.php
Added UTF-8 encoding for HTML being loaded by DOMDocument. 
Fixes garbage output text for links and moderator links.
https://dev.gridrepublic.org/browse/DBOINCP-359
> Drupal: Added UTF-8 encoding for loadHTML.

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
This is used by stats sites to regularly query user credit stats during a special event. The default implementation is inefficient as it creates a DB query per team member which is slowing down the query in big teams. The creditonly switch is also available in upstream where it suppresses certain xml outputs. We still don't support all the fields that upstream supports but the missing fields are not credit relevant.
> Drupal: implement creditonly switch for team_email_list.php RPC

- api/Makefile.am
- lib/Makefile.am
- sched/Makefile.am
- zip/Makefile.am
Remove "-L$(libdir)" from LDFLAGS of boinc libraries in Makefile.am of
api, lib, sched and zlib directories to be able to cross-compile boinc.
Indeed, libdir is not equal to the path where BOINC will be installed
but to exec_prefix/lib. The full installation path is
$(DESTDIR)/$(libdir).
To cross-compile boinc, exec_prefix will be set to the target path (for
example: /usr) and DESTDIR will be set (during make install) to the
staging or target directory on the host (for example /home/xxx/target).
The issue of adding -L$(libdir) is that it is not allowed by the
compiler, the error "unsafe header/library path used in
cross-compilation: '-L/usr/lib'" will be raised.
As a result, remove -L$(libdir)" from LDFLAGS, the default library
search paths are sufficient for "standard" compilation or can …
> Fix LDFLAGS for cross-compilation

- drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.module
l10n_update module has buggy code which can't handle the new ftp-origin.drupal.org URL redirect.
https://dev.gridrepublic.org/browse/DBOINCP-363
> Drupal: Added hook to boinctranslate to update the URL/path for l10n_update

- drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.module
- drupal/sites/default/boinc/modules/boinctranslate/includes/other-boinc-translation-strings.txt
boinctranslate module will read file and use '|' as delimiter to separate the string from its context.
Added context to a number of strings in the other-boinc-translation-strings file.
https://dev.gridrepublic.org/browse/DBOINCP-361
> Drupal: Added ability to add context to other-boinc-translation-strings text file.

- drupal/sites/all/features/user_profiles/user_profiles.features.menu_links.inc
> Drupal: Removed another line in user_profiles feature to remove overrides.

- .travis.yml
- lib/Makefile.mingw
- zip/zip/__p___mb_cur_max.c
The previous command was only working because Travis already exports CC and CXX. This works even if this is not the case.
> Travis: fix mingw build command and add wrapper

- client/hostinfo_win.cpp
V646
Consider inspecting the application's logic. It's possible that 'else' keyword is missing.
https://www.viva64.com/en/w/V646/print/
> Client: Fix missed 'else' keyword.

- lib/run_app_windows.cpp
V667:
The 'throw' operator does not possess any arguments and is not situated within the 'catch' block.
https://www.viva64.com/en/w/V667/print/
> lib: Fix missed parameters from 'throw' statements.

- clientgui/sg_ProjectWebSitesPopup.cpp
V530:
The return value of function 'c_str' is required to be utilized.
https://www.viva64.com/en/w/V530/print/
> Manager: Remove unused function call.

- client/app.cpp
V767
Suspicious access to element of 'msgs' array by a constant index inside a loop.
https://www.viva64.com/en/w/V767/print/
> client: Fix show message cycle

- samples/vboxwrapper/vbox_vboxmanage.cpp
V501:
'There are identical sub-expressions 'enable_isocontextualization' to the left and to the right of the '&&' operator.'
https://www.viva64.com/en/w/V501/print/
> vboxwrapper: Fix double check of the same flag.

- android/build_boinc_arm.sh
* Those explicit FPU flags prevent NEON builds
* The whetstone benchmarks (VFP and NEON) are correctly built without those
> [#1702][android]: remove explicit FPU flags

- clientgui/BOINCBaseWizard.cpp
- clientgui/MainDocument.cpp
V730
Not all members of a class are initialized inside the constructor.
Consider inspecting: m_bCancelInProgress.
Consider inspecting: m_bUseDefaultPassword.
https://www.viva64.com/en/w/V730/print/
> Manager: fix uninitialized class members in constructor

- lib/filesys.cpp
- lib/prefs.h
V730
Not all members of a class are initialized inside the constructor.
Consider inspecting: present.
Consider inspecting: handle.
https://www.viva64.com/en/w/V730/print/
> lib: fix uninitialized class members in constructor

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/AndroidManifest.xml
* Use commit date as version code
* Derive version name from release tag and add commit SHA1
* No more manual updates required, just proper release tagging!
* Resolves https://github.com/BOINC/boinc/issues/1864 (for Android)
FYI, the required tag format is as follows:
`client_release/x.y/x.y.z[suffix]` (suffix is optional but must be separated with `-` or `_`)
> Android: use dynamic versioning instead of hard-coded values

- android/BOINC/app/build.gradle
* Current version doesn't support development well enough
* Gradle seemingly doesn't support distinguishing build variants (debug/release) so I can't enforce proper release tagging
* Thus any non-matching tag will flag a build as DEVELOPMENT and a Gradle warning is displayed
* Also: release builds must be tagged directly (no commit offset)
* Also: release builds are not allowed to use a dirty working tree
This is a follow-up to PR #1866 that got merged prematurely.
> Android: improved auto-versioning

- drupal/sites/default/boinc/themes/boinc/boinc.info
- drupal/sites/default/boinc/themes/boinc/css/responsive-jswidth.css
- drupal/sites/default/boinc/themes/boinc/css/responsive-media.css
- drupal/sites/default/boinc/themes/boinc/js/jquery.detectwidths.js
- drupal/sites/default/boinc/themes/boinc/js/jquery.headerwidth.js
Use javascript to set the width of the header to the width of the content of the page.
Fixed bug where navigation menu bar which is wider than the width of the 980px desktop layout, and breaks the layout. If the whole navigation bar is larger that 980px, use the mobile menu instead.
https://dev.gridrepublic.org/browse/DBOINCP-250
> Drupal: Fix respdes header and menu

- drupal/sites/all/features/boinc_standard/boinc_standard.features.menu_custom.inc
- drupal/sites/all/features/boinc_standard/boinc_standard.features.menu_links.inc
- drupal/sites/all/features/boinc_standard/boinc_standard.pages_default.inc
- drupal/sites/all/features/friends/friends.views_default.inc
- drupal/sites/all/features/global_search_solr/global_search_solr.apachesolr_search_defaults.inc
- drupal/sites/all/features/news/news.features.menu_links.inc
- drupal/sites/all/features/private_messages/private_messages.panels_default.inc
- drupal/sites/all/features/stats_charts/stats_charts.panels_default.inc
- drupal/sites/all/features/stats_charts/stats_charts.views_default.inc
- drupal/sites/all/features/user_account_host_list/user_account_host_list.views_default.inc
- drupal/sites/all/features/user_account_project_list/user_account_project_list.panels_default.inc
- drupal/sites/all/features/user_preferences/user_preferences.features.menu_links.inc
- drupal/sites/all/features/user_preferences/user_preferences.views_default.inc
- drupal/sites/all/features/user_profiles/user_profiles.features.content.inc
- drupal/sites/all/features/user_profiles/user_profiles.features.menu_links.inc
- drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
- drupal/sites/default/boinc/modules/boinctranslate/includes/other-boinc-translation-strings.txt
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/page.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/search-result.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/views-view-fields--boinc-friends--block-1.tpl.php
Changed links in menubar to use `url()` function so language code is properly inserted into URL.
Added a number strings to the boinc textgroup, with context details.
> Drupal: fix i18n add missing strings

- drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.module
_boinctranslate_locale_import_one_string_db() function modified to do the following:
* When a string is in textgroup 'boinc' or 'project', add the use of the `location` field to query the database `locales_soruce` table.
* In other textgroups, the `location` field is not used.
* If multiple strings (rows) are found in the query, loop over the rows to add/overwrite the translations.
* A special token, `ignoreoverwrite` can be placed in the location/context details, to indicate it will **not** overwriting any found translations already in the database.
Update: This PR depends on #1834, and should be merged after 1834 is merged.
> Drupal: fix translation system location/context overwrite

- win_build/vboxwrapper_vs2013.vcxproj
Add missed vbox_mscom51.cpp and vbox_mscom51.h files to the project.
> vboxwrapper: Fix vboxwrapper_vs2013.vcxproj build.

- clientgui/BOINCGUIApp.cpp
- configure.ac
- lib/util.cpp
- lib/util.h
This was not working because the manager was not detecting its own executable name and path so it couldn't start a new instance of itself. Windows and Mac use different codepaths so it worked there.
The new library function can be extended for Windows and Mac to avoid code duplication.
Fixes #1177
> Manager/Lib: fix 'New Manager window' function on Linux

- samples/vboxwrapper/vbox_mscom_impl.cpp
V808
'vm_machine_uuid' object of 'CComBSTR' type was created but was not utilized.
'clean_mediums' object of 'vector' type was created but was not utilized.
https://www.viva64.com/en/w/V808/print
> vboxwrapper: Remove unused variables

- clientgui/AdvancedFrame.cpp
- clientgui/BOINCDialupManager.cpp
- clientgui/BOINCGUIApp.cpp
- clientgui/BOINCTaskBar.cpp
- clientgui/DlgHiddenColumns.cpp
- clientgui/MainDocument.cpp
- clientgui/browser.cpp
- clientgui/sg_BoincSimpleFrame.cpp
- clientgui/sg_TaskPanel.cpp
- clientgui/wizardex.cpp
V808
'strBuffer' object of 'wxString' type was created but was not utilized.
'strValue' object of 'wxString' type was created but was not utilized.
'strName' object of 'wxString' type was created but was not utilized.
'strURL' object of 'wxString' type was created but was not utilized.
'strTeamName' object of 'wxString' type was created but was not utilized.
'strDialogMessage' object of 'wxString' type was created but was not utilized.
'strOldLanguageCode' object of 'wxString' type was created but was not utilized.
'strHiddenColumns' object of 'wxString' type was created but was not utilized.
'strConnectedCompter' object of 'wxString' type was created but was not utilized.
'strEmpty' object of 'wxString' type was created but was not utilized.
'value_w' object of …
> Manager: Remove unused variables

- lib/gui_rpc_client_ops.cpp
V808
'noproxy' object of 'basic_string' type was created but was not utilized.
https://www.viva64.com/en/w/V808/print
> lib: Remove unused variables

- client/cpu_sched.cpp
V808
'preemptable_tasks' object of 'vector' type was created but was not utilized.
https://www.viva64.com/en/w/V808/print
> client: Remove unused variables

- drupal/sites/default/boinc/themes/boinc/template.php
Fix link to use `url()` function.
https://dev.gridrepublic.org/browse/DBOINCP-317
> Drupal: Fix link to use url function

- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
A moved forum topic's shadow topic message had wrong link. Added path "community" to link.
Also, I updated this PR to fix a second bug: the breadcrumbs of topics where a shadow copy is created were incorrect, and needed a minor fix.
https://dev.gridrepublic.org/browse/DBOINCP-366
https://dev.gridrepublic.org/browse/DBOINCP-372
> Drupal: Fixed bug in moved (forum) topic link.

- drupal/sites/all/features/news/news.views_default.inc
News feed items will expire after 90 days.
https://dev.gridrepublic.org/browse/DBOINC-155
> Drupal: Added date filter to RSS news feed.

- drupal/sites/all/features/boinc_standard/boinc_standard.features.inc
If language-code is included in the site-url, the link will not be broken due to a lack of a slash.
https://dev.gridrepublic.org/browse/DBOINCP-346
> Drupal: Fixed URL by adding trailing slash.

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
When create_account is called, check for uniqueness with the user_name when creating Drupal user account.
Fixed error message for Forgot Password form, which was incorrect and misleading.
https://dev.gridrepublic.org/browse/DBOINCP-379
https://dev.gridrepublic.org/browse/DBOINCP-376
> Drupal: Fixes for create account functions.

- drupal/sites/default/boinc/modules/contrib/views/handlers/views_handler_argument_many_to_one.inc
- drupal/sites/default/boinc/modules/contrib/views/handlers/views_handler_field.inc
- drupal/sites/default/boinc/modules/contrib/views/handlers/views_handler_filter_date.inc
- drupal/sites/default/boinc/modules/contrib/views/includes/base.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/comment/views_handler_field_node_new_comments.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/node/views_handler_filter_node_access.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/node/views_handler_filter_node_status.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/profile/views_handler_field_profile_list.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/system/views_handler_field_file.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_field_term_node_tid.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_filter_term_node_tid_depth.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/upload/views_handler_field_upload_description.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/upload/views_handler_field_upload_fid.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/user/views_handler_field_user_name.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/user/views_handler_field_user_roles.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/user/views_handler_filter_user_name.inc
- drupal/sites/default/boinc/modules/contrib/views/views.info
to eliminate E_STRICT PHP notices.
https://dev.gridrepublic.org/browse/DBOINCP-380
Drupal issue: https://www.drupal.org/node/893128
> Drupal: Added patch to Views contrib module, 6.x-2.x-boinc-3-dev

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
If a Drupal user account cannot be created, a BOINC user account is NOT created, and no link between the two is made.
Then
If a BOINC account cannot be created, no link between the BOINC and Drupal user accounts is made.
https://dev.gridrepublic.org/browse/DBOINCP-379
> Drupal: Changed order of if-statements to change logic of account_create.php

- samples/vboxwrapper/vbox_vboxmanage.cpp
After noticing erratic behavior when a machine was deleted (VDIs sometimes remaining in the media registry) and reproducing the problem with VBoxManage commands it was noticed that in order to replicate what is normally done when deleting a machine via VirtualBox Manager (right click on the machine and remove) all that was needed was the command:
VBoxManage -q unregistervm <vm_name> --delete
That way VirtualBox took care of deleting everything. So the commands following this were removed.
> remove ghost mediums from the media registry

- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vboxwrapper.cpp
Give the option to Windows users to choose between the COM interface and the VboxManage interface using a preprocessor flag (COM_OFF). Change the way logs are parsed to get the process ID and to get the guest vm log entries. Add some more detailed logging.
> Give choice between COM and VboxManage interface

- drupal/sites/default/boinc/modules/boincwork/boincwork.module
bts() functions may query the drupal DB. Use `db_set_active()` to make sure boinc/drupal DB queries are being handled correctly.
https://dev.gridrepublic.org/browse/DBOINCP-383
> Drupal: Modified db_set_active() functions so drupal database is correctly queries by bts() function.

- drupal/sites/all/features/news/news.views_default.inc
- drupal/sites/all/features/stats_charts/stats_charts.panels_default.inc
- drupal/sites/all/features/user_profiles/user_profiles.features.content.inc
- drupal/sites/default/boinc/modules/boincstats/boincstats.admin.inc
- drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.module
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/forum-list.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/views-view-rss--news.tpl.php
Changed instances of variable_get('site_name') to use string 'Drupal-BOINC' as default, if site_name system variable is not set. This default string is not translated as the variable should be set by the site admin.
part of:
https://dev.gridrepublic.org/browse/DBOINCP-336
> Drupal: Modified default value for site_name variable.

- .travis.yml
The container-based Trusty does not allow all the packages we need.
> Travis: use Trusty image and use apg-get to install dependencies

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
Fixed bug in table where CPU time was not being loaded correctly.
Removed WHERE deprecated=0 flag from queries.
Added application version and platform to table.
Added sort to Sent column.
https://dev.gridrepublic.org/browse/DBOINCP-387
https://dev.gridrepublic.org/browse/DBOINCP-388
> Drupal: Fixed a few bugs and added features to task table.

- drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node.tpl.php
Changed all timezone strings to 'T'. Made all time strings consisent, hour is 'G', no comma or other separator(s) between date and time.
https://dev.gridrepublic.org/browse/DBOINCP-312
> Drupal: Modified date and time strings to be consistent.

- samples/condor/boinc_gahp.cpp
When uploaded the files just get the md5 as their name but are then submitted with the "jf_" in front of the name. Thus the batch submission fails due to non existent input file.
> Fix inconsistency between uploaded files and queried ones in boinc_gahp

- sched/plan_class_spec.cpp
- sched/plan_class_spec.h
- sched/sched_customize.cpp
- sched/sched_customize.h
- sched/sched_version.cpp
filters `<min_wu_id>`, `<max_wu_id>`, `<min_batch>`, `<max_batch>` and `<disabled>`
- WU information is passed from `check_homogeneous_app_version()` down to `PLAN_CLASS::check()`
- `wu_is_infeasible_custom()` is extended such that additional tasks also follow the plan class restrictions.
> plan classes:  add workunit-related filters

- drupal/sites/default/boinc/themes/boinc/css/comments.css
- drupal/sites/default/boinc/themes/boinc/css/pages.css
- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
Breadcrumb, post new comment, and subscribe links are placed into a single div with separate sub-divs. CSS changed to placed these sub-divs into two columns.
https://dev.gridrepublic.org/browse/DBOINCP-309
> Drupal: Forum top links are now placed into two columns.

- client/client_msgs.cpp
- client/main.cpp
- lib/diagnostics.cpp
The client flushes stdout and stderr at every iteration of the main loop. On Windows, stderr is opened in commit mode and this results in a write to NTFS $Log every time the stream is flushed even if nothing was written to the stream since last flush. These unnecessary writes totals to several hundred megabytes per day. Some users are concerned that this shortens the lifespan of their hardware.
Fix this by removing the flushes from main loop. stderr is unbuffered so it never needed the flush. After freopen() in diagnostics_init() stdout is fully buffered. Change stdout to line buffered mode so that log messages are visible in log files immediately.
MSVCRT doesn't support line buffered streams. It treats them as fully buffered. Emulate line buffered stream by flushing stdout in logging …
> client/lib: don't flush stdout and stderr in main loop

- lib/util.cpp
If the link were max_len bytes long or longer, the null terminator would have been written one past the end of path.
> lib: fix out of bounds write in get_real_executable_path

- lib/filesys.cpp
The function is documented to check if anything exists at the given path. The client depends on this behavior. If the function checks only for regular files the client will fail to clean up slot directories before using them for another task.
Fix the function to match the documentation.
> lib: fix boinc_file_exists() on Windows

- drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
New landing page for account_finish.php, used when user creates an account using BOINC client manager.
In addition, admin can supply a Drupal path to a custom one.
https://dev.gridrepublic.org/browse/DBOINCP-395
> Drupal: New account_finish landing page

- db/boinc_db.cpp
- db/boinc_db_types.h
- db/schema.sql
- html/ops/db_update.php
- sched/sched_shmem.cpp
- sched/sched_version.cpp
- tools/create_work.cpp
- tools/xadd
Allow projects to specify that WUs should be processed by particular version nums.
Add --app_version_num arg to create_work
Set app.min_version to lowest version with outstanding jobs
(can used xadd to do this)
> back end: add feature for assigning WUs to a particular version num

- samples/condor/Makefile
- samples/condor/boinc_gahp.cpp
The hardcoded version information written by boinc_gahp is not very helpful when I need to record which code version a particular binary was built from.
If there is a more suitable (i.e. GAHP protocol conformant) way to write SVN_VERSION to stdout I would be fine with that, too. If so, pleas implement this and reject this merge request.
> BOINC GAHP: print SVN_VERSION with --version CLA

- client/cs_trickle.cpp
- clientgui/ViewResources.cpp
- clientgui/common/wxPieCtrl.cpp
- db/boinc_db.cpp
- lib/Makefile.am
- lib/boinc_fcgi.cpp
- lib/boinc_fcgi.h
- lib/coproc.cpp
- lib/mfile.cpp
- lib/miofile.cpp
- lib/opencl_boinc.cpp
- lib/opencl_boinc.h
- sched/hr.cpp
- sched/sched_shmem.h
Fixes several issues when enforcing C++11 standard using GCC6. Most notably the fcgi compile where I'm not entirely sure if 0a30950 is the correct solution.
> Fix c++11 build

- api/boinc_api.cpp
- client/app.cpp
- client/app_config.cpp
- client/cs_prefs.cpp
- client/cs_trickle.cpp
- client/scheduler_op.cpp
- lib/diagnostics_win.cpp
- lib/parse.cpp
- samples/gfx_html/mongoose.cpp
- samples/wrapper/wrapper.cpp
V814
Decreased performance. The 'strlen' function was called multiple times inside the body of a loop.
https://www.viva64.com/en/w/V814/print
Affected components:
api
client
lib
samples
> Move 'strlen' function outside of the loop

- samples/condor/boinc_gahp.cpp
Do what @ChristianBeer suggested in #1604. 
Also define BOINC_GAHP_VERSION to conform to GAHP spec (major.minor.subminor)
> BOINC GAHP: add git SHA1 to version message

- client/app_control.cpp
- client/app_start.cpp
- client/async_file.cpp
- client/client_state.cpp
- client/client_state.h
- client/cpu_sched.cpp
A result with a lot of failed uploads could overflow a 4K buffer.
Change report_result_error() so you just pass it the error message,
rather than va_args nonsense.
> client: eliminate possible buffer overflow in reporting result errors

- clientgui/DlgAdvPreferencesBase.cpp
- clientgui/DlgDiagnosticLogFlags.cpp
- clientgui/DlgExclusiveApps.cpp
- clientgui/DlgHiddenColumns.cpp
- clientgui/DlgOptions.cpp
- clientgui/sg_DlgPreferences.cpp
Originally requested in #601: Change OK button on Advanced Preferences to Save button.
Button renamed in all dialogs with settings for consistency.
Also now 'Cancel' button is default button.
> Manager: Rename OK button to Save button

- clientgui/MainDocument.cpp
Notices may have e.g.
foo
<br />
blah
The manager replaces the newlines with <br>, resulting in three blank lines.
Change this to one.
TODO: the fix is a kludge.
> Manager: remove excess blank lines in notices

- client/gpu_detect.cpp
Better for the debug version to do the same thing as release.
There's a #define you can change if you want GPU detection to happen in the main process.
> client: do coproc detect in a separate process even for debug

- html/inc/submit.inc
- html/user/submit_rpc_handler.php
- lib/remote_submit.cpp
- lib/remote_submit.h
- lib/submit_api.py
- tools/submit_api_test.py
Change the submit_batch RPC, and the various bindings of it (PHP, Python, C++)
to support an app_version_num arg,
specifying which app version number should be used to process the jobs in the batch.
> Remote job submission: support app_version_num argument

- html/inc/team_types.inc
- html/user/custom.css
- html/user/team.php
- html/user/top_teams.php
At some point we added several team categories (national, computer type, etc.)
but there were a couple of places in the code where the # of categories
was hardwired, so the new categories weren't shown.
Also, for white-backbround color schemes,
in table headers with bg-default,
links were invisible because the text color was same as background.
Fix this in custom.css.
> web: team-related fixes

- clientgui/DlgAdvPreferencesBase.cpp
- clientgui/sg_DlgPreferences.cpp
Change text labels to remove inconsistency between them and button text as described in #601
> Manager: Change OK button on Advanced Preferences to Save button

- drupal/sites/all/features/boinc_standard/boinc_standard.views_default.inc
- drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/themes/boinc/templates/views-view-fields--boinc-friends--block-1.tpl.php
1. Community Stats: top users list uses boinc username.
1. Account dashboard, friends block: hover/alt/title text uses boinc username.
1. User profile images: hover/alt/title text uses boinc username.
https://dev.gridrepublic.org/browse/DBOINCP-254
> Drupal: Use BOINC username in place of Drupal username

- client/acct_mgr.cpp
- client/acct_mgr.h
- client/client_state.h
- client/cs_prefs.cpp
- lib/parse.cpp
- use std::string instead of malloced array for ACCT_MGR_OP::global_prefs_xml
- use copy_element_contents() instead of dup_element_contents()
to get global prefs.
The latter uses fgets instead of fgetc,
so it requires that close tag be on a line by itself.
TODO: don't use fgets anywhere in XML parsing.
- fix a bug in copy_element_contents() where it consumes an extra character
> Fix parsing of AM reply messages

- clientgui/AdvancedFrame.cpp
Fix menu item description as requested in #1033.
Also this fixes #770 because now it shows correct branded product link that should be opened.
> Manager: Fix menu item description.

- drupal/sites/default/boinc/themes/boinc/css/comments.css
Removes extra border from comment link when user cannot post comments to the Web site.
Found by Tristan in PR #2080.
> Drupal: Fix boinc theme css

- client/client_msgs.cpp
- client/main.cpp
- lib/diagnostics.cpp
**lib: set correct buffering mode after cycling logs**
After freopen() stream is fully buffered. In this mode client's log messages are written to stdoutdae.txt BUFSIZ (typically 512) bytes at a time.
Set stdout to line buffered mode after freopen() so that messages are written one line at a time.
Set stderr's buffering mode after making sure freopen() succeeded.
**client: explicitly flush stdout on all Windows builds**
stdout is set to line buffered mode but MSVCRT doesn't support this mode and uses fully buffered mode instead. MinGW uses MSVCRT but the code doesn't take this into account and as a result stdoutdae.txt is 
written BUFSIZ (typically 512) bytes at a time on MinGW builds.
Correct this by flushing stdout after every message regardless of which Windows compiler is used.
Fixes …
> client: fix writing log messages

- html/inc/submit.inc
- lib/submit_api.py
- sched/transitioner.cpp
- tools/backend_lib.cpp
- tools/create_work.cpp
If you specify the input or output templates,
the standard ones (appname_in, appname_out) don't need to exist.
Also, in create_work():
- don't read the output template; just check that it exists.
- deprecate the result_template_filepath arg; redundant
> job submission: don't error out if standard templates missing; change comment in transitioner

- api/MultiGPUMig.defs
- api/graphics2.cpp
- api/graphics2_unix.cpp
- api/macglutfix.m
- api/x_opengl.h
- clientscr/Mac_Saver_Module.h
- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/mac_saver_module.cpp
- clientscr/screensaver.cpp
- clientscr/screensaver.h
- mac_build/boinc.xcodeproj/project.pbxproj
BOINC screensavers have 2 parts. The BOINC "screensaver coordinator" is an actual "native" screensaver for MS Windows (boinc.scr) or Macintosh (BOINCSaver.saver). It communicates with the BOINC client via RPCs to determine which project applications (tasks) are currently running, and which of those have associated graphics executables. Depending on the user's screensaver preference settings, it cycles through the running tasks, launching one of the associated graphics executables at a time. The graphics executables usually communicate with their associated worker app to display information about the work being done by that task.
In addition to being run by the BOINC screensaver coordinator, users can run the graphics executables from the BOINC Manager via the "Show graphics" button when …
> Mac os10 3 screensaver fix

- client/client_state.cpp
In this case there are no fds in the central select, and it returns immediately.
Fix: if no fds, sleep instead of select.
> client: fix bug where client does tight loop if no_gui_rpc set

- client/boinc_cmd.cpp
- client/gui_rpc_server_ops.cpp
forgot to fclose().
Also have get_app_config() return error if no file.
Probably should do this for other get-file RPCs as well.
> client: fix bug in set_app_config GUI RPC

- clientgui/AsyncRPC.cpp
- lib/gui_rpc_client.h
* The nonstandard header <xlocale.h> has been removed.  Most programs should
use <locale.h> instead.  If you have a specific need for the definition of
locale_t with no other declarations, please contact
libc-alpha@sourceware.org and explain.
the old glibc seems to still build correctly, build ongoing in
https://code.launchpad.net/~costamagnagianfranco/+recipe/boinc-upstream-daily
> Fix build with new glibc 2.26

- clientgui/ViewResources.cpp
Also show the slice in the pie diagram if there is no more space available for BOINC.
Original patch by Pepo: http://boinc.berkeley.edu/trac/ticket/737
Fixes #714
> Manager: display zero free space in disk tab

- sched/Makefile.am
- sched/db_purge.cpp
The current `db_purge` pipes its output through external programs for compression, which leads to bad error handling and possible data loss (e.g. if the disk runs full). Add a compress option to use zlib to produce gz files without relying on an external program / pipe.
> db_purge: use zlib

- mac_build/BuildMacBOINC.sh
Fix bug in BuildMacBOINC.sh script when -all argument is implied but not explicitly passed
> Mac project: fix bug in BuildMacBOINC.sh script

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/contrib/privatemsg/privatemsg.module
BOINC usernames may contain any character, including commas. Now when the BOINC username is loaded, spaces are replaced by UTF-8 hex code: "\xc2\xa0", non-breaking space. This allows the code to use a regular space as a delimiter between usernames.
https://dev.gridrepublic.org/browse/DBOINCP-411
part of https://dev.gridrepublic.org/browse/DBOINCP-254
> Drupal: Delimiter changed to space.

- m4/sah_links.m4
The AFS filesystem does not allow hard links between files in different directories. We fall back to symbolic links in that case.
Fixes #1298
> Build: test if hard links are really working

- m4/boinc_wxwidgets.m4
Currently the build system will silently disable the Manager build when wxWidgets is missing or not a recent enough version.
Fix #1714
> Build: fail if wxWidgets lib can not be found but is required

- configure.ac
When using --prefix this override tries to install files from client/scripts to /etc instead of ${prefix}/etc. This is against what the user wants and leads to an error message as normally only root can install files to /etc. There is no need to be backwards compatible in this place as installs are usually done via repository packages.
This still uses /etc to determine where the config file should be copied to which is ok because the user most likely wants to use the Client on the machine it was built on.
Note: The startup scripts and config files in client/scripts are outdated and might not work on recent Linux distributions. Newer ones can be found in the Debian/Fedora packages.
fixes #1227
> Build: use default sysconfdir instead of /etc

- db/boinc_db.cpp
- db/boinc_db_types.h
- db/schema.sql
- html/inc/account.inc
- html/inc/boinc_db.inc
- html/inc/util.inc
- html/ops/db_update.php
- html/user/download.php
- html/user/login_token_lookup.php
- html/user/register.php
- version.h
Add the server parts of the scheme described here:
https://boinc.berkeley.edu/trac/wiki/SimpleAttach
This includes:
- add login_token table and function for creating login tokens
- add Web RPC login_token_lookup.php for mapping token to auth
- change concierge protocol to take project ID and login token
- update download.php so that it gets client version info
from versions.xml (from BOINC web site)
and displays buttons with OS name, versions and file sizes
like on the BOINC download page
- make "register.php" work
I've tested this all the way through downloading the installer file
with the augmented name.
Changes to the installer and client are needed to complete the system.
> Add server-side support for simplified register/download/attach

- db/boinc_db.cpp
In 90f8a1d4b4280ead1d7046efdcaa28eb603ca763 the p_ngpus and p_gpu_fpops fields were added to the host table, and make fields updation, but not the insertion.
On one server I got an error: Database error: Field 'p_ngpus' doesn't have a default value.
> Fixed insert into host

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
Removed the user emails from the RPC (following BOINC upstream).
Replaced `user_load()` function with two SQL queries to the BOINC and drupal databases.
https://dev.gridrepublic.org/browse/DBOINCP-413
part of
https://dev.gridrepublic.org/browse/DBOINCP-362
> Drupal: Improve team_email_list RPC

- html/user/download.php
Fixes issue #2224 and fixes bug where the download page renders a broken vbox download button when a platform doesn't have a vbox version (the fix is to not render the button)
> Fix missing user_id on download page

- client/gpu_opencl.cpp
Eliminates an arithmetic overflow in memory size calculation for AMD GPUs, causing issue #2226 _Mac AMD Compute Engines report negative memory_. This should be released as soon as possible as version 7.8.4 for Macs only.
> Mac OpenCL: fix memory size calculation for AMD GPUs

- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
Fixed bug returning a previously banned user to the role 'community member'.
https://dev.gridrepublic.org/browse/DBOINCP-416
> Drupal: Unbanned users set role 'community member'.

- html/inc/forum.inc
- html/inc/util.inc
- html/user/forum_edit.php
- html/user/forum_post.php
One form of spam involves putting lots of links in a post.
This lets you limit it by setting POST_MAX_LINKS in project.inc.
Limit doesn't apply to moderators.
> web: add option for limiting # of links per post

- lib/opencl_boinc.h
Hello,
I have locally crafted OpenCL support for a BOINC project running on my ARM machine's MALI GPU. This gives quite some bang for few bucks with minuscule power consumption and as such be of importance for BOINC at large.
For it all to work smoothly, I unexpectedly also had to patch the BOINC client - the char[64] vector storing the OpenCL version is too short for the version string produced by the Firefly, i.e. "OpenCL 1.2 v1.r13p0-00rel0-git(a4271c9).31ba04af2d3c01618138bef3aed66c2c" which admittedly is somewhat awkward with 72+1 characters. I hope that you decide to support the emerging diversity of new OpenCL platforms and accept patches for their support.
This patch trivially extends the length of the static array, which is all I needed to get started and does not interfere with …
> increased size of opencl_device_version[] from 64 to 128

- client/hostinfo_unix.cpp
- mac_installer/complist.plist
Fixes a bug which caused BOINC client built with SDK OS 10.11 or later to fail to get correct system RAM size when running on older versions of OS X. This should also be cherry picked to master for BOINC version 7.9.
Also replicates commit 5296088 previously made in master into 7.8 branch: correctly replace screensaver when installing an older version of BOINC to replace a newer version.
> Mac ram size hotfix

- mac_build/HowToBuildBOINC_XCode.rtf
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/buildWxMac.sh
- mac_build/buildc-ares.sh
- mac_build/buildcurl.sh
- mac_build/buildfreetype.sh
- mac_build/buildopenssl.sh
- mac_build/buildsqlite3.sh
- mac_build/dependencyNames.sh
In preparation for building and testing BOINC 7.9.0 for the Mac, update the following third party dependencies:
SQlite 3.11.0 -> SQlite 3.22.0
cURL 7.50.2 -> cURL 7.58.0
c-ares 1.11.0 -> c-ares 1.13.0
OpenSSL 1.1.0 -> OpenSSL 1.1.0g
FreeType 2.6.2 -> FreeType 2.9
I have previously updated wxWidgets 3.0.0 -> wxWidgets 3.1.0
Also:
* Build only 64-bit libraries for wxWidgets and SQLite, instead of 32-bit / 64-bit "universal" libraries. This will reduce the time to build them and reduce the storage requirements for Travis CI.
* Eliminate patching curlrules.h which was needed to build 32-bit BOINC Manager.
> Mac update dependencies

- client/boinc_cmd.cpp
- client/gui_rpc_server_ops.cpp
- lib/gui_rpc_client.h
- lib/gui_rpc_client_print.cpp
New commands:
--acct_mgr info: show name and URL of current AM
--acct_mgr synch: do RPC
also (for uniformity) new names for existing commands:
--acct_mgr attach URL email password
--acct_mgr detach
Tempted to remove old names, but didn't.
> Add boinccmd commands to do acct mgr RPC, and to show acct mgr info

- appveyor.yml
Add 'skip_commits' section to skip commits that are not related to Windows builds.
This PR contains changed to skip on;y most used folders and do not contain ones that are changed very rare.
> [AppVeyor] Skip commits that are not related to Windows build

- mac_build/buildFTGL.sh
- mac_build/buildcurl.sh
Mac: Eliminate needing to update the script which build cURL for each new version of c-ares or OpenSSL; get the names of current c-ares and OpenSSL directories from dependencyNames.sh.
This will reduce the likelihood of errors caused by forgetting to manually update this script.
> Mac: Automate updating cURL build script

- lib/gui_rpc_client_print.cpp
Also only show relevant info.
E.g. don't show exit status of a job that hasn't finished.
> boinccmd: show CPU/GPU resources in --get_task

- .travis.yml
- 3rdParty/buildLinuxDependencies.sh
- 3rdParty/buildWxLinux.sh
- clientgui/DlgEventLog.cpp
- clientgui/DlgItemProperties.cpp
- clientgui/DlgItemProperties.h
- clientgui/NoticeListCtrl.cpp
- clientgui/NoticeListCtrl.h
- clientgui/stdwx.h
Some Linux distributions are dropping webkitgtk support which is needed for wxWebView to work. This will build a second wxWidgets cache that has no webview support in order to test new code.
This should in the end combine #2093, #2104 and the [Debian patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=876940;filename=boinc-no-webview.patch;msg=5) and build two managers. One with webview support and one without.
> make webview support optional

- client/hostinfo_unix.cpp
- client/hostinfo_unix_test.cpp
Try to execute ldd on Linux like systems to gather the libc version installed and report it as part of host.os_version using the same pipe delimited format that is also used in host.serialnum.
A sample entry looks like this: "Debian GNU/Linux 9.1 (stretch) [4.9.0-3-amd64|libc 2.24 (2.24-11+deb9u1)]" where the OS version and codenames, kernel version and libc version information are accessible for use in plan_class restrictions or help in troubleshooting problems by project admins.
closes #2064
> Client: gather libc version on Linux

- clientgui/DlgEventLog.cpp
- clientgui/DlgEventLogListCtrl.cpp
- clientgui/DlgEventLogListCtrl.h
On Windows, `wxListCtrl` has a bug that makes it draw selected unfocused rows with colors used for selected focused rows when the row background color is `wxSYS_COLOUR_BTNFACE`.
With default color schemes, on Windows XP the list is drawn correctly, but on Windows 10 the `(240,240,240)` used in stripe color is coincidentally the same as `wxSYS_COLOUR_BTNFACE` and selected rows are drawn with wrong colors.
Fix this by using the same stripe color that wxWidgets would use by default and that is used in Projects, Tasks and Transfers lists. Future proof the code by including a workaround just in case Windows changes color scheme again. If such color scheme change occurs then the same workaround needs to be added to Projects, Tasks and Transfers lists.
Fixes #1083.
To support the above change …
> mgr: fix eventlog colors

- .gitignore
- client/scripts/Makefile.am
- client/scripts/boinc-client.service.in
- configure.ac
Both Fedora and Debian have their own systemd units for boinc;
this is based on elements of both so we stop duplicating effort.
Closes: #2255
> Add generated systemd unit

- sched/credit.cpp
... and reverted to old way of estimating job FLOPs.
Not sure why this was there.  1 is a perfectly valid ID.
> Credit calculation: remove old code that ignored result.app_version_id =1.  Fixes #2333

- client/client_types.cpp
- client/client_types.h
- client/cs_scheduler.cpp
- sched/plan_class_spec.cpp
- sched/sched_customize.cpp
- sched/sched_types.cpp
- sched/sched_types.h
avg_ncpus is always used instead.
Note: there are two other things named "max_ncpus".
One is a computing prefs field (limit on # of CPUs to use).
The other, a field of SCHED_CONFIG,
is the max # of CPUs the scheduler will believe a client has
in deciding how many jobs to send it.
> Remove HOST_USAGE.max_ncpus.  It's not used anywhere.

- mac_build/buildFTGL.sh
Ensure that buildFTGL.sh script marks FTGL library as compatible with OS 10.6 even when built using Xcode 9.2 under OS 10.13
> Mac: fix linker warning with Xcode 9.2 under OS 10.13

- tools/update_versions
An executable may have more than one string that contains
"API_VERSION" such as:
API_VERSION_7.7.0
API_VERSION
LPAPI_VERSION
If there is more than one string update_versions extracts the
version number from the first one and then puts the version number
and the rest of the strings into <api_version>:
<api_version>7.7.0
API_VERSION
LPAPI_VERSION</api_version>
Change update_versions to extract only those strings that look like
BOINC's API_VERSION and only the first one if there for some reason
is more than one such string.
Fixes #2121.
This commit adapts 7a35b69c642677d048329c0cff56bce8627df55b to the
new PHP version of update_versions.
> update_versions: handle multiple API_VERSION strings

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
- drupal/sites/default/boinc/modules/boincteam/boincteam.module
- drupal/sites/default/boinc/modules/boincteam/includes/boincteam.helpers.inc
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
- drupal/sites/default/boinc/modules/boincwork/boincwork.module
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
- drupal/sites/default/boinc/modules/contrib/privatemsg/pm_block_user/pm_block_user.module
- drupal/sites/default/boinc/themes/boinc/boinc.info
- drupal/sites/default/boinc/themes/boinc/css/forms.css
- drupal/sites/default/boinc/themes/boinc/css/privatemsg-view.css
- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/privatemsg-view.tpl.php
- drupal/sites/default/boinc/themes/boinc/templates/user-profile.tpl.php
Privacy form now contains feature to ignore users, both in the forums and for private messages. There is a current list of ignore users and user may add more to the table. When another user ignored, they are also automatically added to the table which prevents them from sending a PM to the user who ignored them.
In addition, an ignore user button has been added to the user profile page, and to the private message view page, so that users may more easily ignore another.
https://dev.gridrepublic.org/browse/DBOINCP-338
> Drupal: Allow users to ignore private messages.

- mac_build/buildc-ares.sh
- mac_build/buildcurl.sh
Mac: Patch ares_config.h and curl_config.h to not use clock_gettime() which is  defined in OS 10.11 SDK but was not available before OS 10.11. This caused the client built on OS 10.11 or OS 10.12 to crash on launch when run on older versions of OS X.
After this is merged into master, the changes needs to be cherry-picked into the client_release/7/7.10 branch before tagging for version 7.9.3.
> Fix client crash on Mac OS 10.6 - 10.11 when built under OS 10.12 or later

- html/inc/util.inc
This reverts commit 1140ec069daae827509ea17e07dfca5aa1b2dd1f.
I'm trying to get the following working: When accessing the site over http, I want to serve the stylesheet over http. When accessing over https, I want the sylesheet over https. 
With the above commit, that becomes impossible, since the sytlesheet is always served over https (and this breaks the site in cases where the https access is impossible). 
I'm wondering what was the rationale for the commit in the first place? If it was for kind of a blanket redirect, I think the correct method would really be https://wiki.apache.org/httpd/RedirectSSL. If that's the case, then I'd recommend we revert the commit (which can be done by accepting this PR). If it was for something else, then could you let me know for what and I can try to …
> Revert "web: always use secure URL base if available."

- client/file_names.cpp
For example, if you rename account_X.xml to account_X.xml.bak,
if should not be reported as an error.
Same for statistics files.
> client: not an error if a file starts with account_ but is not accounting file

- drupal/sites/default/boinc/modules/boincteam/boincteam.module
- drupal/sites/default/boinc/modules/boincuser/boincuser.views.inc
View boinc_users to use boinc_ro replica DB. 
Some boinc_teams sub-views set to use replica DB as well, on a title-by-title basis.
> Drupal: Set additional Views to use replica DB.

- drupal/sites/all/features/boinc_standard/boinc_standard.features.inc
Update rules to include different rules for when a forum topic is moved, renamed, edited, marked (un)sticky, or (un)locked.
https://dev.gridrepublic.org/browse/DBOINCP-298
> Drupal: Rules updates

- drupal/sites/default/boinc/modules/boincteam/boincteam.admin.inc
- drupal/sites/default/boinc/modules/boincteam/boincteam.module
This adds a page to the Drupal admin interface to delete suspected SPAMMER teams.
https://dev.gridrepublic.org/browse/DBOINCP-364
> Drupal: Add team  delete utility for SPAMMER teams

- drupal/sites/default/boinc/modules/boinctranslate/includes/boinctranslate.helpers.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
Add custom trim function to code where the strings in the project-specific XML are aded to translation table(s).
Custom function removes whitespace from beginning and end of each line, separated by newline.
https://dev.gridrepublic.org/browse/DBOINCP-418
> Drupal: Trim strings in project-specific XML to help translators.

- mac_build/buildWxMac.sh
This patches wxWidgets 3.1.0 on the Mac to fix the bug reported by @DPhilippe4 in PR #1554. This bug was introduced in the Mac (wxCocoa) port of wxWidgets 3.1.0, and has been fixed in wxWidgets 3.1.1. But I feel it is too late in the BOINC 7.10 release cycle to upgrade wxWidgets to 3.1.1 as it won't get adequate testing. (For example, this fairly obvious problem with wxWidgets 3.1.0 was not noticed until the third alpha release 7.9.3; it was not reported in 7.9.1 or 7.9.2 though present in both.)
While analyzing this bug, I have been experimenting with wxWidgets 3.1.1 and found that several changes are needed to BOINC source code to upgrade from 3.1.0 to 3.1.1. I will put those in a separate feature branch for inclusion in the 7.11 / 7.12 release cycle.
>  Mac: Fix wxWidgets 3.1.0 Mac-only bug when wxStaticBox has no label

- clientsetup/win/CAShutdownBOINCManager.cpp
Cppcheck found this issue: Multiplying sizeof() with sizeof() indicates a logic error.
GetWindowText expects the number of characters (3. argument) that fit into the buffer (2. argument).
So a division seems to be correct here instead of a multiplication.
> Fix buffer size for call of function GetWindowText

- html/inc/web_rpc_api.inc
Projects with old server code reply with PHP warnings
interspersed with the XML.
Parse these replies manually.
> create_account web RPC: improve parsing and error handling

- sched/target_batch.cpp
[sched/target_batch.cpp:182]: (warning) printf format string requires 1 parameter but 2 are given.
> cppcheck: printf format string

- client/client_state.cpp
- client/cs_cmdline.cpp
- client/http_curl.cpp
- clientgui/mac/config.h
The client shows what kind of operating system it has detected in startup log message and elsewhere. This is confusing and not helping in troubleshooting when people expect these messages to describe the client itself.
Change the messages to use client's build platform instead.
Startup log message, output of --version and user agent string should be safe to change without breaking anything. The client still uses OS platform in various places but changing these would break stuff:
- Scheduler request XML. Scheduler expects scheduler_request.platform_name to be OS primary platform.
- client_state.xml. Client writes OS primary platform and alt platforms separately to client_state.xml. The client reads primary platform only to see if it has changed. The client doesn't read alt platforms but …
> client: show build not OS platform in messages

- html/inc/util.inc
Allow projects to show (non-DB) content even if stop_web is present
(e.g. description of the project on front page).
stop_web really means "the DB is offline".
> web: don't check for stop_web in page_head().

- drupal/sites/default/boinc/themes/boinc/template.php
Sets locality to `en` if locality variable does not exist.
https://dev.gridrepublic.org/browse/DBOINCP-433
> Drupal: Fix bug when there is no language, a default flag should appear.

- client/acct_mgr.cpp
- client/acct_mgr.h
- client/cs_scheduler.cpp
- client/gui_rpc_server_ops.cpp
- client/project.cpp
- client/project.h
- client/rr_sim.cpp
- client/rr_sim.h
- client/scheduler_op.cpp
- client/scheduler_op.h
Currently, this affects only clients using Science United
> client: if using a dynamic AM and have idle resources, tell the AM

- lib/remote_submit.cpp
Commit SHA:381e0caf1489b5d1190563e96ce95f64bc385265 changed the XML RPC for remote submission by removing the superfluous batch tag. This change aligns the remote submission library with the modified RPC.
>  remote job submission: fix create_batch XML after API change

- html/inc/util.inc
on pages with lots of text, to make it more readable.
Width is a parameter, default 640.
> web: add functions text_start() and text_end() to limit line length

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
Changed `user` to `user_util` to match changes due to commit below.
This change is due to : https://github.com/BOINC/boinc/commit/e712c7af9ac5b4f9c16d691e656788a2112cefe3
Fixes: https://dev.gridrepublic.org/browse/DBOINCP-441
> Drupal: Change library names

- clientgui/ProjectInfoPage.cpp
- clientgui/ProjectInfoPage.h
- clientgui/wizardex.cpp
- clientgui/wizardex.h
When opening 'Add Project' wizard it shows next fields empty:
Research area, Organisation, and Web site.
This happens because of EllipseStringIfNeeded() function that truncates the string to 0 symbols because the wizard window was not constructed yet and has undefined size.
This fixes #2444.
> [Manager] Fix fields populating on 'Add Project' wizard on launch

- html/inc/friend.inc
- html/inc/user.inc
- html/ops/delete_user.php
- html/user/delete_account.php
- html/user/show_user.php
This leaves the user record and host records in the DB
to avoid dangling references from the result table.
It:
- changes the user name, email addr, and auth to "deleted_xxx"
- removes the user from team
- removes posts by the user
- removes PMs by the user
- removes friend connection
- removes profile
- "anonymizes" the hosts (erase IP addr and domain name)
Note 1: this is accessed by admins using a script in ops/;
It's not available to users.
Note 2: this may not satisfy the requirements of EU-GDPR
since it doesn't delete the user and host records.
> Add a mechanism allowing project admins to "delete" a user

- html/inc/util.inc
- html/inc/util_basic.inc
PHP utilities that aren't web-specific should go in util_basic.inc
> move random_string() and dtime() from util.inc to util_basic.inc

- html/user/submit_rpc_handler.php
Obtain the rsc_fpops_est from the job_params when using remote submission to avoid  the _no rsc_fpops_est given_ error.
> Obtain the rsc_fpops_est from the job_params

- lib/Makefile.am
When building the core boinc library on OSX it seems it is missing some files.
The library builds ok, but when linking to an external program I get linker errors on spawn().
Adding these files to the Makefile.am makes the problem go away :)
> Add missing mac_spawn entries to lib/Makefile.am

- sched/make_work.cpp
- sched/validate_util.cpp
- sched/validator.cpp
- tools/create_work.cpp
- tools/stage_file
You can now pre-assign a job's credit, as described here:
https://boinc.berkeley.edu/trac/wiki/CreditOptions
Note: this feature was originally available via an
--additional_xml "<credit>xx</credit>" arg to create_work.
This is an ugly kludge; I removed it.
In fact, the --additional_xml arg should be removed at some point.
Also: change stage_file to it cd's to html/bin when including stuff;
this is needed since util_basic.inc now includes something else
> Server: add support for pre-assigned credit

- db/boinc_db_types.h
- sched/credit.h
- sched/validate_util2.h
- sched/validator.cpp
Add --post_assigned_credit option to validator.
If set, it gets claimed credit from result.claimed_credit
(put there by project's init_result() function).
The claimed credit of the canonical result is the job's granted credit.
Also changed --credit_from_runtime so that it averages
claimed credit across instances,
instead of just using the canonical instance.
> Server: add support for post-assigned credit

- clientgui/AccountInfoPage.cpp
If while using Wizard try to login to the project with wrong credentials
'Next' button is disabled forever.
This is fixed by enabling 'Next' button on AccountInfoPage by default.
> [Manager] Fix 'Next' button on previous pages after failed login

- clientgui/TermsOfUsePage.cpp
- clientgui/TermsOfUsePage.h
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- lib/parse.cpp
Terms Of Use can be displayed now as HTML as well as plain text.
Fixed xml_unescape function to support escaped \r and \n tags.
Enlarged the size of Terms Of Use field to fill all wizard page.
> [WIP] [Manager] Add HTML TOU support to Wizard

- drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
- drupal/sites/default/boinc/modules/boincwork/boincwork.module
Part of: https://dev.gridrepublic.org/browse/DBOINCP-428
> Drupal: Make the get_project_config terms of use overridable.

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Part of https://dev.gridrepublic.org/browse/DBOINCP-429
> Drupal: Delete expired tokens in the token table.

- client/hostinfo_unix.cpp
The code tries to open /dev/input/mice as if it was a directory. If
there are no input devices, like in a headless machine, the code
repeatedly tries to make a list of input devices. On Debian, these bugs,
together with Debian's patches to BOINC, result in useless error
messages in client's log.
On SELinux systems, services can access device nodes in /dev/input/ only
if given that right in SELinux configuration. On some Fedora versions
BOINC client doesn't have that right and the code results in numerous
SELinux warnings. These warnings in turn result in high CPU usage when
the system analyzes the warnings.
Furthermore, the code doesn't work at all. The code expects that input
drivers update timestamps on device nodes when the drivers receive input
from devices. The input drivers however …
> client: remove /dev/input/ based idle detection

- html/inc/boinc_db.inc
In apps.php treat beta app versions independently of non-beta app versions, even if these have the same plan class. This is consistent with what the (array) scheduler does (try 'beta' apps first (with highest version number per plan class), then 'non-beta' (dito)).
> web: fix beta app version handling in apps.php page

- clientgui/AdvancedFrame.cpp
- clientgui/BOINCGUIApp.cpp
- clientgui/BOINCGUIApp.h
- clientgui/mac/BOINCGUIApp.mm
- clientgui/mac/SetupSecurity.cpp
- clientgui/sg_BoincSimpleFrame.cpp
- clientscr/mac_saver_module.cpp
- clientscr/ss_app.cpp
- mac_installer/AddRemoveUser.cpp
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
The current code includes the knowledge of four brands for the Mac applications: BOINC, Grid Republic, Progress thru Processors, and Charity Engine. This pull request includes the changes needed to add a fifth brand for WCG. This will allow Mac installers built with these changes to overwrite the WCG branded manager and screen saver when they are developed in the future. The changes to allow for the building of a WCG branded installer will be included in a future pull request.
> Code changes needed to add the WCG brand for the mac applications

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Buggy RPC regression introduced recently. Authenticator not returned for existing accounts.
> Drupal: Fix create_account RPC.

- client/Makefile.am
- client/client_state.cpp
- client/hostinfo_win.cpp
- client/hostinfo_wsl.cpp
- lib/Makefile.am
- lib/Makefile.mingw
- lib/cc_config.cpp
- lib/cc_config.h
- lib/hostinfo.cpp
- lib/hostinfo.h
- lib/wslinfo.cpp
- lib/wslinfo.h
- win_build/boinc_os_ss.vcxproj
- win_build/boinc_os_ss_vs2013.vcxproj
- win_build/boincmgr.vcxproj
- win_build/boincmgr_vs2013.vcxproj
- win_build/libboinc.vcxproj
- win_build/libboinc_staticcrt.vcxproj
- win_build/libboinc_staticcrt_vs2013.vcxproj
- win_build/libboinc_vs2013.vcxproj
- win_build/sim.vcxproj
- win_build/sim_vs2013.vcxproj
- win_build/wcg_boinc_os_ss.vcxproj
- win_build/wcg_boincmgr.vcxproj
Move WSL detection to get_host_info().
Enumerate available WSLs from registry.
Add wslapi library loading.
Add support of multiple installed wsl distros detection.
Detect only installed and configured distros.
Add extra information parse.
Add wslinfo files to save and parse wsl info.
Add dont_use_wsl param to cc_config.
Add missed hostinfo_wsl.cpp when building win client using gcc.
Fix small issues.
Small refactoring.
> [Client] [WSL] Extend detection.

- clientgui/BOINCGUIApp.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/AddRemoveUser.cpp
- mac_installer/Installer.cpp
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
Fixes to installer for issues under OS 10.13 High Sierra when multiple users are to be allowed to run BOINC Manager
- fix setting or deleting Login Items for users other than the one running the installer
- fix setting the screensaver for users other than the one running the installer
This situation probably occurs fairly infrequently, but I recently noticed these problems when running the Mac installer, Uninstaller, and AddRemoveUser utility under OS 10.13. As far as I have been able to determine, these problems do not occur on earlier versions of OS X.
It may be desirable to back port these fixes to BOINC 7.10 once they are complete.
> [WIP] Mac: fixes to installer for issues under OS 10.13 High Sierra

- html/project.sample/project.inc
- html/user/download.php
- html/user/forum_forum.php
- html/user/forum_index.php
- html/user/join.php
- html/user/prefs.php
- html/user/sample_index.php
- html/user/welcome.php
New and improved registration flow.
Account creation is now done by default on the web, not in the BOINC Manager.
We can add consent stuff here as needed.
For projects that are vetted, and that put their project ID in config.xml,
the autoattach feature now works.
This means that new users (downloading BOINC for the first time)
will be pre-attached to the project when BOINC first runs.
No need for a separate attach/login in the Manager.
I've deployed this on SETI@home; seems to work as intended.
> Updated registration flow

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
This code change will make the Drupal web code match the upstream Web code (PR #2500) for user's email address change. The workflow is described in the [boinc wiki](https://boinc.berkeley.edu/trac/wiki/EmailChangeNotification).
https://dev.gridrepublic.org/browse/DBOINCP-436
> Drupal: Harden email change procedure

- html/inc/util.inc
- html/user/get_project_config.php
BOINC web code [refactored `$master_url` into a global variable](https://github.com/BOINC/boinc/commit/5ea948224ea15ea53bd8167c78e331951d9e1ece). The E@H Drupal installation breaks due to this change. This is due to the scope of the variable not being explicitly set  as global. The functional result is that get_project_rpc does not return the master_url for the E@H project. We believe we're the only ones affected due to our Drupal Web front-end.
If these two small changes are made, this should fix the get_project_config RPC for us. I doubt this will negatively affect the rest of the BOINC html web code, but if someone could check that would be great.
> web rpc: Added global scope to master_url variable.

- client/cs_statefile.cpp
- client/log_flags.cpp
set client state option on re-read
disable anonymous platform wsl plan classes when wsl not permitted
> Fixes for WSL subsystem

- .tx/config
- locale/update_translations.sh
- No testmode anymore as this was unpractical
- added instructions what to check since not everything is automatable
- translations are pulled from transifex when 97% complete. This proved practical in the last release.
- added simple po file check to prevent incorrect tabs and printf problems from translations (potential to break the manager)
> Locale: enhance translation update script

- lib/win_util.cpp
When `MultiByteToWideChar` and `WideCharToMultiByte` are told to process entire input strings the functions include null terminators in required buffer sizes. `std::string` on the other hand stores embedded null characters in the string it manages if it's requested to do so.
The way the code constructs `std::string`s from wide char function outputs makes null terminators part of the strings. This breaks concatenating strings together.
Fix the code by not copying the last character, i.e. the null terminator, to `std::string`.
> lib: fix wide char conversion functions

- clientgui/DlgAbout.cpp
Manager: in the About dialog "For more information, visit" hyperlink, set the value of the link to the same string as the text displayed for the link when using a branded skin.
NOTE: Despite the "mac" in the name of this branch, this fix is needed for all platforms.
> Manager: Fix branded link in About Dialog

- html/inc/host.inc
This adds a row to the host info page that tells the user what version of Virtualbox they have, if they have hardware virtualization support available and whether it is enabled. Having this should make it much easier for users to debug problems stemming from the fact that their CPU doesn't have hardware support or they have it disabled.
> add virtualization info to host info page

- client/check_security.cpp
- clientgui/AdvancedFrame.cpp
- clientgui/mac/SecurityUtility.cpp
- clientgui/mac/SetupSecurity.cpp
- clientgui/sg_BoincSimpleFrame.cpp
- clientscr/mac_saver_module.cpp
- clientscr/ss_app.cpp
- lib/mac/mac_branding.cpp
- lib/mac/mac_branding.h
- lib/procinfo_mac.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/AddRemoveUser.cpp
- mac_installer/Installer.cpp
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
Mac: Consolidate branding strings in one source file and one header file shared among all files which use them; add checks for missing branding strings.
> Mac: Consolidate branding strings

- sched/script_validator.cpp
Current script_validator implementation contains next statements:
`sprintf(cmd, "../bin/%s", init_script[0].c_str());`
and
`sprintf(cmd, "../bin/%s", compare_script[0].c_str());`
It is dangerous to use this arrays
that are filled by parsing command line
without validating whether they contain any elements
and leads to next behavior:
Program received signal SIGSEGV, Segmentation fault.
```
0x000000000040f838 in compare_results (r1=..., r2=..., match=match@entry=@0x7ffffffb6c17: false) at script_validator.cpp:154
154	script_validator.cpp: No such file or directory.
(gdb) bt
#0  0x000000000040f838 in compare_results (r1=..., r2=..., match=match@entry=@0x7ffffffb6c17: false) at script_validator.cpp:154
#1  0x000000000040e85d in check_set (results=std::vector of length 2, capacity 2 = {...}, …
```
> script_validator segfault fix

- mac_build/Mac_SA_Insecure.sh
- mac_build/Mac_SA_Secure.sh
Mac: update comments in mac_sa_secure.sh script to clarify that it should be run in BOINC Data directory
> Mac: clarify comments in mac_sa_secure.sh script

- sched/plan_class_spec.cpp
- sched/plan_class_spec.h
- sched/sched_customize.cpp
- sched/sched_customize.h
- sched/sched_version.cpp
filters <min_wu_id>, <max_wu_id>, <min_batch>, <max_batch> and <disabled>
This is a essentially a copy of #2000 which was merged prematurely (with an unfinished discussion) and later reverted in #2002 (without any discussion).
- WU information is passed from check_homogeneous_app_version() down to PLAN_CLASS::check()
- wu_is_infeasible_custom() is extended such that additional tasks also follow the plan class restrictions.
> plan classes: add workunit-related filters

- mac_installer/AddRemoveUser.cpp
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
mac installer: change pkill() calls to killall() because pkill() was not available before OS 10.8.
When installing BOINC on OS 10.6 or OS 10.7, using pkill() to kill the previous instance of BOINC Manager failed. Changing pkill() calls to killall() fixes this bug.
> mac installer: change pkill() calls to killall()

- client/client_state.cpp
- client/client_state.h
- client/cs_statefile.cpp
- client/current_version.cpp
- client/current_version.h
- client/file_names.h
- client/main.cpp
- mac_installer/preinstall
- win_build/installerv2/redist/default/nvc_config.xml
client: save a copy of nvc_config.client_version_check_url in client_state.xml file, eliminating need for installer to rename previous nvc_config.xml to old_nvc_config.xml.
newer_version_startup_check() compares gstate.client_version_check_url to nvc_config.client_version_check_url. If different, it clears gstate.newer_version and updates gstate.client_version_check_url.
This supersedes part 2 of [this comment](https://github.com/BOINC/boinc/pull/2603#issuecomment-405083071) in my earlier PR #2603.
> Eliminate need for installer to rename previous nvc_config.xml to old_nvc_config.xml

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
When saving community preference form: the user_profile is loaded. If it does not exist, there should be no 'node_save()' function call, otherwise empty nodes are created.
https://dev.gridrepublic.org/browse/DBOINCP-437
> Drupal: Fixed bug in community pref form.

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
User will not see this form element because only admins may access it; users may still change their username in the Community Preferences form.
Fixed some spelling errors and bts() problems.
Part of: https://dev.gridrepublic.org/browse/DBOINCP-435
> Drupal: Allow Admin to change BOINC username of another user.

- samples/condor/boinc_gahp.cpp
In our BOINC adapter, we made a change so that the unzip command
does not produce any output and will not stop to ask questions.
This is appropriate for the HTCondor batch system. We have been using
this change since April 18, 2014.
> Update HTCondor sample code

- tools/make_project
Making Apache v2.4 the default as v2.2 is not longer supported.
> Update apache configuration in make_project

- drupal/sites/all/features/discussion_forums/discussion_forums.features.user_permission.inc
- drupal/sites/default/boinc/modules/boinccore/boinccore.module
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.info
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.module
- drupal/sites/default/boinc/modules/contrib/forum_access/forum_access.node.inc
- drupal/sites/default/boinc/themes/boinc/templates/views-view--boinc-team-forum-topics.tpl.php
Modified module to add feature: user may comment on own topics.
If a user has permission to create a new forum topic, s/he has permission to write comments on that forum topic only. They will not have permission to add comments elsewhere.
Feature updated with new site-wide permissions to allow 'community member' role to create forum topics and make comments.
Forum ACL will need to be set to restrict the 'community member' role to specific forums.
https://dev.gridrepublic.org/browse/DBOINCP-455
> Drupal: Improve forum ACL to allow new user to post in limited forums.

- lib/prefs.cpp
> [Client] Change default end time in daily schedules from 23:59 to 24:00

- android/BOINC/app/src/main/res/values-az/strings.xml
Fix android translation in values-az resource.
Update translation from [transifex](https://www.transifex.com/boinc/boinc/translate/#az/android/93866005?q=key%3Aprojects_credits_host_and_user) to fix format syntax.
> Fix android translation in values-az resource

- .travis.yml
- mac_build/buildMacBOINC-CI.sh
- mac_build/buildcurl.sh
Instead of excluding unwanted jobs this now specifically includes the jobs needed. This allows to run multiple environments or languages within a single repository. This is not fully documented but was confirmed to be supported by Travis via email.
Configuration can be tested on this page: http://config.travis-ci.org/
Original idea came from this blog entry: http://axelnilsson.tech/2017/08/04/travisci-with-multi-language-repository/
A problem with `libcurl` and the updated Travis CI OSX VM occurred because the buildcache needed to be rebuilt. Therefore I added some code to get more information from failed builds and fixed the problem with `libcurl`.
> Travis: restructure travis configuration

- client/cs_benchmark.cpp
Use std::vector instead of allocated piece of memory to store multiple objects.
This hopefully fixes crash originally described in #2646 with heap destruction while copying data and next stacktrace:
>	msvcr100d.dll!_CrtDbgBreak()  Line 85	C
msvcr100d.dll!_VCrtDbgReportW(int nRptType, const wchar_t * szFile, int nLine, const wchar_t * szModule, const wchar_t * szFormat, char * arglist)  Line 502	C
msvcr100d.dll!_CrtDbgReportWV(int nRptType, const wchar_t * szFile, int nLine, const wchar_t * szModule, const wchar_t * szFormat, char * arglist)  Line 242	C++
msvcr100d.dll!_CrtDbgReportW(int nRptType, const wchar_t * szFile, int nLine, const wchar_t * szModule, const wchar_t * szFormat, ...)  Line 258 + 0x2c bytes	C++
msvcp100d.dll!std::_Debug_message(const wchar_t * message, const wchar_t * …
> [WIP] Fix cs_benchmark.cpp heap destruction

- client/acct_mgr.cpp
- client/acct_mgr.h
- client/main.cpp
- client/project.cpp
If the AM is "dynamic", show those for projects attached via AM,
rather than e.g. "Science United user 123456".
> client: parse and store user and team name from account manager.

- db/constraints.sql
- html/ops/db_update.php
When a user has a very large number of hosts attached to a project (i.e. at least 50k), the scheduler requests can slow down as the existing index on userid still returns a significant number of records that have to be checked.  These two indexes address the issues associated with this situation.
See discussion in boinc-projects: https://groups.google.com/a/ssl.berkeley.edu/forum/#!topic/boinc_projects/Z59_4zIrSXE
> Add indexes to host table

- .gitignore
Visual Studio 2015/2017 use new cache/options directory .vs in the root of solution directory and should be ignored
> Fix .gitignore by adding .vs folder

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
strtolower() used on all email addresses input. All passwords are now hashed using lower-case email address.
User may chose an email with upper-case letters, but it will be saved lower-case in the project database.
https://dev.gridrepublic.org/browse/DBOINCP-461
> Drupal: Fixed bug where upper-case letters in email address broke login.

- drupal/sites/default/boinc/modules/boincuser/boincuser_quote/boincuser_quote.info
- drupal/sites/default/boinc/modules/boincuser/boincuser_quote/boincuser_quote.install
- drupal/sites/default/boinc/modules/boincuser/boincuser_quote/boincuser_quote.module
This small module does one thing: it atlers the comment form to replace the drupal username with the BOINC display name, when quoting another user in the forums.
Module weight is +1 to ensure it activates after the 'quote' module.
https://dev.gridrepublic.org/browse/DBOINCP-284
> Drupal: Added boincuser_quote module.

- .travis.yml
- integration_test/executeTestSuite.sh
- integration_test/installTestSuite.sh
This spins up a project using docker and runs some PHPUnit based tests against it.
> Travis: Add integration testing to Travis CI

- clientgui/sg_DlgPreferences.cpp
- clientgui/sg_DlgPreferences.h
Changes match those applied to the advanced dialog in #2585:
Make 'Save' the default button if (and only if) the user already has local preferences active
Show confirmation dialog when (and only when) switching from web to local preferences
> [GUI] Tune simple preferences dialog

- client/acct_setup.cpp
- client/hostinfo_unix.cpp
- client/hostinfo_unix_test.cpp
Some of these strcpy and strcat were added after the security scan.   Also, we have utilized safe_strcpy and safe_strcat when doing set quotes, which is why while fixing a few lines I did more in hostinfo_unix and hostinfo_unix_test files.
> Change strcpy to use the safe_strcpy and strcat to use safe_strcat

- .gitignore
Microsoft Visual Studio Code is a very useful and popular IDE.
This commit adds .vscode folder to .gitignore.
> Improve .gitignore by adding .vscode folder

- lib/coproc.cpp
for new architectures released since 2014, including RTX range released September 2018
> client/scheduler: update NVidia detection

- client/gpu_detect.cpp
- client/main.cpp
- configure.ac
- lib/filesys.cpp
- lib/filesys.h
- lib/util.cpp
Launching GPU detection has a few issues.
- doesn't work reliably with `--detach_console`
- doesn't work if client is run from `$PATH`
- if it fails the user is presented with hard to understand error code
- the code throws compiler warnings
This PR fixes those issues. To support the fixes `get_real_executable_path()` is implemented for several more operating systems and `run_program()` is changed to use `$PATH`. See individual commit messages for details.
Fixes #2657.
> client: fixes for launching GPU detection

- html/user/add_venue.php
While testing and allowing PHP to report warnings, attempts to create a venue resulted in the following being shown on the page:
Warning: Creating default object from empty value in /root/project/html/inc/prefs_project.inc on line 395
This is because the variable $new_prefs was not defined before being passed into prefs_project_parse_form and the application was relying on implicit object creation.
This change initializes $new_prefs before passing it in so that the warning is not triggered.
> Web: Eliminate PHP warning

- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/mac_saver_module.cpp
- mac_installer/ReadMe.rtf
I need to do more testing before removing the [WIP]. 
Since OS 10.14 Mojave was released several days ago and we have already received bug reports about this, should we merge this into the 7.12 branch and issue a hot fix for BOINC on the Mac once my testing is complete?
> Mac: screensaver fixes for OS 10.14 Mojave

- drupal/sites/all/features/user_profiles/user_profiles.views_default.inc
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
Only verified contributors, users with at least 1[*] credit, may create or modify user profiles. Also moderators may edit user profiles.
* adjustable in admin interface, but defaults to 1 credit.
Part of
https://dev.gridrepublic.org/browse/DBOINCP-466
> Drupal: Change user profile permissions

- drupal/sites/all/features/boinc_standard/boinc_standard.strongarm.inc
Changed Drupal config so new accounts require email validation. After validating their account via a one-link link they choose a password.
https://dev.gridrepublic.org/browse/DBOINCP-466
> Drupal: new accounts require email validation.

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
Fixed bug where moderator hiding a forum topic would reach a 404 Access Denied page.
https://dev.gridrepublic.org/browse/DBOINCP-456
> Drupal: Fixed minor moderator forum hide bug. 

- samples/condor/Makefile
- samples/condor/boinc_gahp.cpp
The existing code depended on building within a git repository.  It
included the GIT_REVISION in the startup message.  Unfortunately,
if you built from a downloaded tarball, the build fails. I thought
that the version of BOINC that the GAHP was compiled against would
be useful information as it is logged.  The SVN_VERSION is still
available by using the --version command line option.  Because of
the small change in behavior, I also bumped the version number of
the GAHP to 1.0.2.
> Update GAHP version string

- clientscr/Mac_Saver_ModuleView.m
Under OS 10.13 and later, there was a bug in the Mac screensaver coordinator when the default (overview) screensaver _boincscr_ took longer than 5 seconds to open its window. This incorrectly triggered the message "Screensaver of application _XXX_ is not compatible with this version of OS X" where _XXX_ is normally the name of the worker application associated with the faulty graphics app. 
But instead of substituting one worker app name for _XXX_ in the displayed string, it appended the names of all inactive apps (all those with slot set to -1) up to the buffer size limit of 1024 characters.
Probably the worst problem created by this bug is that it caused the logic to decide that _boincscr_ was defective and stop trying to use it. 
Fortunately, none of these problems persisted once the …
> Mac screensaver: If no application graphics running, don't display bad message

- clientgui/sg_TaskPanel.cpp
There's already an icon that shows whether the task is running.
The slideshow represents the app, not the state of the task.
> Manager: simple view: cycle slideshow even if task not running

- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/AddRemoveUser.cpp
- mac_installer/PostInstall.cpp
- mac_installer/ReadMe.rtf
- mac_installer/finish_install.cpp
- mac_installer/uninstall.cpp
OS 10.14 Mojave has added some new security safeguards. As a result, Macs who have multiple user accounts will see a scary warning when each user other than the one running the installer logs in, and asks for permission to proceed. As a temporary measure, I added the following to the installer's ReadMe file for generic (unbranded) BOINC:
> New for Mojave: If your Mac has more than one user account, each user may see the following dialog upon their first login after you have installed BOINC: "sh" wants to control "System Events...." The BOINC installer needs this access to finish adding or removing its login item for each user; please click "OK".
With the changes in this PR I am trying to either avoid that warning or at least make it easier to understand.
The reason for this problem is …
> Mac installer: Changes to avoid Mojave security dialog

- deploy/deploy_to_bintray.sh
- deploy/prepare_deployment.bat
- deploy/prepare_deployment.sh
- provide sensible defaults for AppVeyor deploy to bintray; Until there is a better mechanism to control deployments on AppVeyor a deployment will happen for every merge into master. This will prevent it from failing.
- stop Travis deploy script when unsupported event happens
- fix intendation
Follow up hotfix for #2712
> fix bintray deploy

- .travis.yml
- mac_build/BuildMacBOINC.sh
- mac_build/HowToBuildBOINC_XCode.rtf
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/buildWxMac.sh
- mac_installer/Installer.cpp
- mac_installer/PostInstall.cpp
BOINC built with Xcode 10 requires at least OS 10.7 (earlier versions worked under OS 10.6.)
With these changes, BOINC can still be built with earlier versions of Xcode, but will still require OS 10.7 to run because it links with libc++ instead of libstdc++.
This PR replaces my PR #2720
> Mac allow building with xcode10

- html/inc/user_util.inc
- py/Boinc/setup_project.py
This PR changes a single flag the BoincUser::insert statement, setting the flag `show_host` to false. Thus by default a user's hosts are not in publicly view.
Part of #2449
> user: set show_host default to false.

- mac_installer/ReadMe.rtf
Several links to the sandbox design diagram document _sandbox.php_ were broken due to another file named _sandbox.php_. The duplicate name was fixed by renaming the sandbox design diagram document to _sandbox_design.php_. This PR updates the broken link in the Mac installer ReadMe file to the [new URL](http://boinc.berkeley.edu/sandbox_design.php).
This PR is ready to be merged into master.
> Mac: In ReadMe.rtf file, fix broken link to sandbox design document

- clientgui/DlgAdvPreferences.cpp
- clientgui/DlgAdvPreferencesBase.cpp
Under OS 10.14 Mojave, the _Computing Preferences_ panel's tab buttons are not wide enough to fit the text. This fixes that issue.
Is this bug significant enough to justify releasing a hot fix 7.14.3 for the Mac?
> Mac: Fix truncated tabs in Computing Preferences dialog under OS 10.14 Mojave

- sched/db_dump.cpp
A refactor of db_dump which splits the compression logic out of ZFILE and into separate output stream classes. This opens up for on-the-fly gzip compression for #694.
I have tested this in the VM image but it could be good if someone with a larger database tries an export to see if there are any concrete time gains.
> db_dump: Add support for dumping straight to gzip.

- lib/parse.cpp
Per XML standard CDATA-section-close delimiter ']]>' is not allowed to
appear in element content without being escaped. XML tools like libxml
that require well-formed XML refuse to parse text that doesn't follow
this rule.
In particular this bug broke processing database result archives
generated by db_purge.
> (wip) lib: escape CDATA-section-close delimiter in xml_escape()

- sched/file_upload_handler.cpp
- sched/sched_config.cpp
- sched/sched_config.h
- sched/sched_util_basic.cpp
- sched/sched_util_basic.h
This is the file_upload_handler code which is running on Einstein@Home for the last year.
- fix `get_file_size()` to be read-only, it does not need to check if the existing file is writable
- fix `copy_socket_to_file()` to make completely uploaded files read-only and add a check if a subsequent upload happens (data will be discarded)
- reopen logfile on user defined signal so log rotation works properly when running as FCGI
- optional variety postfix for upload_dir and logfile when running as FCGI (we use this to split file uploads of small (O(100kB)) and large (O(3MB)) files to be stored in separate file systems for better speed and efficiency
> improved file_upload_handler

- client/http_curl.cpp
The content type for HTTP operations is always set to the default (application/x-www-form-urlencoded). This breaks the signature used by S3/Ceph as described in issue #2764. This change has been tested by building the client without these lines and running a few tasks that download input files from S3/Ceph.
> Remove the default content type

- mac_installer/release_boinc.sh
- mac_installer/release_brand.sh
As of OS 10.14 Mojave, Apple has introduced a new level of security which Apple calls "notarization". Under OS 10.14, the only difference is that Gatekeeper adds the sentence 
> Apple checked it for malicious software and found none. 
However, Apple has warned: 
> In an upcoming release of macOS, Gatekeeper will require Developer ID–signed software to be notarized by Apple.
This PR updates the way the _release_boinc.sh_ script code signs the BOINC installer and its related files to allow submitting the installer and uninstaller to Apple to be "notarized". It also adds comments to the script describing how to run the _Xcode_ utility _notarize_ to have Apple's server scan the files for malware and how to run the _Xcode_ utility _stapler_ to download the approval ticket and attach it to the …
> Mac: changes to allow submission to Apple for "notarizing"

- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
Change the check and set consent functions to use boinc upstream functions for consent. This is mostly for the enroll consent type.
https://dev.gridrepublic.org/browse/DBOINCP-428
> Drupal: Modified boincuser to use upstream consent functions.

- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
Add code to add privacy consent options from consent_type table into privacy preferences form. Form allows users to select their privacy options.
https://dev.gridrepublic.org/browse/DBOINCP-445
> Drupal: Add privacy consent options to privacy preference form.

- html/user/get_project_config.php
- html/user/server_status.php
- py/Boinc/setup_project.py
This PR modifies the make_project command so that it will detect the git commit, branch and tag if it is run from a git directory. The result is stored in release.inc. The get_project_config.php and server_status.php views have been updated to show the git commit and version (from the tag) if it is available. This address #2688
> Added server version detection and publishing

- lib/parse.cpp
Commit ff0b8d08985707f089f934816b0d28841b709c80 (fix CDATA escaping) introduced two bugs to xml_escape():
- it eats ']' characters that are not part of ']]>'
- it eats the next character after ']]>'
Fixes #2809
> lib: fix xml_escape(), again

- html/ops/team_import.php
Found during testing of BOINC server release.
See https://groups.google.com/a/ssl.berkeley.edu/d/msg/boinc_dev/BITKixFRY7k/48Q8oiaRBQAJ
> ops: Fix bug in team import, wrong include path fixed.

- py/Boinc/setup_project.py
While testing [GDPR compliance](https://boinc.berkeley.edu/trac/wiki/GdprCompliance) I have noticed that in `project/config.xml` the attribute `disable_account_creation_rpc` was missing
> added default project value disable_account_creation_rpc

- sched/Makefile.am
This is a minor fix for #2767. On my Debian 8.11 `db_dump` doesn't build without that.
> scheduler: linking db_dump requires -lz

- android/BOINC/app/src/main/AndroidManifest.xml
RESTART_PACKAGES constant was deprecated in API level 8. The ActivityManager.restartPackage(String) API is no longer supported.
Replacement constant is KILL_BACKGROUND_PROCESSES.
N/A
> [Android] Changed the RESTART_PACKAGES to KILL_BACKGROUND_PROCESSES

- android/Vagrant.README.md
- android/Vagrantfile
The Vagrant readme has to be updated because under Windows 10 there are extra requirements. Without the VirtualBox Extension Pack Vagrant drops error, it misses the USB 3.0 port capability.
The base image also updated to Ubuntu 18.04. Tested and Android Studio builds the project.
Ubuntu 18.10 is the latest image, but not LTS.
N/A
> [Android] Update vagrant

- android/Vagrant.README.md
- android/Vagrantfile
This PR is based on #2842, please merge that first.
On Windows, the [VirtualBox can't be used](https://forums.virtualbox.org/viewtopic.php?f=6&t=85438) if someone uses Hyper-V by default.
The user doesn't have to do anything differently. If VirtualBox is installed, the Vagrant detects it and use it as default.
N/A
> Add Hyper-V support to Vagrant

- .travis.yml
- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/AndroidManifest.xml
- android/BOINC/build.gradle
- android/BOINC/gradle/wrapper/gradle-wrapper.properties
To take advantage of the latest features, improvements, and security fixes, Google strongly recommends updating the Android Gradle plugin to version 3.2.1 and Gradle to version 4.6. 
Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, we no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads.
APK optimization.
> [Android] Update Android Gradle

- deploy/deploy_to_bintray.sh
Attributes can be used to easily delete old versions. A script can check if a PR is closed and delete all versions for this PR on bintray. Or it could delete all versions older than a threshold.
Attribtes only need to be added once. Currently this is done in the Travis build because this is running for every PR.
None
N/A
> Travis Bintray: add attributes to versions for better cleanup

- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
The [setBackgroundDrawable ](https://developer.android.com/reference/android/view/View.html#setBackgroundDrawable(android.graphics.drawable.Drawable)) was deprecated in API level 16. Android.com says to use the setBackground instead which was added in API level 16.
We target minimum API 19.
N/A
> [Android] The setBackgroundDrawable was deprecated in API level 16.

- drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-filter.inc
- drupal/sites/default/boinc/modules/contrib/bbcode/bbcode.info
Replace deprecated preg_replace() /e with preg_replace_callback().
Copied from http://cgit.drupalcode.org/bbcode/commit/?id=46a16e5
Part of: https://dev.gridrepublic.org/browse/DBOINCP-468
PHP7 for drupal deprecated the `preg_replace()` function. This PR fixed this.
> Drupal: Update bbcode-filter for PHP7

- android/BOINC/app/build.gradle
The `match.size()` return a `long`, and it was compared with an `int`.
The number 1 now used as long.
Fixes the following inspected error:  '==' between objects of inconvertible types 'Integer' and 'long'
N/A
> [Android] Fix 'equals()' between objects of inconvertible types

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/MessagesParser.java
The `boolean isSpace(char)` method in the `java.lang.Character` class were [deprecated](http://leo.ugr.es/elvira/devel/Tutorial/Java/post1.0/converting/deprecated.html) in favor of `boolean isWhitespace(char)`.
N/A
> [Android] Fix the isSpace deprecated function.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
`android.text.ClipboardManager` is deprecated as of API 11: Android 3.0 (Honeycomb)
`android.content.ClipboardManager` added in API level 11.
We target minimum API 19.
N/A
> [Android] Fix android.text.ClipboardManager deprecated.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
The previous solution used the fix number 4, because it was necessary prior API 17. Now we target minimum API 19, so updated to use the standard method.
N/A
> [Android] Update Charger Type attribute to use the API's constant

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java
Fix deprecated `Builder(android.content.Context)` and `android.support.v7.app.NotificationCompat.Builder`
The NotificationCompat.Builder(Context context) constructor was [deprecated](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder) in API level 26.1.0.
Google suggests to use NotificationCompat.Builder(Context, String) instead.
N/A
> [Android] Fix deprecated NotificationCompat.Builder(Context context)

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
- Fix Redundant String operation inspection.
- Fix Redundant type cast inspection.
- Fix Unnecessary 'return' statement inspections. 
There are 3 other Unnecessary 'return' statement warnings in the `ClientStatus.java`, but IMO they add readability and undesirability to the code.
N/A
> [Android] Fix verbose or redundant code constructs inspections

- lib/boinc_win.h
If building with MINGW, include `windows.h` a bit earlier in `boinc_win.h`. Otherwise the build fails on datatypes in winhttp.h.
This has been an issue for a while when building SixTrack for LHC@home on Windows. Previously we've just fixed it with a bash script.
Include `windows.h` before `winhttp.h` when building on Windows/MINGW
> [MINGW] Added include windows.h before winhttp.h when building with mingw

- html/inc/account.inc
- html/inc/forum.inc
- html/inc/user.inc
- html/inc/user_util.inc
- html/inc/util.inc
- html/inc/util_basic.inc
- html/inc/xml.inc
- html/user/am_set_info.php
- html/user/edit_user_info_action.php
- html/user/edit_user_info_form.php
- lib/util.cpp
- sched/db_dump.cpp
- sched/sched_config.cpp
- sched/sched_config.h
Add constants NO_USER_URL and NO_USER_COUNTRY.
If you set these to true (in project.inc)
there will be no query or display of user web site URL and user country, respectively.
> web: add options for not collecting or showing URL and country

- client/client_state.h
- client/hostinfo_unix.cpp
- client/makefile_sim
- client/work_fetch.cpp
It may take a minute or two between deciding to fetch work
and actually getting some; you may have to try a few projects.
So it's better to start work fetch a bit before a resource instance becomes idle,
rather than waiting until it's idle.
We were already doing this, with a "lead time" of 3 minutes,
except for the case where all the fetchable projects
are zero resource share ("backup" projects).
We'd request work from backup projects only when an instance is idle.
This change fixes that by allowing work fetch from backup projects
if an instance is within 3 minutes of going idle.
It also makes the 3 minutes, in both places,
into a constant WF_EST_FETCH_TIME rather than hardwired.
BTW, the reason for the old policy is that we want to avoid
situations where we fetch a big job from a backup …
> client: fix work fetch edge case to avoid idleness

- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
Fixes #2905
- The getUser never returned the team name, even it was available. This is fixed.
- Saved one `String` variable.
Nope.
[Android] Show the team name with the username in the project tab.
> [Android] Fix to return the user name with the team name.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
The `param` tag was missing in Javadoc.
N/A
> [Android] Add missing 'param' tag to Javadoc.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
Fix number comparison using '==', instead of 'equals()'.
Reports any use of == or != to test for Number equality, rather than the equals() method. With auto-boxing it is easy to make the mistake of comparing two Integer (or other subclasses of java.lang.Number) objects instead of two ints.
N/A
> [Android] Fix number comparison

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
`PendingIntent` function needs `PendingIntent` constant not normal `Intent`.
`FLAG_CANCEL_CURRENT` could be used instead of the `FLAG_UPDATE_CURRENT`
N/A
> [Android] Fix incorrect constants.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
On versions prior to Android N (API 24), initializing the `WifiManager` via `Context#getSystemService` can cause a memory leak if the context is not the application context.  In many cases, it's not obvious from the code where the Context is coming from (e.g. it might be a parameter to a method, or a field initialized from various method calls). It's possible that the context being passed in is the application context, but to be on the safe side, you should consider changing `context.getSystemService()` to `context.getApplicationContext().getSystemService()`.
Update the minimum API to 24.
[Android] Fix WifiManager Leak issue on devices prior to Android 7.
> [Android] Fix WifiManager Leak issue.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/res/values/configuration.xml
The MIPS architecture has been dropped in #2680. This PR cleans up the rest of the code.
N/A
> [Android] Clean up the MIPS architecture.

- android/BOINC/app/src/main/res/layout/attach_project_credential_input_dialog.xml
- android/BOINC/app/src/main/res/layout/attach_project_credential_input_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_list_layout_listitem.xml
- android/BOINC/app/src/main/res/layout/dialog_about.xml
- android/BOINC/app/src/main/res/layout/dialog_confirm.xml
- android/BOINC/app/src/main/res/layout/dialog_list.xml
- android/BOINC/app/src/main/res/layout/notices_layout_listitem.xml
- android/BOINC/app/src/main/res/layout/prefs_layout_dialog_number.xml
- android/BOINC/app/src/main/res/layout/prefs_layout_dialog_pct.xml
- android/BOINC/app/src/main/res/layout/prefs_layout_dialog_selection.xml
- android/BOINC/app/src/main/res/layout/prefs_layout_dialog_text.xml
- android/BOINC/app/src/main/res/layout/prefs_layout_listitem.xml
- android/BOINC/app/src/main/res/layout/project_details_layout.xml
- android/BOINC/app/src/main/res/layout/projects_layout_listitem.xml
- android/BOINC/app/src/main/res/layout/projects_layout_listitem_acctmgr.xml
- android/BOINC/app/src/main/res/layout/tasks_layout.xml
- android/BOINC/app/src/main/res/layout/tasks_layout_listitem.xml
A widget that is declared to be clickable but not declared to be focusable is not accessible via the keyboard. Please add the focusable attribute as well.
[Android] Minor layout fixes.
> [Android] Fix Keyboard inaccessible widget issue

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
- android/BOINC/app/src/main/res/values/strings.xml
#2937 
This PR does not close the issue, because this feature can be implemented in the desktop version too.
- Add 'Bug report' menu item, which redirects to [GitHub/issues](https://github.com/BOINC/boinc/issues). 
- 'Help menu' link changed to https.
- Switch Bug report and Event Log menu icons.
[Android] Add Bug report menu item.
**Screenshot**
> [Android] Add 'Bug report' menu item

- html/inc/util.inc
project.inc can include a constant HEAD_EXTRA.
Its contents are inserted at the beginning of <head> tags.
This makes it possible to use Google Analytics,
which requires that a script be added at that point.
Fixes #
> web: add ability to put extra stuff in <head> element of all pages

- drupal/sites/all/features/boinc_standard/boinc_standard.features.inc
Modified triggered rules email messages to moderators to use the URL without a language code. Use PHP evaluation to produce URI with language 'en', which corresponds to the default language, which has no language code.
https://dev.gridrepublic.org/browse/DBOINCP-463
N/A
> Drupal: Modified email messages to remove language code.

- sched/db_dump.cpp
One too many argument for write function. Introduced in ff91f05.
Fixes #2958
Fix db_dump crash
> Server: fix db_dump segfault

- html/inc/user.inc
As a part of: https://github.com/BOINC/boinc/issues/2975
- Fixed misspelling: `xml_object` -> `$xml_object`
- Fixed bug when getting user projects via Netsoft API 
/cc @davidpanderson
> Fixed get_other_projects function

- .scrutinizer.yml
A lot of issues in Scrutinizer are calls to the Drupal API from BOINC modules. By making the code available, the static code analyzer can do a better job finding the real issues.
N/A
> Scrutinizer: cache Drupal dependency for static code analysis

- drupal/sites/default/boinc/modules/contrib/cck/content.info
- drupal/sites/default/boinc/modules/contrib/cck/content.module
- drupal/sites/default/boinc/modules/contrib/cck/includes/content.diff.inc
- drupal/sites/default/boinc/modules/contrib/cck/includes/content.node_form.inc
- drupal/sites/default/boinc/modules/contrib/cck/includes/content.rules.inc
- drupal/sites/default/boinc/modules/contrib/cck/modules/nodereference/nodereference.info
- drupal/sites/default/boinc/modules/contrib/cck/modules/nodereference/nodereference.module
- drupal/sites/default/boinc/modules/contrib/content_profile/content_profile.info
- drupal/sites/default/boinc/modules/contrib/content_profile/content_profile.theme_vars.inc
- drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.ctools.inc
- drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.info
- drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron_scheduler.inc
- drupal/sites/default/boinc/modules/contrib/filefield/filefield.info
- drupal/sites/default/boinc/modules/contrib/filefield/filefield_field.inc
- drupal/sites/default/boinc/modules/contrib/flag/flag.info
- drupal/sites/default/boinc/modules/contrib/flag/includes/flag_handler_argument_content_id.inc
- drupal/sites/default/boinc/modules/contrib/jump/jump.info
- drupal/sites/default/boinc/modules/contrib/jump/jump_views_plugin_style.inc
- drupal/sites/default/boinc/modules/contrib/mobile_menu_toggle/mobile_menu_toggle.tpl.php
Changes to `contrib` directory modules for PHP7 compatibility.
* Added curly braces to fix variable interpolation.
* Misc other PHP fixes.
N/A
> Drupal: PHP 7 fixes for various contrib modules

- drupal/sites/default/settings.php
Removed PHP INI settings from settings.php that have been removed from PHP 7.0
N/A
> Drupal: Removed old INI settings.

- drupal/sites/default/boinc/modules/contrib/views/includes/handlers.inc
- drupal/sites/default/boinc/modules/contrib/views/includes/query.inc
- drupal/sites/default/boinc/modules/contrib/views/includes/tabs.inc
- drupal/sites/default/boinc/modules/contrib/views/includes/view.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/locale/views_handler_field_locale_language.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/profile/views_handler_field_profile_list.inc
- drupal/sites/default/boinc/modules/contrib/views/modules/profile/views_handler_filter_profile_selection.inc
- drupal/sites/default/boinc/modules/contrib/views/views.info
Fixed PHP7 compatibility issues for the `contrib/views` module.
* Replaced `split()` function with `preg_split()`.
* Add curly braces when necessary.
* Modified constructor to a modern PHP standard.
N/A
> Drupal: PHP7 fixes for views modules

- drupal/sites/default/boinc/modules/contrib/ctools/ctools.info
- drupal/sites/default/boinc/modules/contrib/ctools/includes/context.inc
- drupal/sites/default/boinc/modules/contrib/ctools/includes/math-expr.inc
- drupal/sites/default/boinc/modules/contrib/ctools/page_manager/page_manager.info
- drupal/sites/default/boinc/modules/contrib/ctools/page_manager/plugins/tasks/page.inc
- drupal/sites/default/boinc/modules/contrib/ctools/plugins/export_ui/ctools_export_ui.class.php
For PHP7 compatibility:
* Fixed `func_get_args()` calls
* Modernized PHP4 style constructors.
N/A
> Drupal: PHP7 fixes for ctools module

- drupal/sites/default/boinc/modules/boincimport/boincimport.module
- drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
Modified boinc modules to fix PHP 7 compatibility issues
* mysql_xyz() functions replaced with mysqli_mxyz() functions.
* Removed references to ini settings `safe_mode`.
* Updated a class constructor to use modern PHP standards.
N/A
> Drupal: PHP7 fixes for boinc modules

- html/inc/prefs_project.inc
- html/inc/prefs_util.inc
Fixes #2857
Project Preferences column view now has the consent preferences displayed.
Include consent preferences in the Project Preferences column view.
> web: add consent preferences to column view of project preferences page.

- html/inc/util.inc
error_page() calls page_head(), but there are instances of code that call error_page() having already called page_head() before, thus attempting to send headers twice and creating double page header.
Fixes #2960 
Prevent page_head() from being called multiple times. Notice to projects: If you have a page_head() function override in your project.inc you need to apply this change there too.
> Do not allow page_head() to be called twice

- db/boinc_db_types.h
- html/ops/purge_trickles.php
- sched/trickle_handler.cpp
- sched/trickle_handler.h
Some projects (namely CPDN) need to process trickle-up messages
with two different daemons.
We do this as follows:
- daemon 1 enumerates messages with handled==0, and sets handled=1
- daemon 2 enumerates messages with handled==1, and sets handled=2
You can then purge records with handled==2
To implement this, trickle_handler.cpp has two global vars,
int handled_enum and int handled_set.
By default these are 0 and 1.
For daemon 2, set them to 1 and 2 in trickle_handler_init()
> server: add the ability to have > 1 stages of trickle handling

- html/user/team_members.php
Strip HTML tags for the page title.
- Fixed title for the pages that were subject to localization
> Strip HTML tags for the page title

- drupal/sites/default/settings.php
With this setting present, reCAPTCHA does not work. Removing this setting, un-breaks reCAPTCHA.
Part of PHP 7.0 compatibility.
https://dev.gridrepublic.org/browse/DBOINCP-484
N/A
> Drupal: Removed PHP ini setting 'arg_separator.output'.

- m4/sah_links.m4
Fixes a typo that resulted in `/bin/rmdir: failed to remove 'ln_test': No such file or directory`
error message from configure and a leftover directory in build directory.
None needed
N/A
> build: fix removing ln test directory

- client/gpu_amd.cpp
- client/gpu_nvidia.cpp
- client/gpu_opencl.cpp
- lib/coproc.cpp
- lib/coproc.h
- sched/plan_class_spec.cpp
... and generate a warning message if impossible values
Attempt to fix issue #2988
> client: fix possible overflow in peak FLOPS calculation for OpenCL GPUs

- drupal/sites/default/boinc/modules/boincteam/boincteam.module
- drupal/sites/default/boinc/modules/boincteam/includes/boincteam.forms.inc
- drupal/sites/default/boinc/modules/boincteam/includes/boincteam.helpers.inc
- drupal/sites/default/boinc/themes/boinc/css/forms.css
Boincteam- Send email to all team members. This sends an email to team members but respects the privacy option : do/do not send notification emails. The sender's e-mail address is hidden from the recipients and the recipients email-addresses are hidden as well.
N/A
https://dev.gridrepublic.org/browse/DBOINCP-479
> Drupal: Add form to send email to all team-members.

- drupal/sites/default/boinc/modules/boincteam/includes/boincteam.forms.inc
Adjusted various sentences in the send all team members email page. There should be no changes to the underlying functionality.
N/A
https://dev.gridrepublic.org/browse/DBOINCP-479
> Drupal: Fixed wording on email team page.

- android/BOINC/.idea/misc.xml
- android/BOINC/build.gradle
- android/BOINC/gradle/wrapper/gradle-wrapper.properties
To take advantage of the latest features, improvements, and security fixes, it is strongly recommended to update the Android Gradle plugin to version 3.3.0 and Gradle to version 4.10.1. [Release notes.](https://developer.android.com/studio/releases/gradle-plugin)
N/A
> [Android] Update Graddle to v3.3.0

- client/app_control.cpp
Including checkpoint debug with task debug creates too much spam in log
for those who are interested only in task state change related log
messages.
Those who want both checkpoint debug and task debug can easily enable
both debug log flags.
None
client: separate checkpoint debug from task debug
> client: separate checkpoint debug from task debug

- sched/validate_util2.cpp
- sched/validator.cpp
- sched/validator.h
If a validator (in init_result()) marks a result as 'suspicious', it is replicated. However with the the quorum still being '1' (as it is in 'adaptive replication'), the replication by itself doesn't ensure that the result really gets successfully verified by another result. So in the presence of a 'suspicious' result, raise the quorum to ensure that.
> validator: raise the quorum for 'suspicious' results to ensure validation

- client/app_control.cpp
If a job is suspended (e.g. because of CPU throttling)
its timer thread is suspended and won't process any messages,
including quit messages.
This could cause a delay in client exit,
and possibly job processes that don't go away.
Fixes #
> client: unsuspend jobs before telling them to quit

- drupal/sites/default/boinc/modules/boincuser/boincuser.js
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
- drupal/sites/default/boinc/themes/boinc/css/forms.css
Adds Javascript to terms-of-use forms, both user registration form and terms-of-use form for existing users. Disables submit button until the checkbox has been checked. For non-JS browsers, if the checkbox is not checked the submit button will work, but user will receive error message.
Also, changed a few items in form layout in order to get JS to work cleanly, renamed a few IDs.
N/A
https://dev.gridrepublic.org/browse/DBOINCP-469
> Drupal: Add JS to terms-of-use form

- .gitignore
- generate_svn_version.sh
- html/inc/server_version.inc
- html/user/get_project_config.php
- html/user/server_status.php
... rather than generating it during configure.
This way things work for projects that don't do "configure",
e.g. because they use only the web code.
And it's simpler.
Maintain this as for client version #s.
The minor version # is even in release branches,
odd in development branches like master.
Fixes #
> web: keep server version # in a file (html/inc/server_version.inc)

- client/gpu_amd.cpp
- client/gpu_nvidia.cpp
- client/gpu_opencl.cpp
- lib/coproc.cpp
- lib/coproc.h
- sched/plan_class_spec.cpp
Cherry-pick of the following for the server release branch
Merge pull request #3001 from BOINC/dpa_opencl
client: fix possible overflow in peak FLOPS calculation for OpenCL GPUs
> FLOPS Fix for Server Release Branch

- drupal/sites/default/boinc/themes/boinc/css/forms.css
Removed strikethrough, changed cursor and color, for disabled submit text-link/buttons.
N/A
Part of: https://dev.gridrepublic.org/browse/DBOINCP-469
> Drupal: Modified CSS BOINC theme

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
Changes header and body encoding to use 'quoted-printable'.
N/A
Part of https://dev.gridrepublic.org/browse/DBOINCP-479
> Drupal: Add boinccore_mail_alter to change encoding.

- clientgui/DlgExclusiveApps.cpp
... because the file may be inaccessible to or not executable by user.
Also don't require .exe or .app extension.
The user can use the file picker to locate the file, but they don't have to;
they can just type in the file name.
Addresses issue #2826
Fixes #
> Manager: in select exclusive app, don't check for existence, executability, or filename extension

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
- drupal/sites/default/boinc/themes/boinc/template.php
- drupal/sites/default/boinc/themes/boinc/templates/page.tpl.php
Fixed some misc PHP problems found with xdebug.
There are minor PHP problems that create warning and notice-level errors in the drupal log. They are minor changes result in better code. 
N/A
> Drupal: Fixed misc PHP problems

- html/inc/submit_util.inc
Reverting PR #2794 as the assumption made is incorrect. The field project_state is to define project specific states.
> Reverting PR #2794

- mac_build/buildcurl.sh
- mac_build/buildfreetype.sh
This patch causes two libraries to be built without including two external libraries that get found when already installed on the Mac by other software builds.
Fixes #
Building on a Mac that has libraries installed that are identical or similar to BOINC required libraries, will be found by the BOINC build. These two changes disable two such libraries. nghttp2 and png respectively found by buildcurl.sh and buildfreetype.sh.
It became impossible to cleanly build these two components with the external version libraries included in the build.
On OSX 10.14.3
buildcurl.sh --without-nghttp2
buildfreetype.sh --without-png
> Disabling external libraries

- client/gpu_detect.cpp
- clientgui/AdvancedFrame.cpp
- clientgui/MainDocument.cpp
- clientscr/screensaver.cpp
- lib/util.cpp
lib: change `run_program()` to use `file` parameter as program name on Windows
mgr,scr: fix `argv`s in calls to `run_program()`
client: remove quoting client path in launching GPU detection
See commit messages for details.
Fixes launching graphics apps with Manager and screensaver as reported on boinc_alpha.
> run_program() fixes

- html/inc/bolt_ex.inc
- html/inc/translation.inc
- html/ops/mass_email_script.php
- html/user/bolt_sched.php
- The `ereg` function is deprecated since 5.3 and was removed in 7.0.
- Using `break;` outside a loop was working unintentionally before 7.0 but now throws a compile error.
- Using s call-time pass-by-reference throws an error since 5.4. The `&` is only needed in the function declaration not when calling the function.
Fixes #2102 
N/A
> Web: fix deprecated php stuff

- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
Fixes broken user registration form. 
N/A
https://dev.gridrepublic.org/browse/DBOINCP-497
> Drupal: Fixed registration form terms-of-use checkbox

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCErrors.java
- android/BOINC/app/src/main/res/values/strings.xml
- html/inc/common_defs.inc
- html/user/create_account.php
- lib/error_numbers.h
- lib/str_util.cpp
- py/Boinc/setup_project.py
* Added a new config.xml setting "account_creation_rpc_require_consent" (default: disabled)
* Added condition to create_account RPC to return an error if consent details aren't given but required
* Defined a dedicated error number and default message (for C and Android use)
**See also**
* #2413
* #2835
Allow projects to require explicit consent for RPC-based account creation to comply with GDPR.
> [web][android][lib] Add conditional terms of use consent requirement to create_account RPC

- sched/sched_result.cpp
- sched/sched_version.cpp
- sched/validate_util2.h
- sched/validator.cpp
Say that a job has a "long-term failure" if it fails in a way
(as evidenced by its exit code and/or stderr)
suggesting that other jobs for that (host, app version) will fail too.
In this case we want to avoid sending more jobs to that (host, app version).
This implements this feature.
To use it, have your validator's init_result() return
VAL_RESULT_LONG_TERM_FAIL if it finds a long-term failure,
and run your validator with the --check_punitive option.
("Punitive" because we're "punishing" the host for its failure).
The validator punishes the (host, app version) by
setting host_app_version.max_jobs_per_day to 1.
One job per day can still be sent.
That way if the underlying problem is fixed
(e.g. the user enables VM acceleration in the BIOS)
we'll eventually go back to normal.
Also: …
> Server: add "punitive validation" mechanism

- api/boinc_api.h
- api/graphics_api.h
- lib/diagnostics.h
Apply patch reported almost 10 years ago.
It doesn't make so much affect now but make API headers more consistent.
Also removed header of the function that was removed many years ago.
This is cosmetical change and make doesn't touch existing functionality.
Fixes #861
> Fix prototype warnings in the BOINC API headers

- client/app_control.cpp
- client/client_state.h
When an app finishes, it writes a "finish file",
which ensures the client that the app really finished.
If the app process is still there N seconds after the finish file appears,
the client assumes that something went wrong, and it aborts the job.
Previously N was 10.
This was too small during periods of heavy paging.
I increased it to 300.
It has been pointed out that if the app creates the finish file,
and its output files are present,
it should be treated as successful regardless of whether it exits.
This is probably true, but right now we don't have a mechanism
for killing a job and marking it as success.
The longer timeout makes this moot.
Fixes #3017
> client: increase finish-file timeout

- drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
Fixed bug caused by wrong location of function call.
N/A
Part of https://dev.gridrepublic.org/browse/DBOINCP-493
> Drupal: Fixed bug where rules_invoke_event is called.

- drupal/sites/all/features/boinc_standard/boinc_standard.features.inc
- drupal/sites/all/features/teams/teams.features.inc
Adds some text within square brackets to help with email filtering of these notifications.
No functional change to code, only text changes.
N/A
https://dev.gridrepublic.org/browse/DBOINCP-493
> Drupal: Add subject line text to help email filtering.

- sched/db_dump.cpp
Removed extra .gz from badge_user and badge_team when running du_dump as described in issue #3074. The [open function](https://github.com/BOINC/boinc/blob/master/sched/db_dump.cpp#L309) of the GZIP_FILE class appends '.gz'.
> Removed extra .gz from badge_user and badge_team

- sched/plan_class_spec.cpp
- sched/plan_class_spec.h
I found this problem today while debugging a different server issue, workunits were getting rejected because they were being compared to inititalized values.
Initializing the values solved the problem.
Even though I did a commit range cherry pick, only one commit comment is shown.  Not sure why that is.
> Fixes uninitialized values of min/max_wu_id and min/max_batch

- api/boinc_api.cpp
- lib/proc_control.cpp
To quote from comments in lib/proc_control.cpp:
// The only way to do this on Windows is to enumerate
// all the threads in the entire system,
// and identify those belonging to one of the processes (ugh!!)
//
// In the suspend case, this creates a potential synch problem:
// - CPU throttling sends suspend message
// - we enumerate threads
// - one of those threads creates a new thread T
// - we suspend the enumerated threads
//
// In this case, T will run, which is undesirable but not an error.
// But suppose that
// - the app uses a mutex,
// - at the start of the above sequence some thread holds the mutex
// - T immediately tries to acquire the mutex (and is suspended).
// Then when the client sends a resume message,
// T resumes and there are two threads in the mutex section. Error! …
> client: throttling: only resume threads you suspended

- configure.ac
- m4/boinc_check_flags.m4
- m4/boinc_set_compile_flags.m4
While science apps may use Fortran BOINC itself doesn't use it making
the checks useless.
Removing the checks reduces verbosity of configure a little bit making
its output more accessible.
None
N/A
> build: remove Fortran checks

- html/ops/fix_project_prefs.php
Adds a script that does some maintenance on project specific preferences. Currently does:
* squash duplicate app_id entries (and optionally delete deprecated appids)
* delete empty venue tags (confuses older clients)
* migrate preset from attribute to tag (Drupal specific)
* validates the XML snippet
Can be done using other script languages but we already have everything in place for PHP to work well with the DB.
N/A
> Ops: Script to fix project preferences

- html/inc/bootstrap.inc
- html/user/download_software.php
- html/user/join.php
- html/user/register.php
- html/user/sample_index.php
- html/user/signup.php
Problem: the new signup/download process (auto-attach) wasn't telling
Mac and Linux users to install VirtualBox for projects that require it.
(These platforms don't have a combined BOINC/VBox installer;
the user has to install VBox separately).
Solution: add links to the VirtualBox download page in appropriate places.
Also: we currently have a <need_vbox/> config option
for projects that require VBox (i.e. all their apps are VM)
Add a <recommend_vbox/> option for projects with some but not all VM apps.
Also: rename download.php to download_software.php.
There was a name conflict with a file from the boinc-site repo.
This caused problems on the BOINC web site, which uses both code bases.
Projects with a link to download.php on their home page
should change this to download_software.php.
> web: Fix auto-attach process for VBox projects

- html/user/host_app_versions.php
> web: change "ATI GPU" to "AMD GPU" in host app details

- clientgui/AsyncRPC.cpp
- clientgui/BOINCGUIApp.cpp
- clientgui/BOINCGUIApp.h
- clientgui/MainDocument.cpp
Disables BOINC Manager system tray icon on Linux platforms.
On Linux BOINC client runs regardless the Manager is running or not, so having a Manager system tray icon may suggest the user that calculus are running only when the Manager is running, leading to misunderstandings.
Moreover removing Manager system tray icon, prevents also the user from accessing to tray icon right-clic menu that can let the user interfere with client service, as stated in pull request ["Removed "Exit from BOINC Manager", "Shut down connected client" menu entries on Linux"](https://github.com/BOINC/boinc/pull/3028)
Disablec BOINC Manager system tray icon on Linux platforms.
> Disabled Manager system tray icon for Linux builds

- clientgui/AdvancedFrame.cpp
- clientgui/sg_BoincSimpleFrame.cpp
New version of aborted pull request https://github.com/BOINC/boinc/pull/3028
As by default on Linux BOINC runs as a service, the GUI must not stop it.
Removed "Exit from BOINC Manager", "Shut down connected client" menu entries on Linux
> Removed "Exit from BOINC Manager", "Shut down connected client" menu entries on Linux

- lib/proc_control.cpp
Fixes #3026
Changed SIGSTOP to SIGTSTP as SIGSTOP can not be caught. 
The use of  SIGTSTP allows the code run by the wrapper to act upon this signal such as pausing a running container.
> Changed SIGSTOP to SIGTSTP

- clientgui/BOINCBaseFrame.cpp
New version of https://github.com/BOINC/boinc/pull/2969 that has been closed by mistake
Fixes #2604 #1348 
On Linux when you close the BOINC Manager window, it will be minimized instead of closed.
The patch closes the BOINC Manager window correctly.
Read
https://github.com/BOINC/boinc/issues/2604#issuecomment-445826926
and
https://github.com/BOINC/boinc/issues/1348#issuecomment-444534306
(they are the same comment)
On Linux, when a user closes BOINC Manager window, it will be closed rather than minimized.
> Fixes window close action on Linux

- clientgui/AdvancedFrame.cpp
- clientgui/AdvancedFrame.h
- clientgui/BOINCBaseFrame.cpp
- clientgui/BOINCBaseFrame.h
- clientgui/sg_BoincSimpleFrame.cpp
- clientgui/sg_BoincSimpleFrame.h
Add AM functions (join, leave, synch) to simple view Tools menu, same as Advanced view.
Also did some code cleanup/reorg.
The simple view (CBOINCSimplFrame) and advanced view (CBOINCAdvancedFrame)
each had their own functions for invoking the attach wizard.
Instead, have only one function, and make it a member of CBOINCBaseFrame,
from which each of these classes derives.
Other stuff is duplicated between simple and advanced also,
and we should consolidate it at some point.
Fixes #
> Manager: add account manager functions to simple view

- clientgui/BOINCBaseView.cpp
Reduce the number of times the task list scrolls to the bottom under routine operations.
Fixes #2147
6479868b7c4c2efa87ff69d9e0910d43d2c33df7 (Linux only) scrolls the task list viewport to display the bottom line every time the number of items in the list changes during reporting/requesting new work. This is unnecessary, and goes beyond the design statement for the commit.
Linux only: eliminate unnecessary 'jump to bottom' events in Manager task list, caused by over-enthusiastic wxWidgets bug fix in 6479868b7c4c2efa87ff69d9e0910d43d2c33df7
> Manager: task list scrolling

- html/inc/submit_util.inc
Scenario:
- a submit_batch() creates a batch in INIT state
and starts creating jobs
- while it's in progress, a query_batches() RPC enumerates batches
- while the query_batches() is in progress,
the submit_batch() finishes and changes the state to IN_PROGRESS
- the query_batches() finishes and rewrites the batch in INIT state
Solution: query_batches() doesn't update batches in INIT state
Fixes #
> remote job submission: fix race condition

- client/gui_rpc_server_ops.cpp
- clientgui/ProjectInfoPage.cpp
Remove http(s): at the beginning of project address.
There is no reason to connect to secure address project  if we're already connected to the non-secure address or vice versa.
Partial fix for the issue mentioned in #1043
> [Manager] Fix project urls comparison

- sched/sched_keyword.cpp
- sched/sched_score.cpp
- sched/sched_send.cpp
- sched/sched_version.cpp
- sched/sched_version.h
> scheduler: check daily job limit on each job, not just when choosing AV

- .codecov.yml
- .gitignore
- .travis.yml
- 3rdParty/buildGoogletestLinux.sh
- 3rdParty/buildLinuxDependencies.sh
- Makefile.am
- configure.ac
- lib/Makefile.am
- m4/boinc_set_compile_flags.m4
- sched/Makefile.am
- tests/executeUnitTests.sh
- tests/unit-tests/CMakeLists.txt
- tests/unit-tests/lib/CMakeLists.txt
- tests/unit-tests/lib/test_str_util.cpp
- tests/unit-tests/lib/test_url.cpp
- tests/unit-tests/sched/CMakeLists.txt
- tests/unit-tests/sched/test_credit.cpp
* enable coverage reports from gcc and disable optimizations via option to configure
* install googletest library into buildcache
* script to compile and run unit tests using cmake
* first set of unit tests originally contributed by Keith Uplinger
There are several hardcoded paths and assumptions made in order to get this working on Travis CI. New tooling is using cmake for cross platform builds and as such is not easy to use with an autotools based system.
It's not ideal but better than nothing.
There are other unit testing frameworks out there that could have been used. Googletest satisfies the current needs and should be for the future since it is xUnit compatible.
Added unit-testing capability to BOINC to improve …
> Tests: add unit testing framework using googletest

- client/app_config.cpp
- client/rr_sim.cpp
- client/work_fetch.cpp
- client/work_fetch.h
- lib/cc_config.cpp
- lib/cc_config.h
See https://boinc.berkeley.edu/trac/wiki/WorkFetchMaxConcurrent
> Re-enable work buffering in the presence of max concurrent constraints.

- tests/unit-tests/lib/test_str_util.cpp
Add unit tests for str_util.cpp
Changed ASSERT_* calls to EXPECT_* as the former aborts the testrun immediately and the latter will run the remaining tests and mark the run as failed in the end. The remaining functions either don't need testing or need the googlemock framework to do proper testing.
N/A
> Tests: Add unit tests for str_util.cpp

- .codecov.yml
Turns off a comment to each pull request about the overall coverage status but keeps the comment about the change in coverage the pull request introduces when merged.
Group the coverage reports by components (flags) to be seen on the codecov.io website.
N/A
> Tests: tune codecov configuration

- html/inc/forum.inc
Fixes problem reported by Jord where if you view a thread with no posts
(e.g. the only post got moderated)
the thread continues to be shown as unread.
> web: if view empty thread, mark it as read

- android/Vagrant.README.md
Added a guide on how to set up the git and GitHub to push without a password prompt.
These type of guides should be placed in the Wiki, but we don't have one.
N/A
> [Android] Add guide to Vagrant Readme on how to push to GitHub without password using ssh-key

- android/Vagrantfile
Lubuntu Desktop Environment is lighter than the Mate DE, which is very beneficial in a virtual environments situation.
Lubuntu uses 194 MB RAM and 12,47 GB disk space, while Mate uses 435 MB RAM and 13,95 GB disk space. Plus with the new DE the installation process is also faster.
N/A
> [Android] Change the Desktop Environment from Mate to Lubuntu in Vagrant

- android/BOINC/app/src/main/res/values/theme.xml
By default there is dark-blue color as a background of drop-down menus.
This make black text drawn on blue looks not nice.
This changes default background color to white for better usability.
This fixes #2001
> [Android] Change color to white in drop-down menus

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
By default there was collapse icon on menu button.
After SDK update it looks like that is necessary to add extra function `setHomeAsUpIndicator()` to show correct icon instead of default 'Back' icon
This fixes #2940
> [Android] Fix menu button icon

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
- android/BOINC/app/src/main/res/layout/attach_project_list_layout.xml
Currently there is no way to cancel 'Add Project' procedure once it is started.
This pull request add cancel button to this screen.
Also it fixes the warning with `layout_alignParentRight` setting that could work in not a proper way for right-to-left UI.
I'm not sure whether it is an issue now but definitely will be better to have.
This fixes #3136
> [Android] Add Cancel button to 'Add Project' screen

- appveyor.yml
Change from http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git to https://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git for CI windows builds when loading windows build dependencies from Berkeley git repo
> [Windows] [AppVeyor] Use secure windows git dependencies path

- android/Vagrantfile
- android/buildAndroidBOINC-CI.sh
- android/build_all.sh
Move functionality to install NDK and download curl and openssl sources to CI script that are already presented there.
Fix usage of BUILD_DIR variable that was missed during input parameters parsing.
This fixes #3119
> [Android] Fix build_all.sh script to run CI script

- sched/db_purge.cpp
There are two bugs in db_purge zlib support code:
1. Wrong archive streams flushed (copy-paste programming...)
2. `Z_FULL_FLUSH` must not be used as it clears compression dictionary, this ruins compression. Use `Z_SYNC_FLUSH` instead.
This fixes #3145
Fixes #
> db_purge: fix bugs in zlib support

- client/scripts/boinc-client.service.in
Improve security by isolating boinc as much as possible.
See https://www.freedesktop.org/software/systemd/man/systemd.exec.html for explanations of each option
I don't think there are other designs; this is a means by which security can be improved. With this change, if a malicious job is sent to the boinc client, the damage it can do is significantly reduced.
N/A
> systemd hardening

- client/hostinfo_win.cpp
Fixes #
This patch add Hygon Dhyana("HygonGenuine") CPU Vendor ID detection and reuse AMD CPU feature flag detection codes to enable hygon cpu feature flags in windows boinc client.
As Hygon Dhyana (family 18h) share similiar arch with AMD family 17h arch, so reuse get_processor_features() feature detection codes.
related kernel patch links are:
http://lkml.kernel.org/r/5ce86123a7b9dad925ac583d88d2f921040e859b.1538583282.git.puwen@hygon.cn
Signed-off-by: fanjinke <fanjinke@hygon.cn>
add hygon cpu vendor detection and enable hygon CPU features.
> [Windows]hostinfo_windows:add Hygon dhyana support to enable Hygon CPU feature

- db/boinc_db.cpp
- db/boinc_db.h
- sched/db_purge.cpp
Fixes #3005 
The change adds the option --batches to delete all retired batches from the batch table. It is an alternative implementation to #3101 which does this in a separate php script.
> Purge retired batches from the batch table

- .codecov.yml
While the reason for the double comments by codecov is still unclear to me this change should disable the comments altogether if the coverage is not affected by this PR.
N/A
> Tests: tune codecov comments

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/GlobalPreferencesParser.java
While fixing a warning found by static analyzer:
`V6026 This value is already assigned to the 'mInsideDayPrefs' variable. GlobalPreferencesParser.java(61)`
I found that because of this mistake these settings were not parsed at all.
> [Android] Fix day_prefs parse

- deploy/deploy_to_bintray.sh
The weekly cronjob on Travis CI will trigger a cleanup once a month which will delete artifacts from closed pull requests and weekly builds older than 6 months. The Windows artifacts on AppVeyor are automatically deleted after 6 months.
N/A
> Deployment: run bintray cleanup script once a month

- client/client_state.cpp
> client: clear the vm_extensions_disabled flag on startup.

- sched/plan_class_spec.cpp
(existing code only worked with a.b.c and a.b)
Fixes #3172 
Without this change, Android apps that require a min version won't get sent to devices that report their version as a single number.
> scheduler: parse Android version strings of the form "(Android 9)"

- lib/parse.cpp
- tests/unit-tests/lib/test_parse.cpp
xml_unescape would take these and return incorrect values.
Checks for &quot; and &apos; were only checking for the first 4 characters.  So a string like this &quo1234 would be converted to "34 and the same for &apo1234 would be converted to '34
Checks for escaped ascii codes would allow for a few issues.  Expected escape to handle &#123; would return { 
1.  It didn't handle when semicolon didn't exist.  Thus could take something like &#1234567890 and attempt to convert that into an integer then into a char.  Could have unexpected issues. 
2.  It didn't handle when a character was before the semicolon found.  &#75d; would return K basically handling the issue incorrectly.  
The fix for this is to make sure that ascii values are respected, if not, keep the escape value as it was before …
> Bug:  Fix to xml_unescape function for multiple escape values.

- lib/opencl_boinc.h
Fixes https://boinc.berkeley.edu/forum_thread.php?id=12988:
Request for Intel iGPU support to be a working feature again.
Extensions list for OpenCL in Intel Windows DCH drivers found to require 1,117 bytes
N/A
> Lib: increased size of opencl extensions[] from 1024 to 2048

- html/inc/consent.inc
- html/user/user_agreetermsofuse_action.php
Fixes #3188
Instead of generating an error page when the use hasn't selected to use the "Stay Logged In" feature, the website should handle the absence the checkbox and simply create a session cookie.  This is done by setting $perm = false instead of generating the error page if the tempperm cookie is not present.
Fix bug causing an error when user did not select "Stay Logged In" and they needed to accept the websites terms of use.
> Fix invalid error message on accept terms of use page

- client/project.cpp
- client/work_fetch.h
- db/boinc_db.cpp
- samples/condor/boinc_gahp.cpp
- samples/vboxwrapper/floppyio.cpp
- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
- sched/db_purge.cpp
- sched/sched_types.cpp
Fixes uninitialized variables in several components
N/A
> Quality: fix small issues

- sched/sched_util_basic.cpp
The docs said this was the case, but it wasn't.
Fixes bug (reported by Eric Driver) where hosts w/ AMD GPUs weren't being sent GPU app versions.
> scheduler: if plan class name contains "amd", assume it's AMD GPU

- client/client_state.h
- client/cs_benchmark.cpp
- client/gui_rpc_server_ops.cpp
If CPU benchmark is requested via RPC by user, it should always run even if 'skip_cpu_bechmark' is set.
This fixes #2358
> [Client] Ignore 'skip_cpu_benckmark' flag if requested via RPC

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/res/values/configuration.xml
Assets folder has no possibility to include files with dot at the beginning so `InstallFile` function was modified to enable rename possibility when copying files from assets folder to target device.
This fixes #1437
> [Android] Add .nomedia file to client folder to tell Android Media Server not to check this folder for media files.

- html/inc/consent.inc
- html/inc/result.inc
- html/inc/util.inc
- html/user/submit.php
It's useful to see the stats (mean, max) of memory and disk usage,
e.g. so that you can set the appropriate bounds for future jobs.
In the case of universal VM apps (e.g. nanoHUB@home)
the natural place to put this is at the batch level;
jobs in a a batch use the same tool.
Also: add a general function for printing sizes in MB and GB,
and move a function from util.inc to the appropriate file.
Fixes #
> job submission: add ability to view mem/disk usage stats for a batch.

- sched/db_dump.cpp
> FreeBSD: Add missing #include <sys/wait.h> for WEXITSTATUS macro.

- appveyor.yml
Sometimes in case of non-clean VS cache folder nex issue could happen:
https://stackoverflow.com/questions/17574089/how-can-i-fix-the-microsoft-visual-studio-error-package-did-not-load-correctly
The only way to fix this is to clean this folder manually.
Doing this is this script is safer for potential further image upgrade when mentioned folder could be not cleaned up.
> [AppVeyor] Fix VS2013 build

- sched/plan_class_spec.cpp
Fix message stating batch but printing workunit ID instead.
> Fix incorrect variable printed to sched debug

- html/inc/stats_sites.inc
According to archive.org, the site is down at least since February 2019, so removing it from the list.
Fixes #3244
> Remove boincsynergy.com from the stats site list

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Fixes #
https://dev.gridrepublic.org/browse/DBOINCP-509
Adds a CAPTCHA to the user password reset form.
N/A
N/A
> Drupal: Add ReCaptcha to user password reset form.

- sched/file_upload_handler.cpp
When sizeof(int) != sizeof(size_t) the current code is a bit dangerous, imho. The signed vs unsigned may also be tricky together with the large files as for virtualbox. I admittedly only stumbled across it while chasing one of compiler warnings of the Debian package.
The "ul" instead of "d"+cast for printf, well, maybe I miss some hidden functionality then please add a comment.
Part of this patch lives as a Debian-only patch for years. I was revisiting the code to chase other warnings as promised in https://github.com/BOINC/boinc/issues/3245. There are more size_t issue in other files. If I get some positive vibes back about them then I will add them to this branch.
Cheers,
Steffen
> size_t matters

- client/cpu_sched.cpp
Before, if you changed cc_config.xml ncpus, you had to restart the client.
Note: don't use cc_config.xml to set your CPU usage.  Use computing preferences.
> client: make "reread config files" work for ncpus

- sched/sched_send.cpp
Code around this point suggests that clamping should be done to FRAC_MIN define, but it's finally set to another, hardcoded and unacceptable small, value. 
N/A
> scheduler: Fix incorrect clamping of host' fraction_available

- client/client_types.cpp
- client/result.cpp
This fixes a vulnerability where hacked projects could
write files outside the BOINC data directory.
Also: error-check parsing of file refs.
This doesn't handle Rytis's requirement; we can do that separately.
> client: don't allow ".." or "%" in logical names

- sched/wu_check.cpp
This tool cannot handle workunits without input files (e.g. if task parameters are set from command line). Accesses uninitialized memory, trying to open a file with a garbage name, prints a garbage on screen. In 'repair' mode, it will erroneously kill these completely normal workunits.
The patch silently skips such types of workunits.
N/A
> wu_check: Skip WUs without input files

- html/user/am_set_info.php
success() call was duplicated, resulting in duplicate XML.
Fixes #3297
success() is already called later in the code, so remove the early code, considering that a failure can still happen further on.
Remove duplicate XML in am_set_info.php reply
> Remove duplicate success XML

- client/app.cpp
- client/check_state.cpp
- client/client_state.h
- client/client_types.cpp
- client/client_types.h
- client/cs_files.cpp
Fixes #3287
On startup, the client checks whether files marked as present
actually are present and have the right side.
If not it marks them as not present.
This is fine for downloaded files - they'll downloaded again.
For output files, this could leave the job stuck in the "uploading" state,
since there's no file to upload.
Fix this by marking the job as having an upload error in this stuation.
> if output file missing, mark task as error

- sched/sched_result.cpp
Fixes second scenario of #3017 and improves #3019
This patch deals with "finish file problem" completely, bringing tasks affected by this bug "back to life" on the server side.
As was noted in https://github.com/BOINC/boinc/issues/3017#issuecomment-475907501 , this problem may also appear when client shutting down, and this is not fixed yet (I'll explain this scenario below). In #3019 was mentioned that "it should be treated as successful regardless of whether it exits, but right now we don't have a mechanism for killing a job and marking it as success."
This patch marks job as successful on the server side, so it'll fix all problems with all client versions.
**Cause of the problem**
There are two causes. First reason is a when an application really exits too …
> server: Workaround for "finish file present too long" client bug

- client/gui_rpc_server_ops.cpp
Fixes a problem reported by Germano Massullo, where issuing a GUI RPC using curl didn't work.
> client: remove HTTP header from HTTP GUI RPC request before parsing

- samples/wrapper/wrapper.cpp
In case checkpoint file fopen fails, BOINC stays in critical section.
End critical section in case of fopen failures in the wrapper
N/A
> Fix wrapper not ending critical section

- clientgui/sg_ProjectPanel.cpp
This is one of the ancient patches in Debian. When substituting
g++ with another compiler, here it was clang, one often sees new
warnings. No idea what the exact complaint was, but presumably
it was noted that "j" is used multiple times and in very different
contexts.
This patch declares "j" multiple times to indicate that there is
no information flow between the different parts of the code. The
human reader of the code may appreciate this more than the compiler.
Anchor: https://github.com/BOINC/boinc/issues/3260
> Declaring iterators where they are used, not "globally"

- client/app_control.cpp
Take out #2871.
That change was based on the incorrect assumption
that a suspended process doesn't handle quit messages.
Fixes #
> client: fix bug that caused jobs to run after client exit.

- client/cs_notice.cpp
When projects changed their poll intervals for RSS feeds (such as notices) these changes were being ignored by the client.
> client: don't ignore new poll intervals for RSS feeds.

- appveyor.yml
Don't trigger build when content of '.github' or 'integration_test' directories changed.
Fix 'tests' directory name
> [AppVeyor] Update config to ignore more directories

- client/app.h
- client/app_control.cpp
- client/client_state.cpp
- client/client_state.h
- client/cs_apps.cpp
Should fix problem where jobs finish while client is shutting down, as described in #3300
> client: on startup, check for active task finish files

- clientgui/AccountManagerProcessingPage.cpp
BAM! and GRCPool doesn't return any error code on wrong credentials.
The actual error is written in 'messages' field of the response.
Currently on worng credentials attach wizard shows that everything is fine while in the notices actual error is shown.
It is confusing.
This approach shows message from the response even if error code is equal zero (like when there is no error at all) and process it like an error.
> [GUI][AM] Show error from response when conencting to AM

- lib/shmem.cpp
This is yet another patch that is living for a lllooonnnggg time with Debian, so there should not be too many side issues. In the contrary, it could be contributing to a fix of the rarely observed leak of file descriptors, compare https://github.com/BOINC/boinc/issues/1175.
The motivation for this patch originated from clang who complained that we don't check if the write has failed.
Anchor: https://github.com/BOINC/boinc/issues/3260
> Check return value of write function - avoiding leak of file descriptors

- android/BOINC/app/src/main/aidl/edu/berkeley/boinc/client/IMonitor.aidl
- android/BOINC/app/src/main/aidl/edu/berkeley/boinc/utils/ErrorCodeDescription.aidl
- android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/ErrorCodeDescription.java
BAM! and GRCPool doesn't return any error code on wrong credentials.
Actual error message is written in 'messages' field in response.
This commit fixes this behaviour by showing an error message that is sent via response and treats it like an error while login.
This fixes #3236
> [Android] Show message sent from server when connecting to AM

- lib/procinfo_mac.cpp
Fixes a long-standing bug which caused non-BOINC CPU usage to always be computed as zero on Macs.
> Mac: Fix computation of non_BOINC CPU usage

- api/graphics2_unix.cpp
- api/macglutfix.m
- api/x_opengl.h
- client/app.h
- client/boinc_cmd.cpp
- client/cs_apps.cpp
- client/gui_rpc_server_ops.cpp
- client/switcher.cpp
- clientscr/Mac_Saver_Module.h
- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/gfx_cleanup.mm
- clientscr/gfx_switcher.cpp
- clientscr/mac_saver_module.cpp
- clientscr/screensaver.cpp
- clientscr/screensaver_win.h
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- lib/gui_rpc_client_print.cpp
- lib/mac/mac_spawn.cpp
- lib/mac/mac_util.h
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/PostInstall.cpp
- mac_installer/ReadMe.rtf
- mac_installer/release_boinc.sh
- mac_installer/release_brand.sh
- mac_installer/uninstall.cpp
Under OS 10.15 Catalina:
Problems:
* Screensavers can't launch _setuid_ / _setgid_ executables like `gfx_switcher` or `ps`
* Screensavers can't launch executables downloaded directly from the Internet unless they have first been vetted by the user via _GateKeeper_, but there is no provision for _GateKeeper_ to offer users that option for bare executables like project graphics apps.
Solution:
* Instead of launching graphics apps directly via `gfx_switcher`, the BOINC screensaver coordinator writes a file _BOINCSSHelper.txt_ containing the information about what to launch. The file is detected by a LaunchAgent which then launches `gfx_switcher` for us. `gfx_switcher` then deletes the _BOINCSSHelper.txt_ file, and writes a file _BOINCGfxPid.txt_ containing the graphics app's process ID …
> mac: Fixes for screensaver under OS 10.15 Catalina

- client/cs_scheduler.cpp
[sched_op] tag was missing for some debug messages.
Fixes #3360 
Add missing sched_op tag for some of the debug messages.
> Add sched_op debug flag tag to log messages

- sched/handle_request.cpp
Fixes #3360 
Simply calculated a new difference (time until you can send the work) and printed that instead of the existing difference.
Note: As this is a server change, I am unable to test it so feel free to test it for me.
N/A
N/A
> Made an event message more clearer

- html/inc/submit.inc
- lib/submit_api.py
- tools/submit_api_test.py
boinc_set_timeout($x): set timeout for job submission RPCs to x seconds
> remote job submission: add an API function for setting RPC timeout

- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
In 219a540 a circular dependency was introduced.
This commit fixes it in a similar way from the commit mentioned above for another structures.
> [Manager] Fix Manager crash in APP_VERSION::clear()

- appveyor.yml
- deploy/deploy_to_bintray.bat
- deploy/prepare_deployment.bat
Change build with devenv to more common used msbuild
Change AppVeyor cache saving from zip to 7zip with maximal compression
Fixes #2620
> [AppVeyor] Add Win32 build configuration

- win_build/boinc_ss_vs2013.vcxproj
> [VS2013] Add missed 'keyword' files to boinc_ss_vs2013.vcxproj file

- client/cs_scheduler.cpp
- sched/handle_request.cpp
client - show requested delay always (why hide it?)
server - ignore residual delay from previous RPC
Fixes #3375
> Scheduler (client and server): message tweaks

- android/BOINC/app/src/main/aidl/edu/berkeley/boinc/client/IMonitor.aidl
- android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
On the latest Android SDKs there are a lot of restrictions for background processes.
So if the service is run in background, it could be killed too early and BOINC will not start.
Removed setting to show notification when running only because now it makes no sense since Notification should be shown always when foreground service is running.
> [Android] Make BOINC always run foreground service

- client/cs_platforms.cpp
- client/gpu_opencl.cpp
Don't allow 32-bit project applications if running on Mac OS 10.15 or later
none
N/A
> Mac: allow 32-bit applications only if OS X version < 10.15

- client/log_flags.cpp
- lib/cc_config.cpp
- lib/cc_config.h
- lib/diagnostics.cpp
- lib/diagnostics.h
File sizes should always be double, not int
This fixes #3435
> client: make max_std(err/out)_file_size double

- client/boinc_cmd.cpp
- client/gpu_detect.cpp
- client/gpu_nvidia.cpp
- lib/app_ipc.cpp
- lib/coproc.h
- lib/gui_rpc_client_ops.cpp
- lib/hostinfo.cpp
- lib/hostinfo.h
PR #3364 changed the way we clear structures.
This introduced a bug: HOST_INFO::clear_host_info()
intentionally didn't clear HOST_INFO::coprocs.
But it was replaced with HOST_INFO::clear(), which did.
This caused the client to lose GPU info.
Fix: restore HOST_INFO::clear_host_info(), and add a comment
to avoid future errors like this.
Also add some comments in GPU detection,
which is woefully lacking in them.
> client: fix bug in GPU detection

- sched/handle_request.cpp
- sched/sched_version.cpp
My change a while back to enforce job limits correctly
didn't work with anonymous platform requests.
Also fixed wrong message and int/double format error when
reporting last request too soon.
> scheduler: fix crashing bug in anonymous platform case.

- client/cs_account.cpp
- client/cs_benchmark.cpp
- client/hostinfo_unix.cpp
- lib/coproc.cpp
- lib/coproc.h
Fixes #3454
There were two problems:
1) We weren't fetching work unless benchmarks had been run
(since a scheduler request must include a p_fpops value).
Fix: if --skip_cpu_benchmarks set, pretend that we ran benchmarks
and p_fpops is 1 GFLOPS
2) adding a project via the cmdline (--attach_project)
wasn't setting a flag to fetch the project's scheduler list.
Also: the new way of clearing structures (copying a static instance to *this)
causes a startup hang if the default constructor calls clear().
To fix this, have the static instance use a constructor
that doesn't call clear()
Also: fix message about libc version.
"[foobar] ...." means that the message is conditional on <debug_foobar>
> client: fix stall when --skip_cpu_benchmarks used

- html/inc/recaptchalib.php
I have no idea why, but out of nowhere ReCaptcha stopped working on both SU and S@h.
Changing an arg to the recaptcha constructor
(from a Stack Overflow entry from 2015) fixed the problem.
> Web: fix ReCaptcha problem

- android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
There will be zero or one connected Account Manager, so when found,
no need to iterate more.
Also projects have their unique URLs so once match found - search is
complete.
> [Android] Tiny cleanup project list logic

- client/scripts/Makefile.am
ran into
```
make[1]: Entering directory '/home/boincdev/boinc-client_release-7.16-7.16.5/client/scripts'
rm boinc-client.service
rm: can't remove 'boinc-client.service': No such file or directory
```
> avoid error when files to clean are not existing

- mac_build/buildWxMac.sh
Mac: Add patches to buildWxMac.sh script for building with XcodeMac: Add patches to buildWxMac.sh script for building with Xcode  11 and OS 10.15 sdk
Fixes #3476
> Mac: Add patches to buildWxMac.sh script for building with XcodeMac: Add patches to buildWxMac.sh script for building with Xcode 11

- clientgui/mac/templates/Info.plist
Fixes #3383
Please note: I am currently unable to build BOINC using Xcode 11.4 for Catalina due to a build error with WxWidgets, so I cannot test this change. Until I can fix this issue, if anyone with retina hardware is able to build and test this I would appreciate it.
This simply adds the `NSPrincipleClass` key to `Info.plist` to allow retina support as described [here](https://wiki.wxwidgets.org/WxMac-specific_topics#Retina_display_support).
This may need to be added to other `.plist` files in [clientgui/mac/templates](../tree/master/clientgui/mac/templates) to offer retina support for the installer, screensaver, etc. Without being able to test this I don't know.
Add support for macOS retina displays.
> Add retina display support for BOINC Manager

- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/release_boinc.sh
- mac_installer/release_brand.sh
Mac client and Manager: Improve symbol stripping and fix saving of symbol table files
[1] DWARF symbol table files boinc.dSYM and BOINCManager.app.dSYM are needed to debug crash reports from the field, but they were not being copied correctly into the boinc_x.y.z_macOSX_SymbolTables.zip file by custom scripts embedded in the Xcode project. This corrects that by removing that code from embedded Xcode project scripts and adding code to the release_boinc.sh script to copy them directly from the Built Products folder generated by Xcode.
[2] Symbol stripping was done inconsistently in the Xcode project build settings and the custom scripts embedded in the Xcode project. This PR fixes the Xcode project build settings to let Xcode do the stripping and removes the …
> Mac: Improve symbol stripping and fix saving of symbol table files

- android/buildAndroidBOINC-CI.sh
- android/build_all.sh
Fixes #
Path does not parse correctly for `build_all.sh` in WSL. Use double quotes.
Eliminate the need to redownload the NDK and source code for OpenSSL and cURL for every new build.
Virtualbox VM is slower, heavier, bandwidth intensive and time consuming just to set up one. WSL is much lighter and support is improving with the use of Visual Studio Code. Using Windows version of Android Studio should be possible. WSL needs to install the same dependencies listed in Vagrantfile. WSL also needs python2 to deal with `make_standalone_toolchain.py`.
ATM requires copying of entire repo to a readable path after binary compilation as Android Studio does not allow reading project files over WSL network share. However some files may not be copied …
> [Android] Fix WSL compatibility and improvement to script

- Makefile.am
Fixes #3471
Installs `project_specific_defines.h` in `PREFIX/include/boinc` if `--enable-install-headers` is `configure`d. It's `include`d by `config.h` which in turn gets used when building science apps or screensavers. Right now `config.h` isn't installed, but that's a separate issue dealt with in #2964.
n/a
> Install project_specific_defines.h if configured (required by config.h)

- .travis.yml
* deprecated key sudo (The key `sudo` has no effect anymore.)
* missing os, using the default linux
* key matrix is an alias for jobs, using jobs
> [TravisCI] Adjust script according to updated syntax

- clientgui/mac/SetVersion.cpp
Fixes #3486
* Don't check version string, always update
* Less efficient but allows template updates without version changes
n/a
> Update .plist files unconditionally

- clientgui/mac/templates/Info.plist
- clientscr/gfx_cleanup.mm
Fixes to Mac BOINC 7.14.3:
Add missing source file _clientscr/gfx_cleanup.mm_. This was included in the 7.14.3 release, but somehow it was never added to the `client_release/7/7.14 branch`.
Mac: Prevent OS X Mojave from trying to display BOINC Manager in Dark Mode, since BOINC does not yet support Dark Mode. This was not included in the the 7.14.3 release.
> Fixes to Mac BOINC 7.14.3

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
- android/BOINC/app/src/main/res/values-en/strings.xml
- android/BOINC/app/src/main/res/values/strings.xml
Fixes #
Add code to create a notification channel with the ID "main-channel", which is specified as the channel ID for BOINC notifications. This is required on Android Oreo and later; otherwise, notifications will not be displayed.
Fix display of notifications on Android Oreo and later.
> Create notification channel for use on Android Oreo and later.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
Fixes #
The NetworkInfo class that is currently used in the Android app, together with its associated methods (e.g. getActiveNetworkInfo() in ConnectivityManager), have been deprecated starting with API level 29 (Android Q), so this provides a supported mechanism of detecting network changes that works on API level 23 (Marshmallow) and higher. The deprecated version is still used on API levels 19 through 22 (KitKat and Lollipop).
N/A
> Use getActiveNetwork() to retrieve current network on Android Marshmallow and later.

- lib/network.cpp
Today, it looks like
```
04-Apr-2020 00:33:45 [TN-Grid Platform] Project requested delay of 121 seconds
04-Apr-2020 03:13:20 getaddrinfo(OpenWrt): Name does not resolve04-Apr-2020 03:13:22 [TN-Grid Platform] Project requested delay of 121 seconds
04-Apr-2020 04:36:43 getaddrinfo(OpenWrt): Name does not resolve04-Apr-2020 04:36:45 [TN-Grid Platform] Project requested delay of 121 seconds
04-Apr-2020 06:14:09 getaddrinfo(OpenWrt): Name does not resolve04-Apr-2020 06:14:11 [TN-Grid Platform] Project requested delay of 121 seconds
04-Apr-2020 07:36:18 getaddrinfo(OpenWrt): Name does not resolve04-Apr-2020 07:36:20 [TN-Grid Platform] Project requested delay of 121 seconds
```
which connects two messages that are unrelated - the first being caused by the host or its name server and the second …
> network.cpp: getaddrinfo error msg: "\n" added

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountIn.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountManagerClasses.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/GlobalPreferences.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Notice.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Result.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt
Use the writeBoolean() and readBoolean() methods to write booleans to and read booleans from Parcel objects on Android Q and higher, instead of using the writeBooleanArray() and createBooleanArray() methods.
The aforementioned writeBooleanArray() and createBooleanArray() methods are still called on older Android versions for backward compatibility.
N/A
> Use writeBoolean() and readBoolean() in Parcelable implementations on Android Q and later.

- android/BOINC/app/build.gradle
- android/BOINC/build.gradle
Enable code and resource shrinking for release builds and code shrinking for debug builds (the latter is needed to prevent a build error) and update the Android Gradle plugin to 3.6.2.
N/A
> Enable code shrinking and update Android Gradle plugin.

- db/boinc_db_types.h
Full timestamp is 19 characters long, so it need a 20-bytes buffer.
This is minor issue - this field is used only by db_purge. It causes db_purge output of this field to be truncated.
N/A
> db_purge: fix truncated mod_time data (field too small for timestamp)

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AcctMgrInfoParser.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountManagerParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountOutParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrInfoParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrRPCReplyParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppVersionsParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppsParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStateParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStatusParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/GlobalPreferencesParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/HostInfoParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessageCountParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessagesParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/NoticesParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectAttachReplyParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectConfigReplyParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectInfoParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectsParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ResultsParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/SimpleReplyParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TransfersParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/VersionInfoParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/WorkUnitsParserTest.java
Add tests that cover the catch block for SAXException in the RPC parser classes.
N/A
> [Android] Add SAXException tests for RPC parser classes.

- clientgui/ProjectPropertiesPage.cpp
A user attached to Science United as if it were a project, and confusion resulted.
> Manager: don't let user attach to account manager as a project.

- html/user/get_project_config.php
Fix get_project_config output if config file has <account_manager/>
> Parse config.xml correctly for account managers

- android/BOINC/app/proguard-rules.txt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/ECLists.java
* Add ProGuard configuration file with some useful debugging configurations.
* Create and use local Eclipse Collections list factory constant variables instead of using the ones in Eclipse Collections' `Lists` class, as these variables are not initialized properly in Android - this issue can be reproduced with the current master by long-pressing the BOINC logo on the splash screen, which results in a crash instead of loading the Event Log activity, with an error message stating that an implementation of the `MutableListFactory` interface cannot be found.
N/A
> [Android] Create local Eclipse Collections list factory constant variables.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/CredentialInputActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
Use the static methods included in the Apache Commons Lang library to avoid potential NullPointerExceptions and to simplify some null checks.
N/A
> [Android] Use Apache Commons static methods to avoid potential NPEs and simplify null checks.

- android/BOINC/app/build.gradle
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountManagerTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountOutTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrRPCReplyTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppVersionTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/BaseParserTest.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStateTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStatusTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/GlobalPreferencesTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/GuiUrlTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/HostInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessageTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/NoticeTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/PlatformInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectAttachReplyTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectConfigTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ResultTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TimePreferencesTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TimeSpanTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TransferTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/VersionInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/WorkUnitTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsTest.java
Alter tests that do not rely on PowerMock to use JUnit 5 instead of JUnit 4. JUnit 5 allows for a wider variety of tests to be written and fixes some issues with JUnit 4: https://www.baeldung.com/junit-5-migration
Tests that rely on PowerMock have not been altered as PowerMock is not yet compatible with JUnit 5: https://github.com/powermock/powermock/issues/830
N/A
> [Android] Migrate unit tests not using PowerMock to JUnit 5.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
Rewrite the readAuthToken() method in ClientInterfaceImplementation to read only a single line from the file instead of reading from it in chunks, as the authentication file has only a single line.
N/A
> [Android] Simplify the readAuthToken() method.

- client/hostinfo_network.cpp
- client/log_flags.cpp
- lib/cc_config.cpp
- lib/cc_config.h
If cc_config.xml contains <device_name>x</device_name>,
report that to projects rather than the name returned by gethostname()
Fixes #3587
> client: allow specifying device name in cc_config.xml

- android/BOINC/app/src/main/java/edu/berkeley/boinc/receiver/PackageReplacedReceiver.java
Avoid potential NPEs in PackageReplacedReceiver by using the StringUtils equals() and contains() methods.
N/A
> Use StringUtils methods in PackageReplacedReceiver.

- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/RpcClientTest.java
Use the `Spy` annotation with the existing `rpcClient` variable instead of a separate `mockRpcClient` variable, as this allows both the actual method implementations and stubbed methods to be called from the same variable.
N/A
> [Android] Use Spy annotation instead of a separate mock variable.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
Use the new ActivityManager.TaskDescription constructor, which accepts a String and a resource ID, on Android Pie and later as the older constructor is now deprecated.
N/A
> Use new TaskDescription constructor on Android Pie and later.

- client/boinc_cmd.cpp
- client/gui_rpc_server_ops.cpp
- client/switcher.cpp
- clientscr/Mac_Saver_Module.h
- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/boinc_ss_helper.sh
- clientscr/gfx_cleanup.mm
- clientscr/gfx_switcher.cpp
- clientscr/mac_saver_module.cpp
- clientscr/screensaver.cpp
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- lib/mac/mac_util.h
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
Fixes #
Significantly cleaner implementation of BOINC screensaver for Mac OS 10.15 Catalina than my original #3369
The previous implementation required installing a LaunchAgent for each user. The BOINC Screensaver Coordinator would write a data file to trigger the LaunchAgent. The LaunchAgent launched _gfx_switcher_. This data file contained information on which project graphics app to run. It was read by _gfx_switcher_ which then launched the requested project graphics app, deleted the data file, and wrote another data file with the graphic app's process ID. The Screensaver Coordinator read the process ID from the file. When the graphics app exited, _gfx_switcher_ deleted the process ID file to signal the Screensaver Coordinator. …
> Mac: Improved screensaver logic for OS 10.15 Catalina

- android/BOINC/app/build.gradle
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStateTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/CcStatusTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessageTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectConfigTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectInfoTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TransferTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/ErrorCodeDescriptionTest.kt
* Replace some ordinary tests with parameterized ones.
* Add parameterized test for `ErrorCodeDescription`.
* Remove the `kotlin-test-junit5` dependency, as calls to `JUnit5Asserter` have been replaced with calls to JUnit 5's `Assertions`.
N/A
> [Android] Add parameterized tests and remove kotlin-test-junit5 dependency.

- android/BOINC/app/build.gradle
Previously, only the JUnit 4 unit tests were run during the CI process. This change adds the JUnit Vintage Engine and configures the project to use the JUnit 5 runner by default to allow both the JUnit 4 and 5 tests to be run.
N/A
> [Android] Add JUnit Vintage Engine dependency.

- .travis.yml
- android/BOINC/app/build.gradle
Configure Travis to run the `assemble` task instead of `build` during the CI process.
N/A
> [Travis] Run tests for the Android app only during release builds.
