.travis.yml
build/getWxWidgets.sh

This is just a test to see if it works and what packages are missing.

BUILD: switch to container-based infrastructure on travis-ci

---

html/inc/countries.inc
html/inc/prefs.inc
html/inc/prefs_project.inc
html/inc/result.inc
html/inc/stats_sites.inc

This is a prerequisite for the upcoming integration of the Drupal web front-end for BOINC.

HTML: Make various variables accessible to Drupal by declaring them as global

---

html/ops/manage_app_versions.php

In addition to these two improvements you also might want to think about excluding all app versions of deprecated apps (not to be confused with deprecated app versions). Either generally or optionally by default.

Improve usability of html/ops/manage_app_versions.php for handling large lists

---

locale/Makefile.am

cfr Ubuntu LP bug: #1315614, #1502568
Debian bug: #800838)

Add missing locales and fix localization strings

---

html/ops/pass_percentage_by_platform.php

Fix pass percentage by platform

---

zip/test.cpp

That's better to not duplicate it.
+ Check result of CreateDirectory and emit error to perror, if needed.

Move duplicated zip / unzip code to a one place.

---

html/inc/result.inc

* Added still required code that was removed without apparent reason
* If in doubt about a code's purpose, please check the history first
* Original commit: 8be519a

Fix regression in d4dec27

---

html/inc/team.inc

This simply adds a missing closing td tag on the team members list.

Add closing td tag on team members list

---

html/user/server_status.php

$d-pid_file has spaces in front of it and at the end, so the composed path is wrong.
Therefore trim it.

remove spaces in pid_file

---

html/inc/boinc_db.inc
html/inc/db_ops.inc
html/inc/util.inc
html/inc/util_ops.inc
html/ops/cancel_workunits.php
html/ops/cancel_workunits_action.php

Uses the DB interface and functions for validating POST and GET data.

Ops: update some older ops scripts

---

client/pers_file_xfer.cpp

Try all download servers when multiple URLs are supplied by the project. This is needed because the first download server may be unreachable or out of sync which produces a permanent error. Uploads are handled differently and always use the transient_failure() function.
Can we get this merged into the 7.6 branch and send out to the alpha testers please?

Client: select next download url if the current one fails

---

html/inc/result.inc
lib/error_numbers.h

Added three error codes for use with the completion trigger file mechanism in the vboxwrapper.

Error codes

---

tools/process_input_template.cpp

If no open_name is specified in a file_ref element of the input template but copy_file is set for this file use the physical filename as logical filename.

create_work: use file_name as open_name when copy_file is set

---

tools/check_project

I wrote a python script which is meant to be run after make_project. It checks whether the apache user can write to certain directories. It also checks whether certain php modules are installed.
If there are more directories to add or more php modules to check for, please let me know.
Fixes #1535

Feature checkperm - checks permissions of apache user and presence of php modules

---

android/BOINC/src/edu/berkeley/boinc/adapter/ClientLogListAdapter.java
android/BOINC/src/edu/berkeley/boinc/adapter/NoticesListAdapter.java
android/BOINC/src/edu/berkeley/boinc/adapter/TasksListAdapter.java

Also, renders elapsed time of tasks with ```android.text.format.DateUtils.format()```

AndroidBOINC: Render time stamps according to current locale

---

android/BOINC/assets/all_projects_list.xml

AndroidBOINC: Update all_projects_list.xml from Windows/Mac deployments

---

drupal/sites/all/features/boinc_standard/boinc_standard.input_formats.inc

* Changed the filter order to
1. TOC
2. Pathologic
3. BBCode
4. HTMLPurifier
5. Image Caption
Also, slightly optimized pragmatic HTMLPurifier and BBCode settings
https://dev.gridrepublic.org/browse/DBOINCP-279

Fixed rich text input format filters

---

locale/templates/BOINC-Drupal.pot

* Introducing "msgctxt" providing context details
* Allows to specify identical source strings in separate contexts

Update Drupal i18n strings once again

---

drupal/sites/default/boinc/modules/boincteam/boincteam.module
drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php

Fixes DBOINCP-257 and DBOINCP-258
Anonymous Users (not logged in) will no longer see a link "Send Message" in the Forums. One must be logged in.
Team creation link has been changed: now anonymous users are directed to login if they want to create a new team.

Drupal added code to remove & change certain links for anonymous users

---

drupal/sites/default/boinc/themes/boinc/css/comments.css

very simple fix
https://dev.gridrepublic.org/browse/DBOINCP-278

Drupal: removed extraneous CSS code

---

drupal/sites/default/boinc/modules/boincteam/boincteam.module

Added test to make sure node content is of type==team.
https://dev.gridrepublic.org/browse/DBOINCP-333

Drupal: Fix bug where team view panel could view any node.

---

drupal/sites/default/boinc/modules/boinccore/boinccore.module
drupal/sites/default/boinc/themes/boinc/template.php

Edit link has been moved into the standard user links. Moderator/Admin links have been reordered.
In addition, some indent and whitespace changes to match Drupal coding standards.
https://dev.gridrepublic.org/browse/DBOINCP-334

Drupal: Changed order of comment/forum topic links.

---

drupal/sites/default/boinc/modules/boinccore/boinccore.module
drupal/sites/default/boinc/themes/boinc/template.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php

Subscribe link was accidentally removed in [PR 1683](https://github.com/BOINC/boinc/pull/1683). This PR will restore the link, add some misc documentation, and fix a PHP strict warning message.

Drupal: Fixed subscription link.

---

locale/templates/BOINC-Client.pot
locale/templates/BOINC-Manager.pot
locale/templates/BOINC-Project-Generic.pot
locale/templates/BOINC-Setup.pot
locale/templates/BOINC-Web.pot
locale/update_templates.sh

This is the current state of automatically generating localization templates. I didn't check if I added all the relevant files in `doc/` after the bootstrap conversion. I can add some more before pushing the templates to transifex.

Locale: Update scripts and templates

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

Debug statements removed, after being left in PR #1746 .

Drupal: Removed debugging statements left in accidentally.

---

clientgui/DlgHiddenColumns.cpp

MGR: Fix windows compile warnings (Visual Studio 2013).

MGR: Fix windows compile warnings (Visual Studio 2013).

---

drupal/sites/default/boinc/modules/boinc_solr_search/boinc_solr_comments/boinc_solr_comments.module

Cosmetic fix part of
https://dev.gridrepublic.org/browse/DBOINCP-274

Drupal: Capitalize the bundle for "Comment".

---

drupal/sites/default/boinc/themes/boinc/templates/search-result.tpl.php

Drupal: Search result returns user profile image

---

.travis.yml
lib/diagnostics_win.h

Installs dependencies and runs the custom Makefile using the correct cross compiler.

Build: try to build libraries with mingw on travis-ci

---

drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.module

see comment in https://dev.gridrepublic.org/browse/DBOINCP-317

Drupal: fixed error messages

---

drupal/sites/default/boinc/themes/boinc/templates/views-view-table--boinc-team-forum-topics.tpl.php

Changed template for team forum topic to use different variables. Now template uses $results, not topics/rows variable. The former has numerical values, which won't be translated into another language.
https://dev.gridrepublic.org/browse/DBOINCP-360

Drupal: Fixed bug where font-awesome icons were not appearing correctly on some translated pages.

---

html/ops/delete_job_files

Script was broken after 3f0f36ac5aac7c921bf81f8b90da436010ae6fb2

Ops: fix delete_job_files

---

android/Vagrant.README.md
android/Vagrantfile

Android: Provide dev/build environment using Vagrant

---

android/BOINC/app/src/main/res/values/strings.xml

Android: update copyright details

---

clientgui/MainDocument.cpp

Manager: Fixed spelling in 'Update Version Check'

---

html/inc/boinc_db.inc
html/inc/db_conn.inc
html/user/per_app_list.php

Implemented pagination and first level caching in per_app_list.php

Added pagination and first level caching to per_app_list

---

drupal/sites/default/boinc/modules/contrib/elysia_cron/API.txt
drupal/sites/default/boinc/modules/contrib/elysia_cron/INSTALL.txt
drupal/sites/default/boinc/modules/contrib/elysia_cron/LICENSE.txt
drupal/sites/default/boinc/modules/contrib/elysia_cron/README.txt
drupal/sites/default/boinc/modules/contrib/elysia_cron/cron.php
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.admin.inc
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.ctools.inc
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.drush.inc
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.info
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.install
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron.module
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron_scheduler.inc
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron_scheduler_old.inc
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_cron_update.php
drupal/sites/default/boinc/modules/contrib/elysia_cron/elysia_drupalconv.php

Moved `elysia_cron` module to boinc/modules/contrib. The module has been updated as well.
https://dev.gridrepublic.org/browse/DBOINCP-367

Drupal: update module elysia cron

---

drupal/sites/default/boinc/themes/boinc/template.php
drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/search-result.tpl.php

Thousands separator based on language, which informs the locality to pass to PHP's NumberFormatter.
https://dev.gridrepublic.org/browse/DBOINCP-320

Drupal: Added thousands separator to user info Post, Credit, and RAC.

---

drupal/sites/default/boinc/modules/contrib/features/tests/features_test.info

Part of https://dev.gridrepublic.org/browse/DBOINCP-369

Drupal: Fixed typo in version number for features test module.

---

drupal/sites/all/features/boinc_standard/boinc_standard.pages_default.inc
drupal/sites/all/features/boinc_standard/boinc_standard.panels_default.inc
drupal/sites/all/features/private_messages/private_messages.panels_default.inc
drupal/sites/all/features/stats_charts/stats_charts.panels_default.inc
drupal/sites/all/features/team_forums/team_forums.pages_default.inc
drupal/sites/all/features/teams/teams.pages_default.inc
drupal/sites/all/features/user_account_project_list/user_account_project_list.panels_default.inc
drupal/sites/all/features/user_profiles/user_profiles.panels_default.inc
drupal/sites/all/features/work_and_host_stats/work_and_host_stats.pages_default.inc

Due to change in Panels module, Feature overrides appear. These look to be minor config changes. Hopefully this new config will remove the overrides.
https://dev.gridrepublic.org/browse/DBOINCP-374

Drupal: Updated all Features using Panels

---

drupal/sites/default/boinc/modules/boincteam/boincteam.module
drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-381

Drupal: Fixed bts() function calls.

---

drupal/sites/default/boinc/modules/boinctranslate/boinctranslate.admin.inc

https://dev.gridrepublic.org/browse/DBOINCP-356

Drupal: added description text to BOINC translation tools/buttons.

---

clientgui/DlgItemProperties.cpp
clientgui/DlgItemProperties.h

As requested in #1935 to add the possibility to select any text in this window.

Manager: Use wxHTMLWindow in task property window

---

drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
drupal/sites/default/boinc/modules/boincwork/boincwork.module
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
drupal/sites/default/boinc/themes/boinc/css/forms.css
drupal/sites/default/boinc/themes/boinc/css/pages.css
drupal/sites/default/boinc/themes/boinc/css/tabs.css
drupal/sites/default/boinc/themes/boinc/templates/views-view-table--boinc-account-computers--panel-pane-1.tpl.php

New task table built without Views. Instead custom SQL queries are used to build a table using drupal's theme_table() function. The navigation bar is build with drupal's theme_item_list() function, with the class being 'tabs'.
For details see:
https://dev.gridrepublic.org/browse/DBOINCP-75
https://dev.gridrepublic.org/browse/DBOINCP-30

Drupal: New task table with navigation bar and application filter.

---

drupal/sites/all/features/boinc_standard/boinc_standard.pages_default.inc
drupal/sites/all/features/team_forums/team_forums.pages_default.inc
drupal/sites/all/features/teams/teams.pages_default.inc
drupal/sites/all/features/work_and_host_stats/work_and_host_stats.pages_default.inc
drupal/sites/default/boinc/themes/boinc/template.php
drupal/sites/default/boinc/themes/boinc/templates/user-profile.tpl.php

Add head title to pages which were missing them.
https://dev.gridrepublic.org/browse/DBOINC-65

Drupal: add titles to missing pages

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc

https://dev.gridrepublic.org/browse/DBOINCP-378

Drupal: Add urldecode and regex replace to clean a user name before account creation.

---

drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_argument_term_node_tid.inc
drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_field_term_node_tid.inc
drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_filter_term_node_tid.inc
drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_handler_relationship_node_term_data.inc
drupal/sites/default/boinc/modules/contrib/views/modules/taxonomy/views_plugin_argument_validate_taxonomy_term.inc
drupal/sites/default/boinc/modules/contrib/views/views.info

https://dev.gridrepublic.org/browse/DBOINCP-384

Drupal: Manually patched views with SA-CONTRIB-2017-022.patch¦file.

---

drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc

https://dev.gridrepublic.org/browse/DBOINCP-30
https://dev.gridrepublic.org/browse/DBOINCP-75

Drupal: Fixed spacing in tasks table navigation bar and application drop-down.

---

drupal/sites/all/features/teams/teams.views_default.inc
drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
drupal/sites/default/boinc/modules/boincwork/boincwork.views.inc

https://dev.gridrepublic.org/browse/DBOINCP-386

Drupal: Removed host/users/teams with zero (0) total credit from Statistics Views.

---

drupal/sites/all/features/user_account_host_list/user_account_host_list.views_default.inc
drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
drupal/sites/default/boinc/themes/boinc/templates/views-view-table--boinc-account-computers--panel-pane-1.tpl.php

https://dev.gridrepublic.org/browse/DBOINCP-30
and
https://dev.gridrepublic.org/browse/DBOINCP-71

Drupal: Fix links to task table in Views and Account Dashboard page.

---

drupal/sites/default/boinc/themes/boinc/templates/user-profile.tpl.php

https://dev.gridrepublic.org/browse/DBOINCP-340

Drupal: Changed logic and message to explicitly identify non-existant profiles

---

drupal/sites/default/boinc/modules/boincteam/boincteam_forum.module
drupal/sites/default/boinc/modules/boincteam/includes/boincteam.forms.inc
drupal/sites/default/boinc/modules/boincwork/boincwork.module
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-336

Drupal: Fixes various incorrect btS() function calls: wrong parameters passed

---

drupal/sites/default/boinc/themes/boinc/css/pages.css
drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/page.tpl.php

Adds link near top breadcrumb to post a new comment, for logged in users.
Adds breadcrumb to bottom on forum and team forum pages.
https://dev.gridrepublic.org/browse/DBOINCP-309

Drupal: forum page additions

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

Text should match instructions on Seti@Home site (2017-07-19).
https://dev.gridrepublic.org/browse/DBOINCP-393

Drupal: Updated instructions on Join pages

---

html/inc/email.inc

Fixes https://github.com/BOINC/boinc/issues/1991

skip SFS check for obviously private IP addresses

---

sched/plan_class_spec.cpp
sched/plan_class_spec.h
sched/sched_customize.cpp
sched/sched_customize.h
sched/sched_version.cpp

I'm not sure that the changes are correct; I need to think more about this.

Revert "plan classes:  add workunit-related filters"

---

html/inc/result.inc

Fixes #2011.
https://github.com/BOINC/boinc/issues/2011

Fixed bug where assignment '=' was used instead of comparison '=='.

---

clientgui/DlgItemProperties.cpp
clientgui/DlgItemProperties.h

Fix text styles (font, size) and set backgroung to window default.

Manager: Fix Properties Window

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

so that if either exists, the Join Page will link to it.
https://dev.gridrepublic.org/browse/DBOINCP-393

Drupal: Added a second link to rules-and-policies 

---

drupal/sites/default/boinc/themes/boinc/template.php

https://dev.gridrepublic.org/browse/DBOINCP-390

Drupal: Added logic to print No task/host/workunit found if View returns no results

---

appveyor.yml
win_build/load_dependencies.bat

Build Windows: Add AppVeyor support for Windows CI builds.

---

appveyor.yml

It seems that the repository file overrides the config set via the website.

AppVeyor: update configuration

---

sched/db_purge.cpp

- don't delete if --nodelete arg to db_purge
- reduce DB queries

db_purge: fix bugs with assignment deletion

---

drupal/sites/default/boinc/modules/boincwork/boincwork.module
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc

https://dev.gridrepublic.org/browse/DBOINCP-391

Drupal: Added <modified> tag to project_preferences payload XML.

---

clientgui/BOINCBaseFrame.cpp
clientgui/BOINCGUIApp.cpp
clientgui/DlgOptions.cpp
doc/versions.inc

Manager: use "client" instead of "daemon"

---

clientgui/DlgItemProperties.cpp
clientgui/DlgItemProperties.h

'Copy all' and 'Copy Selected' buttons added.

Manager: Properties Window fix

---

html/inc/prefs.inc
html/inc/util.inc
html/user/prefs.php

- for "add prefs for home" etc. use buttons instead of link
- use green for default button
- use yellow for risky buttons (like "reset prefs")

Improve button appearance in prefs page

---

html/inc/host.inc
html/inc/team.inc
html/inc/user.inc
html/inc/util.inc
html/user/friend.php

web: allow parts of web functionality to be disabled

---

html/inc/bootstrap.inc

NO_COMPUTING defined always after commit https://github.com/BOINC/boinc/commit/e9244a784420e4305ac1f74a842b7d1305bd41da

Fixed displaying the menu "Computing"

---

drupal/sites/default/boinc/modules/contrib/views/includes/ajax.inc
drupal/sites/default/boinc/modules/contrib/views/views.info

* https://dev.gridrepublic.org/browse/DBOINCP-407
* Applied SA-CONTRIB-2017-068-6.x-2.x patch

Drupal: D6 LTS / views

---

drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc

1. BOINC state_num() function was changing the object. Using clone $result to pass a copy of the object instead.
2. Anonymous platforms were not correctly supported. Now two LEFT JOINs and a new pretty_application_version() function should handle anonymous platforms correctly.
https://dev.gridrepublic.org/browse/DBOINCP-387

Drupal: Fixed two bugs in task table.

---

clientgui/DlgAdvPreferences.cpp

As requested in #2044: Daily schedules not checking hours input

Manager: fix daily schedules input data check

---

drupal/sites/default/boinc/themes/boinc/css/pages.css
drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node.tpl.php

Removed "|" for divider, use CSS for a border divider, and add permission check for new comment link.
Part of https://dev.gridrepublic.org/browse/DBOINCP-309

Drupal: Modified how subscribe link layout. 

---

lib/cc_config.cpp

fixes presenting problem in #2103

client library: inconsistent terminology for intel_gpu

---

samples/condor/boinc_gahp_protocol.txt

Based on http://research.cs.wisc.edu/htcondor/gahp/gce_gahp_protocol.txt version 0.1, http://boinc.berkeley.edu/trac/wiki/CondorBoinc version 27 and https://github.com/BOINC/boinc/blob/f640f89bb266db26c09ee2bf6f677dd0df6610ea/samples/condor/boinc_gahp.cpp

Remote job submission: first draft of protocol spec file for BOINC-GAHP

---

client/acct_mgr.cpp
client/client_state.cpp
client/project.cpp
client/project.h

when handling an AM repy:
- check URL signature only for projects being attached.
- clear dont_request_more_work, detach_when_done if not present in reply
Store disk usage and share in state file; report to AM

client: extensions, fixes to account manager functionality

---

README.md

Made link to gnu.org https
Should also make boinc.berkeley.edu link at the top secure! ;)

README.md - HTTPS Link for GNU.org

---

drupal/sites/default/boinc/modules/boincwork/boincwork.admin.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
drupal/sites/default/boinc/modules/boincwork/includes/projectprefs.xsd

Revert commits:
09b619bb97a950c024c1b53458dcb5d188c2bcdc
62b64347f70725af455acd6bec996ffd625d5e7b
3fead8d9a53f140ac3e7e60fcc22106fc6c1186d
c3d8d4dfcf3921a14c5ff683cd317d86779ba123
These four commits are associated with Pull Request (PR) #2025 , topic branch drshawnkwang:drupal_feature-projprefxml-apps.
Conflicts:
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc
Conflict was manually fixed.
See:
https://dev.gridrepublic.org/browse/DBOINC-87

Drupal: Revert PR 2025 project pref XML changes

---

drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-395

Drupal: Fix moderation link on account finish landing page.

---

drupal/sites/default/boinc/modules/boinccore/boinccore.admin.inc

... standard page generator.
https://dev.gridrepublic.org/browse/DBOINCP-401

Drupal: Added moderation and rules and policies page/node to the BOINC

---

locale/Makefile.am

Build: install locale files in out-of-tree builds

---

drupal/sites/default/boinc/modules/contrib/privatemsg/privatemsg.module

https://dev.gridrepublic.org/browse/DBOINCP-411

Drupal: Reverted code to use a comma as separated between BOINC username

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-395

Drupal: Changed moderation link to open in a new window (tab).

---

html/user/login_token_lookup.php

Opening new pull request on behalf of @davidpanderson  since this branch has been previously merged.  The pull request that this continues is: https://github.com/BOINC/boinc/pull/2202
Note on process:  Since this pull request is a continuation of a previous opened by David, I can continue to server as the reviewer since this is David's code, not mine.

lookup_login_token RPC: check for volid token

---

client/gpu_opencl.cpp

This is basically the same as PR #2227 but for master instead of the 7/8 branch. 
But it also adds code to trust the memory size returned from OpenCL on OS 10.7 and later, using the alternate OpenGL-based method only for OS 10.6.x. This addition is based on tests I have run which indicate that OpenCL returns the correct value in OS 10.7+, but it needs testing by more people and on more Macs before release, so I have not included it in the hot fix for the 7.8 branch.

Mac OpenCL: fix memory size calculation for AMD GPUs

---

drupal/sites/default/boinc/modules/boincteam/includes/boincteam.helpers.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-328

Drupal: Fixed bug in autocomplete function.

---

sched/file_deleter.cpp

Allows arbitrary formatting of input, output templates

file_deleter: use new XML parser for wu/result XML docs

---

client/acct_setup.cpp
client/client_state.cpp
client/cs_cmdline.cpp
client/cs_statefile.cpp
client/current_version.cpp
client/log_flags.cpp

http should be replaced with https where possible.  This changes some that I came across.

Client - Change some links and urls to use https instead of http

---

drupal/sites/all/features/private_messages/private_messages.features.user_permission.inc

private messages, read and delete are still allowed for any authenticated user.
https://dev.gridrepublic.org/browse/DBOINCP-415

Drupal: Changed permissions to only community members may write 

---

html/inc/account.inc
html/inc/bootstrap.inc
html/inc/util.inc
html/user/edit_email_form.php
html/user/edit_passwd_form.php
html/user/login_auth.php
html/user/mail_passwd.php

- call it "Reset password"
- move authenticator-based login to a new file, login_auth.php
This is intended for admins, not users
- Use bootstrap forms

web: improve password reset form

---

client/acct_mgr.cpp
client/client_state.h
client/cs_platforms.cpp
client/cs_scheduler.cpp

This lets AMs like TBD make better meta-scheduling decisions

client: include platform names in account manager request

---

drupal/sites/default/boinc/modules/boincteam/boincteam.module

https://dev.gridrepublic.org/browse/DBOINCP-417

Drupal: Add Join a Team link to account dashboard.

---

locale/templates/BOINC-Client.pot
locale/templates/BOINC-Manager.pot
locale/templates/BOINC-Project-Generic.pot
locale/templates/BOINC-Setup.pot

Only translation related changes are from html/user/get_passwd.php. Other changes are just changed references.
Note: BOINC-Web.pot is not updated because the source files moved to a separate repository that does not follow the BOINC development process.

Locale: Update localization template files [skip ci]

---

html/inc/boinc_db.inc
html/inc/util.inc

... and show this with the project banner and footer.
This is a bit tricky.

web: always show "Project down" page if project is in fact down

---

win_build/boinc_cli_vs2013.vcxproj
win_build/boinc_os_ss_vs2013.vcxproj
win_build/boinc_ss_vs2013.vcxproj
win_build/boinccmd_vs2013.vcxproj
win_build/boinclog_vs2013.vcxproj
win_build/boincmgr_vs2013.vcxproj
win_build/sim_vs2013.vcxproj
win_build/sleeper_vs2013.vcxproj
win_build/test_boinc_zip_vs2013.vcxproj

Fix windows build using VS2013.

---

html/inc/result.inc

Fix https://github.com/BOINC/boinc/issues/2277

Optimized the counts of results by states and apps for results page

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-420

Drupal: Fixed join page text for boinc users.

---

appveyor.yml

[AppVeyor] Add more directories to ignore list

---

clientgui/DlgAbout.cpp

This fixes #2372.
Please note that all translation files must be corrected too

[Manager] Fix copyright year in About window

---

html/ops/get_versions.php
html/user/download.php

A new ?dev=1 arg tells it to show Development versions of the client

Make download.php (for auto-attach) work for both test and production

---

html/user/edit_passwd_form.php

BTW, I'd like to have a "show password" checkbox here
for people with no one looking over their shoulder.
Maybe later.

web: fix bugs in change-password page.

---

html/inc/account.inc

Generate a new login token only if the current one is older than a day.
That way if a user does several downloads in quick succession
(for whatever reason) autoattach will work with all of them.

web: in download.php, use current login token if recent

---

drupal/sites/all/features/boinc_standard/boinc_standard.strongarm.inc

Regression/missing in 9de2db9a
see https://dev.gridrepublic.org/browse/DBOINCP-424

Drupal: updated Strongarm variable to reflect new HTMLPurifier version

---

.gitignore
db/schema.sql
html/inc/account.inc
html/inc/user_util.inc
html/ops/db_update.php
html/user/edit_passwd_action.php
html/user/edit_passwd_form.php

web: add 'show password' to join and change password pages.  add label to text for show password to make it easier to select the show password option

Add 'show password' to join and change password pages

---

drupal/sites/default/boinc/modules/boincteam/includes/boincteam.helpers.inc
drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc

part of https://dev.gridrepublic.org/browse/DBOINC-60

Drupal: Changed db_set_active to use proper database name.

---

drupal/sites/default/boinc/themes/boinc/templates/comment.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-forum.tpl.php
drupal/sites/default/boinc/themes/boinc/templates/node-team_forum.tpl.php

https://dev.gridrepublic.org/browse/DBOINCP-253

Drupal: Added user roles to forum user info, below username and stats.

---

html/user/submit_rpc_handler.php

remote job submission: fix bug that caused spurious errors to be returned

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc

Also added help text to Privacy form.
https://dev.gridrepublic.org/browse/DBOINCP-430

Drupal: Changed create account to set show_hosts to false.

---

drupal/sites/all/features/boinc_standard/boinc_standard.strongarm.inc

password reset, etc.
https://dev.gridrepublic.org/browse/DBOINCP-431

Drupal: Changed email templates for user registration, activation

---

html/inc/db_ops.inc
html/inc/util_ops.inc
html/ops/db_action.php
html/ops/result_summary.php
sched/credit.cpp

to avoid conflict with non-admin versions.  Fixes issue #2496.

web: change names of admin functions to e.g. admin_show_user()

---

html/user/forum_post.php

Why did it take me 15 years to do this?

web: show title in thread preview

---

html/inc/user_util.inc
html/ops/login_action.php
html/user/login_action.php
html/user/lookup_account.php

... rather than having it duplicated in 3 places.
Please review https://boinc.berkeley.edu/trac/wiki/CodingStyle

Factor passwd hash logic into a function

---

db/schema.sql

Please read these before changing the schema.
Recent schema changes don't follow these rules.
At some point they should be revised.

Update comments in db/schema.sql

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc

https://dev.gridrepublic.org/browse/DBOINCP-425

Drupal: Changed password hash algorithm to match upstream changes.

---

html/user/submit_rpc_handler.php
lib/remote_submit.cpp
lib/remote_submit.h
tools/backend_lib.h
tools/create_work.cpp

This lets you specify the rsc_* parameters and delay bound in the submit call.
Docs on new interfaces: https://boinc.berkeley.edu/trac/wiki/RemoteJobs

remote job submission: add optional "job params" for batchs

---

html/user/submit_rpc_handler.php

Testing remote job submission using the result from PR #2416 revealed an issue with the job params retrieval.

remote job submission: corrected job params retrieval

---

samples/condor/boinc_gahp.cpp

Added support for job params and app version. Testing against PR #2416.

Added support for job params and app version

---

drupal/sites/default/boinc/themes/boinc/css/html-reset.css
drupal/sites/default/boinc/themes/boinc/css/navigation.css

https://dev.gridrepublic.org/browse/DBOINCP-439

Drupal: Add font-awesome 'link' icon to all external links.

---

drupal/sites/default/boinc/themes/boinc/css/html-reset.css
drupal/sites/default/boinc/themes/boinc/css/navigation.css

Part of https://dev.gridrepublic.org/browse/DBOINCP-439

Drupal: Fix bug in Font Awesome CSS.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc

part of: https://dev.gridrepublic.org/browse/DBOINCP-428

Drupal: Added more paths to ignore opt-in page.

---

drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.module

https://dev.gridrepublic.org/browse/DBOINCP-429

Drupal: Changed wording on delete page and email.

---

client/acct_setup.cpp
html/user/login_token_lookup.php

- token lookup RPC returned wrong tag
- client failed to record AM name

Client: bug fixes for auto-attach

---

html/user/download.php
html/user/join.php
html/user/sample_index.php
html/user/signup.php

- make download page translatable
- change sample_index.php to show different things to:
new users: show project intro, Join link
returning users: show recent credit, link to home page
- add signup page: streamlined registration, goes to download

web: add support for autoattach

---

mac_build/boinc.xcodeproj/project.pbxproj

Remove hostinfo_linux.cpp file from Xcode project

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

Fixes bug where password reset would not go to form where user can reset password.
https://dev.gridrepublic.org/browse/DBOINCP-448

Drupal: Bug fix in user login and terms of use workflow.

---

drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-425

Drupal: Refactor password hash check, uses upstream function

---

drupal/sites/default/boinc/modules/boincuser/boincuser.admin.inc
drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc

Part of: https://dev.gridrepublic.org/browse/DBOINCP-428

Drupal: Changed wording of terms-of-use page.

---

html/inc/delete_account.inc
html/inc/team.inc

* missing include - required for delete_user()
* wrong property access syntax

Web: fixed bugs in delete account feature introduced in bcd853bb4f4

---

mac_build/buildWxMac.sh

BOINC 7.10.2 crashes under OS 10.6 because wxWidgets 3.1.0 calls the` [NSWindow backingScaleFactor]` and `[NSScreen backingScaleFactor]` APIs which are not available before OS 10.7. This change patches wxWidgets to call those APIs only when available, allowing BOINC Manager to run under OS 10.6.
After this is merged, and upon approval from the release manager, I intend to cherry-pick it into the _client_release/7/7.10_ branch, bump the version number in this branch to 7.10.3, create a new tag _client_release/7/7.10.3_, build a new Mac installer from the tagged code, and make it the recommended version for Macintosh.

Mac: Patch wxWidgets 3.1.0 to fix BOINC Manager crash on OS 10.6.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-428

Drupal: Added bts() functions to terms of use forms.

---

clientgui/BOINCGUIApp.cpp
clientgui/BOINCGUIApp.h
clientgui/DlgOptions.cpp
clientgui/DlgOptions.h

This reverts commit cacecc8b0ba1d0e8f8af355a42aa6f8ba58d1914, reversing
changes made to 716ebdd9e1072da4744075fbf4b0c89aaa8d0ccf.

Revert "Merge branch 'master' of git://github.com/AenBleidd/boinc"

---

clientgui/BOINCBaseFrame.cpp

This fixes #2440 in the way discussed in  #2441

[Manager] Always reconnect remote client without user prompt

---

drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-436

Drupal: Fix bug in recovery email workflow.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc

Part of https://dev.gridrepublic.org/browse/DBOINCP-436

Drupal: Add a 'menu redirect' to sent users to recover email menu path.

---

html/inc/common_defs.inc
html/inc/delete_account.inc
html/ops/delete_user.php
html/user/delete_account_confirm.php

- functions generally return zero on success
- improve function names
- comment formatting
See https://boinc.berkeley.edu/trac/wiki/CodingStyle
todo: fix translatable strings

web: code cleanup in delete user area

---

clientscr/screensaver_x11.cpp

Thanks Gord Sipko for the report!

Update screensaver_x11.cpp to new /var/lib/boinc working directory

---

sched/db_purge.cpp

That functionality was first hidden in #2005 , but is better issues as a separate PR

db_purge: log when purging was skipped due to --dont_delete

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-458

Drupal: Fixed bug where profile nodes are created without a title.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-460

Drupal: Fixed bug where changing email would reset username.

---

drupal/sites/all/features/boinc_standard/boinc_standard.pages_default.inc
drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.admin.inc
drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.module
drupal/sites/default/boinc/modules/boincuser/boincuser_delete/includes/boincuser_delete.helpers.inc
drupal/sites/default/boinc/themes/boinc/templates/user-profile.tpl.php

User is presented option of soft (obfuscate) or hard (wipe) delete. 
Admin may also chose these two options, and force the user to use one or the other; or have the user chose.
https://dev.gridrepublic.org/browse/DBOINCP-452

Drupal: Improved delete user operations.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

https://dev.gridrepublic.org/browse/DBOINCP-465

Drupal: Fixed bug in how new users' passwords are saved.

---

drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.module

https://dev.gridrepublic.org/browse/DBOINCP-464

Drupal: Fixed typo and clarified some text. No functional changes.

---

mac_installer/PostInstall.cpp

This is a code change from Charlie Fenton which will clear the launch services database during a Mac install. The issue is that on a Mac machine which has built both generic boinc installers and branded boinc installers they may display the wrong app name and app icon in notifications.

clears the Launch services database during a mac client install

---

client/async_file.cpp

Pull request created using original patches provided in #1197

[client] Verify chunk improvements

---

html/inc/submit.inc

Added the ping function to test the job submission RPC.

Added ping function

---

.travis.yml

[Android] Add Android Manager CI configuration

---

tools/stage_file

Wrong path for touch in https://github.com/BOINC/boinc/commit/b38bf1d9838edad00fc376b2730acba8f4617a30

Fixed touch md5 file path

---

html/inc/bootstrap.inc
html/inc/user.inc
html/inc/util.inc

define CERT_FILENAME in your project.inc to whatever you want;
default is "cert1.php"

Web: let projects customize their certificate

---

appveyor.yml
deploy/prepare_deployment.bat

Add cache dependency to invalidate it properly

[AppVeyor] Switch default build to Release x64

---

html/inc/submit_util.inc

Fix retire,abort and expire batch

---

html/user/submit_rpc_handler.php

remote job submission: increase handler memory limit to 4G

---

drupal/sites/default/boinc/modules/boincuser/boincuser_delete/boincuser_delete.module
drupal/sites/default/boinc/themes/boinc/css/forms.css

Also changed are account delete final confirmation pages.
https://dev.gridrepublic.org/browse/DBOINCP-464

Drupal: Changed layout and style of account delete pages

---

db/boinc_db_types.h
lib/Makefile.am
lib/wslinfo.cpp
lib/wslinfo.h
sched/sched_types.cpp
version.h

Currently these generate a server log error message.
TODO: add plan class support for WSL

scheduler: parse <wsl> and <wsl_available>

---

html/user/server_status.php

Removed surplus bracket

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogClientFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogGuiFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/NoticesFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ClientLogListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsSelectionDialogListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/CredentialInputActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/IndividualCredentialInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListAdapter.java

Micro-optimization. The redundant castings removed.
N/A

[Android] Remove redundant castings

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java

Warning messages shouldn't be suppressed but resolved.
The new function uses API level 13, we target the minimum 19.
N/A

[Android] Warnings shouldn't be suppressed

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListItemWrapperValue.java
android/BOINC/app/src/main/res/values/strings.xml

Fixes #2755
Add WU buffer option to the Preference menu.
[Android] Add "Work unit buffer" option

[Android] Add work unit buffer to preference

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/util/SystemUiHider.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/util/SystemUiHiderHoneycomb.java

We target a minimum API 19 which is always bigger. The conditions are unnecessary.
N/A

[Android] Remove unnecessary SDK_INT checks

---

drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc

See #2063.
NB. Not tested at all.

drupal: change a few "ATI" string to "AMD"

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/TimePreferences.java

Fix the errors found by Android Studio code inspection.
Code style issues: Unnecessary semicolons.
N/A

[Android] Remove unnecessary semicolons

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectInfo.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.java

Reports String concatenation used as the argument to StringBuffer.append(), StringBuilder.append() or Appendable.append(). Such calls may profitably be turned into chained append calls on the existing StringBuffer/Builder/Appendable, saving the cost of an extra StringBuffer/Builder allocation.
Reports String concatenation in loops. As every String concatenation copies the whole String, usually it is preferable to replace it with explicit calls to StringBuilder.append() or StringBuffer.append().
N/A

[Android] Fix string performance warnings

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogClientFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogGuiFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.java

[Android] Remove Unused imports

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountIn.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java

Fixes the 'Declaration has problems in Javadoc references' errors and warnings.
Should the 'Dangling Javadoc comment' warnings be fixed?
Android Studio suggests to remove the `/*******************************************************************************` and use only the `/**`
N/A

[Android] Fix javadoc errors

---

html/inc/consent.inc
html/inc/token.inc
html/user/user_agreetermsofuse_action.php

web: Added token authentication to user_agreetotermsofuse_action, in order to prevent unauthorized use.
Fixes a security vulnerability in BOINC Web code.
N/A

 Added token authentication to agreetotermsofuse form.

---

drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-filter.inc
drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-help.inc
drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-test.css
drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-test.txt
drupal/sites/default/boinc/modules/contrib/bbcode/bbcode.info

Updates code from Drupal bbmode.module, backporting fixes and features into this version.
https://dev.gridrepublic.org/browse/DBOINCP-478

Drupal feature bbcodephp7 part2

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java

The `continue` statement has been used wrongly a couple of times. I changed to `break` or deleted them, but it changes the logic of the loops, so please check thoroughly.
Some `for + break` loop could have changed to `while`.
[Android] Minor improvement.

[Android] Fix misused 'continue' statements.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/App.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectConfigReplyParser.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/VersionInfo.java

_Fix Redundant 'if' statement inspections_
Reports if statements which can be simplified to single assignment, return or assert statements.
_Fix Simplifiable conditional expression inspection_
Reports conditional expressions of the following form
condition ? true : foo
condition ? false : foo
condition ? foo : !foo
condition ? !foo : foo
These expressions may respectively be safely simplified to
condition || foo
!condition && foo
condition == foo
condition != foo
N/A

[Android] Fix control flow issues

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogClientFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogGuiFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/GalleryAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/CcState.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.java

_Unused assignment_
This inspection points out the cases where a variable value is never used after its assignment, i.e.:  - the variable never gets read after assignment OR  - the value is always overwritten with another assignment before the next variable read OR  - the variable initializer is redundant (for one of the above two reasons)
N/A

[Android] Fix 'Unused assignment' inspection.

---

.gitignore

Include the changes discussed here #2956 
N/A

Update to don't ignore the Android Studio code style related files.

---

drupal/sites/default/boinc/modules/boincimport/boincimport.module

Fixes problem with errant chracters
N/A

Drupal: Boincimport - fix errant character problem.

---

html/user/cert1.php
html/user/cert_all.php
html/user/cert_team.php

... which apparently no longer has Optima or ZapfChancery

web: change certificate title font so that it works with Firefox

---

client/sim.cpp
client/time_stats.cpp

client simulator: make the timeline output easier to read
N/A

client simulator: make the timeline output easier to read

---

drupal/sites/default/boinc/modules/boincteam/includes/boincteam.forms.inc

Removes an extra slash from the URL link
N/A
https://dev.gridrepublic.org/browse/DBOINCP-479

Drupal: Removed extra slash

---

html/inc/user_util.inc
html/user/download.php

Web: fix typos in user visible strings

---

android/BOINC/.idea/misc.xml
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
android/BOINC/app/src/main/res/layout/attach_project_acctmgr_dialog.xml

Fixes #1582
This is the first part of the #2867, to lets that issue moving. I don't think that the 2nd part is feasible with the current design.
Added the option to use a custom account manager.
[Android] Allow entering custom Account Manager URL.

[Android] Add option to manually enter Account Manager URL.

---

html/ops/purge_trickles.php

This slipped through my review of #2630
N/A

Ops: fix php syntax error

---

html/inc/submit_util.inc
html/user/submit_rpc_handler.php
tools/submit_api_test.py

Remote job submission requests and errors are now logged to log_host/submit_log.txt.

Remote job submission: add logging

---

clientgui/AccountManagerInfoPage.cpp

When attaching to AM make proper decoding of UTF-8 encoded strings.
Fixes #3068

[Manager] Make proper UTF-8 decoding of AM info

---

html/inc/keywords.inc

fix errors in keywords.inc

---

drupal/sites/all/features/boinc_standard/boinc_standard.features.inc

Misc text changes to subject line. Not functional changes.
N/A
Part of https://dev.gridrepublic.org/browse/DBOINCP-493

Drupal: Changed text of subject line for admin notifications

---

gl.py

Revert "remove gl.py"

---

sched/validator.cpp

validator: fix bugs in #3024

---

clientgui/AdvancedFrame.cpp
clientgui/sg_BoincSimpleFrame.cpp

On the contributors call today, the merge of pull request #3094 was discussed by @lfield @Uplinger @RichardHaselgrove and it was agreed that merge should be reverted.
The core issue that led to the implementation of #3094 is described in issue #3105 and efforts should be made to focus on fixing that issue.

Revert Pull Request #3094

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Message.java

[Android] Remove XML CDATA tag from Event Log messages

---

.gitignore
android/Vagrantfile

Make force upgrade for non-interactive session.
Add android/.vagrant folder to .gitignore
Fixes #3113

[Android] Fix Vagrant build

---

README.md

Add Codecov status badge to README.md

---

samples/vboxwrapper/vbox_common.cpp

Typo fix in vbox_common.cpp

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/util/SystemUiHider.java

[Android] Fix Javadoc issues.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java

[Android] Delete unused imports.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/IndividualCredentialInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Boinc.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Md5.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/util/SystemUiHider.java

- Remove unnecessary interface modifiers.
- Use the standars CharSet object. The constant charset String literal can be replaced with a predefined Charset object. This may work a little bit faster, because charset lookup becomes unnecessary.
N/A

[Android] Fix code style issues

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java

[Android] Fix spelling typo

---

tests/unit-tests/lib/test_str_util.cpp

more unit tests for str_util.cpp
N/A

Tests: more unit tests for str_util.cpp

---

api/boinc_api_fortran.cpp

Added three more API calls to the Fortran interface:
* `boinc_begin_critical_section`
* `boinc_end_critical_section`
* `boinc_get_fraction_done`
N/A (library API)

Added a few more API functions to the Fortran API

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectConfigReplyParser.java

Fixing warning found by static analyzer:
`V6003 The use of 'if (A) {...} else if (A) {...}' pattern was detected. There is a probability of logical error presence.`
This piece of code duplicates the one already presented above where it logically more correct.

[Android] Remove unreachable code

---

tests/unit-tests/lib/test_url.cpp

Fixes #2698 
Test increases for code coverage of unit tests for url.cpp.

Tests:  Get unit tests for url.cpp to 100% coverage.

---

html/ops/check_account_ownership_keys.php
html/ops/generate_account_ownership_keys.php

Pull request #2965 needed some minor adjustments (mostly for text output).  It was easier to make them in a new pull request after merging it rather than go back and forth for minor tweaks.

Minor text output cleanup for the new account ownership pages

---

api/mac_icon.cpp
html/user/account_ownership.php

fix small typo in translatable text
N/A

fix small typo in translatable text

---

samples/vboxwrapper/vbox_common.cpp
samples/vboxwrapper/vbox_common.h
samples/vboxwrapper/vboxwrapper.cpp

vboxwrapper: if control op fails, exit for 5 min instead of 1 day

---

deploy/cleanup_bintray.sh

Previously forgot to remove this check since the script was not intended to be run on CI.
N/A

Deploy: enable bintray cleanup script

---

client/gui_rpc_server_ops.cpp
lib/md5_file.cpp
lib/md5_file.h
samples/electron_gui/index.html
samples/electron_gui/styles.css
samples/electron_gui/window.js

to facilitate Javascript-based GUIs.
Authentication (for operations that require it) is done using
special HTTP header fields.
At some point I'll check in a JS module for this.
Fixes #3190

Client: support GUI RPCs via HTTP POST requests,

---

html/ops/generate_account_ownership_keys.php
tools/make_project

Cleanup generate_account_ownership_keys

---

client/hostinfo_unix.cpp

FreeBSD: Check if the client supports AVX.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java

When users clicks on notification in notification area it should be removed.
Fixes #2090

[Android] Remove notification on user click

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java

[Android] Change notification priority from PRIORITY_MIN to PRIORITY_LOW

---

CONTRIBUTING.md
README.md

Update the README and CONTRIBUTING documents to add information about how to connect and consolidate information about to make a code contribution.

Revise README and CONTRIBUTING documents

---

db/db_base.cpp

Change my_bool to bool - see https://bugs.mysql.com/bug.php?id=85131

---

lib/gui_rpc_client_print.cpp

... or at least a good approximation of it.

boinccmd: show GPU info in --get_host_info

---

CONTRIBUTING.md

Fix tiny formatting bug in Contributing.md

documentation: fix formatting bug in CONTRIBUTING.md

---

lib/procinfo_unix.cpp

Add missing std::pair template arguments.

---

lib/cc_config.cpp

Fix bug that caused bad values to be written to cc_config.xml

---

README.md

Change Discord temporary invite link to permanent

---

html/inc/db_ops.inc

Fixes #2529
Adds missing fields identified by Bernd to the ops database browser

Add missing fields to ops DB browser

---

html/inc/text_transform.inc

Web: fix bug in output of [list] BBcode

---

configure.ac
lib/Makefile.am

FreeBSD: Add a check in configure.ac and in lib/Makefile.am link to

---

tools/Makefile.am

Remove deleted files tools/db_query and tool/watch_tcp from tools/Makefile.am

Fix broken master after 4af1ef748db93bec1fbe10cd4ea7a862cb222f86

---

client/client_types.cpp

... which causes parsing of scheduler replies to completely fail.
My bad.

client: fix heinous bug in #3266

---

client/file_xfer.cpp

client: if physical name of download file contains /, create subdirs

---

sched/plan_class_spec.cpp

scheduler: fix a compile warning.  No functional change

---

html/user/user_search.php

Make user search title translatable

---

client/cs_files.cpp

client: fix bug in missing-file logic that cause task abort at startup

---

client/cs_apps.cpp
client/gpu_nvidia.cpp

client simulator: fix build

---

html/user/forum_forum.php

... since it appears in browser tab title
Fixes #3358

web: don't put HTML in title for team forums

---

clientgui/BOINCGUIApp.cpp
clientgui/BOINCGUIApp.h
clientgui/MainDocument.cpp

[Manager] Fix connection to second local client instance

---

client/gui_rpc_server_ops.cpp
samples/electron_gui/README.txt
samples/electron_gui/window.js

RPC requests need to be enclosed in <boinc_gui_rpc_request>.
I'm not sure how it ever worked.
Also: improve GUI RPC error reporting in the client.

Make the electron-based GUI work again.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/themes/boinc/css/forms.css

Part of https://dev.gridrepublic.org/browse/DBOINCP-509
Moves the captcha box to the left for certain forms.

Drupal: Add ID to captcha element to theme it.

---

deploy/cleanup_bintray.sh

fix bug in Travis bintray cleanup script
N/A

Travis Bintray: fix bug in cleanup script

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module

Fixes https://dev.gridrepublic.org/browse/DBOINCP-509
Moves the captcha to above the submit buttons.

Drupal: Changed weight of Captcha to move it above submit buttons.

---

drupal/sites/default/boinc/modules/boincuser/boincuser.module
drupal/sites/default/boinc/themes/boinc/css/forms.css

Moved the Captcha box to align with email address field.
Part of https://dev.gridrepublic.org/browse/DBOINCP-509

Drupal: Created new div id for Captcha for password reset.

---

clientgui/MainDocument.cpp
clientgui/mac/SecurityUtility.cpp
clientscr/mac_saver_module.cpp
clientscr/screensaver.cpp
mac_build/boinc.xcodeproj/project.pbxproj
mac_installer/AddRemoveUser.cpp
mac_installer/Installer.cpp
mac_installer/PostInstall.cpp
mac_installer/ReadMe.rtf
mac_installer/WaitPermissions.cpp
mac_installer/finish_install.cpp
mac_installer/release_brand.sh
mac_installer/uninstall.cpp

Fix Mac installer & uninstaller to properly handle branded BOINC screensavers on OS 10.15 Catalina.

Fix Mac installer & uninstaller for branded BOINC screensavers on OS 10.15

---

client/acct_mgr.cpp
client/acct_mgr.h
client/client_state.cpp
client/client_state.h
client/cs_cmdline.cpp
client/gui_rpc_server.cpp
client/gui_rpc_server_ops.cpp
client/hostinfo_network.cpp
client/main.cpp
lib/boinc_win.h
lib/hostinfo.h
lib/md5_file.cpp
lib/md5_file.h
samples/electron_gui/README.txt
samples/electron_gui/window.js

electron sample GUI: add support for starting the client,
and for attaching a project
Fixes #

client: fix bug that broke HTTP GUI RPC for authenticated ops

---

deploy/deploy_to_bintray.bat

[AppVeyor] Fix upload to Bintray

---

html/user/create_account.php

The create-account RPC returned "Account creation disabled"
even if account creation on the web site is allowed.
Fix this.
Fixes #3420

Fix error messages in account creation RPC

---

android/buildAndroidBOINC-CI.sh

[Android] Upgrade OpenSSL version to 1.0.2s

---

win_build/installerv2/redist/all_projects_list.xml

update project list

---

android/BOINC/app/src/main/res/values/strings.xml
clientgui/DlgAbout.cpp
clientsetup/win/boinccas.rc
doc/manpages/boinc.xml
doc/manpages/boinccmd.xml
doc/manpages/boincmgr.xml
win_build/installerv2/BOINC.ism
win_build/installerv2/BOINC_vbox.ism
win_build/installerv2/BOINCx64.ism
win_build/installerv2/BOINCx64_vbox.ism
win_build/installerv2/CharityEngine.ism
win_build/installerv2/Progress.ism
win_build/installerv2/WCG.ism

Update copyright year

---

client/hostinfo_unix.cpp
client/hostinfo_win.cpp
lib/hostinfo.cpp
lib/hostinfo.h

[client] [Win]: don't truncate p_features at 255 characters

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/res/values/configuration.xml
android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh

[Android] Remove boinccmd binary from apk

---

client/acct_mgr.cpp

Fix simulator build

---

lib/Makefile.am

Mac: Add missing .cpp + .h file to lib/Makefile.am

---

configure.ac

Error message sentence structure
N/A

Grammar in configure.ac

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/BoincNotExclusiveDialog.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ConfirmationDialog.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/NoticesFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/CredentialInputActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/IndividualCredentialInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListAdapter.java
android/buildAndroidBOINC-CI.sh
android/build_all.sh
configure.ac

Fixes #
Replace functional interface declarations with lambda expressions where possible. This allows the code to be much easier to read.
N/A

Replace functional interface declarations with lambda expressions.

---

client/hostinfo_unix.cpp

client (Linux): Fix X-based idle detection

---

.travis.yml
android/BOINC/app/build.gradle

[Android] Upgrade build tools from 28 to 29

---

.codecov.yml
.travis.yml
android/BOINC/app/build.gradle
android/BOINC/build.gradle

Fixes #
Add support for generating code coverage reports for use with codecov.io in the Android app.
N/A

Add Codecov support for the Android app.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/Logging.java

Convert the boolean wrapper variables in the Logging class to boolean primitives. This change will eliminate the overhead associated with boxing and unboxing the boolean wrappers.
N/A

Convert the boolean wrapper variables in Logging to primitives.

---

.travis.yml
tests/executeUnitTests.sh

[Codecov] Fix uploading CodeCov reports

---

client/client_types.cpp
client/file_xfer.cpp
client/result.cpp
mac_installer/wcgrid-ReadMe.rtf

This pull request would add the following pull requests that address a security hole to the client release 7.14 branch:
- #3266
- #3292
- #3275
And #3574 which fixes a minor issue with WCG's readme file for mac.

Updates to client release 7.14

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ClientLogListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/gradle.properties

Use the built-in methods in Eclipse Collections' MutableList and ImmutableList to simplify some operations that would otherwise require complex for loops to be implemented.
Using Java 8's Streams API and functional interfaces was considered, but their use requires the minimum API level to be 24 (Nougat) or higher ([this will change with Android Studio 4.0](https://developer.android.com/studio/preview/features#j8-desugar)), and Eclipse Collections provides similar simplified operations without using the Streams API.
N/A

[Android] Simplify some operations using Eclipse Collections.

---

android/BOINC/app/build.gradle
android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsTest.java

Add unit tests for the readLineLimit() method in BOINCUtils.
N/A

[Android] Add unit tests for BOINCUtils.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Result.kt

Fix the implementation of the Parcelable interface in the Result class.
N/A

[Android] Fix Result's Parcelable implementation.

---

appveyor.yml
win_build/load_dependencies.bat

[AppVeyor] Fix Windows CI build

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java

* Use the `Files.delete()` static method to delete the target file on Android Oreo and later, as this method is recommended by SonarLint due to providing more descriptive error messages than the `File.delete()` method, which merely returns `false` in the event of failure.
* Fix some other issues reported by SonarLint.
N/A

Use Files.delete() to delete file on Android Oreo and later.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.java

Replace the implementation of onAttach(Activity), which is a deprecated method, with the supported onAttach(Context).
N/A

[Android] Replace onAttach(Activity) with onAttach(Context) implementation.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java

* Use the getActiveNetwork() method instead of getActiveNetworkInfo() to retrieve the current network used on Android Marshmallow and later in AcctMgrFragment, as getActiveNetworkInfo() is deprecated.
* Fix some issues reported by SonarLint.
N/A

Use getActiveNetwork() to retrieve current active network in AcctMgrFragment on Android Marshmallow and later.

---

android/BOINC/build.gradle

Update the Android Gradle plugin to 3.6.3 and Kotlin to 1.3.72.
N/A

Update Android plugin and Kotlin versions.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/NoticesFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsSelectionDialogListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/CredentialInputActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/IndividualCredentialInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java

Add missing annotations that help with documentation or are used in superclass methods, such as Override and NonNull.
N/A

[Android] Add missing annotations.

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt

Simplify adding values to the SharedPreferences object by using the edit() extension function, which can optionally be used to perform transactions asynchronously.
N/A

Use Android KTX in AppPreferences.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountClasses.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountManagerClasses.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/GlobalPreferences.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Notice.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Result.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt

Use ParcelCompat's static `readBoolean()` and `writeBoolean()` methods to read and write boolean values from `Parcel`s, as these methods are not restricted to a specific API level.
N/A

[Android] Use ParcelCompat's readBoolean() and writeBoolean() methods.

---

drupal/sites/default/boinc/modules/boinccore/boinccore.module

Fixes: https://dev.gridrepublic.org/browse/DBOINCP-524
Fixed bug in pagination where hidden comments would result in incorrect page number for the drupal goto.
N/A

Drupal: Fixed bug in comment goto code.

---

drupal/sites/default/boinc/modules/contrib/bbcode/bbcode-help.inc

Help text needs HTML format.
N/A

Drupal: Fixes missing HTML format.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AcctMgrInfoParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AppVersionsParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/CcStatusParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/GlobalPreferencesParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/HostInfoParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/NoticesParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectConfigReplyParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectsParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/TransfersParser.kt

Removes unused and unnecessary imports (i.e. imports from the same package) in the RPC classes.
N/A

[Android] Remove unused and unnecessary imports.

---

samples/sleeper/Makefile

I just had a look around - please take this PR just as an anchor to discuss what should happen in general with "make install" when components are configured that are more assigned to the server side of boinc - like these scientific/sample apps.

added install target, $(CXX)

---

android/BOINC/app/build.gradle

Update Grgit and Git-Version plugins to their latest versions (4.0.2 and 0.12.3, respectively).
N/A

Update Gradle Git plugins to their latest versions.

---

samples/wrapper/Makefile

added install target, minimal beautification

samples/wrapper: don't fail "make install"

---

.travis.yml
android/BOINC/app/build.gradle

> If you put it in release, this will make the APK / App Bundle debuggable, and Google Play Console will consider it's not signed. Removing this resolved the issue.
https://stackoverflow.com/a/56823288/550384
For compile signed bundle
#3566

testCoverageEnabled true only in debug.

---

android/BOINC/app/src/main/res/values-sk/strings.xml

Fix build errors caused by Slovak strings that are not present in the default strings.xml file.
N/A

[Android] Fix translation build errors.

---

vda/des.h
vda/vda_lib.cpp
vda/vda_lib.h
vda/vda_lib2.cpp

Added virtual destructors.
Fixed some sprintf warnings but not all; that seems like an infinite rat-hole.
Fixes #3675

Eliminate some compile warnings in vda/.

---

configure.ac

I had a problem running that code on "ash" on OpenWRT. No idea what could possibly be wrong about it, but since there is no need for that piece of code, it should just go IMHO.

Remove remnants to subversion

---

lib/coproc.cpp
lib/daemonmgt_win.cpp
lib/mfile.cpp
lib/parse.cpp
lib/procinfo_win.cpp
lib/stackwalker_win.cpp
lib/url.cpp

lib fixes by PVS Studio static code analyzer
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/
None
N/A

lib: PVS Studio static code analyzer fixes

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt

Use `ParcelCompat`'s `readBoolean` and `writeBoolean` methods in `ProjectConfig`.
N/A

[Android] Use ParcelCompat in ProjectConfig.

---

client/acct_mgr.cpp
client/acct_mgr.h
client/acct_setup.cpp
client/app_control.cpp
client/app_start.cpp
client/async_file.cpp
client/client_state.cpp
client/client_types.cpp
client/client_types.h
client/cs_notice.cpp
client/cs_scheduler.cpp
client/cs_trickle.h
client/current_version.cpp
client/file_names.cpp
client/gpu_amd.cpp
client/gpu_nvidia.cpp
client/gpu_opencl.cpp
client/hostinfo_win.cpp
client/hostinfo_wsl.cpp
client/http_curl.cpp
client/project.cpp
client/result.cpp
client/scheduler_op.cpp
client/sysmon_win.cpp
lib/crypt.h
lib/msg_log.h

client fixes by PVS Studio static code analyzer.
None
N/A

client: PVS Studio static code analyzer fixes

---

db/content.sql
db/schema.sql

This change prpoposes fixes to a couple of typos in comments and removes an outdated todo comment.
N/A - this just fixes a couple of comments.
N/A

Fix comment typos and remove an outdated todo.

---

html/inc/forum.inc
html/inc/text_transform.inc
html/user/create_profile.php
html/user/forum_report_post.php
html/user/forum_thread.php

There were lots of PHP warnings in the apache error log.
Fix most of these.

Web: fix some PHP warnings

---

android/BOINC/app/build.gradle
android/BOINC/app/proguard-rules-debug.txt

Add proguard-rules-debug.txt
In debug turn on option for default.
In Release turn off all the option.
Remove Irrelevant option for android boinc app.

[Android] Add proguard-rules-debug.txt

---

.travis.yml
android/BOINC/.idea/jarRepositories.xml
android/BOINC/app/build.gradle
android/BOINC/app/src/main/AndroidManifest.xml
android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/NoticesFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ClientLogListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/build.gradle

Add support for desugaring of Java 8 language APIs, and alter code to use Java 8 Date/Time API.
N/A
**Note**
Some warnings are displayed during the desugaring process: https://issuetracker.google.com/issues/155423440

[Android] Add Java 8 API support.

---

android/buildAndroidBOINC-CI.sh
android/build_all.sh

Update prefix to be 3rdParty\buildCache

Update prefix to be 3rdParty\buildCache

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/AndroidManifest.xml
android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCApplication.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/di/AppComponent.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/mutex/BoincMutex.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/mutex/MutexModule.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/mutex/BoincMutexTest.java

Make use of [Dagger's](https://dagger.dev/) dependency injection functionality to initialize some variables that would otherwise be initialized using their object constructors. Using dependency injection provides the following advantages:
- Code reusability
- Ease of testing
- Ease of refactoring
Useful information about Dagger can be found [here](https://developer.android.com/training/dependency-injection/dagger-android) and [here](https://codelabs.developers.google.com/codelabs/android-dagger).
N/A

[Android] Modify app to make use of dependency injection via Dagger.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java

This reduces the complexity of reading data from `InputStream` objects in `Monitor` by using the methods in Apache Commons IO's `IOUtils` class.
N/A

[Android] Simplify InputStream reading using IOUtils.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java

Fix an issue in `installFile()` that prevents the app from progressing past the splash screen.
N/A

[Android] Fix issue in installFile() method.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountManagerClasses.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AcctMgrInfoParser.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrInfoParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrInfoTest.kt

[Android] Remove unused code.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java

Fix  account  manager authentication.

[Android] Fix account manager  authentication

---

client/hostinfo_unix.cpp

Use native FreeBSD CPUID tools to detect vendor, family, model, and stepping info. Rectify duplicate reporting of CPU model, and use host.p_features for CPU flags instead of host.p_model. Tested on FreeBSD 12.1.
Original output:
> Processor: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz [Family 6 Model 158 Stepping 13]Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz [Family 6 Model 158 Stepping 13] [] [sse sse2 pni mmx]
Processor features:
Output after applying PR:
>Processor: 4 GenuineIntel Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz [Family 6 Model 158 Stepping 13]
Processor features: sse sse2 pni mmx avx
1. dmidecode: GNU tool creates unnecessary external dependency, and has trouble running in some VMs.
2. cpuinfo: FreeBSD has a kernel linux …

Improve FreeBSD CPU detection & reporting format

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java

Use the `removeIf()` method introduced in the `Collection` interface in Java 8 to remove elements conditionally instead of using the `remove()` method in `Iterator`.
N/A

[Android] Use Collection.removeIf() to remove elements of a collection conditionally.

---

android/BOINC/app/build.gradle

Add exist asserts for generated files from android scripts

[Android]Add exist asserts for generated files from android scripts 

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java

Projects name didn't update in the drawer when added in AM (BAM).
Update projects name in the drawer.

[Android] Update projects name in the drawer

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt

Use the `FragmentTransaction.replace` extension function to make replacement operations in `BOINCActivity` more Kotlin-idiomatic.
N/A

[Android] Use Fragment KTX in BOINCActivity.

---

android/BOINC/app/src/main/res/drawable/navlist_dark_selector.xml
android/BOINC/app/src/main/res/drawable/navlist_light_selector.xml
android/BOINC/app/src/main/res/layout/dialog_list.xml
android/BOINC/app/src/main/res/values-night/theme.xml
android/BOINC/app/src/main/res/values/theme.xml

Control list of account manager and project now look same as light / dark mode.

[Android] Dark mode support to control list

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt

Use the `toBitmap()` extension function for `Drawable` in `BOINCUtils`.
N/A

[Android] Use toBitmap() extension function.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.kt

Fix lint errors by replacing calls to `activity`, `view` and `arguments` with their `require` versions.
N/A

[Android] Fix lint errors.

---

android/BOINC/build.gradle

Update the Android Gradle plugin to 4.0 from 4.0 RC1.
N/A

[Android] Update Android Gradle plugin to 4.0.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.kt

[Android] Fix compilation error in AcctMgrFragment.

---

android/build_boinc_x86.sh

[Android] Fix typo in script boinc x86.

---

client/app_control.cpp
client/client_state.cpp
client/cs_scheduler.cpp
client/gui_rpc_server_ops.cpp
client/log_flags.cpp
client/project.cpp
lib/url.cpp
lib/url.h

 Client: let a project master URL change from http: to https: without involving the user.

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/StringExtensions.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/RpcClientTest.java

Simplify calculating the MD5 values of `String`s and `InputStream`s using Apache Commons Codec's `DigestUtils` class.
N/A

[Android] Simplify MD5 calculations using Apache Commons Codec.

---

android/BOINC/app/build.gradle

[Android] Remove duplicate line.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
android/BOINC/app/src/main/res/values-en/strings.xml
android/BOINC/app/src/main/res/values/strings.xml
android/BOINC/app/src/main/res/xml/root_preferences.xml

* Hide advanced settings instead of disabling them when the "Show advanced" option is unchecked.
* Make use of the `useSimpleSummaryProvider` attribute where possible.
Hide advanced settings instead of disabling them when the "Show advanced" option is unchecked.

[Android] Fix remaining settings issues.

---

android/buildAndroidBOINC-CI.sh
android/build_all.sh
android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh
android/build_curl_arm.sh
android/build_curl_arm64.sh
android/build_curl_x86.sh
android/build_curl_x86_64.sh
android/build_openssl_arm.sh
android/build_openssl_arm64.sh
android/build_openssl_x86.sh
android/build_openssl_x86_64.sh

Add flag verbose for makefiles.

[Android][Scripts] Add flag verbose for makefiles.

---

android/build_androidtc_arm.sh
android/build_boinc_arm.sh
android/build_curl_arm.sh
android/build_openssl_arm.sh
lib/filesys.cpp

Add android 4.1 api 16 support in cpp compilation.
I will check on AVD 4.1 (api 16) and I will past here a screenshots.

[Android][Scripts] Add android 4.1 api 16 support in cpp compilation.

---

android/build_androidtc_x86.sh
android/build_boinc_x86.sh
android/build_curl_x86.sh
android/build_openssl_x86.sh

[Android] Support x86 API 16

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
android/BOINC/app/src/main/res/values-en/strings.xml
android/BOINC/app/src/main/res/values/strings.xml
android/BOINC/app/src/main/res/xml/root_preferences.xml

Fix dailyTransferLimitMB default and title.
Add dailyTransferPeriodDays setting in adv settings.
screenshots for settings:

[Android] Fix dailyTransferLimitMB default and title.

---

win_build/boinc.props

[VS2019] Fix VcpkgCacheDir location path

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Use Dagger to instantiate a singleton variable of `ClientNotification`.
N/A

[Android] Inject ClientNotification into Monitor using Dagger.

---

appveyor.yml
tests/unit-tests/lib/test_str_util.cpp
win_build/boinc_vs2019.sln
win_build/unittests_vs2019.vcxproj
win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj

[VS2019][Windows] Enable unit tests

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java

Replace deprecated method calls on `getResources()` with calls to `ContextCompat`.
N/A

[Android] Use ContextCompat methods.

---

appveyor.yml

[VS2019] Fix CI build

---

android/BOINC/.idea/misc.xml
android/BOINC/app/build.gradle

Update dependencies to their latest versions.
N/A

[Android] Update project dependencies.

---

android/BOINC/app/src/main/res/layout/attach_project_hint_platforms_layout.xml
android/BOINC/app/src/main/res/layout/dialog_about.xml

Replace usages of `LinearLayout` containing a `TextView` and an `ImageView` with compound drawables.
N/A

[Android] Use compound drawables.

---

android/BOINC/.idea/compiler.xml
android/BOINC/.idea/misc.xml
android/BOINC/build.gradle
android/BOINC/gradle/wrapper/gradle-wrapper.properties

Upgrade to Android Studio 4.1.0-beta03

[Android] Upgrade to Android Studio 4.1.0-beta03

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Fix an issue that caused tasks to not execute.
Tasks should now be executed normally.

[Android] Fix task execution issue.

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorExtensions.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt

Use the [Okio](https://github.com/square/okio) library to handle hashing and file copy operations.
N/A

[Android] Use Okio.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java

Add null checks in `NavDrawerListAdapter` to avoid `NullPointerExceptions`.
N/A

[Android] Add null checks in NavDrawerListAdapter.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorExtensions.kt

Fix an issue where the BOINC client is not copied to the internal storage.
N/A

[Android] Fix client copy issue.

---

clientsetup/win/CACreateBOINCAccounts.cpp

[Windows] Enlarge default generated password to be 32 symbols long

---

android/BOINC/app/build.gradle

Update the Core KTX and [desugar_jdk_libs](https://github.com/google/desugar_jdk_libs) libraries to their latest versions.
N/A

[Android] Update Core KTX and desugar_jdk_libs versions.

---

client/client_state.cpp
clientgui/MainDocument.cpp
mac_build/boinc.xcodeproj/project.pbxproj

Fixes my changes in #3970 when running on MacOS 10.16 or later
Correctly implements _Stop graphics_ on MS Windows

Fix bugs in my PR #3970 mgr_add_stop_graphics_button

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Fix it will no throw an exception when the state == null.

Fix it will no throw an exception when the state == null.

---

appveyor.yml
win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj

[VS2019] Fix VS2019 CI build cache

---

3rdParty/vcpkg_ports/ports/rappture/CMakeLists.txt

Fix build after libexpat update on vcpkg

---

api/graphics2_unix.cpp
api/x_opengl.h
client/app.h
client/app_start.cpp
client/client_state.cpp
client/client_state.h
client/cs_platforms.cpp
client/hostinfo_unix.cpp
clientgui/DlgAbout.cpp
clientgui/MainDocument.cpp
clientgui/MainDocument.h
clientgui/ViewWork.cpp
clientgui/mac/SetupSecurity.cpp
clientgui/mac/config.h
clientgui/sg_BoincSimpleFrame.cpp
clientgui/sg_TaskCommandPopup.cpp
lib/proc_control.cpp
lib/procinfo_mac.cpp

client: Remove obsolete code I had removed in commit e2ec61e47f which was accidentally restored by commit b2ca098750.
Also, update copyright dates in source files I have recently modified.

Cf remove obsolete code (no functional changes)

---

samples/wrapper/BuildMacWrapper.sh
samples/wrapper/Makefile_mac
samples/wrapper/wrapper.cpp

Mac: Update building wrapper app for compatibility with Xcode 10

Mac: Update building wrapper app for compatibility with Xcode 10

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ClientLogRecyclerViewAdapter.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesRecyclerViewAdapter.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TaskRecyclerViewAdapter.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/glide/ScaleBitmapBy2.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt

* Make use of more extension functions provided in Jetpack, such as `String.toUri()`.
* Add an extension function to convert a `long` to a `LocalDateTime`.
N/A
N/A

[Android] Use more extensions.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TaskRecyclerViewAdapter.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt

* Add extension function that calls `ContextCompat.getColor()`.
* Set the navigation drawer's hamburger button color to white, as it is rendered black with the light theme on newer versions of Android.
N/A

[Android] Use ContextCompat.getColor().

---

android/BOINC/app/build.gradle
android/BOINC/app/src/test/java/edu/berkeley/boinc/client/MonitorTest.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountManagerParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountOutParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrRPCReplyParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/HostInfoParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessagesParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/NoticesParserTest.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectConfigReplyParserTest.java
android/BOINC/build.gradle

* Update Kotlin to 1.4, which provides [many improvements](https://kotlinlang.org/docs/reference/whatsnew14.html).
* Update other dependencies to their latest versions.
N/A

[Android] Update dependencies.

---

android/BOINC/app/src/main/res/layout/tasks_layout.xml

[Android] Fix blueish task screen.

---

drupal/sites/default/boinc/modules/contrib/ctools/ctools.info
drupal/sites/default/boinc/modules/contrib/ctools/js/ajax-responder.js

https://dev.gridrepublic.org/browse/DBOINCP-530
Upstream security fix: https://www.drupal.org/sa-core-2020-007

Drupal: SA-CORE-2020-007 fix for ctools

---

html/user/sample_index.php

Fixes #4019
Add a check for account creation being disabled into the sample_index.php file which becomes a default project webpage when the project is created.
Note: will not update existing projects unless sample_index is manually copied as index.php
Do not display account creation links in the project frontpage if project has disabled account creation (needs manual update for existing projects)

Check account creation in the project frontpage

---

win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj

[VS2019] Clean vcpkg buildtrees after build

---

html/inc/user.inc
html/user/cert_all.php

... rather than a certificate with PHP warnings at the top

web: in "all projects" certificate, show message if no projects

---

html/inc/bootstrap.inc
html/inc/language_names.inc
html/inc/util.inc

- allow specification of panel body class
- say "Language: default" in language selector

web: minor tweaks

---

win_build/boinc_signing.targets

[VS2019] Fix signing *.scr

---

client/gui_rpc_server_ops.cpp

This feature isn't being used and is a security risk.

client: disable GET feature of GUI RPC

---

clientgui/DlgExclusiveApps.cpp
clientgui/sg_BoincSimpleFrame.cpp
clientgui/sg_ProjectPanel.cpp
clientgui/sg_TaskPanel.cpp

[Manager] Fix wxSizer alignments

---

html/inc/forum.inc

The explanation for an error code could be years old.

web: remove 30-day limit in forum search function

---

tools/Makefile.am

Anchor: https://github.com/BOINC/boinc/issues/3260

Complete list of files to be installed for tools

---

lib/crypt.cpp

fix compilation without deprecated OpenSSL APIs

---

README.md

add OSX CI badge to readme
None
N/A

add OSX CI badge to readme

---

android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsIsOnlineTest.kt

[Android] Suppress deprecation warning in unit test

---

html/inc/web_rpc_api.inc
html/user/download_software.php

Web RPC: add an RPC that lets "front-end" web sites show Download buttons that auto-attach to back-end BOINC projects or account managers.

---

win_build/boinc_signing.targets

[VS2019] Add more timestamp backup servers

---

tests/unit-tests/lib/test_util.cpp
win_build/unittests_vs2019.vcxproj

Fixes #
Add test class for util library using Google test suite.

Test util library

---

tests/unit-tests/lib/test_parse.cpp

Fixes #
Copy xml parser test program code from `lib/parse_test.cpp` to `tests/unit-tests/lib/test_parse.cpp ` and run it as a unit test.

Add xml parser test

---

README.md

doc: add links to github actions on badge status

---

clientgui/AdvancedFrame.cpp
clientgui/sg_BoincSimpleFrame.cpp

Manager: don't crash when alt-space is pressed

---

.github/workflows/linux.yml

[linux] Fix CI build on Ubuntu 20.04

---

clientgui/ViewResources.cpp
clientgui/ViewStatistics.cpp

Fix: https://github.com/BOINC/boinc/issues/3822 https://github.com/BOINC/boinc/issues/988
I try to look on the CPP code, and understand where is the decision is made that the disk tab is mirror when choosing Hebrew.
All other tab is nor mirror, it specific tab, so it made me believe that the decision is in our code.
Any help will be appreciated, hopefully I will crush this bug.
Can you help me find some pointer in the cpp code? Thanks in advance.

Fix Disk tab in advanced view at Hebrew show as mirror view.

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/windows.yml

checkout two commits for codecov to work
None
N/A

[CI] Linux: checkout two commits for codecov to work

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/assets/armeabi/placeholder.txt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/res/values/configuration.xml
android/buildAndroidBOINC-CI.sh
android/build_all.sh
android/build_androidtc_armv6.sh
android/build_boinc_armv6.sh
android/build_curl_armv6.sh
android/build_openssl_armv6.sh
android/ci_build_all.sh
client/cs_benchmark.cpp
client/hostinfo_unix.cpp
configure.ac

APK 7.4.53 do not support armv6 devices. 
I create a PR, compile and run 3 projects on my 2 armv6 devices.
My device: samsung galaxy gio GT-S5660, samsung galaxy pop plus GT-S5570i
Projects: einstein@home, yoyo@home, moo! wrapper
Also I uploaded the compiled binaries as @AenBleidd requested. 
armv6 finished tasks at the 3 projects: 
https://einsteinathome.org/host/12873266
https://moowrap.net/show_host_detail.php?hostid=1309533
https://www.rechenkraft.net/yoyo/show_host_detail.php?hostid=500196
Some screenshots:

Support ARMv6 devices.

---

client/hostinfo_unix.cpp

[Android] Fix build

---

client/Makefile.linux
client/acct_setup.cpp
client/app_control.cpp
client/app_start.cpp
client/hostinfo_unix.cpp
client/project.cpp
lib/Makefile.linux
lib/crypt.cpp
lib/diagnostics.cpp
lib/gui_rpc_client_ops.cpp

Check returns from fgets(), sscanf() etc.
Use %.*s to fix truncation warnings.
Fix code formatting.
Fix Makefile.linux

Fix compile warnings in client/ and lib/.

---

lib/notice.cpp

client: put CDATA around link field of notice; may have &

---

configure.ac
m4/ax_check_cl.m4
samples/Makefile.am

Investigating issue in Ubuntu and Debian in installation process #4252

Fix opencl check in configure.ac

---

configure.ac

Check for supports shared libraries.

Check for supports shared libraries

---

android/buildAndroidBOINC-CI.sh

[Android] armv6 ndk16b

---

android/buildAndroidBOINC-CI.sh
android/build_androidtc_armv6.sh

[Android] Switch to ndk 15c for armv6

---

android/buildAndroidBOINC-CI.sh
android/build_apps.sh
android/build_client.sh

[Android] Fix cache

---

tests/unit-tests/lib/test_synch.cpp
win_build/unittests_vs2019.vcxproj

Fixes #
Add test class for synch library copying synch test program code from `lib/synch_test.cpp` to `tests/unit-tests/lib/test_synch.cpp`.

Add test class for synch library.

---

.github/workflows/linux.yml
.gitignore
android/buildAndroidBOINC-CI.sh
android/build_apps.sh
android/build_component.sh
android/build_example_arm.sh
android/build_example_arm64.sh
android/build_example_armv6.sh
android/build_example_x86.sh
android/build_example_x86_64.sh
android/ci_build_apps.sh
android/clear_environment.sh
configure.ac
deploy/prepare_deployment.sh
linux/ci_configure_apps.sh
samples/Makefile.am
samples/wrappture/Makefile
samples/wrappture/wrappture.cpp

Compile wrappture app for linux and android

[Linux][Android][Scripts][Ci] Compile wrappture app for linux and android

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml
tests/executeUnitTests.sh

[Codecov] Use action to upload coverage report

---

android/buildAndroidBOINC-CI.sh
android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_armv6.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh
android/build_component.sh
android/build_curl_arm.sh
android/build_curl_arm64.sh
android/build_curl_armv6.sh
android/build_curl_x86.sh
android/build_curl_x86_64.sh
android/build_example_arm.sh
android/build_example_arm64.sh
android/build_example_armv6.sh
android/build_example_x86.sh
android/build_example_x86_64.sh
android/build_libraries_arm.sh
android/build_libraries_arm64.sh
android/build_libraries_armv6.sh
android/build_libraries_x86.sh
android/build_libraries_x86_64.sh
android/build_openssl_arm.sh
android/build_openssl_arm64.sh
android/build_openssl_armv6.sh
android/build_openssl_x86.sh
android/build_openssl_x86_64.sh

[Android] Parallel make in Android scripts

---

.github/workflows/android.yml
android/buildAndroidBOINC-CI.sh
android/build_curl_arm.sh
android/build_curl_arm64.sh
android/build_curl_armv6.sh
android/build_curl_x86.sh
android/build_curl_x86_64.sh
android/build_openssl_arm.sh
android/build_openssl_arm64.sh
android/build_openssl_armv6.sh
android/build_openssl_x86.sh
android/build_openssl_x86_64.sh
client/Makefile.curl.am
client/Makefile.linux

[Android] Arrange android ci

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ui/eventlog/EventLogActivity.kt

[Android] Fix copy of event log entries

---

.github/workflows/linux.yml
linux/ci_configure_apps.sh
linux/update_vcpkg.sh
samples/wrappture/Makefile

Change vcpkg dir and vcpkg cache dir location

[Linux][Script] Change vcpkg dir and vcpkg cache dir location

---

android/BOINC/app/src/test/java/edu/berkeley/boinc/adapter/ClientLogRecyclerViewAdapterTest.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/adapter/GuiLogRecyclerViewAdapterTest.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/adapter/ProjectListEntryTest.kt

[Android][UnitTest] Add ClientLogRecyclerViewAdapterTest

---

android/BOINC/app/src/main/res/xml/root_preferences.xml

[Android] Fix verbosity level change

---

.github/workflows/linux.yml
deploy/prepare_deployment.sh
linux/ci_configure_client.sh
linux/ci_configure_libs.sh
linux/update_vcpkg.sh
m4/libcurl.m4

Compile Linux with vcpkg
boinc client running with the latest libcurl and libssl:

[Linux][vcpkg] Compile Linux with vcpkg

---

samples/condor/Makefile
samples/example_app/Makefile
samples/multi_thread/Makefile
samples/sleeper/Makefile
samples/vboxmonitor/Makefile
samples/vboxwrapper/Makefile
samples/wrapper/Makefile
samples/wrappture/Makefile

Arrange apps makefiles:
- `LINUX_LDFLAGS` -> `MAKEFILE_LDFLAGS`
- `LINUX_STDLIB `&nbsp;-> `MAKEFILE_STDLIB `&nbsp;
- change the order of the if:
`ifndef ANDROID` -> `ifdef ANDROID`

[Apps][Linux][Android] Arrange apps makefiles

---

android/BOINC/app/build.gradle
android/BOINC/build.gradle

[Android] Upgrade Kotlin backend to 1.4.30 and enable IR compiler

---

.codecov.yml
.github/workflows/windows.yml

[Windows][Codecov] Add Codecov support to Windows builds

---

android/BOINC/app/build.gradle

[Android] Remove deprecated 'kotlin-android-extensions' plugin

---

android/BOINC/app/src/main/res/values-night-v29/styles.xml
android/BOINC/app/src/main/res/values-v29/styles.xml

[Android] Remove forced dark mode for API 29

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.kt

For now Einstein@home is the only project that could return an error in error message instead of error code.
Attach behavior fixed to include this situation in flow and react accordingly

[Android] Fix Einstein@home attach

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/windows.yml

[CI] Upload build logs on failure for android, linux, windows

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountOutParser.kt

[Android] Fix AccountOut parser

---

android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_armv6.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh
android/build_curl_arm.sh
android/build_curl_arm64.sh
android/build_curl_armv6.sh
android/build_curl_x86.sh
android/build_curl_x86_64.sh
android/build_example_arm.sh
android/build_example_arm64.sh
android/build_example_armv6.sh
android/build_example_x86.sh
android/build_example_x86_64.sh
android/build_libraries_arm.sh
android/build_libraries_arm64.sh
android/build_libraries_armv6.sh
android/build_libraries_x86.sh
android/build_libraries_x86_64.sh
android/build_openssl_arm.sh
android/build_openssl_arm64.sh
android/build_openssl_armv6.sh
android/build_openssl_x86.sh
android/build_openssl_x86_64.sh

Add green color in message done

[Android][Scripts] Add green color in message done

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt
android/BOINC/app/src/main/res/values/strings.xml

Fixes #3928
implement cpp code:
https://github.com/BOINC/boinc/blob/b2b790e6d740a811d25bf58ecc3dc7fe067602a6/clientgui/ViewTransfers.cpp#L851-L868

[Android] Fix counter is up on retry transfer

---

android/BOINC/.idea/compiler.xml
android/BOINC/.idea/misc.xml
android/BOINC/.idea/runConfigurations.xml
android/BOINC/app/build.gradle

[Android] Upgrade to android studio 4.2

---

android/BOINC/app/src/main/res/layout/activity_welcome.xml

[Android] Remove New Year text from Xiaomi specific screen.

---

android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_armv6.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh
linux/ci_configure_client.sh
m4/libcurl.m4

Switch to pkg-config for vcpkg

[Android][Linux][vcpkg][scripts] Switch to pkg-config for vcpkg

---

.gitignore
android/BOINC/.idea/codeStyles/Project.xml
android/BOINC/.idea/misc.xml
android/BOINC/.project

[Android] Update project files

---

.github/workflows/android.yml

[Android] Upload build logs in case of build failure

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/windows.yml
deploy/manage_vcpkg_archive_cache.py

[vcpkg] Upload vcpkg binary cache to s3

---

deploy/manage_vcpkg_archive_cache.py

[vcpkg] Fix vcpkg cache upload to s3

---

.github/workflows/android.yml

Compile android with java 11 in ci.

[CI] Compile android with java 11 in ci.

---

doc/manpages/boinccmd.xml

[Documentation] Fix typo

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/maintenance.yml
.github/workflows/windows.yml
deploy/cleanup_vcpkg_archive_cache.py
deploy/manage_vcpkg_archive_cache.py
deploy/s3.py

Small workflow clean-ups and fixes

[CI] Add maintenance script to clean outdated vcpkg archives.

---

android/BOINC/app/src/main/AndroidManifest.xml
android/BOINC/app/src/main/java/edu/berkeley/boinc/receiver/BOINCReceivers.kt

Run boinc after boot
Fix for android 8 and above
Tested on 
- oneplus one android 10. (lineageOS)
- galaxy gio android 4.4. (cyanogenmod)

[Android] Run boinc after boot

---

.github/workflows/maintenance.yml

[CI] Fix S3 Maintenance script

---

deploy/cleanup_vcpkg_archive_cache.py
deploy/s3.py

[CI] Improve cleanup_vcpkg_archive_cache.py by removing duplicates

---

android/BOINC/app/build.gradle

Update build version name and code
- it's a client_release branch
- it contains a tag that points to the last commit in this branch
- there are no commits on top of this tag
- there is not any changes that is not committed

[Android] Update build version name and code

---

.github/workflows/maintenance.yml

[CI] Fix target folder used by s3 maintenance script

---

drupal/sites/default/boinc/modules/boincteam/includes/boincteam.forms.inc

Minor improvements to Drupal's BOINC team messaging form
* Fix: proper mail header format (fold/wrap at whitespace)
* Fix: HTML to plain text conversion of team message body
n/a
n/a

[Drupal] Improvements to BOINC team module

---

android/BOINC/app/build.gradle
android/BOINC/build.gradle
android/BOINC/gradle/wrapper/gradle-wrapper.properties
android/ci_build_vcpkg_manager.sh

Get latest and re-arrange dependencies
Upgrade to gradle 7.1
Upgrade to build tool sdk to 30.0.3
Update 'com.android.tools.build:gradle' to 4.2.1
Update kotlin_version to 1.5.20
Compile and run and crunch on oneplus one(Android 10).

[Android] Get latest and re-arrange dependencies

---

clientgui/mac/SetVersion.cpp
mac_build/boinc.xcodeproj/project.pbxproj
mac_installer/Installer.cpp
mac_installer/PostInstall.cpp
mac_installer/ReadMe.rtf
mac_installer/myDistribution
mac_installer/release_boinc.sh
mac_installer/release_brand.sh
mac_installer/wcgrid-ReadMe.rtf

Mac installer: on arm64 Macs, check whether Rosetta 2 ialready installed; optionally install Rosetta 2 if not already installed.

Mac installer: on arm64 Macs, optionally install Rosetta 2 if not already installed

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectDetailsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/App.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
android/ci_build_manager.sh

Fix kotlin warning
Compile and run and crunch on OnePlus one (Android 10)

[Android] Fix kotlin warning

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
android/BOINC/app/src/main/res/layout/attach_project_batch_processing_layout.xml

Fix deprecated ViewPager and NetworkInfor.
Update gradle.build to show Java deprecations.

[Android] Fix Kotlin and Java deprecations

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt

[Android] Fix changing GUI log level.

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.kt

[Android] Fix crash when show tabs

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/ProjectsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/StatusFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Change repeatedly debug msgs to verbose priority.

[Android] Change repeatedly debug msgs to verbose priority

---

android/BOINC/app/build.gradle
android/BOINC/build.gradle

Update android packages.
Update tests dependencies:
update to androidx.test:core:1.4.0
Update to mockk:1.12.0
update powermock_version to 2.0.9
Remove junit4 dependency

[Android] Update android packages

---

android/BOINC/app/build.gradle
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorExtensions.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsTest.kt

Remove common-io (Not working on old android (4.4 and below))
Add guava
Fix `without declaring an explicit or implicit dependency` warning 
Compile and run and crunch on 
OnePlus One (Android 10)
Galaxy gio (Android 4.4)

[Android] Remove common-io (Not working on old android)

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Fix Message duplication class import for auto optimize tool

[Android] Fix Message duplication class import

---

android/BOINC/app/src/main/resources/jacoco-agent.properties

Fix init jacoco exception
Compile and run and crunch on:
- OnePlus One (Android 10)
- Galaxy Gio (Android 4.4)

[Android] Fix init jacoco exception

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml
.github/workflows/osx.yml
.github/workflows/windows.yml

Add CI to `vko_android_improve_logging_system_combined` branch.

[CI] Add CI to combined branch.

---

client/hostinfo_win.cpp

[Windows][Client] Update client to report correctly Windows 11

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/Logging.kt

Print all categories in Event log -> GUI Messges ui.

[Log] Print all categories in Event log -> GUI Messges ui.

---

android/BOINC/app/src/main/aidl/edu/berkeley/boinc/client/IMonitor.aidl
android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorAsync.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/Logging.kt
android/BOINC/app/src/main/res/values/configuration.xml
android/BOINC/app/src/main/res/values/strings.xml
android/BOINC/app/src/main/res/xml/root_preferences.xml

Add gui for logger (categories ui).
I did minimal checks. need to do 3 more checks:
Additional Tasks:

[Android] Add gui for logger (categories ui).

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.kt

Fix logger bug. 
Need to init Logger log level and log categories on both processes.

[Android] Fix logger bug. 

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

Fix logger bug. 
Need to init Logger log level on both process.

[Android] Bug fix Loglevel

---

.github/workflows/test-report.yml

[CI] Add test report ci

---

.github/workflows/android.yml
.github/workflows/test-report.yml

Add Android Junit test reporter

[CI][Android] Add Android Junit test reporter

---

.github/workflows/linux.yml
tests/executeUnitTests.sh

[CI][Linux] Add Linux  test report CI

---

.github/workflows/test-report.yml

[CI][Windows] Add windows report

---

.github/workflows/windows.yml

Upload google unit test of windows.

[CI][Windows] Upload google unit test of windows.

---

.github/workflows/test-report.yml

Test report don't fail the build on test errors
Add personal token for each test report

[CI] Test report don't fail the build on test errors

---

.github/workflows/test-report.yml

[CI] Fix report bug: Remove token.

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/windows.yml

Always upload unit tests results

[CI] Always upload unit tests results

---

android/BOINC/app/build.gradle

Update buildToolsVersion to 31.0.0

[Android] Update buildToolsVersion to 31.0.0

---

android/buildAndroidBOINC-CI.sh

Arrange android boinc ci script.    
Make it more simple

[Android][Script] Arrange android boinc ci script.

---

deploy/cleanup_vcpkg_archive_cache.py
deploy/s3.py

[Maintenance] Update maintenance script to remove more outdated packages

---

android/BOINC/app/build.gradle
deploy/prepare_deployment.sh

Add armv6 build to generate light small apk for amrv6.

[Android] Add armv6 build to generate light small apk for amrv6.

---

linux/ci_configure_apps.sh
linux/ci_configure_libs.sh

Fix detection for curl.
Switch to new way.

[Linux] Fix detection for curl

---

android/buildAndroidBOINC-CI.sh
android/build_curl_arm.sh
android/build_curl_arm64.sh
android/build_curl_armv6.sh
android/build_curl_x86.sh
android/build_curl_x86_64.sh

Update curl to 7.78.0
Add --with-openssl option
Fix #4500 
Run and crunch on OnePlush One(Android 10)

[Android][CI] Update curl to 7.78.0

---

.github/workflows/android.yml
.github/workflows/linux.yml

[CI] Remove 7zip action

---

android/build_boinc_arm.sh
android/build_boinc_arm64.sh
android/build_boinc_armv6.sh
android/build_boinc_x86.sh
android/build_boinc_x86_64.sh
android/build_example_arm.sh
android/build_example_arm64.sh
android/build_example_armv6.sh
android/build_example_x86.sh
android/build_example_x86_64.sh
android/build_libraries_arm.sh
android/build_libraries_arm64.sh
android/build_libraries_armv6.sh
android/build_libraries_x86.sh
android/build_libraries_x86_64.sh
configure.ac
linux/ci_configure_apps.sh
linux/ci_configure_client.sh
linux/ci_configure_libs.sh

Arrange scripts using --enable-apps-vcpkg

[Linux][Android][vcpkg] Arrange scripts using --enable-apps-vcpkg

---

.github/workflows/linux.yml
configure.ac
linux/ci_configure_apps.sh
linux/ci_configure_client.sh
linux/ci_configure_libs.sh
linux/update_vcpkg_apps.sh
linux/update_vcpkg_client.sh
linux/update_vcpkg_libs.sh
samples/Makefile.am
samples/example_app/Makefile

[Linux][Apps] Compile gui apps for linux

---

client/cs_scheduler.cpp

If a scheduler reply has a different master URL than the current one:
- if it's a http: to https: change, do it
- otherwise tell the user the project seems to have changed its master URL,
and they should detach/reattach.
Remove the nonsensical "your are attached twice..." message.
Note: code you wrote a long time ago sometimes doesn't seem
to make any sense at all.

all master URL update to https:

---

.github/workflows/linux.yml
.github/workflows/maintenance.yml

Fix version of boto3 library because of the issue with the newer one

---

html/inc/team.inc

web: remove use of "group by" to avoid error w/ newer MySQL

---

android/buildAndroidBOINC-CI.sh
android/build_boinc_armv6.sh

Use curl 7.80.0 for non-vcpkg Android build.

[Android] Fix armv6 vcpkg build.

---

html/inc/util.inc
html/user/create_profile.php
html/user/forum_post.php
html/user/forum_reply.php
html/user/forum_report_post.php
html/user/pm.php

define('VALIDATE_EMAIL_TO_POST', '1');
in your project.inc, users have to validate their email addrs
to post in the forums, send PMs, or create profiles.

Add a new mechanism to discourage spam: if you put

---

.github/workflows/flutter-macos.yml
.github/workflows/flutter-ubuntu.yml
.github/workflows/osx.yml
samples/flutter/boinc/android/app/build.gradle

- Fix Flutter-Linux dependencies in ci.
- Fix Flutter-android skd compile version.
- Fix Flutter-macos/ios  xcode-version in ci.
- Fix macos xcode-version in ci.
@AenBleidd Please enable flutter ci for check this PR.

Fix Flutter and mac os bugs in ci.

---

.github/workflows/flutter-macos.yml
.github/workflows/flutter-ubuntu.yml
.github/workflows/flutter-windows.yml

Add flutter binaries cache

---

.github/workflows/flutter-macos.yml
.github/workflows/flutter-ubuntu.yml
.github/workflows/flutter-windows.yml

[CI] Fix flutter cache

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectsParser.kt
android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectsParserTest.kt

Parse project disk usage.
Until now, never use the disk usage, although we get the information from the state xml.

[Android] Parse project disk usage

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
android/BOINC/app/src/main/res/layout/projects_layout_listitem.xml
android/BOINC/app/src/main/res/values-en/strings.xml
android/BOINC/app/src/main/res/values/strings.xml

Display disk usage on project tab:

[Android][Gui] Display disk usage on project tab

---

.github/workflows/android.yml
.github/workflows/coverity.yml
.github/workflows/flutter-macos.yml
.github/workflows/flutter-ubuntu.yml
.github/workflows/flutter-windows.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml

[CI] Add *.yml files to the hash while resolving cache, remove restore-key

---

.github/workflows/windows.yml

[Windows][CI] Upload PDB files

---

.github/workflows/flutter-windows.yml
.github/workflows/windows.yml

[CI][Windows] Build using 'windows-2019' image on CI

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/MessagesParser.kt

[Android] Fix issue with empty log when any flags enabled.

---

win_build/boincmgr_vs2019.vcxproj

[Windows] Fix failing Debug build because of the lzma library rename

---

clientgui/AccountManagerInfoPage.cpp
clientgui/AccountManagerProcessingPage.cpp
clientgui/AccountManagerPropertiesPage.cpp
clientgui/AdvancedFrame.cpp
clientgui/BOINCTaskCtrl.cpp
clientgui/DlgAdvPreferences.cpp
clientgui/DlgAdvPreferencesBase.cpp
clientgui/DlgDiagnosticLogFlags.cpp
clientgui/DlgEventLog.cpp
clientgui/DlgHiddenColumns.cpp
clientgui/MainDocument.cpp
clientgui/MainDocument.h
clientgui/ProjectInfoPage.cpp
clientgui/ProjectProcessingPage.cpp
clientgui/ProjectPropertiesPage.cpp
clientgui/SkinManager.cpp
clientgui/TermsOfUsePage.cpp
clientgui/sg_BoincSimpleFrame.cpp
clientgui/sg_DlgMessages.cpp
clientgui/sg_DlgPreferences.cpp
clientgui/sg_PanelBase.cpp
clientgui/sg_PanelBase.h
clientgui/sg_ProjectPanel.cpp
clientgui/sg_TaskPanel.cpp

[Manager][Windows] Make Manager DPI unaware to let wxWidgets and Windows scale GUI elements properly

---

deploy/prepare_deployment.py

[CI] Clean deploy python script

---

client/hostinfo_win.cpp

[Windows] Fix detection of Windows product

---

mingw/ci_make_apps.sh

[CI] Fix mingw-vcpkg build

---

.github/workflows/linux.yml
.gitignore
lib/CMakeLists.txt
lib/vcpkg.json
linux/bootstrap_vcpkg_cmake.sh
linux/ci_configure_apps.sh
linux/ci_configure_client.sh
linux/ci_configure_libs.sh
linux/ci_configure_libs_cmake.sh
linux/update_vcpkg_client.sh
linux/update_vcpkg_libs.sh

Compile boinc libs with cmake.

[cmake] Compile boinc libs with cmake

---

.github/workflows/windows.yml
linux/ci_configure_libs_cmake.sh
windows/bootstrap_vcpkg_cmake.bat
windows/ci_build_libs_cmake.bat

[windows][cmake][ci] Add windows libs cmake

---

linux/update_vcpkg_apps.sh
linux/update_vcpkg_client.sh
linux/update_vcpkg_libs.sh
linux/vcpkg_config_apps/vcpkg.json
linux/vcpkg_config_client/vcpkg.json
linux/vcpkg_config_libs/vcpkg.json

vcpkg Linux in manifests mode.

[Linux][vcpkg][manifests] vcpkg Linux in manifests mode

---

linux/update_vcpkg_apps.sh
linux/update_vcpkg_client.sh
linux/update_vcpkg_libs.sh
mingw/update_vcpkg.sh
mingw/vcpkg_config_apps/vcpkg.json

[Mingw][vcpkg][manifests] mingw vcpkg manifests mode

---

win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj
win_build/vcpkg_config_msbuild_ARM64/vcpkg.json
win_build/vcpkg_config_msbuild_x64/vcpkg.json

Add windows msbuild manifests mode.

[Windows][vcpkg][CI] Add windows msbuild manifests mode

---

.github/workflows/mingw.yml
mingw/bootstrap_vcpkg_cmake.sh
mingw/ci_configure_libs_cmake.sh

[MinGW][cmake] Add cmake libs in mingw

---

.github/workflows/android.yml
.gitignore
android/bootstrap_vcpkg_cmake.sh
android/buildAndroidBOINC-CI.sh
android/ci_build_libs_cmake.sh
android/ndk_common.sh
lib/vcpkg_config_android/vcpkg.json

[Android][cmake] Add android libs cmake

---

py/Boinc/db_base.py

Fix bug in python DB code

---

linux/vcpkg_config_apps/vcpkg.json
samples/Makefile.am
samples/example_app/Makefile

Linux apps compile gui with vcpkg.

[CI][vcpkgl][Apps] Linux apps compile gui with vcpkg

---

locale/templates/BOINC-Client.pot
locale/templates/BOINC-Manager.pot
locale/templates/BOINC-Project-Generic.pot
locale/templates/BOINC-Setup.pot

[l10n] Update localization templates

---

mingw/ci_make_apps.sh
samples/condor/Makefile

Fix condor app to compile with curl vcpkg.

[Bugfix] Fix condor app to compile with curl vcpkg

---

win_build/boincmgr_vs2019.vcxproj

~~test wxwidgets 3.1.6~~
windows wxwidgets 3.1.6

[Windows] windows wxwidgets 3.1.6

---

android/BOINC/.idea/misc.xml
android/BOINC/app/build.gradle
android/BOINC/app/src/main/AndroidManifest.xml
android/BOINC/build.gradle
android/BOINC/gradle/wrapper/gradle-wrapper.properties

Update android dependencies.
Compile, and run and crunch on One plus One (android 9) and emulator Arm7 (android 4.1)

[Android] Update android dependencies

---

lib/Makefile.am

Install headers required to build wrapper app

---

set-vboxwrapper-version.py
set-version.py
set-wrapper-version.py
win_build/installerv2/BOINCx64.ism
win_build/installerv2/BOINCx64_vbox.ism
win_build/wrapper.vcxproj
win_build/wrapper_vs2013.vcxproj

[Bugfix] Fix version util and files

---

clientgui/DlgAbout.cpp

Updated the copyright year in the About dialog box of Manager

[Manager] Updated copyright year

---

m4/boinc_wxwidgets.m4

[bugfix] Add webkit2gtk ld flags

---

html/inc/user.inc
html/inc/util.inc

web: a couple more PHP 8.1 fixes

---

.gitignore
Makefile.am
configure.ac
deploy/prepare_deployment.py
samples/wasm/index.html

[Wasm] Compile wasm with html

---

clientgui/sg_BoincSimpleFrame.cpp
clientgui/sg_BoincSimpleFrame.h

[Manager] Create proper sizing on SimpleView

---

win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj

[Windows] Remove vcpkg cache miss error workaround

---

.github/workflows/wasm.yml
wasm/ci_configure_client.sh

[wasm] Add debug information

---

html/ops/build_po.php
html/ops/delete_spammers.php
html/ops/team_import.php

use date() instead of strftime()

PHP 8.1 fixes

---

linux/ci_configure_manager.sh

This fix is interduce to vcpkg
https://github.com/microsoft/vcpkg/pull/25240:
I suspect it give us build errors in vcpkg manager build.
We should fix it.
@AenBleidd

[vcpkg] wxwidgets vcpkg fix

---

html/inc/bolt_db.inc
html/inc/bossa_db.inc
html/inc/bossa_example.inc

(which they miraculously do, on the test project).

Tweak Bolt and Bossa to make them work again

---

client/client_state.cpp

client: ignore case in project lookup by URL

---

client/hostinfo_network.cpp

Disable get mac address in wasm.
After the change we have some progress in client on the web:
```
17-Jun-2022 06:33:17 [---] cc_config.xml not found - using defaults
17-Jun-2022 06:33:17 [---] Starting BOINC client version 7.21.0 for i686-pc-linux-gnu
17-Jun-2022 06:33:17 [---] This a development version of BOINC and may not function properly
17-Jun-2022 06:33:17 [---] log flags: file_xfer, sched_ops, task
17-Jun-2022 06:33:17 [---] Libraries: libcurl/7.83.1-DEV OpenSSL/3.0.3 zlib/1.2.12
17-Jun-2022 06:33:17 [---] Data directory: /
17-Jun-2022 06:33:17 [---] No usable GPUs found
17-Jun-2022 06:33:17 [---] Creating new client state file
17-Jun-2022 06:33:17 [---] Host name: emscripten
17-Jun-2022 06:33:17 [---] Processor: 1 WASM WASM
17-Jun-2022 06:33:17 [---] Processor features: …
```

[wasm] Disable get mac address in wasm.

---

.github/workflows/android.yml

Fix android ANDROID_NDK_ROOT environment variable in CI.

[Android][CI] Fix android ANDROID_NDK_ROOT environment variable in CI

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml
.github/workflows/osx.yml
.github/workflows/wasm.yml
.github/workflows/windows.yml
deploy/prepare_deployment.py

Add to deploy logs, locale and skins.

[CI] Add to deploy logs, locale and skins

---

.github/workflows/wasm.yml

[wasm][ci] Fix wasm vcpkg cache

---

.github/workflows/osx.yml

[osx][ci] Add vcpkg cache

---

client/work_fetch.cpp

client: fix bug in work fetch logic for case of zero resource share and zero work buf.

---

clientgui/sg_BoincSimpleFrame.cpp
win_build/boinc_finalize.targets

Fix switch skin when manager is not connected
Fixes #4834

[Bugfix] Switch skin when manager is not connected

---

3rdParty/buildLinuxDependencies.sh

[Linux][Manager] Updating wxwidgets to v3.2.0.

[Linux][Manager] Updating wxwidgets to v3.2.0

---

3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
linux/update_vcpkg_manager.sh

Update vcpkg wxwidgets to compile with -DwxBUILD_DEBUG_LEVEL=0.

[vcpkg] Update vcpkg wxwidgets to compile with -DwxBUILD_DEBUG_LEVEL=0

---

.github/workflows/osx.yml

[CI] Fix deploy log on osx

---

.github/workflows/mingw.yml
.github/workflows/wasm.yml

Remove edgarrc/action-7z from ci.

[CI] Remove edgarrc/action-7z from ci

---

mac_build/buildfreetype.sh

[CI][OSX] Specify to build FreeType library without brotli support

---

deploy/prepare_deployment.py

[CI][osx] Add mac osx logs files

---

mac_build/buildMacBOINC-CI.sh

[OSX][CI] Enable ss_app build on CI.

---

.github/workflows/linux.yml
linux/ci_configure_manager.sh
win_build/boincmgr_vs2019.vcxproj

[CI][Windows][linux] Fix build with wxWidgets 3.2.0

---

.github/workflows/linux.yml

[CI] Remove redundant packages from the list

---

samples/vboxwrapper/vbox_vboxmanage.cpp
samples/vboxwrapper/vboxwrapper.cpp

Replaces all occurrences of 'sprintf' with 'snprintf' within the sources forming vboxwrapper.

[vboxwrapper] Replace sprintf with snprintf

---

client/file_names.cpp

Revoke previous change

---

win_build/unittests_vs2019.vcxproj

[Windows] Fix Debug build

---

.github/workflows/linux.yml
.gitignore
deploy/prepare_deployment.py
linux/arm64/build_curl_arm64.sh
linux/arm64/build_example_arm64.sh
linux/arm64/build_libraries_arm64.sh
linux/arm64/build_openssl_arm64.sh

[CI] Add scripts to build libboinc and samples for linux arm64.

---

samples/wrapper/BuildMacWrapper.sh

Mac wrapper: build Universal M1 / x86_64 binary

---

set-version.py

Fix set-verion.py script to update version.h.in file as well.

---

sched/db_dump.cpp
sched/message_handler.cpp
sched/sched_locality.cpp
sched/sched_main.cpp
sched/sched_resend.cpp
sched/sched_result.cpp
sched/sched_types.cpp
sched/sched_util.cpp
sched/trickle_echo.cpp
sched/update_stats.cpp
sched/validator.cpp

Ref: https://gcc.gnu.org/gcc-12/porting_to.html
Co-authored-by: Gianfranco Costamagna <costamagnagianfranco@yahoo.it>

Fix build of server utils with gcc12.

---

.github/workflows/linux.yml

Fixes #
This was for Arm64 but it was called amd64

Fix a typo

---

clientgui/ViewWork.cpp

Fix null pointer dereferences

---

clientgui/DlgAdvPreferences.cpp
clientgui/DlgAdvPreferencesBase.cpp
clientgui/DlgAdvPreferencesBase.h

[Manager] Convert ProcessorTab in Preferences dialog from wxPanel to wxScrolledWindow to show all content on small screens (e.g. 1024x768).

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt

[Android] Remove unused piece of code

---

clientgui/Makefile.am
linux/ci_configure_manager.sh
linux/update_vcpkg_manager.sh

Add missed '-lresolv' library.

[CI] Fix Manager build using vcpkg for linux.

---

html/user/server_status.php

server status page: 'last 100' -> 'recent'

---

.github/workflows/android.yml
.github/workflows/coverity.yml
.github/workflows/flutter-macos.yml
.github/workflows/flutter-ubuntu.yml
.github/workflows/flutter-windows.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml
.github/workflows/osx.yml
.github/workflows/source-code-check.yml
.github/workflows/wasm.yml
.github/workflows/windows.yml
3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
mac_build/buildfreetype.sh

[CI] Update actions to fix deprecations

---

clientgui/DlgExclusiveApps.cpp

Link at the bottom of the Exclusive applications dialog box is listed as http.  Revising to https.
N/A
N/A

[Manager] Revise link from http to https under Exclusive Applications

---

android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.kt

[Android] Suppress immutable missing warning

---

.github/workflows/windows.yml
win_build/boinc.props

[CI][Windows] Always generate full PDBs

---

android/BOINC/app/build.gradle

[Android] Upgrade grgit dependency to 5.0.0

---

sched/sched_send.cpp

We were decrementing by predicted job duration.
Need to multiply this by the # of instances used.
This resulted in too many MT jobs being sent, for example.
Fixes #4151

scheduler: when sending a job, decrement work request time by the correct amount.

---

tools/update_versions

PHP Notice:  Undefined variable: confirm in /home/boincadm/projects/fitcrack/bin/update_versions on line 480

Fix broken confirm in process_version

---

clientgui/MainDocument.cpp

Fixes #5019 
Also clean up Show graphics / Stop graphics logic on MacOS.

MSW: Fix "Stop graphics" button operation on MS Windows

---

clientgui/AccountManagerProcessingPage.cpp
clientgui/ProjectProcessingPage.cpp

Fix for issue 5024

---

win_build/wrappture_example_vs2019.vcxproj

[CI][Windows] Fix build after expat update on vcpkg

---

html/inc/recaptchalib.php

The old code stopped working; I don't know why.
Maybe some change at Google's end.
I switched to a simpler method, as described here: https://developers.google.com/recaptcha/docs/verify

web: fix recaptcha validation

---

locale/templates/BOINC-Client.pot
locale/templates/BOINC-Manager.pot
locale/templates/BOINC-Project-Generic.pot
locale/templates/BOINC-Setup.pot

[locale]: update localixation template files

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml

[CI] Build linux, Android and mingw with ubuntu-20.04

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/mingw.yml
.github/workflows/osx.yml
.github/workflows/source-code-check.yml
.github/workflows/wasm.yml
.github/workflows/windows.yml

[CI} Run CI on every push to 'client_release/**' branch

---

set-client-version.py

Rename set-version.py to set-client-version.py

---

.github/workflows/osx.yml

[CI][OSX] Update OSX CI to use XCode 14.2.0

---

.github/workflows/coverity.yml

[CI] Fix Coverity builds

---

.github/workflows/android.yml

[CI][Android] Fix build on ubuntu-latest

---

client/app.cpp
client/client_state.cpp
client/rr_sim.cpp

Somehow I had removed
#define NEW_CPU_THROTTLE in an earlier commit.
Fix a compile warning.
Fixes #5072

client: enable CPU throttling

---

3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
linux/update_vcpkg_manager.sh
set-client-version.py

Compile Linux vcpkg manager in manifest mode.
tested on wsl2 ubuntu 22.04.

[Linux][Manager][vcpkg] Compile Linux vcpkg manager in manifest mode.

---

3rdParty/vcpkg_ports/configs/apps/android/vcpkg.json
3rdParty/vcpkg_ports/configs/apps/linux/vcpkg.json
3rdParty/vcpkg_ports/configs/apps/mingw/vcpkg.json
3rdParty/vcpkg_ports/configs/client/vcpkg.json
3rdParty/vcpkg_ports/configs/client/wasm/vcpkg.json
3rdParty/vcpkg_ports/configs/libs/vcpkg.json
3rdParty/vcpkg_ports/configs/libs/windows/vcpkg.json
3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
set-client-version.py

Remove versions from manifests files.

[vcpkg] Remove versions from manifests files

---

deploy/prepare_deployment.py

[ci] Fix deploy logs

---

README.md

Add snap and test report status.

[Readme] Add snap and test report status

---

README.md

[Readme] Delete test report badge

---

client/boinc_cmd.cpp

Shows task summaries, one per line
Fixes #5130

boinc_cmd: add --get_task_summary command.

---

html/inc/util.inc
html/user/team_members.php
html/user/top_hosts.php
html/user/top_teams.php
html/user/top_users.php

team_members.php and top_*.php have a textual parameter "sort"by". Validate it.

Web: remove XSS vulnerability.

---

android/BOINC/app/build.gradle

Remove hard coded Android manifest string.

[Android] Remove hard coded Android manifest string

---

3rdParty/vcpkg_ports/vcpkg_link.bat
3rdParty/vcpkg_ports/vcpkg_link.sh
win_build/vcpkg_3rdparty_dependencies.vcxproj
windows/bootstrap_vcpkg_cmake.bat

Add vcpkg link also for windows.

[CI][Windows] Add vcpkg link also for windows

---

win_build/boincmgr.vcxproj

linux build failure requires upstream fix: https://github.com/microsoft/vcpkg/issues/30361

[Windows] Fix build error after wxWidgets update

---

clientgui/BOINCBaseFrame.cpp

[Manager][Windows] Prevent close request on minimized window exiting the app

---

android/ci_build_libs_cmake.sh
linux/ci_configure_libs_cmake.sh
mingw/ci_configure_libs_cmake.sh
osx/ci_build_libs_cmake.sh
windows/ci_build_libs_cmake.bat

Change to DVCPKG_INSTALLED_DIR in cmake builds.

[Bugfix][cmake] Change to DVCPKG_INSTALLED_DIR in cmake builds

---

client/gpu_amd.cpp
client/gpu_detect.cpp
client/gpu_detect.h
client/gpu_nvidia.cpp
client/gpu_opencl.cpp
client/main.cpp

Otherwise, if the GPU detection process fails, they're lost.
Could help debug problems in GPU detection.

client: write GPU detection warnings to stderr

---

3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
configure.ac
linux/ci_configure_apps.sh
linux/ci_configure_manager.sh

Detect vcpkg freeglut for linux

[Linux][vcpkg] Detect vcpkg freeglut for linux

---

html/inc/dir_hier.inc
html/inc/sandbox.inc
html/user/manage_app.php
html/user/sandbox.php

Add function to map sandbox logical name to physical.
Uncomment permissions functions in app manage page.
Add basic function for staging an input file.

web: job-submission tweaks

---

html/inc/submit_util.inc
html/user/submit.php

color-code success, error, in progress, unsent

web, job submission: show progress bar on batch page

---

clientgui/BOINCTaskBar.cpp

Mac: Use higher resolution menubar icon.

---

html/ops/dbinfo.php

also: fix warning because latest_consent is a view, not a table
(should redo the whole consent thing at some point)
Fixes #5457

fix PHP8 deprecations in admin web

---

sched/sample_assimilator.cpp
tools/demo_query
tools/demo_submit

These scripts are useful for debugging; may as well generalize them a bit.

demo_submit, demo_query: allow > 1 input and output files

---

html/inc/util.inc
html/user/am_set_info.php

am_set_info.php: some bad code here.
Fixes #5467

Fix some PHP8 warnings

---

.github/workflows/debrepo/package_depends.sh
.github/workflows/debrepo/package_prepare.sh
.github/workflows/debrepo/repo_update.sh
.github/workflows/linux-package.yml
.github/workflows/rpmrepo/package_depends.sh
.github/workflows/rpmrepo/package_filelist.sh
.github/workflows/rpmrepo/package_prepare.sh
.github/workflows/rpmrepo/repo_update.sh
3rdParty/vcpkg_ports/configs/client/vcpkg.json
3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
deploy/prepare_deployment.py
linux/ci_configure_manager.sh
packages/deb/postinst
packages/generic/36x11-common_xhost-boinc
tests/linux_package_tests/integration_tests.py
tests/linux_package_tests/testset.py

This PR contains the following changes:
- Fix installation of translations.
- Put icons to the correct location.
- Run boinc-client service after package installation.
- Add ca-certificates package dependency.
- Create link to the system ca certificates file during installation.
- Create /etc/boinc-client folder if not exists.
- Set permissions to the data directory. Create configuration files (and symbolic links to them) if not exist.
- Add X11 config file. Fix boinc.conf file installation.
- Add current user to the boinc group.
- Add boinc user to the video and render groups.
- Create boinc user and boinc group when installing the package.
- Put postinst script to the package.
- Add integration tests.
This PR fixes the following issues: #5324, #5325, #5335, #5431.

[Linux][CI] Fix building DEB and RPM packages.

---

client/cs_files.cpp
samples/worker/run_worker_1.sh

Make it possible to fiddle with app version files (to facilitate debugging).

client: enforce dont_check_file_sizes option

---

clientgui/sg_DlgMessages.cpp
clientgui/sg_DlgPreferences.cpp

[Linux] Fix blank windows in Simple GUI.

---

py/Boinc/setup_project.py

(introduced in 2018)
Fixes #5538

project setup: remove extraneous " from schedulers.txt

---

html/inc/bootstrap.inc

Note: this function isn't used in BOINC.

form_select_multiple(): optional arg is list of selected values

---

samples/vboxwrapper/vbox_common.cpp

vboxwrapper: fix bug that caused VB version detection to fail

---

3rdParty/vcpkg_ports/ports/liblzma/add_support_ios.patch
3rdParty/vcpkg_ports/ports/liblzma/build-tools.patch
3rdParty/vcpkg_ports/ports/liblzma/fix_config_include.patch
3rdParty/vcpkg_ports/ports/liblzma/portfile.cmake
3rdParty/vcpkg_ports/ports/liblzma/usage
3rdParty/vcpkg_ports/ports/liblzma/vcpkg-cmake-wrapper.cmake
3rdParty/vcpkg_ports/ports/liblzma/vcpkg.json
3rdParty/vcpkg_ports/ports/liblzma/win_output_name.patch

[CI] Add custom liblzma port

---

drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc

As the title suggests, it complements David's commit 73fba33 with regards to Drupal.
"[drupal] added Apple GPU support to project preferences"

[drupal] added Apple GPU support to project preferences

---

snap/snapcraft.yaml

[CI] Replace unofficial PPA with the official snap package of aws cli

---

CONTRIBUTING.md

Remove slack links. Put discord links instead.

---

drupal/sites/default/boinc/modules/boincwork/includes/boincwork.helpers.inc

* Commit 73fba3369 [renamed](https://github.com/BOINC/boinc/commit/73fba33695afa07c70f1934fc1d0b15b2800cea9#diff-dd4f6b6ee9fc4118dd664d41cba97df53c02cb5f95c0b78e1447e81bafb7d6ba) a constant but lacks the rename here
* Also added new constant added by 73fba3369

[drupal] fix regression in 73fba3369

---

.github/workflows/linux-package.yml
packages/deb/postinst
tests/linux_package_tests/integration_tests.py

[linux] fix install scripts to handle upgrade cases.

---

client/hostinfo_win.cpp

Correct typo in hostinfo_win.cpp

---

client/client_state.cpp
client/cs_prefs.cpp

'Host' -> 'Computer'
'General preferences' -> 'Computing preferences'.

client: fix terminology

---

clientgui/AdvancedFrame.cpp
clientgui/DlgGenericMessage.cpp
clientgui/DlgGenericMessage.h

This is a preparation for another PR that will utilize this new functionality.

[Manager] Make DlgGenericMessage dialog more generic.

---

clientgui/MainDocument.cpp

[Manager] Add possibility to navigate to the download page when the new version of BOINC is available.

---

html/inc/host.inc
html/inc/team.inc
html/inc/user.inc
html/user/custom_dark.css
html/user/edit_forum_preferences_form.php
html/user/show_user.php

- in user page, use panels to group content
- change custom RSS for dark mode so that tables in panels have the same background color as the panel
- use appropriate units for host info (e.g. GB for memory size)

web tweaks

---

tools/update_versions

Also format --verbose output better
Fixes #1366

update_versions: keep going if find bad app version directory

---

html/user/forum_reply.php

e.g. In reply to Joe Smith's message of 28 Jul 2024:
Fixes #1496

forums: when quote a message, identify its sender and date

---

html/inc/forum.inc
html/inc/pm.inc
html/user/pm.php

Moderators need to be able to contact everyone.
Fixes #1926

web: don't allow blocking PMs from a moderator or admin.

---

db/schema.sql
html/inc/forum.inc
html/inc/forum_db.inc
html/inc/forum_email.inc
html/inc/notify.inc
html/inc/user.inc
html/inc/util.inc
html/ops/notify.php
html/user/forum_forum.php
html/user/forum_thread.php

E.g. you could subscribe to the BOINC News forum and get it view email
Fixes #4637

Add the ability to subscribe to forums (as well as threads).

---

html/ops/botnet.php
sched/handle_request.cpp

...which could be evidence of botnets, like the recent one.
- scheduler: update comments in authenticate_user()

- add ops script to check for users to large numbers of hosts.

---

html/inc/bbcode_html.inc
html/inc/forum.inc
html/inc/pm.inc
html/inc/text_transform.inc
html/user/forum_edit.php
html/user/forum_forum.php
html/user/forum_post.php
html/user/forum_reply.php
html/user/forum_search_action.php
html/user/forum_thread.php
html/user/forum_user_posts.php

web: when create or post to a thread, add option for subscribing (default on)

---

html/user/forum_index.php

(so the BOINC web site doesn't need a custom version of the file).

web: add an optional project-specific intro in forum index.

---

html/user/forum_post.php
html/user/forum_reply.php

forums: 'subscribe' checkbox is initially unchecked

---

clientgui/DlgAdvPreferencesBase.cpp

[linux][manager] Fix fonts on Advanced Computing Preferences dialog.

---

html/inc/boinc_db.inc
html/ops/db_update.php
sched/plan_class_spec.cpp

admin web: fix bug in opening DB

scheduler: fix WSL plan class

---

samples/wsl_wrapper/wsl_wrapper.cpp

Fix typo in wsl_wrapper

---

html/inc/user_util.inc
html/user/edit_user_info_action.php

Check this (and show appropriate message) in both account creation and user name update

web: don't allow special chars in user names.

---

client/app_test.cpp
lib/util.cpp

lib: fix file descriptor leak
Fixes #5859

client: disable debugging code

---

html/inc/submit_util.inc
html/user/buda.php
html/user/buda_submit.php
html/user/submit.php
html/user/submit_rpc_handler.php

... and unify access control for web and remote job submission

BUDA job submission: add access control

---

html/user/mail_passwd.php

Lets them give emergency instructions.

mail_passwd.php: allow projects to add their own message at end of page about password reset email.

---

html/inc/sandbox.inc
html/user/job_file.php
html/user/submit_rpc_handler.php
lib/boinc_submit.py
tools/boinc_submit_test.py
tools/submit_api_test.py

job submission: change logic for handling input files in user sandbox to use new sandbox structure
BOINC_SERVER::upload_files(): fix logic for missing files
etree_to_dict(): we weren't handling lists of XML elements correctly
submit_api_test.py: deprecate (replaced by boinc_submit_test.py)
Fixes #6091

remote job submission and file management: various bug fixes

---

clientgui/ViewStatistics.cpp

Apologies, but ViewStatistics.cpp had a bunch of "incorrect" styling from the BOINC styling guide.  Mostly using tabs instead of spaces, but some formatting with brackets for if statements as well.  Normally I would just fix these as I go when submitting a PR for something substantial, but I figured these formatting changes are substantial enough.
Leaving well enough alone.
N/A

style: change tabs to spaces, other miscellaneous formatting

---

html/ops/delete_spammers.php

Check whether user has actually posted something
(having forum prefs doesn't imply this)
and whether any of their posts contain URLs or links.
Note: this option is not recommended.
It will delete non-spamming users who join a project to participate in its message boards.
I added some comments to this effect.

delete_spammers.php: fix --forums option

---

samples/docker_wrapper/docker_wrapper.cpp

'mount' lets you mount host directories, possibly read-only. 'portmap' lets you map container ports to host ports. See https://github.com/BOINC/boinc/wiki/Docker-apps#the-docker-wrapper
Also implement the 'use_gpu' option in job.toml (need to test this).
Fixes #6136

docker_wrapper: add 'mount' and 'portmap' options to job.toml

---

lib/util.cpp
lib/win_util.cpp
samples/docker_wrapper/docker_wrapper.cpp

Add 'verbose', 'build_args', 'create_args' options to job.toml.
Fix logging on podman.
Write error msgs to stderr in various places.
Fixes #6155

docker_wrapper: add features and improve error messages

---

html/user/submit.php

- when showing list of batches, call get_batch_params() for in-progress batches; they might be complete now
- add the ability to retire multiple batches
- code simplification

web: job submission improvements

---

html/ops/failure_result_summary_by_host.php
html/ops/failure_result_summary_by_platform.php
html/ops/pass_percentage_by_platform.php

- don't fetch unused stuff
- use get_int() instead of $_GET[]
- don't put quotes around ints in queries
- don't put DESC in GROUP_BY
Fixes #6160

fix DB queries

---

client/client_state.cpp

initialization was in the wrong order.
Fixes #6181

client: fix bug that caused anonymous platform apps to have ncpus=0

---

samples/docker_wrapper/docker_wrapper.cpp

**Current status**
Docker wrapper reports either '0' or '1' to BOINC client.
Status codes from inside a container are not forwarded.
**Expected**
In case of a container 'JOB_SUCCESS' get the status code from the main process running inside a container and forward that status code to BOINC client.
Tested with a task from lhcathomedev.cern.ch which was forced to report status 206.
https://lhcathomedev.cern.ch/lhcathome-dev/result.php?resultid=3392131

Enable docker wrapper to forward exit codes from a container to BOINC client

---

samples/wrapper/wrapper.cpp

Fixes #6214
Adds an argument flag `--passthrough_child` to the wrapper app.
When supplied, any arguments in argv that come after that flag will be disregarded by the wrapper app itself and instead will be passed through to the child process as the sole arguments given to it.
Alternative solutions may be to either:
1. Disable the logic that exits the program when it finds an invalid argument from the wrapper's perspective, since it should passthrough those arguments to the child.
2. Rely solely on job.xml for cmdline args
The reason I selected this implementation is because I utilize the cmdline args in jobsubmission to iterate through a range of variables and create the tasks for our project, and we can't easily replace job.xml for each …

Add --passthrough_child arg to wrapper app

---

html/inc/util.inc

web: declare $config global (for Drupal)

---

html/inc/bootstrap.inc
html/inc/util.inc
html/user/manage_project.php

If 'all apps' is checked, disable app selection.
Note: this uses a 3rd-party widget called select2 for multiple selection. Add an interface for this; we might use it elsewhere. Get its files from a CDN.

web: fix job submission admin page

---

html/inc/bootstrap.inc
html/user/buda.php
html/user/custom_dark.css

Make select2 work with dark mode

web: use select2 for app file selection in BUDA

---

html/inc/bootstrap.inc
html/user/buda.php
html/user/submit.php

- Move job submission functions to their own navbar menu
- The main job submission page just shows job submission, not a bunch of other stuff. Use icons for the various apps. Use radio buttons for all hosts / only my hosts
- Simplify the BUDA page Don't show delete app button unless there are no variants

web: improve job submission interface

---

tools/submit_buda

Probably not needed since we have the web interface, but may as well fix it.

submit_buda: make it work again

---

html/inc/result.inc
html/inc/submit_util.inc
html/project.sample/project.inc
html/user/buda.php
html/user/submit.php
tools/project.xml

- batch page: fix bug that erroneously showed jobs as in progress
- Result page: don't show stderr if job not over
- BUDA: require that max total >= target success
- sample project.inc: include DARK_MODE and SHORTCUT_ICON

web (job submission): various tweaks

---

client/hostinfo_unix.cpp

In some scenarios, 'docker --version' works but it can't run a container because of permissions.
Check this by running hello-world.
We've only seen this on Linux, and the check is slightly time-consuming, so only do this on Linux.
Fixes #6262

client (linux): verify docker/podman detection by running hello world image

---

html/inc/keywords.inc
html/user/show_apps.php

show_apps.php:
- show researchers (job submitters); get the info from a JSON file.
- show which apps need Docker

web (job submission) additions

---

drupal/sites/all/features/user_account_host_list/user_account_host_list.views_default.inc
drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc

Original changes:
* https://github.com/BOINC/boinc/commit/fc745ae0a03abd3ec2db90b7317aade9c2130d75
* https://github.com/BOINC/boinc/commit/e896ee7ec15be8d8bb4283b519e3236f62dce167

Fix regressions in Drupal following BOINC changes

---

html/user/buda_submit.php
html/user/job_fpops.php

add script to show runtime distribution

web (BUDA) add 'expected runtime' to submission form

---

html/inc/account.inc
html/inc/akismet.inc
html/inc/bootstrap.inc
html/inc/forum_email.inc
html/inc/host.inc
html/inc/prefs.inc
html/inc/submit_util.inc
html/inc/user_util.inc
html/inc/util.inc
html/inc/util_basic.inc
html/user/account_ownership.php
html/user/create_account_form.php
html/user/create_profile.php
html/user/download_software.php
html/user/ffmail_form.php
html/user/get_project_config.php
html/user/join.php
html/user/login_token_lookup.php
html/user/logout.php
html/user/register.php
html/user/sample_index.php
html/user/signup.php
html/user/submit_example.php
html/user/team_create_action.php
html/user/validate_email_addr.php

Remove globals $master_url, $config, $g_config,
$recaptcha_public_key, and $recaptcha_private_key.
Add functions that return these.
There are still some globals but they're within one file. We can remove them later.
Fix small bug in batch display.

web: Remove some globals.  No functional change.

---

html/inc/app_types.inc

web: fix warning if 'buda_plan_classes' doesn't exist

---

html/user/manage_project.php

web: fix DB error (newer MySQL) when add user submit permission

---

set-client-version.py

This reverts commit c2fb32c76b00528275a656aa0f9f279bd18e6718, reversing changes made to 874837180c90465a98132145ebf2813e811e90ed.

Revert "Merge pull request #6322 from BOINC/vko_add_Final_Install-info.plist_to_the_version_update_script"

---

html/user/submit.php

... and don't hardwire the colors

web: tweak colors in batch display to work better for white mode

---

html/inc/recaptchalib.inc
html/inc/user_util.inc
html/user/account_ownership.php
html/user/create_account_form.php
html/user/create_profile.php
html/user/register.php
html/user/signup.php
html/user/team_create_action.php
html/user/team_create_form.php

when I changed recaptcha_public_key from a global to a function, I failed to change html/inc/recaptchalib.php.
That's because it's a .php file in inc/, so grep *.inc didn't see it. Change it to recaptchalib.inc

web: fix recaptcha bug

---

samples/docker_wrapper/docker_wrapper.cpp
samples/worker/worker.cpp

worker: generate a fraction done file (to test the above)

docker_wrapper: read fraction done from a file and report to client

---

html/user/buda.php
html/user/submit.php
samples/docker_wrapper/docker_wrapper.cpp
tools/create_work.cpp

- add the ability to edit a variant
- show counts of completed/in progress batches
- create_work: handle long (4KB) command lines.
- docker wrapper: print distro to stderr

BUDA enhancements

---

html/user/submit.php
html/user/submit_stats.php

Add batch commands to
- show hosts with the most error results
- show the most common exit codes
- show a graph of job durations

web (job submission): add batch features

---

html/inc/keywords.inc
html/inc/submit_db.inc
html/inc/submit_util.inc
html/user/submit.php

- allow mass retirement of aborted batches
- set completion time when abort batch
- add BoincBatch::delete_batch()
- add keywords for new Central projects

Web: job submit enhancements

---

client/pers_file_xfer.cpp
clientgui/ViewTransfers.cpp

Client, Manager: show project files as correct size, not 0

---

lib/hostinfo.cpp

Fixes [microsoft/vcpkg#47181](https://github.com/microsoft/vcpkg/issues/47181)

[lib] fix build on mingw 10
