BOINC/boinc

- py/Boinc/tools.py
- tools/make_project
- tools/upgrade
These scripts use the python mysqldb module, which is available only for Python 2.
To use Python 3 for these scripts, we'd need to find a new MySQL interface module,
and change our Python code to use it.
> Make the upgrade and make_project scripts work again.

- api/macglutfix.m
- clientscr/Mac_Saver_ModuleView.m
- mac_build/boinc.xcodeproj/project.pbxproj
- samples/example_app/MakeMacExample.sh
- samples/example_app/Makefile_mac
- samples/example_app/Makefile_mac2
- samples/example_app/ReadMe.txt
- samples/mac_build/UpperCase2.xcodeproj/project.pbxproj
his adds to my previous fixes (PR #3369) for the Macintosh BOINC screensaver running under OS 10.15 Catalina when built using Xcode 11. That PR solved problems with displaying graphics applications in the screensaver on Retina displays, but overlooked the same problem displaying project graphics apps in a window when invoked by the "Show graphics" button in the BOINC Manager.
This PR adds a fix for that issue. It also updates the graphics sample code in samples/example_app.
None of these problems occurred when building with earlier versions of Xcode or on versions of MacOS before OS 10.15 Catalina. These changes, along with my earlier ones, preserve proper operation when built with earlier Xcode or run on earlier versions of MacOS.
OpenGL / GLUT apps built under Xcode 11 apparently use …
> Mac fix gfx apps on xcode11

- clientgui/BOINCGUIApp.cpp
Adds a warning when manager's second instance is running.
Seriously?
"N/A"
> Added a warning when the manager detects a second copy of itself

- client/cs_scheduler.cpp
to match other scheduler operations (not sched_op_debug, as before)
Another tweak to #3402
> Client: place request_delay log flag under sched_ops control

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
Fix build warnings by adding the generic parameter to the `ArrayAdapter` declaration in `AcctMgrFragment` and disabling R8 in `gradle.properties`.
N/A
> [Android] Fix build warnings.

- android/BOINC/app/src/main/res/values/strings.xml
Change the tasks_result_files_downloading string from 'waiting for download' to 'downloading' for a more accurate message.
Display 'downloading' instead of 'waiting for download'.
> [Android] Change downloading string from 'waiting for download' to 'downloading'.

- m4/libcurl.m4
Checking for `-lssl` in `$LIBCURL` may not be enough to find where is the SSL lib
The test may fail with `cannot find -lssl` and `cannot find -lcrypto`
Add additional check if `$SSL_LIBS` can provide the SSL lib before moving on
Fixes #3591
In short libcurl link test may fail with `cannot find -lssl` and `cannot find -lcrypto`
`$SSL_LIBS` may have the proper `-L/...` so we add check for that
Note that it is impossible to fail `-lssl` test before and after this patch, the end result is libcurl assumes to have SSL support anyway.
If there's other ways, please comment.
N/A
> Add check for "-L/..." in "$SSL_LIBS"

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
Use Apache Commons IO's `CharSequenceReader` instead of `StringReader`, as the former supports all classes that implement the `CharSequence` interface.
N/A
> [Android] Replace StringReader with CharSequenceReader in RpcClient.

- samples/worker/Makefile
Without the $(CXX) the cross-compilation failed for OpenWrt ... in a very subtle manner that did cost me some time. I know, the worker is not needed for anything, but this should nonetheless just work.
> samples/worker: added install target, $(CXX)

- .travis.yml
- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountClasses.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/ErrorCodeDescription.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountInParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountManagerParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AccountOutParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AcctMgrInfoParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/AppVersionParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/GlobalPreferencesParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/GuiUrlParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/HostInfoParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/MessageParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/NoticeParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/PlatformInfoParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectConfigParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectInfoParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ResultParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TimePreferencesParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/TransferParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/WorkUnitParcelableTest.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/ErrorCodeDescriptionParcelableTest.kt
Add tests that use the Robolectric framework, to eliminate the need to set up an Android emulator for testing certain functionality.
N/A
**Note**
JaCoCo code coverage does not currently work for Robolectric tests: https://github.com/robolectric/robolectric/issues/3023
> [Android] Add Robolectric tests.

- api/macglutfix.m
- clientscr/Mac_Saver_ModuleView.m
- clientscr/ss_app.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/PostInstall.cpp
- mac_installer/uninstall.cpp
- samples/mac_build/UpperCase2.xcodeproj/project.pbxproj
* Restores Xcode project settings lost in commit _e091b98d07_ PR #3667
* Optimizes handling of graphics applications on Retina displays when built on Xcode 11 and run on OS 10.15 Catalina.
> Mac: clean up gfx changes from PR #3667

- m4/libcurl.m4
If "--with-libcurl" is passed, prefer using "curl-config" from directory instead of system provided
Really makes no sense not to do this
N/A
> Prefer curl-config from --with-libcurl

- api/macglutfix.m
- clientscr/Mac_Saver_ModuleView.m
- clientscr/ss_app.cpp
- samples/mac_build/UpperCase2.xcodeproj/project.pbxproj
Optimizes handling of graphics applications on Retina displays when built on Xcode 11 and run on OS 10.15 Catalina. My earlier code assumed that the problem (which I consider a bug in Apple's code) will continue on future versions of Xcode and OS X, and applied the workaround whenever built on Xcode 11 or later and run on OS 10.15 or later. This new approach is my attempt to future-proof the graphics apps and should work correctly whether or not Apple fixes the bug in the future.
Retina displays have 2X2 pixels per point. When OpenGL / GLUT apps built using Xcode 11 are run on a Retina display under OS 10.15, they fail to adjust their pixel dimensions to double the window size, and so fill only 1/4 of the window (display at half width and height.) They do correct this if resized resized …
> Mac: clean up gfx changes from PR #3666 (7.14 branch)

- db/boinc_db.cpp
Fixes race condition between transitoner and file_upload_handler, leading to following symptoms:
- The workunit have two results successfully uploaded, but it's "stuck" and not requested to validate;
- User are complaining "why it's not validating";
- Eventually, workunit will be validated when what-should-be a "no reply" timeout on one of results expires. which may be days or even weeks.
The problem is caused by incorrect value of transition_time of affected workunit. One of possible, but not limited to, sequences of events leading to race condition in standard scenario (min_quorum=2) is:
- Transitioner started processing a workunit which has one completed and one "in progress" result;
- Transitioner did a database scan and recorded that WU have one good …
> transitioner: Fix race condition with file_upload_handler

- android/BOINC/app/src/main/java/edu/berkeley/boinc/receiver/BOINCReceivers.kt
Add if conditions to check whether the `Intent` action strings match the expected ones, as this is recommended by Android Studio to prevent undesirable behavior which could be caused by a third-party `Intent`.
N/A
> [Android] Add checks for Intent action strings.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/EventLogActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ClientLogListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/PrefsSelectionDialogListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java
Make use of `ContextCompat`'s `getSystemService` method instead of directly calling `Context`'s `getSystemService` method, as the former calls `Context`'s `getSystemService(Class)` on Android Marshmallow and later and `getSystemService(String)` on versions of Android older than Marshmallow.
N/A
> [Android] Use ContextCompat to retrieve system services.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
- android/BOINC/app/src/test/java/edu/berkeley/boinc/client/MonitorTest.kt
Adds Robolectric tests for the Monitor class.
Note: Tests for methods that call the RPC XML parsers could not be added as Robolectric does not support them.
N/A
> [Android] Add some tests for Monitor.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/PersistentStorage.kt
Make use of the edit() extension function for `SharedPreferences` in `PersistentStorage` and remove the `commit = true` parameter from its usages in `AppPreferences`.
N/A
> [Android] Use asynchronous edit() extension function for SharedPreferences.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
Use the try-with resources language feature in the `installFile()` method of `Monitor`, as this eliminates the need to close the resources separately and ensures that they will be closed even if an exception is thrown.
N/A
> [Android] Use try-with resources in Monitor's installFile().

- .travis.yml
Fix a warning displayed during the CI process: `[warn] on jobs.include.jdk: unexpected sequence, using the first value (openjdk9)`
N/A
> [Travis] Fix JDK warning.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/AccountManagerClasses.kt
This changes the constant values in the `Fields` class of `AcctMgrInfo` to those of the tags in the XML returned by the BOINC client, so that the XML can be parsed correctly.
If an account manager is used, it will be displayed properly.
> [Android] Fix issue preventing an account manager being displayed.

- client/hostinfo_unix.cpp
Drop X11 fallback as Wayland can show a desktop session with no X11 servers, but XWayland can be started temporarily (and is useless for idle detection).
This reduces the occurrence of #2256 but is not a full fix.
This makes Xorg idle detection much more predicable which might help debug the random Xorg related failures (or potentially be the cause).
See #3153. 
Xorg idle detection now requires X to properly set files in /tmp/.X11-unix/.  This should reduce log noise and help prepare for a Wayland future.
> Drop X11 fallback 

- client/app.h
- client/cs_prefs.cpp
- client/gui_rpc_server_ops.cpp
- client/project.cpp
- lib/filesys.cpp
- lib/filesys.h
- lib/gui_rpc_client_print.cpp
Fixes #3706 
Tested on Win and Linux, though not on compressed FS.
-------------------
On filesystems that use compression, the disk space allocated to a file
is generally less than the (logical) size of the file.
In this case, the client can fail to get work
because it thinks there's insufficient disk space.
Fix: change things so that the client measures disk usage
(per-project and total) in terms of allocated space rather than file size.
But still use logical file sizes in two places:
- in checking that downloaded files are the right size
- in calculating a job's disk usage to see if it exceeds
the project-specified limit.
New functions: file_size_alloc() and dir_size_alloc().
These are like file_size() and dir_size() except they return
allocated rather than logical size.
>  Client: measure disk usage in terms of allocated disk space, not file size

- client/rr_sim.cpp
Suppose we have 1 CPU and have (only) a GPU job that takes 1 CPU.
If GPU computing is suspended we won't fetch GPU work,
because the RR simulation doesn't take "suspended" into account.
Solution: in the RR simulation, if GPU computing is suspended,
act like GPU jobs don't use any CPU.
Seems like this should work though there may be unintended consequences.
Addresses #3679
> client: avoid CPU starvation when GPU computing is suspended

- android/BOINC/.idea/misc.xml
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/AcctMgrFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ManualUrlInputFragment.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsIsOnlineTest.kt
Add an extension property for `ConnectivityManager` to determine if the device is currently online and alter the existing code to make use of this. This is so that the mechanism to determine if the device is online can also be used in any future code.
N/A
> [Android] Add extension property to determine if the device is online.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt
This fixes an issue that resulted in `ProjectInfoParser` not parsing the project image URL.
The project logo now shows up in the project info dialog.
> [Android] Fix image download issue in ProjectInfoFragment.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TasksListAdapter.java
This alters the display of the task progress percentage to use upto 3 decimal places instead of just 1, to match the desktop client.
Task progress is displayed up to 3 decimal places instead of 1.
> [Android] Display task progress in a percentage of upto 3 decimal places.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
Simplify an if condition in `NavDrawerListAdapter` by using `StringUtils`' `isEmpty` method.
N/A
> [Android] Use StringUtils.isEmpty() in NavDrawerListAdapter.

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/glide/ScaleBitmapBy2.kt
- android/BOINC/app/src/main/res/layout/attach_project_info_layout.xml
Make use of [Glide](https://github.com/bumptech/glide) to handle loading the project logos in `ProjectInfoFragment` instead of handling it manually, as the library supports caching and requires much less code.
* The project logos displayed in the dialog shown when a project is selected in the selection screen are now cached locally to reduce network bandwidth usage.
* A placeholder image (the BOINC logo) is displayed for projects that do not have a logo or until the actual project logo has been downloaded.
> [Android] Use Glide to handle image loading in ProjectInfoFragment.

- android/BOINC/app/build.gradle
Remove the unused `packagingOptions` configuration from `app/build.gradle`.
N/A
> [Android] Remove unused packagingOptions configuration.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
Use the `ArraySet` class included in AndroidX Collections instead of `ArrayList` in `getSlideshowForProject()`, as this eliminates the need for a call to `contains`.
N/A
> [Android] Use ArraySet instead of ArrayList in ClientStatus' getSlideshowForProject().

- client/boinc_cmd.cpp
- client/boinc_log.cpp
- client/gui_rpc_server.cpp
- clientgui/BOINCBaseFrame.cpp
- clientgui/BOINCBaseFrame.h
- clientgui/BOINCClientManager.cpp
- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientscr/gfx_cleanup.mm
- clientscr/mac_saver_module.cpp
- lib/common_defs.h
- lib/gui_rpc_client.cpp
- lib/gui_rpc_client.h
If the GUI RPC file exists and is empty,
create a random password and write it to the file.
Running with an empty password is a security risk.
It means anyone on the same machine can control the client,
e.g. attach it to an arbitrary project.
> Client: don't allow empty GUI RPC password

- lib/gui_rpc_client_print.cpp
Add elapsed time to task info for boinccmd.
Fixes #3463 
Prints the current elapsed time of a task (RESULT), if it is still running. The property was already available to the RESULT struct.
Added elapsed time to boinc-cmd task information.
> [Client] Add Elapsed Time

- client/Makefile.am
Split off from #3665
That one is getting too big and is more a feature change PR now
Will remove this change in that PR
Add `EXTRA_boinc_client_DEPENDENCIES =` to ensure `libwhet*.a` are built before linking with boinc_client
This fixes the issue when building with Automake 1.16.1 where generated `boinc/client/Makefile` yields:
`all-am: Makefile $(PROGRAMS) $(LIBRARIES) all-local`
instead of the output from Automake 1.15.1 and earlier:
`all-am: Makefile $(LIBRARIES) $(PROGRAMS) all-local`
This is only a bug fix for building 32bit ARM Android client and does not change BOINC workings
N/A
> Fix 32bit ARM Android build in Automake 1.16.1

- client/client_state.h
- client/cs_notice.cpp
- client/cs_notice.h
- client/project.cpp
On startup the client sees, for each project,
whether it's barred from using particular resources (CPU, GPU).
It was showing these situations as notices.
I think the idea was to make sure the user hadn't changed
a setting and forgotten about it.
But this was annoying overkill.
Instead, just show startup messages (not notices)
saying what (project, resource) pairs are disallowed, and wy.
Fixes #3590 (subject to review - RH 28 May)
> client: don't show "no work" messages as notices

- android/build_all.sh
Remove exit from script:
I think it not good thing that there is an `exit` in the end of the script. It never has, and also it will be exit if you in another window.
> [Android] [Scripts] Remove exit from script

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
Use `FileUtils`' `copyInputStreamToFile` method to simplify `installFile`, as it handles the directory creation, overwrites the destination file if it already exists and closes the `InputStream` afterwards.
N/A
> [Android] Simplify installFile() using FileUtils.copyInputStreamToFile().

- client/main.cpp
- clientgui/AccountInfoPage.cpp
- clientgui/AccountManagerInfoPage.cpp
- clientgui/MainDocument.cpp
- lib/diagnostics.cpp
- lib/diagnostics.h
In VS2019, making CRT calls like printf after main.cpp() has returned
raises and exception.  Don't do this.
Also, there were some runtime warnings from WxWidgets about bad flags
for vertical spacers.  Fix these.
> Client and manager, Win: fix crashes and runtime warnings with VS2019

- android/BOINC/app/src/main/res/values-en/strings.xml
Correct the unit in `prefs_disk_min_free_gb_header` to GB from MB.
Display the unit of the minimum storage setting as GB instead of MB.
> [Android] Correct string unit to GB.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectAttachService.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientInterfaceImplementation.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/DeviceStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/PersistentStorage.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/di/AppComponent.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/DeviceStatusData.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/client/MonitorTest.kt
Initialize more class variables, such as `Monitor`'s `clientStatus`, `deviceStatus` and `noticeNotification` variables, using dependency injection, as this removes the need to implement the singleton pattern for these variables separately.
N/A
> [Android] Initialize more variables using dependency injection.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCApplication.kt
Fix a crash that occurs on API levels lower than 21 (Lollipop) due to the use of vector drawables in the app.
Fix the app crashing on Android versions older than Lollipop.
> [Android] Fix crash on API levels < 21.

- android/BOINC/app/src/main/res/values/styles.xml
For Tablet and Android TV: (For landscape view). 
Set action menu text color to white.
Screenshot will be in the next posts.
> [Android] Fix: Set action menu text color to white.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.java
Correct the if condition in `computeMd5` to prevent a blank MD5 hash string from being returned, which causes the app to be unable to start.
N/A
> [Android] Fix DigestUtils usage to prevent a blank MD5 hash being returned.

- tools/update_versions
BOINC client correctly handles subdirectories when downloading application files, however, update_versions expects directories to have a signature files, which is impossible.
This change skips signature check for directories and independently processes files in subdirectories denoted in the version.xml file. Files deployed to the download dir preserve directory structure.
Add subdirectory support for application versions.
> Add subdirectory support to update_versions

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
Use hardcoded boolean values as defined in `configuration.xml` instead of retrieving them using the `resources` property.
Selecting a check box option after switching between themes should no longer cause a crash.
> [Android] Fix possible crash when selecting a check box after switching between themes.

- android/build_boinc_arm.sh
- client/Makefile.am
Remove neon optimization from arm, to support old devices (android 4.4 Kitkat, api 19)
Our arm compiler compile the code with neon optimization by default:
```bash
./boinc/3rdParty/buildCache/android-tc/arm/bin/arm-linux-androideabi-clang -E -dM - < /dev/null | grep -i neon
```
```c++
#define ARM_NEON 1
#define ARM_NEON_FP 0x4
#define ARM_NEON 1
```
This information brought to me by @truboxl.
I also verify it in different way.
The global flag: ` -mfpu=vfpv3-d16` disable neon optimization.
There was conflict with neon benchmark module that I solve.
Running on AVD 4.4:
> [Android] Remove neon optimization from arm.

- android/BOINC/app/src/main/AndroidManifest.xml
Fix a crash by using the `AppCompat.Dialog` theme for `BoincNotExclusiveDialog`.
Fix a crash that occurs when displaying the "Volunteer computing app detected" dialog.
> [Android] Use AppCompat theme for BoincNotExclusiveDialog.

- android/BOINC/app/src/main/res/layout/attach_project_batch_conflicts_listitem.xml
Fix bug that status image always black.
Now the image is black / white according to theme.
> [Android] Fix bug that status image always black.

- clientgui/msw/taskbarex.cpp
lstrcpyn takes size of buffer in *characters*, not in bytes as last argument. If Unicode version of the function is used, `sizeof(buffer)` returns twice as much buffer size than expected by the function. And it may lead to out of buffer write.
See https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lstrcpynw#security-warning: 
"If the buffer pointed to by lpString1 is not large enough to contain the copied string, a buffer overrun can occur. When copying an entire string, note that sizeof returns the number of bytes. For example, if lpString1 points to a buffer szString1 which is declared as TCHAR szString[100], then sizeof(szString1) gives the size of the buffer in bytes rather than WCHAR, which could lead to a buffer overflow for the …
> ClientGui: Fix potential buffer overflow in lstrcpyn

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCApplication.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt
- android/BOINC/app/src/main/res/values-v29/arrays.xml
- android/BOINC/app/src/main/res/values/arrays.xml
- android/BOINC/app/src/main/res/values/strings.xml
- android/BOINC/app/src/main/res/xml/root_preferences.xml
* Remove the "Set by Battery Saver" option on Android versions < Q.
* Set the light theme as default for consistency between Android Q and Android versions < Q.
* Remove the "Set by Battery Saver" option on Android versions < Q.
* Set the light theme as default.
> [Android] Set light theme as default and remove "Set by Battery Saver" option.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
Fix an issue that causes the app to stop visibly responding to events after turning the screen off and then on again.
N/A
> [Android] Fix issue that causes app to stop updating after turning the screen off.

- m4/boinc_platform.m4
Some compiled clients may appear as `$ARCH-unknown-linux-android` instead of
`$ARCH-android-linux-gnu` to project servers
This is because of Android NDK specifies `$ARCH-linux-android` triplets and
users forget to specify `--with-boinc-platform`
Fix this in `boinc_platform.m4` so that Android boinc platform strings changes are not needed across all projects
boinc_alt_platform is excluded to prepare for 64bit only Android devices
Users can add back requesting 32bit tasks with `--with-boinc-alt-platform` during compile or `<alt_platform>` during runtime
Feedbacks are welcome.
N/A
> Fix boinc platform strings for Android

- android/BOINC/app/src/test/java/edu/berkeley/boinc/utils/BOINCUtilsIsOnlineTest.kt
Update the test for the `isOnline` extension property for Android versions below Marshmallow to run on Android 4.1 (Jelly Bean) and above.
N/A
> [Android] Update isOnline test for Android versions below Marshmallow.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
- android/BOINC/app/src/main/res/xml/root_preferences.xml
Fixes #
Set the default value of the `maxRamUsedIdleFrac` shared property to 50 and divide it by 100 when assigning it to `ramMaxUsedIdleFrac`.
The "RAM limit" setting should now work as expected.
> [Android] Correct the way in which the value of ramMaxUsedIdleFrac is assigned.

- api/reduce_lib.cpp
- client/boinc_cmd.cpp
- lib/gui_rpc_client_ops.cpp
list of changes:
* api/reduce_lib.cpp:188:10: warning: declaration of 'h' shadows a previous local
* lib/gui_rpc_client_ops.cpp:1479:42: warning: clearing an object of non-trivial type 'struct VERSION_INFO'
* client/boinc_cmd.cpp:434:32: warning: clearing an object of non-trivial type 'class HOST_INFO'
> fix some gcc warnings

- android/BOINC/app/src/main/res/layout/projects_layout_listitem.xml
Make the text black.
No change in light mode.
Before the fix in Android TV:
> [Android] Fix white text on yellow warning in dark mode.

- android/buildAndroidBOINC-CI.sh
- android/build_curl_arm.sh
- android/build_curl_arm64.sh
- android/build_curl_x86.sh
- android/build_curl_x86_64.sh
- android/build_openssl_arm.sh
- android/build_openssl_arm64.sh
- android/build_openssl_x86.sh
- android/build_openssl_x86_64.sh
Before the fix: 
If you stop the compilation process in middle of curl or openssl, when next time you compile, it will think you already
compile curl or openssl, and skip it, and try to compile boinc without the libs.
This fix: 
Create the touch files after it finish all compilation process of curl or openssl.
> [Android][Scripts] Fix touch files.

- android/BOINC/app/src/main/res/layout/attach_project_acct_mgr_dialog.xml
- android/BOINC/app/src/main/res/layout/attach_project_batch_conflicts_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_batch_conflicts_listitem.xml
- android/BOINC/app/src/main/res/layout/attach_project_batch_processing_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_credential_input_dialog.xml
- android/BOINC/app/src/main/res/layout/attach_project_credential_input_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_hint_contribution_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_hint_projectwebsite_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_info_layout.xml
- android/BOINC/app/src/main/res/layout/attach_project_manual_url_input_dialog.xml
- android/BOINC/app/src/main/res/layout/dialog_about.xml
- android/BOINC/app/src/main/res/layout/dialog_confirm.xml
- android/BOINC/app/src/main/res/layout/event_log_client_list_item_layout.xml
- android/BOINC/app/src/main/res/layout/project_details_layout.xml
- android/BOINC/app/src/main/res/layout/projects_layout_listitem.xml
- android/BOINC/app/src/main/res/layout/status_layout.xml
- android/BOINC/app/src/main/res/layout/tasks_layout_list_item.xml
Make use of XML attributes that provide RTL support, such as `layout_marginEnd`.
Also add missing XML attributes that support API level 16 (Android 4.1), such as `layout_alignParentLeft`.
RTL layouts should now be improved.
> [Android] Add XML attributes that provide RTL layout support.

- .gitignore
- .travis.yml
- android/buildAndroidBOINC-CI.sh
- android/build_boinc_arm.sh
- android/build_boinc_arm64.sh
- android/build_boinc_x86.sh
- android/build_boinc_x86_64.sh
- android/build_curl_arm.sh
- android/build_curl_arm64.sh
- android/build_curl_x86.sh
- android/build_curl_x86_64.sh
- android/build_openssl_arm.sh
- android/build_openssl_arm64.sh
- android/build_openssl_x86.sh
- android/build_openssl_x86_64.sh
- android/travis_build_all.sh
Important: Please delete the old ndk zip in tmp folder before you try local:
`rm -rf /tmp/ndk.zip`
Upgrade android scripts to ndk r-21d.
Remove toolchain. deprecated in ndk21.
> [Android][Scripts] Upgrade android scripts to ndk r-21d

- client/gpu_nvidia.cpp
I guess we thought these would never exceed 99, but they do.
This is a temp workaround.
Fixes #3893
> When parsing NVIDIA driver version, max minor version with 99.

- .travis.yml
- android/BOINC/build.gradle
- android/BOINC/gradle/wrapper/gradle-wrapper.properties
Update the Android Gradle plugin to 4.1 beta 2, which includes a fix for the Java 8 API desugar warnings: https://issuetracker.google.com/issues/155423440
N/A
> [Android] Update Android Gradle plugin to 4.1 beta 2.

- drupal/sites/default/boinc/modules/boinccore/boinccore.module
* The original commit df966c74 fixed the goto/pagination for admins/mods but broke it for regular users
* We need to handle *both* user groups differently (i.e. conditionally include hidden comments)
N/A
> Drupal: fixed regression in df966c74

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/SelectionListActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorExtensions.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt
* Replace `supportInvalidateOptionsMenu()` with `invalidateOptionsMenu()`.
* Suppress deprecation warnings for methods needed on older versions of Android, such as `getActiveNetworkInfo()`.
* Suppress unused variable warnings for methods that are assigned via the `onClick` XML attribute.
N/A
> [Android] Suppress warnings displayed during compilation.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt
Correct the key of the notification preference defined in `root_preference.xml` to match the one checked in `SettingsFragment`.
The notification setting should now work properly.
> [Android] Fix notification preference.

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/ui/eventlog/EventLogClientFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/ui/eventlog/EventLogGuiFragment.java
- android/BOINC/app/src/main/res/layout/event_log_client_layout.xml
- android/BOINC/app/src/main/res/layout/event_log_gui_layout.xml
Use `SwipeRefreshLayout` instead of `LinearLayout` as the parent layout in the event log fragments and implement the corresponding refresh functionality.
The event log can now be refreshed using a swipe gesture.
**Video**
> [Android] Use SwipeRefreshLayout in event log fragments.

- client/gui_rpc_server.cpp
- client/gui_rpc_server.h
Instead of binding to INADDR_ANY as soon as remote_hosts.cfg exists,
only do so if the file actually contains at least one host. Prior to
this change, boinc client would bind to INADDR_ANY even if
--allow_remote_gui_rpc was *not* given and the remote_hosts.cfg
does *not* contain any hosts (but exists). This behavior is not
sensible, because in that case no client would be allowed to connect
eventually.
Furthermore, many distributions ship an example remote_hosts.cfg as
part of their boinc client package. And the previous behavior caused
boinc client to bind on INADDR_ANY, opening a remotely accessible port
per default.
To tighten security further, boinc client will now only
bind to localhost even if remote-hosts.cfg exists, but there are no
remote hosts configured witin that file. …
> GUI RPC: bind to INADDR_ANY if a remote host is actually configured

- client/acct_mgr.cpp
- clientgui/DlgItemProperties.cpp
Also: fix WxWidgets runtime warnings about spacers.
Possibly fixes #3877
> Client: if AM reply includes a project we're attached to under a different account,  honor the params in the AM reply, e.g resource share.

- lib/app_ipc.cpp
- lib/app_ipc.h
- samples/wrapper/wrapper.cpp
The user can specify 3 priority-related prefs in cc_config.h:
bool no_priority_change
int process_priority
int process_priority_special
Wrappers should honor these prefs,
but currently they don't have access to them.
Pass them in the APP_INIT_DATA structure.
Modify wrapper.cpp to use these prefs if they exist;
this overrides the priority specified in the job file, if any.
Fixes #
> Pass user priority config items to wrappers

- html/inc/submit.inc
- html/user/submit_rpc_handler.php
- html/user/submit_test.php
- lib/submit_api.py
- tools/create_work.cpp
Remote job submission was always using allocation-based prioritization.
This is not necessarily the right thing.
For example, nanoHUB submits batches of jobs that are mixtures
of speculative and user-submitted;
these simply need to be given low and high priorities.
The way things work now:
- if you want allocation-based prioritization,
set the "allocation_priority" flag in the request object
(Python or PHP API)
- or set the "priority" field in the request object;
that sets the priority of all the jobs in the batch
- or set the "priority" field of jobs in the batch.
Updated wiki docs accordingly.
Also fixed a bug in the test script
(note to self: adding an object to an array adds a reference, not a copy).
Fixes #
> Add priority options to remote job submission

- clientgui/AdvancedFrame.cpp
Fixes #3934 
Removed the pre-processor directives that stopped the loading of the EVT_MENU_OPEN event. This means that `CAdvancedFrame::OnMenuOpening()` will be executed as an event as expected on all platforms and hence prevent particular menu functionality from being accessed when the client is shut down.
Changes affect the BOINC manager.
Adding appropriate code to shutting down and then connecting to a client was one alternative.
Options are now greyed-out when the BOINC client is shutdown on Microsoft Windows.
> Added EVT_MENU_OPEN to the event table for Windows - Fixes #3934

- api/graphics2_unix.cpp
- api/macglutfix.m
- api/x_opengl.h
Enable close button in project graphics run by _BOINC Manager_ `Show Graphics` under MacOS 11 Big Sur.
**This is an urgent fix**, since I expect that MacOS 11, which is well into beta testing, will be released soon. **All projects should relink their graphics applications with this updated library code as soon as possible.**
When a user presses the `Show graphics` button in the _BOINC Manager_, the project graphics application is run for the selected task. On the Macintosh, the graphics app runs as a free standing process, without a functioning menu bar, so the usual way to shut it is to use the red close button at the top left corner of the application's window. But under MacOS 11 Big Sur, that button is disabled. 
There is a workaround: the user can control-click (or right-click) on the …
> Mac: Enable close button in project graphics run by BOINC Manager "Show Graphics"

- clientscr/gfx_switcher.cpp
- clientscr/screensaver.cpp
These changes are necessary for the BOINC screensaver controller to run on MacOS 11 Big Sur. I have tested this code on OS 10.13 High Sierra, OS 10.15 Catalina and OS 11.0 Beta 4 Big Sur. This PR is ready to merge needs to be included in the next release of BOINC for the Macintosh.
> Mac: FIx screensaver coordinator to run properly under Mac OS 11 Big Sur

- sched/script_validator.cpp
You need to supply at least one (init or compare)
but you don't have to supply both.
Fixes #3953
> script_validator: make scripts optional.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
Use Okio's `BufferedSource` and `BufferedSink` classes to handle RPC communication instead of using the raw `InputStream` and `OutputStreamWriter`, due to providing many advantages over the standard Java IO APIs: https://jakewharton.com/a-few-ok-libraries/.
N/A
> [Android] Use Okio to handle RPC.

- configure.ac
The Linux-specific <sys/sysctl.h> header and the sysctl function have been deprecated in glibc v2.30.
> exclude sysctl.h in linux

- client/app.h
- client/app_start.cpp
- client/client_state.cpp
- client/client_state.h
- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientgui/ViewWork.cpp
- clientgui/sg_BoincSimpleFrame.cpp
- clientgui/sg_TaskCommandPopup.cpp
This is an important feature in preparation for the imminent release of MacOS 11 Big Sur, and complements PR #3964 by providing another workaround. As explained in that PR:
> When a user presses the Show graphics button in the _BOINC Manager_, the project graphics application is run for the selected task. On the Macintosh, the graphics app runs as a free standing process, without a functioning menu bar, so the usual way to shut it is to use the red close button at the top left corner of the application's window. But under MacOS 11 Big Sur, that button is disabled.
Until projects relink their graphics apps with the new code from #3964, when a user clicks the _Show graphics_ button, the only way to stop the graphics app will be by a control-click (or right-click) on the graphics app's icon …
> Manager: change  "Show graphics" button to "Stop graphics" when gfx running

- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
Remove:
* `w: boinc\android\BOINC\app\src\main\java\edu\berkeley\boinc\attach\BatchProcessingActivity.kt: (137, 29): 'FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET: Int' is deprecated. Deprecated in Java`
Solution from:
https://stackoverflow.com/questions/33179042/i-tried-using-this-flag-in-setflags-from-tutorial-but-its-deprecated-what-do-i
* `w: boinc\android\BOINC\app\src\main\java\edu\berkeley\boinc\client\Monitor.kt: (340, 25): Condition 'state == null' is always 'false'` warning.
Add check to state if it null. if yes, write to log. and continue as before this change.
> [Android] Remove warnings in compilation time.

- clientscr/mac_saver_module.cpp
Mac: restore updated error message lost by my commit fcbdcc75b7 (which was from PR# 3631)
In my PR #3369, I had changed this error message from  `Screenaver of application <name>  is not compatible with this version of OS X. `
to `Could not connect to screensaver of application  <name>.`
Somehow that part of PR #3669 was lost / reversed in my more recent PR #3631. This corrects that.
> Mac: restore updated error message lost by my commit fcbdcc75b7

- clientgui/AdvancedFrame.cpp
Fixes #3933
The "shutdown connected client" modal will not show ever again if you check the "do not show this dialog again" box provided.
This fix only fixes the non-persistence issue and does not allow the user to make the modal appear once again and hence reverse their check of the box.
For future changes, people may want to be able to re-enable the modal and a setting being placed in the options was considered but not followed through.
The shutdown client dialog will no longer appear after checking the "don't show this dialog again" checkbox
> [Manager] Stopped shutdown client dialog from showing when told not to

- 3rdParty/vcpkg_ports/ports/rappture/CMakeLists.txt
- client/client_state.cpp
- client/gui_rpc_server_ops.cpp
- clientgui/AccountInfoPage.cpp
- clientgui/ProjectWelcomePage.cpp
- clientgui/WizardAttach.cpp
- clientsetup/win/CACreateProjectInitFile.cpp
- lib/gui_rpc_client_ops.cpp
- lib/project_init.cpp
- lib/project_init.h
- win_build/boinc_ss_vs2019.vcxproj
- win_build/boinccas_vs2019.vcxproj
- win_build/slide_show_vs2019.vcxproj
- win_build/uc2_graphics_vs2019.vcxproj
- win_build/wrappture_example_vs2019.vcxproj
When a client and manager start up and there are no projects attached,
the client checks for a project_info.xml and passes its into to the manager.
If the file has both a project URL and an account key,
the manager tells the client to attach that project, and that's it.
If the file has URL but no account key, the manager puts up a "Welcome page".
The idea is to notify the user of what they're about to sign up for.
If the user clicks Next, they go to the name/password dialog.
Both of these cases work now.
The <name> element in project_info.xml is required.
I had to do a bit more work to make things work right when the user cancels
out of the welcome page, then adds a project the usual way.
This part of Manager is convoluted.
Big chunks of it should be deleted, the Welcome page among them. …
> Manager: clean up "Welcome page"

- client/switcher.cpp
this fixes a build failure on Linux/Debian systems where mac/* directory is stripped from the source tarball.
> Update switcher.cpp to include mac_spawn only if the system is APPLE

- client/app_start.cpp
- lib/cc_config.cpp
- lib/cc_config.h
- lib/common_defs.h
- lib/proc_control.cpp
- samples/wrapper/wrapper.cpp
It turns out we have two different encodings of process priority:
1) specified in cc_config.xml and used by the client: 0 (low) to 4 (high)
2) specified in job.xml and used by the wrapper: 1 (low) to 5 (high).
This didn't cause any problems until recently when I added code
to pass the cc_config.xml info to the wrapper;
it was interpreting it on the 1-5 scale.
Fix: have the wrapper convert it (add one).
Also: I forgot to have the client actually put the priority into
in the app_init_data.xml file.
> client and wrapper: fix process priority mismatch

- clientgui/DlgOptions.cpp
- clientgui/DlgOptions.h
Fixes #3968
Adds an additional checkbox to the 'Other options' dialog, to restore display of the 'Shut down connected client' confirmation dialog.
Added option to restore display of 'shutdown client' confirmation.
**Testing status**
Built and tested locally in Windows VS2013/x64
Will test again, plus Linux version, from CI versions.
**Other notes**
Linux repo managers who remove the 'Shutdown connected client' menu item may wish to remove this control as well.
> Manager: Add option to restore 'shutdown client' confirmation.

- configure.ac
Fixes: unreported issue
Add test to check value of `no_x` to prevent undesired inclusion of libXss, even if present. The **AC_PATH_X** macro sets the shell variable `no_x` to 'yes' if the user gave the command line option `--without-x`, so this must be respected for the screensaver idle detection. However, since the macro sets `no_x` to the same value if the X Window System include files and libraries cannot be located, provide build warning to assist with debugging.
- Place test for value of `no_x` at line 628 (`if test "X${no_x}" != "Xyes" -a "$enable_xss" = yes; then`) . This would silently disable the X ScreenSaver user idle detection, whether or not that is what the user desired (i.e., didn't supply `--without-x`, but X libraries …
> configure.ac: Fix have_xss test to respect --without-x

- db/constraints.sql
- db/schema.sql
Change all tables to InnoDB, which now supports fulltext indices.
Fixes #3976
> Make DB work with MySQL 8.0

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
Add a check to ensure that the first navigation bar item is retrieved if the target fragment ID is -1.
The `onNewIntent` warning in the event log should no longer appear.
> [Android] Fix onNewIntent() warning in the event log.

- android/BOINC/app/src/main/AndroidManifest.xml
Remove the Ouya category from the Android manifest, as Ouya services were [shut down in June 2019](https://www.theverge.com/2019/5/22/18635800/razer-ouya-kickstarter-gaming-service-shutting-down-june-25).
Drop Ouya support.
> [Android] Remove Ouya category.

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCApplication.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java
- android/BOINC/app/src/main/res/values-en/strings.xml
- android/BOINC/app/src/main/res/values/strings.xml
Create a separate notification channel for notices, so that users can choose to disable notice notifications if they wish.
Notice notifications can now be disabled separately on Android Oreo and higher.
> [Android] Create separate notification channel for notices.

- html/inc/result.inc
Workunit pages already have a hook to display project-specific data for a workunit, but result pages lack such functionality. This change adds a similar hook to the result pages.
Add a hook to easily specify project-specific information in the result pages.
> Add a project-customizable hook to result pages

- sched/file_upload_handler.cpp
Currently file_upload_handler stops accepting new uploads when there is less than 1MB free disk space. That is too late as multiple concurrent writes can hit the disk limits, so increasing this limit to 1GB and making it configurable instead of using a hardcoded constant.
Could also read from config file, but this would entail more disk accesses where they aren't really needed.
Make file_upload_handler stop accepting uploads early when low disk space
> Make file_upload_handler stop early when low disk space

- html/inc/util_ops.inc
- tools/manage_privileges
For newer MySQLs, need to specify values for all fields
Fixes #4045
Fixes #4035
> manage_privileges, badge_assign.php: fix DB inserts

- html/user/submit_rpc_handler.php
- lib/submit_api.py
- tools/submit_api_test.py
Newer versions of MySQL error out if you don't.
Fixes #4029
> remote job submission: specify all fields on batch creation.

- py/Boinc/add_util.py
- py/Boinc/boincxml.py
- py/Boinc/configxml.py
- py/Boinc/db_base.py
- py/Boinc/projectxml.py
- py/Boinc/setup_project.py
- py/Boinc/tools.py
- sched/pymw_assimilator.py
- sched/start
- tools/check_project
- tools/make_project
- tools/upgrade
You have to install mysqlclient for python3;
that has the same interface as mysqldb, which we used with python2.
The scripts don't work with python2.
> Change python scripts to use python3.

- lib/submit_api.py
Fixes #
Changed print command formatting to work with python 3
> updated print to work with python 3

- clientgui/msw/taskbarex.cpp
- clientgui/msw/taskbarex.h
This issue affects only Windows 8.1/10 x64 built with VS2013 and VS2019.
The reason is a different memory addressing on these OSs in pure 64-bit mode.
This fixes #4072.
> [Windows] Fix Window create function on x64.

- mac_build/buildopenssl.sh
Adapts code I found in the OpenSSL GitHub project to correctly build OpenSSL for BOINC as a Universal 2 binary containing code for both Intel (x86_64) and the coming new Apple Silicon (arm64) Macs. This is a more reliable implementation the the one I made as part of #3956, since it patches an openSSL configuration file to match a change by an OpenSSL project developer.
> Update OpenSSL build script to build arm64 and x86_64 Universal binary

- client/switcher.cpp
… to be quoted to allow for spaces in branded screensaver names
Fixes #
switcher.cpp sets up the command line used for boinc_ss_helper.sh on macOS Catalina or newer. The screensaver name is added to the commandline without quotes so if a branded screensaver name has spaces the parameters are off and the project specific graphics will not launch.
A better approach would probably be to not allow branded screensaver names to have spaces but this is a bigger change and should be done for a future version.
NA
> MACOS Bug Fix: Modify the screen saver name parameter passed to boinc_ss_helper.sh..

- m4/ax_check_gl.m4
- m4/ax_check_glu.m4
- m4/ax_check_glut.m4
- m4/check_ssl.m4
Fixes #4095
This commit removes the superfluous hard-coded injection of `-L/usr` and `-L/usr/lib` into the command line.
The resulting build system has been tested with
* Clang + LLD
* gcc + ld.bfd
* gcc + ld.gold
BOINC fails to link with LLD because of /usr/lib in the link command line.
LLD does not continue to search for the correct library, once it finds one that doesn't fit. This is made by design and will not change.
See also : https://bugs.gentoo.org/732024
The reason for LLD failing is, that its build system puts `-L/usr` and `-L/usr/lib` into the command line options. While these are not neccessary at all, they cause LLD to find 32bit libraries on 64bit systems first. As these 32bit libraries can not be used, LLD errors out.
Bug: #4095
Signed-off-by: …
> Remove */lib paths from m4 (Issue #4095: boinc fails to link with LLD)

- py/Boinc/db_mid.py
No associated issue ID.
This PR fixes a bug in the string formatting for the representation of `front_Host` (an incompatible number of placeholders `%s` and substitution variables supplied, namely 2 and 3).
The one-line change is quite straightforward.
N/A
N/A
> Fix bug in number of placeholders in repr formatting for `front_Host`

- client/scripts/boinc-client.service.in
This fixes part of an issue described in #3715 - confirmed to help.
Systemd unit file - allowed access to /tmp/ to keep X11 idle detection working
> Unblock x11 idle detection

- configure.ac
Fixes #3501 and #2600
Add check for libcurl when building for server
Block early rather than fail after a long time of compile when libcurl is not supplied
`lib/remote_submit.cpp` needs `curl/curl.h`
https://github.com/BOINC/boinc/blob/faf272ff362cd9fc22bba5d2cbd4f57ff374364c/lib/remote_submit.cpp#L24
`lib/remote_submit.cpp` is built when building in `tools` folder
https://github.com/BOINC/boinc/blob/faf272ff362cd9fc22bba5d2cbd4f57ff374364c/tools/Makefile.am#L61
which is only built when ENABLE_SERVER
https://github.com/BOINC/boinc/blob/faf272ff362cd9fc22bba5d2cbd4f57ff374364c/Makefile.am#L25-L28
ENABLE_SERVER is checked here
https://github.com/BOINC/boinc/blob/faf272ff362cd9fc22bba5d2cbd4f57ff374364c/configure.ac#L1065
N/A
**Release …
> Add check for libcurl when building for server

- clientgui/mac/SetVersion.cpp
- clientgui/mac/templates/BoincCmd-Info.plist
- clientscr/Mac_Saver_ModuleView.m
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/release_boinc.sh
Mac: 
* Fix command-line (stand-alone) version for newer MacOS versions so Apple will "notarize" it. Otherwise newer versions of MacOS will refer to run it.
* Code-sign command-line executables
* Add info.plist file with identifier to boinccmd
* Package as DMG (disk image) file instead of Zip file
* Set minimum MacOS version to OS 10.9 to eliminate most warnings from Xcode version 12.2.
* Fix a problem running BOINC screensaver on MacOS 11 Big Sur when built with Xcode version earlier than Xcode 11.
> Mac: improvements for Xcode 12 and MacOS 11 Big Sur

- client/acct_mgr.cpp
- client/boinc_cmd.cpp
- client/gui_rpc_server.cpp
- client/switcher.cpp
- lib/common_defs.h
- lib/gui_rpc_client.cpp
boinccmd: show alert messages after attach RPCs
PR #3709 disallowed empty GUI RPC password files.
This increased security on shared machines.
But it meant that on Linux, after installing BOINC as a package,
the user had to locate and change the protection
and/or the ownership of the password file, which is undesirable.
This change allows empty password files but tells the user
that they should think about the security implications.
With the Manager this is delivered as a notice.
With boinccmd the message is written to stderr after an attach operation.
> client: allow an empty GUI RPC password, but generate alert message

- android/BOINC/app/build.gradle
Add the Javax Annotation library, as the `javax` package doesn't appear to be available on Java 9.
N/A
> Add Javax Annotation.

- client/gui_rpc_server.cpp
Fixes #3340
This is the same as #3342 but with an additional check for unknown address type
> client: show IPV6 address correctly

- m4/boinc_wxwidgets.m4
Fixes #
On several platforms (e.g. [Elbrus]()) `wx-config --selected-config` produces a value that don't start with `gtk*`. For example, it may look like `e2k-mcst-linux-gnu-gtk2-unicode-3.0`. So I've expanded detection procedure a bit to allow these configurations to be treated correctly, e.g. `boinc-wxwidgets.m4` should react properly not just to `gtk-*`, `gtk2-*`, and `gtk3-*`, but also to `*-gtk-*`, `*-gtk2-*`, and `*-gtk3-*`.
I have no idea how to do it better, it seems that expanding the check in `boinc-wxwidgets.m4` might be the only reasonable option. No `configure` parameters can solve this problem, as far as I guessed.
Determine GTK version for wxWidgets more correctly
> Determine gtkver for wxWidgets more correctly

- lib/crypt.cpp
This was once found by cppcheck and lives for a long time in
the Debian distribution. The decrypt_public function should set the data
attribute, so this is of no functional danger. But as much
as this irritated cppcheck, a human reader is confused at first
sight. Also, at some point the function called may be happy to
know that it is not overwriting a string or the well-defined
string helps some debug output.
Most notably, with this patch, the final copy will always copy
reasonable data, even if the decrypt_public function changes its return
codes.
Anchor: https://github.com/BOINC/boinc/pull/3276
> cppcheck: avoid chance to read from uninitialised data

- clientgui/AdvancedFrame.cpp
- clientgui/AdvancedFrame.h
- clientgui/Events.h
Fixes #2155
Define shortcut on accelerator table and bind it with event table. 
Tested only on Linux environment. It should work as well on Windows but **it should be tested on MacOS X**.
Add CTRL+A shortcut for advance view of boinc manager.
> Add CTRL+A shortcut

- sched/plan_class_spec.cpp
At one point Linux versions were like "3.13.0-103-generic"
but now they can be various things like
"CentOS Linux 7 (Core) [3.10.0-862.14.4.el7.x86_64|libc 2.17 (GNU libc)]"
Parse both of these.
Fixes #4107
> Scheduler, XML plan class spec: parse Linux version correctly

- .github/workflows/android.yml
- .github/workflows/linux.yml
- .github/workflows/mingw.yml
- .github/workflows/windows.yml
Make build artifacts available through github. When PRs are generated from forked repositories the upload to bintray is not working. This is an alternative.
None avilable.
N/A
> [CI] make build artifacts available through github

- client/app.cpp
- client/client_state.cpp
- client/client_state.h
- client/client_types.cpp
- client/client_types.h
- client/hostinfo_unix.cpp
- lib/common_defs.h
- lib/hostinfo.h
Problem: when parsing an APP_VERSIOn (e.g. in scheduler reply)
we check whether it has a graphics app (i.e. a file named "graphics_app").
If so we could report it to the GUI before the file has been downloaded,
causing an error when "Shot Graphics" is clicked.
Also, on Mac we check whether the graphics app can run on
this CPU, given its header.
But this check was being done during APP_VERSION parsing,
when typically the file doesn't exist yet.
Fix: when parsing APP_VERSION,
store a pointer to the FILE_INFO for the graphics app.
When reporting an ACTIVE_TASK to the GUI,
check whether the file is present and (on Mac) can be executed.
Only then tell the GUI about it.
If the file download failed or the file can't be executed,
zero out the pointer so we don't do the check again.
> Check graphics app before telling GUI about it

- android/BOINC/app/src/main/aidl/edu/berkeley/boinc/client/IMonitor.aidl
- android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientStatus.java
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
On modern devices with more than 4 cores or when there is a big tasks cache set could happen a situation when 0 tasks are shown.
This happens because of the limit of 1MB to transfer data between processes.
This commit breaks this flow and instead adds a possibility to load data by chunks.
Also small optimization implemented to update only active tasks every second.
Full update is done every 10 seconds now because most of the time non-active tasks are not updated so often.
This fixes #2123
> [Android] Fix Tasks loading

- db/boinc_db_types.h
- db/schema.sql
- html/user/create_account.php
- html/user/validate_email_addr.php
If you define INVITE_CODES_RPC, create-account RPCs must include
a matching invitation code.
Record this code in user.signature to keep track
of where the RPCs are coming from.
> Allow invitation codes for create-account RPCs only

- api/graphics2_util.cpp
- lib/filesys.cpp
This patch is about 7 years old in Debian. I don't recally the exact original. Typically the compiler warns about something or say, the (admittedly, mostly irrelelvant) Hurd platform does not have a limit in the maxpathlen and so one has a look into that.
The patch is about using MAXPATHLEN both to limit the number of bytes copied into a char[] and to prepare the size of the char[]s for it. When there are MAXPATHLEN characters allowed, a buffer needs MAXPATHLEN+1 characters max because of the terminating 0. snprintf adds the terminating 0 itself and the "n" in snprintf helps to avoid buffer overruns.
When looking at this code, I wish the boinc_getcwd would be allowed to fail. It happens all the time to me that I have removed a directory that I was still in with another shell. And the same …
> Revisited Debian patch 'more_maxpathlen.patch'

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Ignore another form field. Its value is used for temporary purposes only.
none
N/A
> Drupal: ignore temporary field

- client/hostinfo_unix.cpp
GLIBC version string can be detected easier by calling gnu_get_libc_version() instead of parsing it from ldd output.
Not all systems even have ldd script itself available to begin with as it is not required for normal system runtime. This function was made available around libc 2.1 I think so it is pretty safe nowadays.
There was also __GLIBC__ and __GLIBC_MINOR__ macros but those are compile time.
Detect and report GLIBC version from a glibc function call rather than from parsing ldd output when possible.
> Detect GLIBC version by calling gnu_get_libc_version()

- clientgui/mac/MacBitmapComboBox.cpp
Fixes excessive CPU use by Simple View when run on MacOS 10.14 and later
> Mac: Fix high CPU use by Simple View when run on MacOS 10.14 and later

- lib/gui_rpc_client.h
- lib/parse.cpp
- lib/parse.h
> [linux] Remove config.h from installable headers.

- lib/coproc.cpp
for new RTX 30x0 range released September 2020
GFLOPS peak is under-reported by a factor of 2 on the new cards, compared with other reporting tools
I've been asked if we could use NvAPI_GPU_GetGpuCoreCount() instead  (available since 2014), but rejected as a more complex modification which might break backwards compatibility.
Correct detection of NVidia RTX30x0 range GPUs
> client/scheduler: update NVidia detection again

- client/hostinfo_unix.cpp
The atime (access time) of device nodes whose name starts with
/dev/ttyS (serial port) or /dev/ttyACM (serial USB) should not be used
for TTY idle time calculation. It is perfectly possible that they are
used without any user being active.
Previously BOINC would not run on some of our systems, because those systems also had a monitoring device connected via a serial port. Since this monitoring device is periodically checked, BOINC would assume that a user is active. I think it is sensible to exclude `ttyS` and `ttyACM` (and probably also `ttyUSB` devices. But those I couldn't test as we do not have one of those) from TTY idle time calculation.
> hostinfo_unix: Ignore tty(S|ACM) devices in TTY idle time calculation

- m4/check_ssl.m4
1. Errors are only emitted by pkg-config so discard early
2. grep only takes paths with lower case a to z. There are plenty of path variations so don't take chances.
3. $SSLDIR is for cosmetic only and not used during compilation
N/A
N/A
N/A
> Fix empty path for message "OpenSSL found in"

- drupal/sites/default/boinc/modules/boincstats/boincstats.module
- drupal/sites/default/boinc/modules/boincuser/boincuser.module
* In case of a redirect the return code does NOT overwrite the original return code
* It's stored in the result's `redirect_code` instead, so check that as well
N/A
> [Drupal] Allow for HTTP redirects

- client/boinc_cmd.cpp
- client/gui_rpc_server_ops.cpp
- lib/gui_rpc_client.cpp
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
This is so that if you're running the client in a container,
and you change the params of the container (e.g. reduce its memory size)
the client can learn of this.
> Add a GUI RPC "reset_host_info" that tells the client to get host params again (RAM size, disk, NCPUs, etc.).

- client/gui_rpc_server_ops.cpp
Fixes invalid XML in the RPC response when an error occurs during the `set_app_config` RPC.
> client: Fix invalid XML tags in handle_set_app_config

- lib/diagnostics.h
Fixes build and install of the API (headers) for building C apps
- there's a declaration of a `bool` variable in `diagnostics.h`, which makes C compilers throw an error. Protect this with `#ifdef __cplusplus`
> fix API build for C apps

- db/db_base.cpp
- db/db_base.h
Fixes #4276
Changed DB_BASE::insert_id() to return DB_ID_TYPE, which is long, and use atol instead of atoi for number parsing. This fixes the scheduler assigned-work feature.
> Make DB_BASE::insert_id() correctly return numbers exceeding 32bits

- m4/boinc_set_compile_flags.m4
Since gcc 8.1.0 release, source file is needed to generate correct coverage report.
New compilation flag `-fprofile-abs-path` was introduced to preserve correct path to source file in *.gcno file.
> [Codecov] Fix unit tests coverage report

- client/gui_rpc_server_ops.cpp
- lib/cc_config.cpp
In May 2017, a new RPC was added for reading and writing remote app_config.xml files (commit 5b6f648570cdef551b77bbabf3e69243dac69de4, no associated PR). The file written contained unparsable XML with unrecognised tags. This patch restores compliance with the existing documentation at
https://boinc.berkeley.edu/wiki/Client_configuration#Project-level_configuration
https://scienceunited.org/trac/wiki/ClientAppConfig
Fixes 5b6f648570cdef551b77bbabf3e69243dac69de4
Bug re-discovered during Beta testing of covid-19 app at World Community Grid.
Allow edit of app_config.xml files by BoincTasks
> Client: fix app_config write from RPC

- client/dhrystone.cpp
- client/dhrystone.h
- clientgui/mac/MacAccessiblity.mm
- clientgui/sg_PanelBase.cpp
- clientscr/Mac_Saver_Module.h
- clientscr/mac_saver_module.cpp
- mac_build/BuildMacBOINC.sh
- mac_build/boinc.xcodeproj/project.pbxproj
> Mac: Fix Mac builds to support C++11

- lib/cc_config.cpp
Treat project_max_concurrent=0 as 'unspecified'.
Follow-up to #4291: further consequential change after 5b6f648570cdef551b77bbabf3e69243dac69de4
When an app_config.xml file is written by RPC (from BoincTasks or other account manager), it includes the pro-forma line
`<project_max_concurrent>0</project_max_concurrent>`
if no value is specified. This leads to work-fetch issues like
```
20-Apr-2021 16:13:35 [Einstein@Home] choose_project: scanning
20-Apr-2021 16:13:35 [Einstein@Home] can't fetch CPU: blocked by project preferences
20-Apr-2021 16:13:35 [Einstein@Home] can fetch NVIDIA GPU
20-Apr-2021 16:13:35 [Einstein@Home] NVIDIA GPU needs work - excluded instance starved
20-Apr-2021 16:13:35 [Einstein@Home] checking CPU
20-Apr-2021 16:13:35 [Einstein@Home] CPU not high prio proj
20-Apr-2021 …
```
> Client: fix work_fetch after app_config write from RPC

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.java
When taping on notificaion about client status, open 'Tasks' tab instead of 'Notices' tab.
This fixes #4187
> [Android] Fix notification action

- html/user/gpu_list.php
> GPU list: strip leading "AMD" or "NVIDIA" from model to avoid dups in list

- mac_build/boinc.xcodeproj/project.pbxproj
During the BOINC build with Xcode a utility called "SetVersion" gets built and ran.
However, on a new Apple Silicon / M1 / ARM64 Mac the build can't get beyond running SetVersion, because the built binary can't run. For some reason the arm64 version of the "SetVersion" crashes mysteriously. Actually, the process is killed by signal 9 before it actually runs, possibly it's the loader that gets killed.
However, the x86_64 version of "SetVersion" (that is also built) runs fine even on M1 Macs.
Rosetta2, which allows to run x64_86 on ARM64/M1 Macs, is required when installing Xcode, so an M1 Mac with xcode should always be able to run x86_64 binaries.
Thus, a feasible solution to the problem is to build SetVersion only for x86_64. This patch does this.
> Fix Xcode build for Apple Silicon M1 Macs

- client/hostinfo_unix.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
Fixes two minor issues noticed by Charlie in #4386 after merging
- Xcode: add libboinc dependency to detect_rosetta_cpu instead of the client
- client/hostinfo_unix.cpp: variables 'family', 'stepping' and 'model' are
only used on Intel, 'feature' and 'feature_string' only on ARM64
(resulted in 'unused variable' warnings before)
> Mac: fixes for #4386

- mac_build/BuildMacBOINC.sh
Fix BuildMacBOINC,sh script to build libboinc_zip.a when running under bash, not only under zsh
Fixes a bug I introduced in my PR #4369
This is ready to be merged.
> Mac: Fix BuildMacBOINC,sh script to build libboinc_zip.a on bash

- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
- android/BOINC/app/src/main/res/values/configuration.xml
- android/BOINC/app/src/test/java/edu/berkeley/boinc/client/MonitorTest.kt
Fix deprecated hard coded data dir:
https://stackoverflow.com/questions/20391671/warning-do-not-hardcode-data-use-context-getfilesdir-getpath-instead
With this solution:
https://stackoverflow.com/a/19630415/550384
I compile and run and crunch on OnePlus one (Android 10).
> [Android] Fix deprecated hard coded data dir

- android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt
Fix `delicate api` warning
Remove inline modifier
Compile and run and crunch:
OnePlus One (Android 10)
Galaxy gio (Android 4.4)
> [Android] Fix delicate api warning

- android/BOINC/app/build.gradle
- android/BOINC/build.gradle
jacoco 0.8.7 (for gradle 7.1.1)
https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/
> [Android] Switch to new jacoco

- clientgui/MainDocument.cpp
The variable `m_dtProjectsStatusTimestamp` was misspelled as `m_dtProjecStatusTimestamp` in this piece of code, leading to the correct variable not being used.  This fixes what should otherwise be a compiler error.
N/A
> Fix a typo that introduced a bug

- lib/submit_api.py
- py/Boinc/boincxml.py
- py/Boinc/sched_messages.py
- py/Boinc/setup_project.py
- samples/vm_wrapper/VMwrapper.py
- tests/old/test_1sec.py
- tests/old/test_uc.py
- tests/old/testbase.py
- tools/submit_api_test.py
This removes semicolons that were accidentally added to the end of statements in the python code files.
N/A
> Remove semicolons in python code

- 3rdParty/buildMacDependencies.sh
- mac_build/buildcurl.sh
Curl's `make` builds curl so that it requires a number of libraries if `configure` finds those libraries on the computer used for building curl. But those libraries may have been installed on the build machine even though they are not normally present in that OS. Since the BOINC client is not linked with those libraries, the build will probably fail.
Even if the build succeeds, this situation may cause the built executable to crash on computers other than the build machine. 
This PR modifies the _buildcurl.sh_ script to explicitly tell `configure` not to use libraries which are not normally present on MacOS, even if they are present on the build machine.
This PR also simplifies some redundant code in the _buildcurl.sh_ script, and adds a comment in _3rdParty/buildMacDependencies.sh_ …
> Mac: ensure curl is built without needing libraries not normally available

- client/rr_sim.cpp
- client/work_fetch.cpp
- client/work_fetch.h
The round-robin simulation would stop simulating jobs for a project
once a max concurrent limit (app or project) was reached.
As a result it would decide there was a shortfall,
and keep requesting work up to the limit of 1000 jobs.
To fix this:
1) keep simulating a project after an MCL is reached
2) for each (project, resource) pair, keep track of the latest
simulation time T when an MCL was reached.
3) for such a project, don't request work for a resource if
T > now + work buf size
This allows us, e.g., to request GPU jobs from a project
even if its CPU jobs (taking MCL into account) fill the buffer.
This works in the simulation case that showed the problem (#192).
Also: add a bit more logging, and improve names
Fixes #
**Release …
> client: fix work-fetch logic when max concurrent limits are used

- client/client_types.cpp
- client/client_types.h
- client/project.cpp
Old: if we get more than 3 upload or download failures for a project,
do a backoff for each failure.
Problem: if we start a bunch of transfers (say the N output files of a job)
and they all fail, we back off for too long, e.g.:
try N uploads
back off 2^N minutes
try N uploads
back off 4^N minutes
...
New: on a failure, ignore it if we're already backed off.
So the behavior should be something like:
try N uploads
back off 1 minute
try N uploads
back off 2 minutes
...
Should fix #4572
> client: fix overly aggressive project-wide file transfer backoff policy.

- client/dhrystone.cpp
- client/dhrystone.h
- client/whetstone.cpp
I'm compiling BOINC on Opensuse Tumbleweed using gcc 11.2.1.
During compilation a couple of warnings appear.
This PR fixes some of them.
N/A
N/A
> Fix gcc warnings

- client/app_start.cpp
Fix #2549 
Remove old Android scheduling method and use Linux scheduling policies instead
Newer NDK have `SCHED_IDLE` defined and we should use that instead.
I am also not a fan of directly writing to files instead of using system calls.
Direct access to `/dev/cpuctl` directory is not available Android 10 anyway without root.
`set_sched_policy()` can be used to update this code but its considered legacy, see https://source.android.com/devices/tech/perf/cgroups
This is a cgroup feature used by Android system internally and should not be used by app.
see `PCY` sections:
https://stackoverflow.com/questions/10051152/does-any-one-know-the-top-command-s-results-meaning-in-android
https://stackoverflow.com/questions/32701187/adb-shell-top-shows- …
> [Android] Remove old sched method in client

- m4/sah_select_bitness.m4
Fixes #853
Rework `sah_select_bitness.m4` to:
fix bitness test,
clarify errors and messages,
clean up formatting and use 2 spaces indents,
allow user defined ${OBJDUMP},
change from hardcoded file descriptor to AS_MESSAGE_LOG_FD,
add C++ compiler bitness tests (C and C++ must be same bitness to pass test)
Better use declarative unit test rather than iterative unit test in the future
Tested so far on Linux and emsdk
N/A
> Fix sah_select_bitness.m4

- client/gpu_nvidia.cpp
This was not an issue when running normally (not from within Xcode)
> Mac: fix sigabort of GPU detection when running under Xcode debugger

- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vboxjob.cpp
- samples/vboxwrapper/vboxjob.h
Roughly 10% of Rosetta's vbox tasks get stuck when the VM starts.
This is most likely caused by not enough vram given to the virtual graphics adapter.
For years vboxwrapper uses a hard-wired value of 8 MB.
Recent VirtualBox versions (6.1.30) configure 16 MB when a VM is configured manually and a Linux 64-bit template is used.
A site moderator from the VirtualBox forum even requests 128 MB vram:
https://forums.virtualbox.org/viewtopic.php?f=3&t=105195#p513161
This seems to be OK for Windows guests but far too much for Linux guests.
A test with nearly 100 Rosetta vbox tasks over the last 24 h didn't result in a single stuck task when 16 MB vram are configured.
This PR makes the vram size configurable via vbox_job.xml in case future VirtualBox releases require …
> Configure more vram to avoid VMs get stuck during boot

- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vbox_vboxmanage.h
Nearly all modern computer systems have a CMOS real time clock (rtc) to store the time when the computer is switched off.
A more detailed description can be found here:
https://man7.org/linux/man-pages/man8/hwclock.8.html
The manual and many other sources describe that the rtc is usually set to UTC on most non-Windows systems and why Windows should also be set to UTC.
When BOINC (vboxwrapper) creates a VirtualBox VM it configures that VM to use localtime instead of UTC.
This can be changed using the "--rtcuseutc on" option of vboxmanage and should be the new default.
Windows hosts can be configured with a registry key to either use localtime or UTC.
That setting should be forwarded to the guest. 
This PR introduces the necessary changes.
Since I don't have a …
> forward rtc setting from host to guest

- samples/vboxwrapper/vboxjob.cpp
Vboxwrapper configures the default virtual disk controller as ide/PIIX4.
According to the VirtualBox manual sata/IntelAHCI should be the default for different reasons:
https://www.virtualbox.org/manual/ch05.html#harddiskcontrollers
The same chapter from an older VirtualBox manual (5.0.0) is a bit more verbose:
https://download.virtualbox.org/virtualbox/5.0.0/UserManual.pdf#section.5.1
"VirtualBox’s virtual SATA controller operates faster and also
consumes fewer CPU resources than the virtual IDE controller"
"...starting with **version 3.2** and depending on the selected guest operating
system, VirtualBox uses SATA as the default for newly created virtual machines"
"The entire SATA controller ... will not be seen by operating systems that do not
have device …
> Make sata/IntelAHCI the default virtual disk controller

- samples/vboxwrapper/vbox_common.cpp
A volunteer recently complained it's bad English because it's past tense instead of present tense.
N/A
N/A
> Change error message

- clientgui/DlgAdvPreferences.cpp
(which writes scientific notation for large numbers,
which then can't be read).
Fixes #4650
> Computing prefs dialog: use %f instead of %g

- client/scripts/boinc-client.service.in
Linux/Systemd
If service dependencies are not explicitly configured systemd tries to start services in parallel.
This may occasionally lead to a situation where BOINC checks for VirtualBox although that service is not yet present.
A Rosetta user recently posted an issue that might be caused by that:
https://boinc.bakerlab.org/rosetta/forum_thread.php?id=14966&postid=105428
This PR sets a clear dependency and starting order between BOINC and VirtualBox but also ensures BOINC doesn't fail if VirtualBox is not used.
N/A
N/A
> Systemd service order

- .gitignore
- api/Makefile.am
- api/libboinc_api.pc.in
- api/libboinc_graphics2.pc.in
- api/libboinc_opencl.pc.in
- configure.ac
- lib/Makefile.am
- lib/libboinc.pc.in
- lib/libboinc_crypt.pc.in
- lib/libboinc_fcgi.pc.in
- zip/Makefile.am
- zip/libboinc_zip.pc.in
Autoconf generates .pc files from .pc.in files, substituting certain variables.
`PKG_INSTALLDIR` macro from pkg.m4 sets `pkgconfigdir` for `pkgconfig_DATA` targets, which install pkg-config files on the system.
Libtool archives (.la) are historically used to find packages and track static library dependencies but only autotools support them. pkg-config files are build-system agnostic and more portable.
N/A - only app developers might find it useful
**Checks**
Testing configure and installation on different systems is needed.
> Add pkg-config files

- win_build/installerv2/BOINCx64.ism
- win_build/installerv2/BOINCx64_vbox.ism
We're building binaries with all dependencies linked statically for better usability.
This fixes #4168.
> [Windows Installer] Remove dlls from the installer.

- client/current_version.cpp
- client/gui_rpc_server_ops.cpp
client: the get_newer_version() GUI RPC (from the Manager) initiates
an RPC to the BOINC server to get new version info,
but it wasn't waiting for the RPC to finish.
Make it do so.
> Fix bug in new version check

- client/client_state.cpp
- client/current_version.cpp
- client/current_version.h
- client/main.cpp
* Allow restricting to specified OS versions (implemented for MacOS only so far)
* Show newest acceptable BOINC version even if not in ascending order in versions.inc and get_current_version.xml files
* Remove cached newer version number from client_state file if the build was removed from versions.inc (e.g., if a bug was found)
* Fix typos and add comments
Fixes #4551
> client: Fixes for new version check

- lib/prefs.h
I made a mistake in #4600.  I added a variable to the GLOBAL_PREFS structure that isn't used.  This removes that variable.
> Remove unused variable in GLOBAL_PREFS.

- .github/workflows/linux.yml
- deploy/prepare_deployment.py
- linux/ci_configure_manager.sh
- linux/update_vcpkg_manager.sh
Compile Linux manager with vcpkg.
Wait for PRs in vcpkg to be merge: 
* ~~https://github.com/microsoft/vcpkg/pull/17111~~
* ~~https://github.com/microsoft/vcpkg/pull/18580~~
* ~~https://github.com/mesonbuild/meson/issues/6710~~
* ~~https://github.com/microsoft/vcpkg/pull/22201~~
> [Linux][Manager][Scripts] Compile linux manager with vcpkg

- clientgui/DlgExitMessage.cpp
Mac: Add new exit message for OS 10.5 Catalina or newer where Mac screensaver can't launch client
> Mac: Add new exit message for OS 10.5 Catalina or newer

- configure.ac
With autoconf 2.71, [AC_CHECK_DECLS] calls new internal macro
[_AC_UNDECLARED_BUILTIN], which raises error with unknown compiler
flag. On non-x86 archs, -mavx or so is not recognized, so configure
fails on such architecture.
To fix this, reset vector related compiler flags before calling
AC_CHECK_DECLS.
Fixes #4736
> configure.ac: reset compiler flags before calling AC_CHECK_DECLS

- .github/workflows/linux.yml
- 3rdParty/buildLinuxDependencies.sh
Compile manager with: 
- New libwebkit2gtk lib for newer unbuntu.
- Update to latest wxwidgets v3.1.6
Tested on gwsl2 on windows 11
manager with webview:
manager without webview:
manager with webview with vcpkg:
> [Manager] Compile manager with new libwebkit2gtk lib for newer unbuntu

- client/gpu_nvidia.cpp
> Client: use cuDeviceTotalMem_v2() if available to get >4GB mem size for NVIDIA GPUs

- py/Boinc/setup_project.py
During `make_project` I got these warnings:
```
Creating directories
Generating encryption keys
Copying files
failed to copy /usr/local/boinc/tools/db_query to /home/boincadm/projects/loda/bin/db_query
failed to copy /usr/local/boinc/tools/watch_tcp to /home/boincadm/projects/loda/bin/watch_tcp
Setting up database
```
When `Project.install_project` reaches `Copying files`, it attempts to copy `db_query` and `watch_tcp`, but the files aren't there causing 2 warnings to be printed.
In PR #3269 the tools/Makefile.am was updated.
However `setup_project.py` continued to depended on `db_query` and `watch_tcp`, triggering these warnings.
My PR makes similar change to `setup_project.py`.
There may still be old installations of boinc that depends …
> make_project: Removed dependency of long gone files causing "failed to copy" warnings

- samples/vboxwrapper/BuildMacVboxWrapper.sh
- samples/vboxwrapper/vboxwrapper.xcodeproj/project.pbxproj
Updates to Mac VBoxWrapper build script _BuildMacVboxWrapper.sh_ and Xcode project _vboxwrapper.xcodeproj_ for compatibility with Xcode 13,
Eliminate building 32-bit VBoxWrapper because Apple's recent compilers only build 64-bit binaries. Also added the ability to optionally code sign VBoxWrapper when building it on the Mac.
> Update for Xcode 13: Mac VBoxWrapper build script & Xcode project

- html/inc/boinc_db.inc
Fixes #4768 
Casting the parameter $string to type string before passing it to the trim function to prevent passing null to the trim function.  see https://github.com/BOINC/boinc/issues/4768
Casting the parameter $string to type string before passing it to the trim function
> [web] fix deprecated passing null to parameter of type string.

- html/inc/boinc_db.inc
- html/inc/user.inc
- html/inc/util.inc
- html/inc/util_basic.inc
- html/user/server_status.php
- html/user/validate_email_addr.php
Note: if a function expects, say, a string (and not null)
and you get a warning about a null arg,
don't fix it by casting the param to string.
That masks possible bugs.
Instead, find out where null is being passed, and fix it there.
web: server status: fix case where app has no results
web: fix case where get_logged_in_user() is called twice,
first with must_be_logged_in == false and later true.
web: xml_error(): $num default is -1
web: validate_email_addr(): tell user to check spam folder if no email
Fixes #
> Web: fix some PHP 8 deprecation warnings

- html/inc/bootstrap.inc
- html/inc/db_ops.inc
- html/inc/host.inc
- html/inc/team.inc
- html/inc/user.inc
- html/inc/util_basic.inc
- html/ops/db_action.php
- html/ops/mass_email.php
- html/user/cert1.php
- html/user/cert_all.php
- html/user/cert_team.php
- html/user/forum_post.php
- implode() cares about arg order
- strlen(), strstr(), stripslashes() don't take null arg
- time() takes no args
There are probably others.
I don't currently have 8.1 set up, and am working off bug reports.
Fixes #4772, #4773
> Web: various changes to remove PHP 8.1 warnings and errors

- linux/ci_configure_manager.sh
- m4/boinc_wxwidgets.m4
Set webkit2gtk-4.0 ldflags only for wxwidgets vcpkg manager.
> [Linux][Manger][vcpkg] Set webkit2gtk-4.0 ldflags only for wxwidgets vcpkg manager.

- client/work_fetch.cpp
Apparently this is desired by users who compete to return results first.
Fixes #4396
> client: if project has zero resource share AND work buf min is zero, don't fetch from it unless device instance is actually idle.

- clientgui/ViewWork.cpp
Sometimes Advanced Frame is destroyed much more later, when e.g. MainDocument is already destroyed.
This fixes #4793.
> [Windows][Manager] Do proper verifications when saving state on application exit

- .github/workflows/android.yml
- .github/workflows/flutter-macos.yml
- .github/workflows/flutter-ubuntu.yml
- .github/workflows/flutter-windows.yml
- .github/workflows/linux.yml
- .github/workflows/mingw.yml
- .github/workflows/osx.yml
- .github/workflows/source-code-check.yml
- .github/workflows/wasm.yml
- .github/workflows/windows.yml
Single job on PRs only.
From here:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
> If you build the group name with a property that is only defined for specific events, you can use a fallback value. For example, github.head_ref is only defined on pull_request events. If your workflow responds to other events in addition to pull_request events, you will need to provide a fallback to avoid a syntax error. The following concurrency group cancels in-progress jobs or runs on pull_request events only; if github.head_ref is undefined, the concurrency group will fallback to the run ID, which is guaranteed to be both unique and defined for the run.
> ```yaml
> concurrency: 
>   group: ${{ github.head_ref || github.run_id }}
> …
```
> [CI] Single job on PRs only

- Makefile.am
- clientgui/SkinManager.cpp
- clientgui/skins/Makefile.am
- configure.ac
> [Manager][linux] Search for skins in /usr/(local)/share/boinc-manager/skins or ./skins folders.

- client/file_xfer.cpp
- client/file_xfer.h
Logic cleanup in this area.
Fixes #1071
> client: if bandwidth limit is removed (up or down), remove limit from active transfers.

- mac_build/BuildMacBOINC.sh
> [OSX] Move get command exit code from eval string.

- client/pers_file_xfer.cpp
- client/pers_file_xfer.h
- clientgui/ViewTransfers.cpp
- clientgui/ViewTransfers.h
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- lib/gui_rpc_client_print.cpp
Fixes #
Adds estimated transfer time remaining to transfer tab in Manager advanced view.
Also adds ability to see estimated transfer time remaining on active transfers when invoking "--get_file_transfers" from boinccmd.
Provides solution to #4644
The equation for calculating the estimated time remaining is very simple.  I see a possibility of this time fluxuating wildly since it is linear with the actual transfer rate.  It would be nice for it to adjust based on a recent average of transfer rates, but I feel that may make this a bit more complicated than it needs to be.  However, I am open to suggestions. 
Added estimated time remaining to transfers window in advanced view.
> [Manager] [Boinccmd] Add estimated time remaining for file transfers

- tools/stage_file_native.cpp
Coverity tool found the bug in my tool: there was resource leakage to storage (gzFile) if written bytes equaled 0.
https://github.com/BOINC/boinc/pull/4816#issuecomment-1186534073
Fix: close gzFile right after the writes.
Bugfix in stage_file in writing to gzip
> fix resource leakage in stage_file in writing to gzip

- client/Makefile.am
- deploy/prepare_deployment.py
Based on a comment from  @CharlieFenton made here:
#4853
"... switcher is used only on the Macintosh."
> Ensure to compile switcher only for Macintosh

- client/http_curl.cpp
While compiling the BOINC client on Linux using gcc I stumbled over another warning:
```
http_curl.cpp: In member function ‘int HTTP_OP::libcurl_exec(const char*, const char*, const char*, double, double, bool)’:
http_curl.cpp:605:13: warning: the address of ‘HTTP_OP::infile’ will never be NULL [-Waddress]
605 |         if (infile && strlen(infile)>0) {
|             ^~~~~~
In file included from gui_http.h:53,
from cs_notice.h:58,
from client_types.h:45,
from client_msgs.h:26,
from http_curl.cpp:44:
http_curl.h:86:10: note: ‘HTTP_OP::infile’ declared here
86 |     char infile[256];
|          ^~~~~~
```
Wouldn't it be enough to just test:
`if (strlen(infile)>0) {`
> Remove redundant test in if-statement

- clientgui/ViewTransfers.cpp
Fixes #
The Master was having a wxWidgets debug error that was caused from #4825 and prevented the manger from running .  After discussing with @AenBleidd privately, we have decided the column ID order for estimated transfer time remaining should be after the Elapsed column.  I did some testing by having different columns selected and/or moved, and there were no issues.
m_aStdColNameOrder and m_aStdColWidthOrder could have been corrected to match the ID order, but then the estimated time remaining would have appeared at the end of the page, which seems out of place.
"N/A"
> Revise column ID order.

- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
Vboxwrapper 26204 calls "vboxmanage -q list hdds" which can lead to a race condition when multiple instances of vboxwrapper (even older versions) are running concurrently.
This PR replaces "list hdds" with "showhdinfo ..." which implicitly asks for a lock.
Since "showhdinfo" requires a bit more error handling this is used to automatically set a new UUID to the vdi if necessary.
N/A
Fix possible race condition in Vboxwrapper 26204
> Vboxwrapper improvements

- client/sandbox.cpp
- lib/gui_rpc_client.cpp
gcc prints other warnings during compilation of the client.
They could be avoided by generously increasing the buffer size.
Would it be OK to increase it by factor 5?
```
gui_rpc_client.cpp: In function 'int read_gui_rpc_password(char*, std::string&)':
gui_rpc_client.cpp:477:26: warning: '%s' directive writing up to 4095 bytes into a region of size 1024 [-Wformat-overflow=]
477 |                         "%s exists but can't be read.  See %s",
|                          ^~
478 |                         path, HELP_URL
|                         ~~~~
gui_rpc_client.cpp:476:28: note: 'sprintf' output between 71 and 4166 bytes into a destination of size 1024
476 |                     sprintf(msg_buf,
|                     ~~~~~~~^~~~~~~~~
477 |                         "%s exists but can't be …
```
> Increase msg_buf size

- client/app.cpp
- client/cs_prefs.cpp
- lib/procinfo.cpp
- lib/procinfo.h
- lib/procinfo_unix.cpp
- lib/procinfo_win.cpp
Fixes #4327, #4328
The pref "suspend_cpu_usage" lets you suspend BOINC computing
when the non-BOINC CPU usage (NBCU) exceeds a threshold T.
NBCU excludes BOINC-related processes
- the BOINC client
- the BOINC Manager
- BOINC apps and their process trees
- graphics apps
- VBox daemon
This can use significant time.
We count it as BOINC-related only if BOINC is running a Vbox app
NBCU also excludes low-priority processors:
"niced" on Linux, idle class on Win.
We don't want such processes to keep BOINC from computing.
This preference is enforced every 10 seconds.
The client estimates the NBCU over the last 10 sec,
and suspends BOINC processing if the load exceeds T
Currently, NBCU is estimated by scanning the list of all processes,
skipping the types of processes listed above,
and adding up …
> fix non-BOINC CPU usage limit on Win and Linux

- tools/Makefile.am
> Fix missing '-lz' parameter when building 'stage_file_native' tool

- clientgui/DlgDiagnosticLogFlags.cpp
- clientgui/DlgHiddenColumns.cpp
Not sure, but shouldn't the file reference point to the header file instead of the cpp file?
```
DlgDiagnosticLogFlags.cpp:19:24: warning: ‘#pragma implementation’ for ‘DlgDiagnosticLogFlags.cpp’ appears after file is included
19 | #pragma implementation "DlgDiagnosticLogFlags.cpp"
|                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix pragma warning

- clientgui/MainDocument.cpp
... like these:
```
MainDocument.cpp: In member function ‘void CMainDocument::KillGraphicsApp(int)’:
MainDocument.cpp:1715:19: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
1715 |         argv[0] = "switcher";
|                   ^~~~~~~~~~
MainDocument.cpp: In function ‘void color_cycle(int, int, wxColour&)’:
MainDocument.cpp:2655:42: warning: ‘b’ may be used uninitialized [-Wmaybe-uninitialized]
2655 |     unsigned char cb = (unsigned char) (b*256);
```
> Fix gcc compiler warnings

- clientgui/sg_TaskPanel.cpp
'fileName' size needs to be increased to avoid the warnings below.
```
sg_TaskPanel.cpp: In member function ‘void CSimpleTaskPanel::FindSlideShowFiles(TaskSelectionData*)’:
sg_TaskPanel.cpp:897:53: warning: ‘/slideshow_’ directive output may be truncated writing 11 bytes into a region of size between 1 and 1024 [-Wformat-truncation=]
897 |             snprintf(fileName, sizeof(fileName), "%s/slideshow_%s_%02d", proj_dir, state_result->app->name, j);
|                                                     ^~~~~~~~~~~
sg_TaskPanel.cpp:897:50: note: directive argument in the range [0, 98]
897 |             snprintf(fileName, sizeof(fileName), "%s/slideshow_%s_%02d", proj_dir, state_result->app->name, j);
|                                                  ^~~~~~~~~~~~~~~~~~~~~~ …
```
> Increase buffer size

- client/app.cpp
- lib/procinfo_mac.cpp
- lib/procinfo_unix.cpp
Fixes #4327, #4328
Implement #4859 for Macintosh computers
> Mac: compute non-BOINC CPU usage in a more accurate way

- lib/cc_config.cpp
> Client: don't crash when <exclude_gpu> has bad device #

- clientgui/BOINCListCtrl.cpp
If a developer adds a new column to a tab in the Manager, that column will be added regardless of the default visibility.  There is no way of having the column hide by default unless the user resets to default columns.  This PR revises the code so that if a column is hidden by default, it will not be visible the first time the Manager is started.
> [Manager] Add check if new columns are to be visible by default

- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientgui/ViewWork.cpp
- clientgui/ViewWork.h
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
Fixes #2115
Added a new column -- "Estimated Completion" -- to the Advanced > Tasks screen to show the calculated date and time by which a task should complete. It is positioned immediately next to the existing "Deadline" column to make it easier for users to visually assess which task(s) may not complete by the deadline.
I opted to design "estimated completion" as a derived field. It is calculated as "current date and time" + "remaining time". Therefore, I opted to *not* add a new saved field to the data model for it.
Also, the original issue (#2115) had specified another new field to be added, to explicitly calculate and display the delta between the estimated completion date/time and the deadline date/time. However, it is my opinion …
> Added Estimated Completion column to Advanced view > Tasks

- clientgui/BOINCListCtrl.cpp
Fixes #4888
Implements a freeze and thaw of the active view window when adding or removing columns.
Also unrelated, but wxWidgets has a remove all columns function.  I've added this to replace the iterative remove column function.
N/A
Fixed crash when removing columns when horizontal scroll bar is not at left-most position
> [Manager] Freeze view when modifying columns

- client/http_curl.cpp
- client/http_curl.h
HTTP_OP::libcurl_exec() opens input and/or output files.
In the normal case these eventually are closed in handle_messages()
when the HTTP op finishes.
But if the call to curl_multi_add_handle() returns an error
(which I believe happens on a connect failure, e.g. if the project is down)
then we need to close the files.
We weren't doing this, possibly leading to running out of file descriptors.
Fixes #4914 (possibly)
> client: close file descriptors if Curl initialization fails.

- client/app.cpp
- client/app_start.cpp
Fixes #3430
When a task is initialized (or resuming computation), the progress percentage is updated to the progress percentage of the last checkpoint.  This happens to be 0 if the task has not reached a checkpoint.
None.
Progress percentage is reset to 0 for tasks restarting with pseudo-progress.
> Reset progress percentage to last checkpoint when task is initialized

- client/app.cpp
- client/app_control.cpp
- client/client_state.cpp
- client/client_state.h
- client/cpu_sched.cpp
- client/cs_benchmark.cpp
- client/cs_prefs.cpp
- client/cs_scheduler.cpp
- client/gui_rpc_server_ops.cpp
- client/rr_sim.cpp
- client/rrsim_test.cpp
- client/sim.cpp
- client/work_fetch.cpp
- clientgui/DlgAdvPreferences.cpp
- clientgui/DlgAdvPreferences.h
- clientgui/DlgAdvPreferencesBase.cpp
- clientgui/DlgAdvPreferencesBase.h
- html/inc/prefs.inc
- lib/prefs.cpp
- lib/prefs.h
Fixes #41 (!)
Previously there were single prefs for
- % of CPUs
- % of CPU time
- suspend if non-BOINC CPU load above X
These applied whether or not the computer was in use.
This PR adds separate prefs for when the computer is not in use.
It includes both web-based and Manager interfaces for editing them.
Backwards compatible; if the new prefs are not specified, it uses the old ones for both cases.
> Add not-in-use computing prefs

- sched/sched_config.cpp
- sched/sched_config.h
- sched/sched_send.cpp
If max_used_gb or max_used_pct are zero (in client prefs) treat as "no limit".
I haven't tested this.
> scheduler: calculate max disk usage based on user prefs correctly.

- client/client_state.h
- client/cs_statefile.cpp
- client/gui_rpc_server_ops.cpp
- client/result.cpp
- client/result.h
Fixes #1903
When the app_config is re-read, the CPU/GPU resources will be updated in the Manager and boinccmd without requiring BOINC to restart.
Edit:  Changes are made in the client.  The CPU/GPU string stored in "resources" is printed only once.  If there is a string present, the client was not reprinting the resources if they changed.  This PR now passes a bool for the case when app_config is re-read so the resources can be reprinted.  No changes were made to the Manager.
Also note that if app_config is removed, the CPU/GPU resources do not change.  The client doesn't update these currently, it needs information from the server to provide default CPU/GPU usage.
None.
CPU/GPU usage in Manager displays correctly …
> Client:  Update cpu/gpu resources when app_config is re-read

- clientgui/BOINCListCtrl.cpp
Code cleanup of unused variables as a result of #4897 and #4912.  Thank you, @CharlieFenton for the catch, apologizes for the sloppy work.
> Remove unused variables from #4897 and #4912

- android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/SplashActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/ProjectInfoFragment.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt
Fixes most of the deprecations that were caused by updating the API to v33 (Tiramisu). However, the last deprecation of issue #4946 (readSerializable() in ProjectRelatedClasses.kt) is not fixed within this PR. It needs some more work.
I tested the changes with API 30 and API 33 and the app seems to work.
> Fix most of the deprecations introduced by API level 33

- android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectRelatedClasses.kt
- android/BOINC/app/src/test/java/edu/berkeley/boinc/client/ClientNotificationTest.kt
- android/BOINC/build.gradle
Fixes #4946 - Fixed the deprecations in the unit tests and readSerialization() in ProjectRelatedClasses.kt. I also upgraded gradle to version 7.3.1.
> 4946 Fix ClientNotificationTest and readSerialization() deprecations

- samples/vboxwrapper/vbox_vboxmanage.cpp
Avoid possibly unsafe character conversion 'tolower'. Instead, rely on the output of vboxmanage.
Should be fine as long as the virtualbox developers keep their outputs stable. If not, all tests against their messages would need a revision.
Fixes #4993
> Avoid character conversion

- android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt
- android/BOINC/app/src/main/res/values-en/strings.xml
- android/BOINC/app/src/main/res/values/configuration.xml
- android/BOINC/app/src/main/res/values/strings.xml
- android/BOINC/app/src/main/res/xml/root_preferences.xml
Fixes #4214 
Added an additional shared preference which can be set to automatically expand all tasks details in the task list screen
N/A
Added an option to have task details always expanded
> Added an option to have task details always expanded #4214

- client/check_security.cpp
- client/gui_rpc_server_ops.cpp
- client/sandbox.cpp
- client/sandbox.h
- client/setprojectgrp.cpp
- client/switcher.cpp
- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientgui/mac/SetupSecurity.cpp
- clientscr/gfx_switcher.cpp
- clientscr/mac_saver_module.cpp
- clientscr/res/BOINCSaver.xib
- clientscr/res/mac_restrict_access.sb
- clientscr/screensaver.cpp
- lib/gui_rpc_client_ops.cpp
- mac_build/Mac_SA_Secure.sh
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_installer/finish_install.cpp
Fixes BOINC screensaver and Manager "Show Graphics" button functionality to work with MacOS 13 Ventura. This also required a different implementation of security to prevent access to user's files in the unlikely case of  malevolent or buggy project graphics apps.
As of MacOS 13.0 Ventura IOSurface cannot be used to share graphics between apps unless they are running as the same user, so  the screensaver can no longer run the graphics apps as user boinc_master or user boinc_project. Similarly, project graphics no longer work if run as user boinc_master or user boinc_project when run from the Manager's _Show Graphics_ button, though I don't fully understand why.
As a result, they now must be run as the logged in user, creating a potential security risk. I have implemented a technique to …
> Mac: Fixes for MacOS 13 and Xcode 14

- client/check_security.cpp
- client/gui_rpc_server_ops.cpp
- client/sandbox.cpp
- client/sandbox.h
- client/setprojectgrp.cpp
- client/switcher.cpp
- clientscr/gfx_cleanup.mm
- clientscr/gfx_switcher.cpp
- clientscr/screensaver.cpp
- lib/gui_rpc_client.cpp
- mac_build/Mac_SA_Secure.sh
- mac_build/boinc.xcodeproj/project.pbxproj
This PR fixes a remaining bug after implementing my previous PR #5002.
Mac: After running screensaver fix slot permissions modified by project gfx apps.
Also updated copyright dates on files I modified in PR #5002.
> Mac: More fixes for MacOS 13 and Xcode 14

- samples/vboxwrapper/vboxlogging.cpp
After a system upgrade to the recent Tumbleweed version a few days ago making vboxwrapper fails with the errors below.
As suggested by the make output adding `#include <ctime>` solves the problem.
That's weird since "vboxlogging.cpp" hasn't changed for years.
```
vboxlogging.cpp: In function 'int vboxlog_msg(const char*, ...)':
vboxlogging.cpp:39:15: error: aggregate 'tm tm' has incomplete type and cannot be defined
39 |     struct tm tm;
|               ^~
vboxlogging.cpp:44:16: error: 'time' was not declared in this scope
44 |     time_t x = time(0);
|                ^~~~
vboxlogging.cpp:33:1: note: 'time' is defined in header '<ctime>'; did you forget to '#include <ctime>'?
32 | #include "vboxlogging.h"
+++ |+#include <ctime>
33 | 
vboxlogging.cpp:51:5: error: 'localtime_r' was not …
```
> Fix compile errors caused by missing header file

- clientgui/DlgAdvPreferences.cpp
Partially fixes #4939
This commit checks for the condition stated in #4939 when advanced preferences are changed locally.  An error message is created if the condition exists.  The user will have to modify one of the values in order to save their preferences.  The revised error message is:
#4634 was my previous draft.  The conditional logic was slightly different.  I decided this time to validate both values first separately, then check to see if both doubles are "active".  This minimizes additional variables for a condition that is probably rare.
Fixed indefinite suspension when suspension times were not set correctly in preferences.
> [Manager] [Advanced View] Add warning message in preferences for suspension

- tools/project.xml
Note: there's some inconsistency between this list and https://boinc.berkeley.edu/trac/wiki/BoincPlatforms
> Add Android ARM64 to default platform list (tools/project.xml).

- clientgui/TermsOfUsePage.cpp
Put labels in constructor; not sure why this is needed.
Fixes #5034
> Manager: make button labels appear in terms of use dialog.

- client/gui_rpc_server_ops.cpp
- lib/url.cpp
- tests/unit-tests/lib/test_url.cpp
Fixes #4937
This introduces new functionality to `canonicalize_master_url`, namely converting all input ASCII alphabet characters to their respective lower-case representations.
`std::tolower(static_cast<unsigned char>(ch))` is utilised for this purpose from `ctypes.h`.
Unit tests have been added correspondingly.
N/A
Updates canonicalize_master_url to normalize all URLs to lower-case, wherever applicable.
> Canonicalize URLs to lower case

- lib/coproc.cpp
When the client reports an OpenCL GPU (other than NVIDIA/AMD/Intel) in a scheduler request, the "type" field is the model name. In the case of Apple GPUs this is "Apple M1" or "Apple M2" (and other models as time goes on).
The type field is used in plan class descriptions.
In the case of Apple the models are (I think) equivalent software-wise, and it would be a nuisance to have to make a new plan class (and app versions) for each model.
So - in the case of Apple GPUs - use "Apple" as the type. The model name is still available (as opencl_prop.name) if needed.
Fixes #5036
> scheduler: set type of Apple GPUs to "Apple"

- configure.ac
With GCC 12, this header file cannot be included on its own. Doing so fails with #error, but also produces many warnings related to implicit ints and implicit function declarations. This is inconvenient for distributions who are trying to switch to newer C versions (without implicit ints/function declarations), and monitor builds for suspicious warnings related to obsolete C features.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> configure.ac: Do not probe for <avxintrin.h>

- client/check_security.cpp
- clientgui/mac/SetupSecurity.cpp
Fixes #5057 
Fixes a problem changing ownership of project-specific files to boinc_project. This issue occurs only when the Mac client is [set up](https://boinc.berkeley.edu/wiki/Tools_for_Mac_OS_X#Running_BOINC_as_a_daemon_or_system_service) to run as a daemon / system service. This bug was introduced by my commit aecfe8ed15.
> Mac: Fix permission errors when running client as a daemon / system service

- configure.ac
> [linux] zlib is required when building client, server or apps

- client/cs_scheduler.cpp
for a project and a scheduler reply contains an http:// URL. Keep using https://
> client: don't print a (confusing) warning if we're using an https:// URL

- client/cs_scheduler.cpp
- clientgui/DlgAdvPreferences.cpp
- clientgui/DlgAdvPreferences.h
In-use prefs:
- cpu_usage_limit
- max_ncpus_pct
- ram_max_used_busy_frac
- suspend_cpu_usage
Don't clear their values when in-use computing is disabled, and write them to the override file.
That way if the user enables in-use computing again, they'll see the values they had set before.
Fixes some of Charlie's comments in #5072
> Manager: don't clear in-use prefs when disable in-use computing

- client/cs_scheduler.cpp
This was originally done to propagate prefs between projects.
When you edit prefs on project A, they propagate to project B and you can edit them there too.
But this doesn't make sense - and can lead to undesirable behavior - when projects
have different prefs-editing web code.
And it's not a particularly useful feature.
If you're using web prefs, the Manager tells you what project they came from.
You can go there to edit them.
Note: we still send working prefs,, which are used for scheduler decisions.
> client: don't send "web prefs" in scheduler requests.

- apps/Makefile.am
- lib/CMakeLists.txt
- lib/Makefile.am
- sched/Makefile.am
- tools/Makefile.am
- vda/Makefile.am
* Use `$(libdir)` in automake
* Use **GNUInstallDirs** in CMake
> Account for systems where library directory is named `lib64`

- linux/ci_configure_manager.sh
Hello @davidpanderson 
Here is a bug fix of compilation of vcpkg manager in ubuntu.
It not compile correctly with the ld flags, results unable to run the compiled manager under ubuntu 22.04, and maybe other Linux distro / versions.
This is known issue and I test my fix on my wsl2 ubuntu 22.04.
Fix https://github.com/microsoft/vcpkg/issues/25786
I decided to continue contribute and not let ruined for me and the boinc community and let it improve and grow. 
Here some of my contributions to boinc in the recent year:
- Android boinc switch to dark mode along with all icons convert them to graphic vector images.
- Android boinc add tcp ip mode, also lead to remote control on android.
- Refactor Android Monitor to kotlin making it MonitorAsync.
- Add support ARMv6 devices to android.
- Started …
> [Linux][Manager][vcpkg] Fix Linux vcpkg manager compilation

- client/pers_file_xfer.cpp
> client: show file size in event log message when file transfer finishes

- mac_installer/PostInstall.cpp
- mac_installer/finish_install.cpp
- mac_installer/uninstall.cpp
Fixes a rare problem with the Mac uninstaller on Macs configured with multiple users. It failed to remove some items for users who had not logged into the computer before the administrator deleted the BOINC Data folder.
This PR is ready to be merged once all CI builds succeed.
> Mac: make uninstaller work even if user deleted BOINC Data directory

- client/hostinfo_unix.cpp
- db/boinc_db_types.h
- lib/hostinfo.h
- sched/plan_class_spec.cpp
1024 wasn't enough for some CPUs.
This caused some hosts to not get sse3 app versions, for example.
Note: ideally we'd change this to std::string.
But that would have disrupted the code that populates it (hostinfo_unix.cpp, hostinfo_win.cpp).
Easier/safer to do it this way.
Fixes #5122
> client and server: increase p_features size from 1024 to 8192.

- mac_build/BuildMacBOINC.sh
- mac_build/buildMacBOINC-CI.sh
Mac CI: 
Don't hard-code the names of targets and built executables in the Mac CI build script.
Don't unnecessary rebuild libraries for the _Zip Apps_, _UpperCase2_ or _VBoxWrapper_ projects.
Simplify and generalize the logic in the Mac CI build script.
The script _buildMacBOINC-CI.sh_ hard coded each of the targets and resulting executables for the main BOINC Xcode project. When I modified the _boinc_finish_install_ target in PR #5125 to build a full application bundle instead of a command-line style executable, this hard coding caused the CI builds to fail. I wasted many hours trying to fix the failure in my code before I realized it was due to a problem in the _buildMacBOINC-CI.sh_ script and not in my code.
This PR generalizes the _buildMacBOINC-CI.sh_ script to automatically …
> Mac CI: Simplify and generalize logic in the Mac CI build script

- client/cpu_sched.cpp
- client/log_flags.cpp
- client/sandbox.cpp
- lib/cc_config.cpp
- lib/cc_config.h
If set, it skips the check to see if Remote Desktop Protocol (RDP) is in use, allowing GPU apps to run while using RDP.
This should be done only if you have configured RDP as described here: https://knowledge.civilgeo.com/knowledge-base/enabling-gpu-rendering-for-microsoft-remote-desktop/
Fixes #5143
> client, Win: add a cc_config.xml option <no_rdp_check>.

- clientgui/DlgAdvPreferences.cpp
- If a checkbox for a value is unchecked, don't clear the value.
- If suspend while in use, write suspend_cpu_usage (even though it won't be used)
- For fields with checkboxes, when box is checked, set to default value only currently blank
Fixes #5092
> Manager: enhance computing prefs dialog

- android/bootstrap_vcpkg_cmake.sh
- wasm/update_emsdk_vcpkg.sh
Fix: vcpkg will clone from $VCPKG_LINK.
> [ci] Fix: vcpkg will clone from $VCPKG_LINK

- lib/procinfo.cpp
- lib/procinfo.h
- lib/procinfo_win.cpp
client, win: when building the global process tree, don't make a parent->child link if the parent is newer than the child (this can happen in Win because a process's parentID isn't changed when its parent exits).
This prevents two potential problems:
- when killing a runaway app, killing unrelated processes too
- incorrect CPU time accounting
Fixes #5152
> fix potential bug in building process tree on Win

- html/inc/util.inc
- html/user/download_software.php
The Linux installers on the BOINC web site (.sh files) have out-of-date binaries, and are not real installers. We shouldn't direct users to them.
But projects and AMs that use auto-attach were directing Linux users to these installers.
This change fixes that.
Linux users are not shown a download button, but are instead directed to https://boinc.berkeley.edu/wiki/Installing_on_Linux which lists various options for installing BOINC on Linux (starting with package managers).
Also: the download page (download_software.php) is also used by account managers (Science United).
In this case, it should show instructions for
adding an account manager, not attaching to a project.
Note: there's an analogous update to download.php on the BOINC web site: if the machine is Linux,
show a link to the Linux …
> web: fix problems with download page on project sites

- api/boinc_api.cpp
- client/client_state.cpp
- client/client_types.cpp
- client/cs_notice.cpp
- client/hostinfo_win.cpp
- client/project.h
- client/sim.cpp
- lib/boinc_stdio.h
- lib/boinc_win.h
- lib/str_replace.h
- tools/backend_lib.cpp
- tools/create_work.cpp
Remove outdated stuff (e.g. VS has snprintf() now).
I'd like to have a clean build (no warnings) on both VS and gcc. Currently VS has a bunch of printf code warnings in diagnostics.cpp, diagnostics_win.cpp, and stackwalker_win.cpp. These should be easy to fix.
gcc has a bunch of sprintf buffer-size warnings, not easy to fix. There are lots of warnings in zip (to be fixed with vcpkg?) and in old graphics code.
> Fix some compile warnings on Win (VS 2022).

- client/app_start.cpp
- client/client_state.cpp
- client/client_state.h
- client/client_types.h
- client/cs_apps.cpp
- client/cs_files.cpp
- client/project.cpp
- client/project.h
- client/scheduler_op.cpp
- lib/boinc_stdio.h
- lib/error_numbers.h
- lib/str_util.cpp
When a task starts:
- don't re-checksum its files.
This was already done after the file was downloaded.
Doing it again doesn't accomplish anything,
and causes performance problems if the file is big.
- do check that the files exist and have the right size
- if the program launch (e.g. exec()) fails,
re-checksum the app version files on the (unlikely) chance
that one of them was accidentally corrupted.
Fixes #5165
> client: improve file checking on task start

- clientsetup/win/launcher.cpp
> [Windows Installer] Prevent handle leaks

- samples/wrapper/wrapper.cpp
Logging the child process PID is useful on Windows, where we otherwise have to go rummaging in undocumented internals to find process parent-child relationships
> [Wrapper] Add logging of child process PID, plus minor fixes for Windows

- client/app.cpp
> client: print log message (conditioned on log_flags.task) when an exclusive app or exclusive GPU app starts or stops.

- lib/procinfo.cpp
- lib/procinfo_win.cpp
> Client, Win: include kernel time in non-BOINC CPU usage

- client/acct_mgr.cpp
- client/rr_sim.cpp
- client/rr_sim.h
Fixes a problem where, no hosts with no GPUs  Science United would attach to projects with no jobs, and the client would fail to reconnect to SU to get other projects.
> client: when using a dynamic AM and checking for idle devices, include CPU

- clientgui/MainDocument.cpp
- clientgui/MainDocument.h
- clientgui/ViewWork.cpp
- lib/gui_rpc_client.h
Resolves #1024 by making the Manager smarter when suspending/​resuming/​aborting multiple tasks at once.
When suspending or aborting multiple tasks, the requests are sorted to prevent the situation where as soon as a running task is stopped, a slot becomes free and the client immediately starts the next ready task, not knowing that the user wants to suspend/​abort that one as well.
When resuming multiple tasks, the ordering is reversed to favour resuming tasks that have already started over those that have not.
> [Manager] Sort requests to suspend/resume/abort multiple tasks

- clientgui/BOINCTaskBar.cpp
- clientgui/BOINCTaskBar.h
- mac_build/Mac_SA_Secure.sh
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/buildWxMac.sh
- mac_build/buildc-ares.sh
- mac_build/buildcurl.sh
- mac_build/buildopenssl.sh
- mac_build/dependencyNames.sh
- mac_installer/uninstall.cpp
PR #5176 requires wxWidgets 3.1.6. This PR:
* Updates the Mac Xcode project, source files and build scripts for wxWidgets 3.1.6 and Xcode 14.3.
* Fixes dependency build scripts for changes in the way the patch utility expects its arguments.
* Changes missed OS 10.10 references in build scripts to OS 10.13 for consistency and completeness.
* Fixes a compiler warning.
> Mac: upgrade tp wxWidgets 3.1.6

- client/app.cpp
Fixes #5072 more
Without this, if the CPU limit is 100%, the throttler thread suspends all tasks, resumes them all 1 s later, then goes to sleep forever (meaning subsequent changes to the limit are never applied)
(Commit 3b1ebfd1b0c3aefd45446d1ec6dacb6d7be4d4c5 changed the ‘nothing to do’ check to `limit == 0` at the same time as implementing `CLIENT_STATE::current_cpu_usage_limit()` which makes that condition impossible)
> [Client] Correct limit check in throttler thread

- client/acct_mgr.cpp
- client/acct_setup.cpp
- client/boinc_cmd.cpp
- client/client_state.cpp
- client/client_state.h
- client/client_types.cpp
- client/client_types.h
- client/cs_account.cpp
- client/cs_cmdline.cpp
- client/cs_scheduler.cpp
- client/cs_statefile.cpp
- client/gui_rpc_server_ops.cpp
- clientgui/AsyncRPC.cpp
- clientgui/AsyncRPC.h
- clientgui/ProjectProcessingPage.cpp
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- Maintain a map from email hash to the oldest user CPID and its time.
This doesn't change if that project is detached.
- Write/parse write this in client_state.xml
- Update it when handling a scheduler reply
- Use it when sending a scheduler request
- If, on startup, the map is empty, populate it from PROJECT data.
This should happen only once, when update to this version
Fixes #5177
> client: don't change user CPID if detach from oldest project

- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/buildMacBOINC-CI.sh
- mac_build/checkDependentLibraryVersions.sh
- mac_build/dependencyNames.sh
Mac: Verify dependent library versions cached by CI match those in the Xcode project by comparing the directory names in dependencyNames.sh with those in the Xcode project search paths.
> Mac CI: Verify cached library versions match those in Xcode project

- lib/diagnostics.cpp
- lib/diagnostics.h
- lib/diagnostics_win.cpp
- lib/diagnostics_win.h
- lib/stackwalker_imports.h
- lib/stackwalker_win.cpp
Fixes all the bugs the compiler has been warning about, and several others I found while I was in there
> [Lib] Improve Windows diagnostics

- lib/win_util.cpp
Use `FORMAT_MESSAGE_IGNORE_INSERTS` to prevent trying to replace insert sequences in system message definitions with nonexistent arguments
> [Lib][Windows] Correct flags for `FormatMessage()`

- html/user/host_venue_action.php
(should do this uniformly in user-facing web pages)
> web: when update venue, call it a "computer" rather than a "host".

- lib/gui_rpc_client.h
MacOS 13.3.1 apparently broke per-thread locale uselocale() so we must use our SET_LOCALE struct on MacOS even though HAVE_USELOCALE is defined.
When BOINC Manager is run with a locale which uses comma instead of period as the decimal delimiter, this bug in MacOS causes strtod() to stop on the period decimal point. XML_PARSER::parse_double() then returns false because strtod() reports that it has processed fewer characters than expected. This results in all values obtained by parse_double() being set to zero.
Fixes #5205
> Work around uselocale() apparently broken in MacOS 13.3.1

- lib/gui_rpc_client.h
- lib/parse.cpp
- lib/parse.h
This is a safer version of #5207. I became concerned about the possibility that using setlocale() in BOINC Manager's separate RPC thread (used for asynchronous RPCs) might sometimes cause the main thread to temporarily have the "C" locale instead of the locale for the selected language. I have reverted my change in #5207.
MacOS 13.3.1 apparently broke per-thread locale `uselocale()`. 
When BOINC Manager is run with a locale which uses comma instead of period as the decimal delimiter, this bug in MacOS causes `strtod()` to stop on the period decimal point. `XML_PARSER::parse_double()` then returns false because `strtod()` reports that it has processed fewer characters than expected. This results in all values obtained by `XML_PARSER::parse_double()` being set to zero. This fix uses …
> Safer work around uselocale() apparently broken in MacOS 13.3.1

- client/main.cpp
Fixes #2156
Adds a couple new error messages to the lockfile check. This change ensures that there is no confusion caused by the application incorrectly reporting the presence of another instance.
No alternate solutions were considered. The current solution is sufficiently small and simple.
Fix misleading "Another instance of BOINC is running" messages
> Add more error messages for directory locking

- clientscr/screensaver.cpp
- mac_installer/AddRemoveUser.cpp
- mac_installer/PostInstall.cpp
- mac_installer/finish_install.cpp
- mac_installer/release_boinc.sh
- mac_installer/uninstall.cpp
We have always used login items to launch BOINC Manager in the background when a user logs in. This no longer works correctly under MacOS 13.3.1,. This PR implements using a LaunchAgent to do that under MacOS 13 and later.
> Mac: Fix automatic launch on login under MacOS 13.3.1

- clientgui/MainDocument.cpp
The manager runs "rdesktop-vrdp" to connect to a running VM. This program used to be included with VBox but no longer is. If it's not there, try "rdesktop" instead, then "xfreerdp". See https://www.helpwire.app/blog/rdesktop-linux/
Fixes #5214
> Manager (Unix): fix "Show VM" bug

- clientgui/ViewWork.cpp
The original PR had
if (result->active_task_state == 1) {
This is checking the wrong field, and it has a "magic number" (1).
BOINC code should never have magic numbers!
Use symbolic constants.
> Manager: fix bug where "estimated completion" and "completion before deadline" task fields switch back and forth to --- during CPU throttling.

- clientgui/mac/SetVersion.cpp
- clientgui/mac/templates/BoincCmd-Info.plist
- clientgui/mac/templates/Info.plist
- clientgui/mac/templates/Installer-Info.plist
- clientgui/mac/templates/PostInstall-Info.plist
- clientgui/mac/templates/ScreenSaver-Info.plist
- clientgui/mac/templates/SystemMenu-Info.plist
- clientgui/mac/templates/Uninstaller-Info.plist
- clientgui/mac/templates/WaitPermissions-Info.plist
Fixes #3794 
Adds the CFBundleShortVersionString property list key which is a [recommended key](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-SW1) to include with macOS apps. This is what is used to display the version in Spotlight, which is why the BOINC Manager is currently listed as having an "Unknown version" when searching for it.
Previously, SetVersion sort of tried to parse the plist files in clientgui/mac/templates, find the CFBundleVersion, and then replace the contents of the following <string> tags. This doesn't work well for replacing multiple property values however. So I instead simply search for and replace any …
> Add CFBundleShortVersionString to macOS app plist files

- clientgui/BOINCTaskBar.h
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/buildWxMac.sh
- mac_build/dependencyNames.sh
Upgrade BOINC Manager for Macintosh to use wxWidgets 3.2.2.1
> Mac: upgrade to wxWidgets 3.2.2.1

- lib/filesys.cpp
- lib/str_util.h
- lib/util.cpp
- lib/win_util.cpp
Header files that are exposed should not contain any 'config.h' file reference.
By this PR next issue is fixed:
```
In file included from /home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/x64-linux-static/vcpkg_installed/x64-linux-static/include/boinc/str_util.h:25,
from /home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/x64-linux-static/vcpkg_installed/x64-linux-static/include/boinc/parse.h:31,
from /home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/x64-linux-static/vcpkg_installed/x64-linux-static/include/boinc/coproc.h:83,
from /home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/x64-linux-static/vcpkg_installed/x64-linux-static/include/boinc/hostinfo.h:32,
from /home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/x …
```
> [libboinc] fix build when integrator tries to link app with libboinc

- client/app.cpp
- client/cpu_sched.cpp
Old: if target CPU usage is (say) 1%,
we'd unthrottle, sleep 1 sec, throttle, and sleep 99 sec. A change to the usage pref wouldn't be enforced during that sleep.
New: do something every second; changes are seen immediately.
This makes a difference only when setting is very close to 0 or 100
Fixes #5231
> client: improve implementation of CPU throttling

- mac_installer/AddRemoveUser_ReadMe.rtf
- mac_installer/ReadMe.rtf
- mac_installer/notarize_boinc.sh
- mac_installer/release_boinc.sh
Mac: add script to notarize BOINC Installer, Uninstaller, stand-alone client and AddRemoveUser utility.
As of MacOS 10.15 Catalina, the OS does not allow the user to run downloaded software unless it has been "notarized" by Apple. This PR adds the mac_installer/notarize_boinc.sh script, which can be run to notarize the downloadable BOINC executables after building the installer, uninstaller, etc. with the mac_installer/release_boinc.sh script.
Instructions for running both mac_installer/release_boinc.sh and mac_installer/notarize_boinc.sh can be found in the comments near the top of each script.
I have tested these changes and this PR will be ready to merge as soon as CI checks finish.
> Mac: add script to notarize BOINC executables

- apps/Makefile.am
- lib/Makefile.am
- sched/Makefile.am
- tools/Makefile.am
- vda/Makefile.am
Fixes wrong #5085 (d727a3d61611891b5601b57577d449ebdababc9e).
Install server executables to `$(libexecdir)` instead of `$(libdir)`.
> Automake: use $(libexecdir) instead of $(libdir)

- clientscr/screensaver.cpp
Commit 689a6eae25 changed the variable from a signed variable (`int`) to unsigned (`size_t`), effectively causing an infinite `for` loop.
I believe this crash bug also affects MS Windows. I don't know whether this code is used for the X11 screensaver, but if so that will also be affected.
Once this is merged, it should be cherry-picked into the 7.22 branch so that we can build BOINC 7.22.2 for all platforms. I will next create another PR to improve backtrace generation on the Mac, which should also be included in BOINC 7.22.2.
> Fix screensaver crash bug introduced in PR #5197 commit 689a6eae25

- lib/diagnostics.cpp
- lib/mac/mac_backtrace.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
Fixes some issues with Mac backtrace under macOS 13.4.
This is ready to be merged and should then be cherry-picked into the 7.22 branch.
> Mac: update backtrace for MacOS 13.4

- html/inc/bootstrap.inc
- html/inc/sandbox.inc
- html/user/sandbox.php
web, file sandbox:
- it's not an error to create a file with the same MD5 as an existing file
- sandbox_file_select() should use regexp only if one is supplied
- when delete a file, don't delete the physical file if another link is using it.
> File sandbox fixes

- lib/prefs.cpp
Otherwise BOINC will stop computing after 60 minutes of idleness.
Is this a show-stopper?  Quite possibly.
BTW, this should have been called "suspend_if_no_recent_input_min" (times are in seconds unless otherwise specified)
> client: the default value for the "suspend_if_no_recent_input" pref should to 0, not 60

- client/cs_prefs.cpp
Partially fixes #4939 
When global preferences are read in the client, a check is in place to see if the idle time to resume computing is greater than the idle time to suspend computing, but only if CPU or GPU computing is to be suspended when the computer is in use.  If this condition is true, CPU or GPU computing could be suspended indefinitely regardless of the activity of the computer.  This check will send an alert to the user to make them aware.
Previous ideas were discussed in #4960, but this was favored since it did not modify preferences.  Thank you to @AenBleidd and @davidpanderson for the feedback!
[Client] Alert added if idle time to resume computing exceeds idle time to suspend computing.
> [Client] Add alert if idle time to resume computing is greater than idle time to suspend computing

- client/cpu_sched.cpp
- client/result.h
- client/rr_sim.cpp
- client/sim.cpp
- client/sim_util.cpp
In 20ff585 we changed the sched policy so that e.g. if there are 2 4-CPU jobs on a 6-CPU host, it runs them both. I.e. overscheduling the CPUs is better than starving them.
This commit refines this a bit: if in addition to the MT jobs there are some 1-CPU jobs,
it runs one MT job and two of the 1-CPU jobs.
Also: show resource usage in cpu_sched_debug messages
Also: if CPUs are starved, trigger a work request. This logic was mistakenly hidden in an
if (log_flags.cpu_sched_debug)
Also: don't ignore log flags in the simulator
Fixes #5254
> client: avoid overscheduling CPUs in presence of MT jobs

- clientgui/DlgAdvPreferences.cpp
The problem was that wxWidgets' ToDouble(&x) returns an error (which we weren't checking for)
and doesn't modify x if the string is empty.
So we were getting the value from a previous field.
Solution: set x to zero before each such call.
Fixes the bug reported in #5266
> Manager, computing prefs dialog: Fix bug where the "In use means..." value mysteriously showed up in the "suspend when non-BOINC..." field.

- lib/parse.cpp
- lib/parse.h
- mac_build/boinc.xcodeproj/project.pbxproj
Fixes #5249, #5211
PR #5211 implemented a workaround for MacOS 13.3.1 having apparently broken the per-thread locale API `useloclae()`, by using the `strtod_l()` function instead of `strtod()`. This change was needed only in the Manager (since the client doesn't use a separate RPC thread), but the changes were in _lib/parse.cpp_ and  _lib/parse.h_ which are used by the BOINC client as well as the BOINC Manager (and also other components of BOINC.)
While my tests indicate that `strtod_l()` actually takes less CPU time than `strtod()` on the M1 Mac, this PR lists the use of `strtod_l()` to BIONC Manager just in case its use in the client might contribute to the long task CPU times reported in issue #5249.
> Mac: Use strtod_l() only in Manager. Use strtod() in client, etc.

- gl
- html/inc/dir_hier.inc
- html/inc/submit_util.inc
- html/user/get_output2.php
- html/user/submit.php
Problem: the old interface for getting output files (get_output.php) downloaded files with their physical name,
which is a cryptic string with no extension.
If the output file is, for example, a .zip, you don't see this. You also don't see the logical name of the file.
Solution: give downloaded files better names.
For example, if a result has a single output file
with logical name 'output.zip',
download it as resultname__output.zip
Similar for multiple output files per result,
for workunits, for single files from a result, and for batches.
Fixes #5262
This can be used as a web API, or directly from web pages (submit.php) This replaces the old interface,
but I'm leaving it there in case anyone is using it.
Add utility functions for
- getting the full path of an output file
- getting the …
> web-based remote job submission: improve interface for getting output files

- .github/workflows/rpm-package.yml
- .github/workflows/rpmrepo/Dockerfile.fedora
- .github/workflows/rpmrepo/Dockerfile.suse
- .github/workflows/rpmrepo/package_depends.sh
- .github/workflows/rpmrepo/package_filelist.sh
- .github/workflows/rpmrepo/package_prepare.sh
- .github/workflows/rpmrepo/repo_remove.sh
- .github/workflows/rpmrepo/repo_update.sh
Fixes https://github.com/TheSCInitiative/bounties/issues/1, please review and send feedback.
The change implements a new workflow that allows to generate and manage an RPM repo.
Support is implemented currently for:
* Fedora 38, 37
* OpenSuse Leap 15.5, 15.4
More versions or distros rpm-based can be included as necessary.
Two channels will be available: 
* alpha
* stable
Both are uploaded to the https://boinc.berkeley.edu/dl/linux url, which can however be changed in the
workflow environment BASEREPO.
To add stable and alpha channel download the repository definition file, eg.:
> https://boinc.berkeley.edu/dl/linux/stable/fc38/boinc-stable-fc38.repo
And install it in the dnf/yum/zypper folder for repositories.
Two operations are implemented:
* Repository update with new package
* Done at …
> RPM workflow

- clientgui/AdvancedFrame.cpp
- clientgui/sg_BoincSimpleFrame.cpp
Mac: Add standard command-comma shortcut for Preferences (aka Settings) menu item.
Fixes #5273
> Mac: Add standard command-comma shortcut for Preferences menu item

- configure.ac
…e, added in BOINC/boinc@/e2a130f648ae2d581d69da0b8fc0de1eef3327c0
Fixes #
BOINC/boinc@/e2a130f648ae2d581d69da0b8fc0de1eef3327c0 uses wxSystemAppearance, which was added to wxWidgets in version 3.1.3.
As such, BOINC will fail to build with earlier versions of wxWidgets, so this pull request updates the minimum required version accordingly.
N/A
N/A
> Update required wxWidgets to 3.1.3 (first with wxSystemAppearance)

- clientgui/BOINCListCtrl.cpp
- clientgui/BOINCListCtrl.h
Fixes #
This no-op change to TokenizedStringToArray's signature resolves the following compiler warning:
BOINCListCtrl.cpp:251:54: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
N/A
N/A
> Make delimiters argument const so it can (legally) be a string literal.

- client/http_curl.cpp
Otherwise some RPC-handling frameworks complain.
Fixes #5298
> client: set Content-type of POST requests to text/xml.

- clientgui/Localization.cpp
- clientgui/Localization.h
Fixes #5297
Just reference all the strings for amicable numbers project as is already done for some other projects
Added translations strings for Amicable numbers project.
> Correction for issue #5297

- lib/crypt_prog.cpp
> crypt_prog: add -verify_string command (to verify a string signature)

- client/client_state.h
- client/cs_prefs.cpp
Avoid rapid start/stop when at threshold.
Fixes #5310
> client, Android: if suspend because of battery heat or charge, don't resume for at least 5 minutes.

- clientgui/DlgEventLog.cpp
- clientgui/DlgEventLog.h
- clientgui/Events.h
Fixes #4258 
Button added to the event log window to filter out alerts (aka errors).  Button toggles to display only alerts and to all message types.  Functionality was also added to the "show all messages" button as well.  For example, if messages are filtered by a project and then the alert button is clicked, then only alerts for that specific project are displayed.
Screen shots:
New button added:
When alerts are filtered:
When alerts and a project are filtered:
None considered.
Add button in event log to display only alerts.
> [Manager] Add button in event log to display only alerts (errors)

- clientgui/BOINCGUIApp.cpp
- clientgui/DlgEventLog.cpp
- clientgui/DlgOptions.cpp
Fixes #5321 
Commit e0ffbf106d failed t check for a NULL return from `wxLocale::GetLanguageInfo(wxLANGUAGE_DEFAULT)` which causes BOINC Manager to crash if the default system locale is unknown to wxWidgets.
This also means that the code added by #5176 which adds automatic selection of the language to the list of languages does not work on the Mac. In fact, that code broke automatic language selection on the Mac, which worked correctly in BOINC 7.22.2.
I have tried to guard the new automatic language selection code with `#ifndef __WXMAC__`, but I am getting an assert from wxWidgets "Invalid combobox index" if I scroll all the way to the top of the language selection combo box. 
@BrianNixon can you please look at this and tel me what more I need to do. Also, please note that line 752 of …
> Fix Mac crash bug introduced by commit e0ffbf106d

- sched/plan_class_spec.cpp
- sched/plan_class_spec.h
(Linux) If you build an app on a machine with a given version of libc, it won't run on hosts with older versions.
Until now you had to build on a super-old system.
With this change you can build on a newer system,
and give the app version a plan class that limits it to hosts with that min libc version.
> Scheduler: add <min_libc_version> option to plan_class_spec.xml

- android/BOINC/app/src/main/AndroidManifest.xml
- android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt
1. Battery Optimization settings are available
2. and application was not already set to ignore Battery Optimization
3. and these settings were not shown before
This fixes #4420
> [Android] Show Battery Optimization settings when:

- clientgui/BOINCGUIApp.cpp
This PR fixes a problem on MacOS automatically detecting the language set for system to use in menus, dialogs, etc.
The regional attributes (date, time and numeric [decimal point & thousands separator] formats) were not getting set properly on the Mac when Automatic Detection was used, though they were correct when the country and region were explicitly selected from the list in the Other Options dialog. This was true in 7.22.2. (BOINC has long used automatic detection if the _LanguageISO_ preference tag was an empty string, thus: `LanguageISO=`.) I believe this issue has been present for a very long time, and this may never have worked on the Mac.
This occurred because _wxLocale_ for _wxLANGUAGE_DEFAULT_ does not work as expected on the Mac. Mac applications normally provide localization …
> Mac: Fix Automatic language detection

- android/BOINC/.idea/misc.xml
- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/aidl/edu/berkeley/boinc/client/IMonitor.aidl
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/AppPreferences.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/ClientNotification.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
- android/BOINC/app/src/main/java/edu/berkeley/boinc/client/MonitorAsync.kt
- android/BOINC/app/src/main/res/values-en/strings.xml
- android/BOINC/app/src/main/res/values/strings.xml
- android/BOINC/app/src/main/res/xml/root_preferences.xml
- android/BOINC/app/src/test/java/edu/berkeley/boinc/client/ClientNotificationTest.kt
In #3418 I changed the behavior of BOINC to run always in the foreground mode. This lead to the situation when notification was always shown, even when BOINC in not running, and thus making a lot of notification noise. 3 years ago I thought that this is good decision and a necessary evil. Unfortunately, I was wrong.
My main motivation of this was to be able to be on track, and have our application in the Play Store. But every new API increase the limitations from the Android side become stronger and stronger, and prevent us from doing what we want. For example, in the Android versions starting from Oreo, it is not possible to start a service from the background. And while we can leave with that fact, we received and issue with the notifications. I thought, that if we will have BOINC …
> [Android] Revert back to target API 21

- .github/workflows/android.yml
- android/ci_build_vcpkg_manager.sh
Do not build Debug since it's useless on CI.
> [Android][CI] Split Android Manager builds to decrease total build time.

- db/db_base.cpp
Starting with 8.0.34, the MySQL reconnection option is deprecated, and using it produces a warning message.
So don't use it with MySQL 8.0.34 and later.
Note: this means that if the MySQL server dies,
long-running programs like the transitioner will stop working, and you'll have to stop/start the project.
If this proves to be a problem, we could add our own reconnect logic.
Fixes #5341
> server (all components that use DB): don't use MYSQL_OPT_RECONNECT if deprecated

- android/BOINC/app/build.gradle
Most of the breaking changes from API 21 to API 28 were made in a way that it doesn't really matter which API your applications targets. That is why there is no risk by increasing API level to 28. This will remove the message about outdated application, and also will remove an issue with the newer phones that have 4k display. It's not possible to increase it further, because starting from API 29 W^X feature was introduced, and this prevent us from running any executable that is not the part of our APK (even the client that we are copying from the assets folder based on the current device architecture).
> [Android] Increase Target SDK Version API to 28.

- client/gpu_opencl.cpp
- lib/cl_boinc.h
- lib/opencl_boinc.h
Starting from Android 8, the GPU detection is broken due to the fact that dlopen() now return NULL. This was done to fix issues with library names resolution. New API was introduced, but it's not available from the NDK. Instead, we have to load the library manually and call the function directly. Unfortunately, on Android this behavior was changed even more, and now we need to look for other functions.
By fixing this behavior, we have now successful Mali GPU detection. But unfortunately, this doesn't work for Qualcomm Adreno GPUs.
Looks like implementation of Qualcomm has some problems with clGetDeviceIDs. It returns CL_DEVICE_NOT_FOUND for CL_DEVICE_TYPE_GPU and CL_DEVICE_TYPE_ACCELERATOR combined. But it returns CL_SUCCESS when asking separately for CL_DEVICE_TYPE_GPU or …
> [Android] Fix GPU detection

- client/Makefile.am
- client/Makefile.linux
- client/app_control.cpp
- client/app_start.cpp
- client/app_test.cpp
- client/client_state.cpp
- client/client_state.h
- client/cs_cmdline.cpp
- client/file_names.cpp
- client/project.cpp
- client/project.h
- client/work_fetch.cpp
- lib/msg_queue.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
- win_build/boinc_cli.vcxproj
Add a cmdline option '--app_test filename'.
Runs a job with the given executable, in a slot directory slots/app_test.
No XML files are required.
This is a new and simpler way of testing an application,
interacting with the client, without involving a project.
It's documented here: https://github.com/BOINC/boinc/wiki/AppDebug
I added this to facilitate development of the 'sporadic app' feature,
which involves complex client/app interaction.
> client: add app testing feature

- mac_build/boinc.xcodeproj/project.pbxproj
Remove app_test.cpp from build of switcher
Also, add switcher and setprojectgrp targets as dependencies to client so CI builds will detect problems building them.
> Mac: Fix build break introduced by commit 8ea2aba1d8

- html/inc/delete_account.inc
- html/inc/forum_email.inc
- html/inc/team.inc
- html/user/team_admins.php
And ignore team_admin entries for nonexistent users.
> Web: when delete a user, delete team_admin entries for that user.

- client/hostinfo_unix.cpp
CPU cores are not correctly detected when eg running within a container that uses cgroup cpusets. This change should improve the detection. I am not 100% sure about other platforms and may need some ifdefing, but I do not have many platforms to test it on.
this code was checked against `nproc` which uses the same method
Detect CPU cores when using cpuset to limit core count
> Correctly detect CPU cores when cpuset cgroup is used

- android/BOINC/app/build.gradle
- android/BOINC/app/src/main/java/edu/berkeley/boinc/SettingsFragment.kt
- android/BOINC/app/src/main/res/layout/authenticationkey_preference_dialog.xml
- android/BOINC/app/src/main/res/values-en/strings.xml
- android/BOINC/app/src/main/res/values/strings.xml
- android/BOINC/app/src/main/res/xml/root_preferences.xml
Fixes # 4236
To ensure secure access and editing, implement biometric authentication for the Authentication Key field.
Add protection to the Authentication Key field with biometric authentication.
> Add Biometric authentication for GUI Authentication Key

- db/boinc_db_types.h
- sched/plan_class_spec.cpp
Fixes #5123
In the current version of the code (master branch), p_features size of the host record is still fixed 1024. That doesn't look right (and probably won't help):
char p_features[1024];
https://github.com/BOINC/boinc/blob/master/db/boinc_db_types.h#L369
> complete #5123: client and server: increase p_features size from 1024 to 8192

- db/boinc_db_types.h
- html/inc/user.inc
- html/user/edit_email_form.php
- html/user/edit_passwd_form.php
- html/user/weak_auth.php
- in the page showing the weak auth, say that it depends on password and email addr (and make this page nicer looking)
- in the pages for changing password and email addr, say that doing so will change your weak auth.
> Improve text related to weak auth (account key)

- py/Boinc/setup_project.py
{url}, not url.
Introduced in 01df1879aaf84cddfee8497ce36d08deedb96d1f
Related to #5407; not sure if it fixes it.
> make_project: fix bug in creation of schedulers.txt

- api/boinc_api.cpp
- api/boinc_api.h
- client/app_control.cpp
- client/app_test.cpp
- client/cpu_sched.cpp
- client/cs_cmdline.cpp
- client/cs_sporadic.cpp
- samples/sporadic/sporadic.cpp
- samples/vboxwrapper/vboxwrapper.cpp
- samples/wrapper/wrapper.cpp
Add --sporadic option to wrapper and vboxwrapper.
When used, the wrapper communicates sporadic state with the app via files.
This allows, for example, sporadic apps that run in VMs.
The logic for reading/writing these files is in the BOINC runtime library;
to enable it, the wrapper calls boinc_sporadic_dir().
So changes to the wrappers is minimal.
> Make wrappers work with sporadic apps

- clientscr/Mac_Saver_Module.h
- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/gfx_cleanup.mm
- clientscr/gfx_switcher.cpp
- clientscr/mac_saver_module.cpp
- clientscr/res/mac_restrict_access.sb
- mac_installer/PostInstall.cpp
MacOS 14.0 Sonoma broke many third-party screensavers, including BOINC's. This PR addresses several issues:
[1] The most serious was that once the BOINC screensaver runs, the desktop remained black, leaving the user unable to access the desktop. The user had to log out using the keyboard shortcut to regain access. This is fixed.
[2] The BOINC screensaver can no longer run the default graphics _boincscr_ or any project graphics, though project graphics still work when launched from the BOINC Manager using the _Show graphics_ button.
To get around Apple's earlier sandbox restrictions on screensavers, we use IOSurfaceBuffers to allow the screensaver to display the project application's or _boincscr's_ graphics. This involves the use of Mach communication. But Apple has added a new sandbox …
> Mac screensaver: update for MacOS 14.0 Sonoma

- html/user/team_search.php
There's a fulltext index on team(name, description). You can't match() against just 'name'.
> web: fix bug in team search

- html/user/login_action.php
- sched/file_upload_handler.cpp
Apparently urldecode(null) gets a warning in current PHP
Fixes #5441
> web: fix PHP warning in login action.

- html/inc/boinc_db.inc
- html/inc/prefs_util.inc
- html/user/login_form.php
- html/user/notices.php
Note: PHP 8.2 deprecates stuff like dynamic elements. There may be other instances.
Fixes #5442
> Eliminate some PHP warnings.

- clientgui/ViewResources.cpp
Fixes #5330
The bad data occurred as project_total was not cleared out when a client disconnects. A simple addition fixes the issue. I also updated dark mode display of empty BOINC disk.
> Fix bad data in Diskwhen client disconnects

- client/hostinfo_win.cpp
Fixes #3180
on Windows, BOINC CPU feature detection is limited, so apps can't use this information even if the CPU does support these features.
Ryzen 7950x
Linux
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 …
```
> Windows: add AVX512 support

- client/hostinfo_win.cpp
**added missing Windows SKUs**:
- IoT Enterprise & Enterprise LTSC
- Azure HCI
- Datacenter Azure Edition
**added detection of Windows Server 23H2**
Until now BOINC cant identify some current/new Windows SKUs
Windows 10 IoT Enterprise LTSC is only identified as "Microsoft Windows 10 x64 Edition, (10.00.19044.00)" see https://yafu.myfirewall.org/yafu/show_host_detail.php?hostid=58911
BOINC cant even identify the newest stable Windows Server version (10.00.25398.0) as Windows Server 23H2 - see https://support.microsoft.com/en-us/topic/windows-server-version-23h2-update-history-68c851ff-825a-4dbc-857b-51c5aa0ab248
> Updated hostinfo_win.cpp - missing Windows SKUs (IoT Enterprise, Azure..)

- samples/vboxwrapper/boinc_resolve
- samples/worker/run_worker_1.sh
- samples/worker/vbox_job_1.xml
- samples/worker/vm_version.xml
This makes the cookbooks simpler.
> Add some files (in samples/) that are needed to run the example apps as VM apps.

- html/inc/boinc_db.inc
- html/inc/user.inc
- html/inc/util.inc
- html/inc/xml.inc
- html/user/server_status.php
- don't pass null to trim() or is_numeric()
- gmdate() expects an integer; truncate
- server status page: if app has no results, SQL aggregate functions return null; handle this.
Fixes #5467
> web: fix some PHP8 warnings

- client/project.cpp
- client/project.h
- client/scheduler_op.cpp
Problem: If a project is non-CPU-intensive and has no jobs we ask it for work repeatedly, without backoff.
A project is marked as non-CPU-intensive if
it has no CPU-intensive apps.
This means that a project with no apps
(e.g. because it doesn't have any jobs)
is marked as non-CPU-intensive and pinged without backoff.
Solution: mark a project as non-CPU-intensive only if its scheduler reply says it is
(i.e. there's <non_cpu_intensive/> in its config.xml).
> client: fix non-CPU-intensive logic

- client/cs_account.cpp
- client/cs_files.cpp
- client/cs_scheduler.cpp
The Einstein@home web site says its master URL is
https://einsteinathome.org.
But its scheduler replies say the master URL is
https://einstein.phys.uwm.edu
If you attach to URL1 the client creates a file
account_einsteinathome.org.xml
Then it does a scheduler RPC and gets a reply saying the master URL is URL2. It then creates a file
account_einstein.phys.uwm.edu.xml
If you then detach from the project, it deletes the 2nd account file but the first one is still there,
so the next time you run the client you're still attached to Einstein@home!
To fix this situation:
1) on startup, check for misnamed account files
(file name doesn't match master URL in the file).
Delete (if there's already a file of the right name) or rename.
2) on scheduler RPC reply with a URL that differs by more than …
> client: handle changes to project master URLs

- client/work_fetch.cpp
e.g.:
1/8/2024 1:12:13 AM | BOINC test project | Not requesting tasks: don't need (CPU: blocked by project preferences; NVIDIA GPU: blocked by project preferences; Intel GPU: no applications)
It used to say
1/8/2024 1:12:13 AM | BOINC test project | Not requesting tasks: don't need (CPU: ; NVIDIA GPU: ; Intel GPU:)
> client: when not requesting work for a resource, show correct message

- lib/proc_control.cpp
- lib/proc_control.h
- samples/wrapper/wrapper.cpp
The former can't be caught, the latter can.
The goal was to support wrapped program that are themselves wrappers of some sort.
Problem (as reported in #5840): contrary to documentation, SIGTSTP doesn't actually stop processes not connected to a TTY (at least on Linux - I checked).
This PR changes the default signal back to SIGSTOP, but provides the option (via a --use_tstp cmdline arg to wrapper) to use SIGTSTP instead.
Fixes #5840
> Wrapper (Unix): use SIGSTOP instead of SIGTSTP to suspend subprocesses

- html/inc/email.inc
Define('EMAIL_USE_CMD', true) in your html/project/project.inc
I recently configured our server to use DKIM (email authentication). This can avoid spam classification.
For some reason, this didn't work with PHPMailer,
but it worked with the Unix 'mail' command.
> web: add option to use Unix 'mail' command to send emails

- gl
- gl.py
- html/inc/db_ops.inc
- html/inc/util.inc
- html/inc/util_basic.inc
- html/inc/util_ops.inc
- html/project.sample/project.inc
- html/user/job_file.php
- html/user/lammps.php
- html/user/manage_app.php
- html/user/sandbox.php
- html/user/submit.php
- html/user/submit_example.php
- html/user/submit_rpc_handler.php
- html/user/submit_status.php
- html/user/tree_threader.php
Move the code to show PHP errors into a function display_errors(). If you want to show PHP errors in web pages, call this from your project.inc.
But always show errors in:
- admin pages
- job submission pages
These pages are not seen by regular users.
Fixes #5492
> web: showing PHP errors on web pages is optional

- html/inc/user.inc
- html/inc/util.inc
- html/user/edit_user_info_action.php
Add a function sanitize_user_url() to do this.
It accepts things like
google.com
http://google.com
https://google.com?blah=foo&x=y
but nothing else.
There doesn't seem to be a PHP function that works, and stack overflow didn't yield anything plausible.
When showing a user page,
show 'Invalid URL' if it's nonempty and doesn't pass this.
When a user edits their info, show error page if they enter an invalid URL.
Fixes #5491
> Web: sanitize user URLs to prevent XSS attacks

- client/check_security.cpp
- clientgui/mac/SetupSecurity.cpp
User boinc_master should have primary group boinc_master. User boincproject should have primary group boincproject. 
But updating MacOS to a new version sometimes changes the PrimaryGroupID of users boinc_master and boincproject to staff (20). This seems to be responsible for OpenCL projects failing after a MacOS update with the following error:
`UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
<built-in>:1:10: fatal error: cannot open file './opencl-c.h': Permission denied
#include "opencl-c.h"`
Fixes #5456
This PR makes the following changes:
* Added a check of the Primary Group IDs of users boinc_master and  boinc_project along with the other permissions checks when the Mac Manager or client is launched. If incorrect, refuses to run and displays an alert "BOINC ownership or …
> Mac: fix Apple Silicon GPU errors after MacOS update

- client/app_test.cpp
- client/client_types.cpp
- client/client_types.h
This feature lets you run an app under a BOINC client without having a project.
You describe the app (i.e. its input/output files) in C++ code, in the function app_test_init().
I used this to debug sporadic apps and VM aps.
This PR is a rewrite of app_test_init() to make it clearer, and to facilitate describing apps with input and output files.
> client: make the --app_test feature more general.

- client/app.h
- client/client_state.cpp
- client/project.cpp
- client/project.h
- client/result.h
If a project says it's NCI, treat all its apps as NCI.
Save project.non_compute_intensive in the client state file.
> Client: fix non-compute-intensive logic

- clientgui/AdvancedFrame.cpp
> [Linux] When user closes BOINC Manager window with the EventLog open, close properly the application

- samples/vboxwrapper/vbox_vboxmanage.cpp
The changelog for VirtualBox 7.0.6 (released January 17 2023) states this:
"Audio: The "--audio" option in VBoxManage is now marked as deprecated; please use "--audio-driver" and "--audio-enabled" instead. This will allow more flexibility when changing the driver and/or controlling the audio functionality"
See:
https://www.virtualbox.org/wiki/Changelog-7.0#v6
Since vboxwrapper uses "--audio none" to disable the VM's audio hardware it should be modified to a conditional "--audio-enabled off" for VirtualBox releases newer than 7.0.4.
> Replace deprecated VBoxManage command

- samples/vboxwrapper/vboxwrapper.cpp
Got a compiler warning in vboxwrapper.cpp
```
vboxwrapper.cpp:684:20: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::__cxx11::basic_string<char> >::size_type' {aka 'long unsigned int'} [-Wsign-compare]
684 |     for (int i=0; i<pVM->copy_to_shared.size(); ++i) {
|                   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Declared i as long unsigned int to avoid it.
> Avoid compiler warning in vboxwrapper.cpp

- samples/vboxwrapper/vbox_common.cpp
TIMEOUT is checked by various functions calling `vbm_popen`.
Ensure `vbm_popen` reports it.
> Report TIMEOUT from vbm_popen

- client/cs_statefile.cpp
This addresses an issue introduced when we changed GPU names from (e.g.) 'Apple M3 Pro' to 'apple_gpu'.
Note: this means that if a host has in-progress jobs using a discrete GPU, and you remove that GPU, those jobs will be discarded. This is a change, which I think is good because otherwise you'd get error messages forever.
> client: if GPU is missing, discard app versions and results that refer to it.

- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
Certain Vbox tasks from LHC@home recently failed with log entries like this:
```
2024-04-13 16:06:31 (7532): Detected: VirtualBox VboxManage Interface (Version: Unknown)
.
.
.
2024-04-13 16:06:43 (7532): Error in add storage controller (fixed disk) for VM: -108
Command:
VBoxManage -q storagectl "boinc_2f92bf95dc688693" --name "Hard Disk Controller" --add "sata" --controller "IntelAHCI" --hostiocache off --sataportcount 3
Output:
Oracle VM VirtualBox Command Line Management Interface Version 7.0.8
Copyright (C) 2005-2023 Oracle and/or its affiliates
VBoxManage.exe: error: Unknown option: --sataportcount
Usage - Manage a storage controller:
VBoxManage storagectl <uuid | vmname> <--name=controller-name> [--add= floppy
| ide | pcie | sas | sata | scsi | usb ] [--controller= BusLogic | I82078 …
```
> Vboxwrapper - handling of outdated vboxmanage command options

- samples/vboxwrapper/Makefile
- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vbox_vboxmanage.h
- samples/vboxwrapper/vboxwrapper.cpp
**Introduction**
Vboxwrapper allows to use VirtualBox multiattach/differencing disk images since version 26206.
Attaching a disk in this mode can't be done in 1 step.
Hence, a workaround suggested by VirtualBox had to be implemented in vboxwrapper and improved.
The required steps (in short):
1. Create a VM
2. Attach a virtual disk in normal mode to register it
3. Handle errors like the "4.0 or later" error ("closemedium"; see below)
4. Disconnect the disk from the VM but leave it in the registry
5. Reconnect the disk in multiattach mode ("storageattach")
For more details see:
#4602
#4603
Long term experience with LHC@home shows that errors like these happen more often than expected:
```
Command: VBoxManage -q storageattach "boinc_086a07090bec38dd" --storagectl "Hard Disk Controller" …
```
> Add race mitigation lock to vboxwrapper

- samples/vboxwrapper/vbox_vboxmanage.cpp
Fixes a logical bug that was introduced with the last commit to #5571.
The bug can cause an endless loop under certain conditions.
> Fix possible endless loop

- samples/vboxwrapper/vbox_vboxmanage.cpp
On LHC@home a user running Darwin 19.6.0 and Darwin 23.4.0 got the following error:
```
Could not set race mitigation lock.
Lockname: '/boinc_vboxwrapper_lock_c94b628801c684e7'
Error: 63, File name too long
```
A couple of internet sources state that on Darwin the filename size is limited to 31 characters plus trailing '0'.
> Fix 'File name too long' on Darwin

- html/inc/forum_rss.inc
- html/user/rss_main.php
we had a time limit of 90 days.
Change this so there's no limit by default,
and if you want a limit you can add e.g. ?ndays=90
> In exporting of project's news as RSS (rss_main.php), remove time limit.

- db/constraints.sql
- html/inc/bootstrap.inc
- html/inc/forum.inc
- html/inc/friend.inc
- html/inc/more.inc
- html/inc/pm.inc
- html/inc/user.inc
- html/inc/user_util.inc
- html/inc/util.inc
- html/project.sample/project.inc
- html/user/account_finish_action.php
- html/user/create_account_action.php
- html/user/edit_forum_preferences_action.php
- html/user/edit_forum_preferences_form.php
- html/user/edit_user_info_action.php
- html/user/friend.php
- html/user/login_action.php
- html/user/login_form.php
- html/user/openid_login.php
- html/user/pm.php
- html/user/stats.php
- html/user/team_founder_transfer_action.php
- html/user/team_join.php
- html/user/team_quit_action.php
- html/user/team_search.php
- html/user/user_agreetermsofuse_action.php
- html/user/user_search.php
We currently allow different accounts to have the same user name.
Hence in places where we need to identify users
(sending PMs, blocking users) we have to use numeric IDs,
which means that we have to display them in various places.
This is ugly; I'm not sure why I thought it was a good idea.
Anyway.  Add a project.inc option UNIQUE_USER_NAME.  If set:
- it won't let you create an account with a dup name,
of change your name to a dup
- it doesn't show user IDs anywhere
- in places where you specify users, you use names
This is now the default for new projects.
Existing projects - which have lots of duplicate names -
can't use it unless they de-dup their names somehow
(and this might anger users).
Also some minor code cleanup.  sprintf() is our friend.
> web: add option for making user name unique

- clientgui/BOINCClientManager.cpp
- clientgui/DlgExitMessage.cpp
Remove 'Stop running tasks...' checkbox from the Exit Confirmation dialog on linux when the client is configured to run as a daemon. Small refactoring.
This fixes #5601.
> [linux][client] Fix check whether the client is configured to run as a daemon.

- client/cpu_sched.cpp
> Client: don't start jobs that will exceed RAM

- mac_build/dependencyNames.sh
When building the BOINC client for Macintosh, both GitHub Actions Ci and local builds download the third-party dependent libraries using the URLs in _mac_build/dependencyNames.sh_. The Mac uses the c-ares library to enable curl to do asynchronous file transfers. The developers of c-ares have announced:
> Any distributions that are currently pulling packages from https://c-ares.org/download/c-ares-X.Y.Z.tar.gz (or even the legacy https://c-ares.haxx.se/) are now broken.  Please update your packaging scripts to point to the github release assets, which is now the official repository for signed release packages.
This PR updates the URL for c-ares in _mac_build/dependencyNames.sh_ to the new URL.
> Mac: update URL to download c-ares, which has moved to GitHub

- client/cpu_sched.cpp
- client/project.cpp
- client/project.h
- client/scheduler_op.cpp
- sched/sched_config.cpp
- sched/sched_config.h
- sched/sched_types.cpp
I recently changed the client so that its estimate of a job's WSS is at least wu.rsc_memory_bound.
This addressed a problem with CPDN apps,
which have small WSS for a while and then get big; the client would run too many of these at once
and when they get big the system would run out of RAM and/or swap.
However, some projects have rsc_memory_bound quite a bit larger than actual WSS,
and this change caused the client to run fewer of these jobs, causing idle CPUs in some cases.
Solution: have a per-project 'strict memory bound' flag, specified in config.xml.
For projects that set this (like CPDN) we'll estimate WSS the new way; otherwise we'll use the old way.
> scheduler/client: add notion of 'strict memory bound' projects

- client/client_msgs.cpp
- client/current_version.cpp
(affects only 'new client version' message AFAIK)
Relevant to #5676
> client: don't put HTML in event log messages

- drupal/sites/default/boinc/modules/boincuser/boincuser.module
Updated Android download instructions on join page.
@davidpanderson, please remove [footnote](https://github.com/BOINC/boinc/wiki/Simple-attach-usage#projects-using-old-attach) after this got merged.
Thanks
> [Drupal] Updated Android download instructions

- samples/vboxwrapper/vbox_vboxmanage.cpp
If Vboxwrapper couldn't find the Vbox 'home dir' (normally ~/.VirtualBox) based on env vars, it would create one: projects/virtualbox (owned by boinc_projects, not boinc_master)
This is wrong because
1) on startup, the client deletes anything in projects/
that's not a project directory
2) on Mac it causes installer error messages
because the dir is not owned by boinc_master.
Fix: don't create projects/virtualbox.
> vboxwrapper: don't create projects/virtualbox

- html/inc/bootstrap.inc
- html/inc/email.inc
- html/inc/pm.inc
- html/inc/prefs.inc
- html/inc/team.inc
- html/inc/user.inc
- html/inc/util.inc
- html/user/forum_forum.php
- html/user/forum_reply.php
- html/user/forum_search.php
- html/user/host_venue_action.php
- html/user/profile_menu.php
- html/user/sample_index.php
- html/user/show_coproc.php
- html/user/team_admins.php
- html/user/team_change_founder_form.php
- html/user/user_search.php
- html/user/view_profile.php
use a darker green than the bootstrap 'success' color
> make buttons more legible

- html/inc/host.inc
The PHP code (gpu_desc()) skipped GPUs with < 5 description fields. Older clients return only 4 fields.
> web: fix bug that hid GPUs in host page

- lib/prefs.cpp
If we parse for a target venue, and it's present,
and mod_time/source_project/source_scheduler appear after the venue, we were failing to parse them.
Fixes #5682
> client: fix minor prefs parsing bug

- html/inc/pm.inc
- html/user/pm.php
... rather than comma-separated.
User names can contain commas but not newlines.
Fixes #572
> web: in PM send to multiple users, but names/IDs on separate lines

- sched/db_dump.cpp
> db_dump: report encoding correctly ('utf-8' rather than 'iso-8859-1')

- html/inc/text_transform.inc
[code] and [pre] aren't nestable.
Process them separately from nestable constructs.
Fixes #1381
> web: fix edge case in bbcode processing

- 3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/add_optional_svg_support.patch
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/fix-static-deps.patch
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/fix_build_error_windows.patch
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/loaders-cache.patch
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/portfile.cmake
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/use-libtiff-4-pkgconfig.patch
- 3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
- 3rdParty/vcpkg_ports/ports/librsvg/CMakeLists.txt
- 3rdParty/vcpkg_ports/ports/librsvg/config.h.linux
- 3rdParty/vcpkg_ports/ports/librsvg/fix_io_svg_for_static_build.patch
- 3rdParty/vcpkg_ports/ports/librsvg/portfile.cmake
- 3rdParty/vcpkg_ports/ports/librsvg/unofficial-librsvg-config.cmake
- 3rdParty/vcpkg_ports/ports/librsvg/usage
- 3rdParty/vcpkg_ports/ports/librsvg/vcpkg.json
- clientgui/BOINCGUIApp.cpp
- linux/ci_configure_manager.sh
When BOINC for Linux is built with vcpkg, and links all the dependencies statically, gdk-pixbuf cannot load dynamically loaded modules (like SVG loader) during runtime. To fix thism we need to modify gdk-pixbuf in a way that it uses librsvg as a built-in format. However, librsvg internally requires gdk-pixbuf during build stage, that makes a circular dependency. To avoid this, we have to include necessary librsvg symbols into boincmgr binary manually and do some dummy calls to them to force linker to include them into the final binary.
This fixes: #5563.
> [vcpkg][linux] Add custom gdk-pixbuf and librsvg vcpkg ports

- lib/gui_rpc_client_print.cpp
Instead of 'reported time:', say 'acked by project:', which is more or less accurate.
Fixes #2268
> boinccmd: clarify old tasks output

- html/user/server_status.php
The scheduler is a CGI program, not a daemon; it doesn't have a PID file.
So the only way we can see if it's 'running'
is to check the 'stop_sched' trigger file.
Do this whether the scheduler is local or remote.
Fixes #2209
> server status page: show remote scheduler correctly

- html/inc/email.inc
- html/inc/user_util.inc
- html/ops/mass_email_script.php
- html/user/am_set_info.php
- html/user/create_account.php
- html/user/edit_email_action.php
- html/user/edit_email_form.php
- html/user/login_action.php
- html/user/openid_login.php
There are two types of email address check:
1) syntax check
2) stopforumspam.com (SFS) check: enabled by USE_STOPFORUMSPAM in project.inc
- Separate these.  Sometimes it's appropriate to use just syntax check.
When we do use SFS check, and the email is flagged,
we should tell the user what happened;
maybe they're incorrectly in the SFS DB.
- use PHP's filter_var() for the syntax check,
rather than our own funky regexp.
Fixes #1828
> fix email address checks

- html/inc/forum.inc
- html/user/forum_edit.php
- html/user/forum_forum.php
- html/user/forum_help_desk.php
- html/user/forum_index.php
- html/user/forum_post.php
- html/user/forum_reply.php
- html/user/forum_search_action.php
- html/user/forum_subscribe.php
- html/user/forum_thread.php
On the main Forums page, show all subscriptions
(to both threads and forums) with checkboxes,
so you can unsubscribe to multiple items at once.
Modernize the forum code here and there.
- Get rid of <span>s - we don't do our own CSS anymore.
- Have functions return strings rather than printing text; it makes them more general.
- Use table_row() etc. instead of printing <td> etc.
- Move code from top level to functions
- start_table() and end_table() always at same code level
Fixes #2595
(though I chose to do this on Forums index page rather than Community Preferences)
> web: facilitate unsubscription

- html/inc/db.inc
- html/inc/user.inc
- html/user/user_permissions.php
- only admins (which actually includes ADMIN, DEV, and SCIENTIST) can administer user permissions (not, e.g. moderators)
- Add a link to the user-permissions admin page on the home page of admins (there were previously no links to it)
- modernize the code of the admin page; replace _mysql_query() stuff
\
> web: fix user permissions admin

- api/boinc_opencl.cpp
- client/project.cpp
- clientgui/DlgItemProperties.cpp
- lib/cc_config.cpp
API: get_vendor() and boinc_get_opencl_ids() were missing Apple case,
causing missing device IDs
Manager:
show Apple GPU info in project properties
GUI RPC client: parse <ignore_apple_dev> in client config
(e.g. so that Manager shows if Apple GPU is ignored)
Fixes #5738
> Missing items for Apple GPU support

- client/cs_prefs.cpp
- lib/coproc.cpp
- lib/gui_rpc_client_print.cpp
- lib/opencl_boinc.cpp
When showing a system size (total RAM or VRAM, disk, swap)
use GB (with %.2f) instead of MB.
When showing the RAM or disk usage of particular job, use MB.
Fixes #4832
> client and boinccmd: show some RAM/disk sizes in GB rather than MB

- tools/backend_lib.cpp
A work generator can create and use its own DB connection.
Fix a bug in create_work() that incorrectly used the boinc_db connection
(which might not even be initialized).
Fixes #4032
> server: use correct DB connection in create_work()

- db/schema.sql
- py/Boinc/database.py
Going forward, BOINC databases should use char encoding utf8mb4
and collation utf8mb4-unicode-ci.
Each char can then be up to 4 bytes.
MariaDB/InnoDB has a limit of 767 bytes on index keys.
That means a limit of 191 chars on indexed fields.
Change the size of such fields from 255 to 191
(in some cases less, where indices involve other fields too).
Note: MySQL 8 doesn't have this issue.
make_project: use utf8mb4.
This change does not affect existing projects.
Fixes #4515
> database: make it work with utf8mb4

- client/client_state.cpp
- client/hostinfo_wsl.cpp
- lib/wslinfo.cpp
- lib/wslinfo.h
In the most cases, WSL2 (currently the latest) is the recommended version, but there are some cases when WSL1 is more suitable. For example, WSL1 is faster in some cases (e.g. file operations), and it is the only option for Windows 10 Home users. More details here: https://docs.microsoft.com/en-us/windows/wsl/compare-versions
> [Windows] Detect WSL version of enabled distros.

- client/client_state.cpp
- client/makefile_sim
- client/project.h
- client/rr_sim.cpp
- client/sim.cpp
- client/work_fetch.cpp
- client/work_fetch.h
- lib/cc_config.h
Fixes #5749 (hopefully)
Max concurrent is a limit on jobs, not processor instances.
The work fetch logic made the erroneous implicit assumption
that all jobs use 1 CPU.
So e.g. if project has max concurrent 4,
and the client has two 2-CPU jobs,
it will think (if work buf is zero) that there's
no point in fetching more work.
But in fact the project could use 8 CPUs, so 4 are idle.
Fix: if a project has MC constraints,
then for each resource compute 'mc_max_could_use':
the max # of instances the project could use, given its MC constraints.
Use this to compute the project's shortfall,
and hence to decide whether to fetch work from it.
Note: the way mc_max_could_use is computed is crude;
it takes the max over all apps,
when it's possible that only one of them has a MC constraint.
This could …
> address issue with max concurrent and work fetch

- api/ttfont.cpp
- client/check_security.cpp
- lib/gui_rpc_client.cpp
- lib/gui_rpc_client_print.cpp
- lib/proc_control.cpp
I was testing boinc_cmd and was surprised to see that it was
printing the GUI RPC XML messages.
Turned out this was because of a puts(req) conditioned on DEBUG,
which is set (globally) when you configure with --enable-debug.
I looked around and there were several other cases of
very specific debugging printf's enabled by DEBUG.
This isn't the right idea.
A global flag should do global things (like compile with -g).
Use specific #defines (like SHOW_MSGS for GUI RPCs).
> clarify meaning of DEBUG in C++ code

- html/inc/db.inc
This is used in the upgrade script and some old web pages. You need to check $mysql->connect_errno after doing new mysqli
Fixes #2481
> database: report connection failure in _mysql_connect()

- client/client_state.cpp
- client/work_fetch.cpp
- lib/coproc.cpp
The client shows messages like
8/16/2024 8:13:47 PM | PrimeGrid | Not requesting tasks: don't need (CPU: ; NVIDIA GPU: ; Intel GPU: )
The reasons are missing.
This is because there are two levels of reason for not fetching a resource:
project-level (like it has no app versions that use the resource)
and global (like the buffer is full).
We were only looking at the project-level reason.
Look at both, to produce e.g.
8/16/2024 8:13:47 PM | PrimeGrid | Not requesting tasks: don't need (CPU: buffer full; NVIDIA GPU: buffer full; Intel GPU: buffer full)
> client: fix work fetch messages

- client/acct_mgr.cpp
- client/acct_mgr.h
- client/cs_scheduler.cpp
- client/rr_sim.cpp
SU uses pre-made project accounts, which users can't log in to.
> If using dynamic AM (like Science United) use prefs from the AM, not from projects

- client/client_types.h
- client/net_stats.h
- client/sim.h
- client/work_fetch.h
- lib/common_defs.h
- lib/coproc.h
- lib/opencl_boinc.h
- lib/prefs.h
To create zero-filled structs, we use a method where we create a static struct using a 'dummy constructor' taking an (unused) int argument. The problem is that if you mistakenly have e.g.
COPROC c = 1;
you don't get a compile error;
you get an uninitialized struct as if you had done
COPROC c = COPROC(1);
I changed this so that we use a type DUMMY_TYPE
(guaranteed not to be convertible from anything)
as the arg type for the dummy constructors.
So now you get a compile error in the above case.
> C++ code: eliminate a source of potential bugs

- lib/common_defs.h
- lib/gui_rpc_client.cpp
Official BOINC packages for Linux use '/var/lib/boinc' directory instead of '/var/lib/boinc-client'.
This fixes #5775.
> [linux] set default data directory location to '/var/lib/boinc'.

- html/inc/boinc_db.inc
- html/inc/db.inc
- html/inc/db_conn.inc
Also always use mysqli interface
> PHP DB code: clean up the logic, and allow for > 1 readonly replica

- client/gui_rpc_server_ops.cpp
In many places we use int where in theory we should use size_t or ssize_t. This would cause problems if things like RPC messages exceeded 2GB.
Should fix Coverity 426653
> client: fix potential byte count overflow

- sched/db_purge.cpp
- sched/script_validator.cpp
- sched/validate_util2.cpp
- sched/validate_util2.h
A 'transient error' is one that will go away in a while, e.g. an fopen failure because of a broken NSF mount. In general, the BOINC back-end code (validation, assimilation) handles transient errors sensibly:
if there's a bad NSF mount, it retries validation for a few hours rather than marking thousands of jobs as failed.
Extend this to script-based validation.
If a script (either init_result or compare_results) exits with 3, treat that as a transient error.
Treat other nonzero exits (or lack of an exit code) as a permanent error.
More generally (for all validators) add a return value VAL_RESULT_TRANSIENT_ERROR for init_result() and compute_results(). This means any transient error.
Previously we checked only for ERR_OPENDIR.
And for compare_results() we treated all nonzero returns as …
> validator: handle transient errors

- html/inc/util_ops.inc
- html/ops/cancel_workunits.php
Don't use hardwired constants in DB queries.
Note: we have 2 scripts that do about the same thing ops/cancel_workunits.php
ops/cancel_wu_form.php
Both are linked to from ops page.  Remove one of them.
Fixes #5807
> fix typo in script to cancel WUs

- sched/script_validator.cpp
- sched/validate_util2.cpp
> validator: fix potential infinite loop

- samples/vboxwrapper/vbox_vboxmanage.cpp
With version 7.1.0 VirtualBox changed the default behavior of RDP encryption if a user hasn't created own certificates.
See the VirtualBox changelog:
> VirtualBox 7.1.0 (released September 09 2024)
> VRDE: If user does not set up TLS with custom certificates, enable it with self-signed certificate, including issuing a new one before the old one expires
Old default:
VirtualBox used hard wired internal certificates or even no encryption.
Since the self-signed certificates are not known by the host the first RDP connection to a VM starts with a warning like this (provided by a volunteer from LHC@home):
The VirtualBox manual gives a hint how the old behavior can be enabled:
https://www.virtualbox.org/manual/topics/remotevm.html#vrde-crypt
Vboxwrapper should configure VMs using standard RDP …
> Set virtualbox vrde-property

- samples/condor/Makefile
- samples/multi_thread/Makefile
Fixes ##5690
Added a **install** rule for the following Makefiles:
- condor
- multi_thread
`make install` no longer fails for samples.
> Added a placeholder install step

- lib/Makefile.mingw
boinc_stdio.h should be installed as well when doing a 'make -f lib/Makefile.mingw install'
> lib/Makefile.mingw: add boinc_stdio.h to install headers

- clientgui/DlgItemProperties.cpp
As suggested by @RichardHaselgrove in #5827, this PR adds the plan class to the properties window.
I considered having the plan class line only visible if there was one present, but if someone is expecting a plan class and doesn't see it, then this should at least indicate that one was not found.
[Manager] Added plan class name to task's properties window.
> [Manager] Add application name to task properties window

- html/inc/forum_db.inc
- html/inc/pm.inc
> web: fix PHP8 deprecation warnings

- client/app.h
- client/client_state.h
- client/cs_notice.h
- client/http_curl.h
- client/project.h
- clientgui/AsyncRPC.h
- clientgui/BOINCListCtrl.h
- clientgui/DlgEventLog.h
- clientgui/DlgOptions.h
- clientgui/MainDocument.h
- clientgui/ViewNotices.h
- clientgui/sg_BoincSimpleFrame.h
- clientgui/sg_DlgPreferences.h
- lib/app_ipc.h
- lib/common_defs.h
- lib/gui_rpc_client.h
- lib/prefs.h
- lib/str_util.h
- lib/url.h
Browsing through the code, I have found several functions defined in header files that Visual Studio found did not have an associated function nor inline code.  Since these functions do not exist, this PR removes them.
I have broken up the PR into three commits; each commit is for a subfolder (client, manager, and lib).
This PR does not clean up ALL unused functions.  There were some functions that were empty constructors that I didn't feel comfortable removing.  Another thing I discovered were some functions were noted by Visual Studio as not defined, but the function was written in one or more preprocessor definitions.  With that said, I tried to carefully remove only functions that were obvious to me that weren't defined.  Thank you in advance for …
> Remove unused functions

- html/user/forum_forum.php
Users not logged in get a 
```
Warning: foreach() argument must be of type array\|object, null given in /home/boinc/whatever/html/inc/forum.inc on line 1420
```
message because `subs` is `null`, not `[]` by default and it is called so in the foreach.
fix warning when users are not logged in on the forums
> subs should be empty by default, not null

- samples/vboxwrapper/vboxwrapper.cpp
Volunteers from LHC@home often report issues (false positives) in connection with the heartbeat file detection.
In most cases it affects Windows hosts.
This PR introduces a revised heartbeat file handling and a slightly modified reporting.
> Revised heartbeat check

- client/client_state.cpp
- client/hostinfo_win.cpp
- client/hostinfo_wsl.cpp
- client/log_flags.cpp
- lib/cc_config.cpp
- lib/cc_config.h
- lib/hostinfo.h
- lib/util.cpp
- lib/util.h
- lib/wslinfo.cpp
- lib/wslinfo.h
- samples/wsl_wrapper/wsl_wrapper.cpp
- sched/plan_class_spec.cpp
- sched/plan_class_spec.h
- sched/sched_types.cpp
- sched/sched_types.h
- New philosophy: always query the presence of software (WSL distros, Docker)
even if client config doesn't allow its use.
Send the config info to scheduler, and enforce it there.
- New philosophy: allow running jobs in any WSL distro
except those disallowed in the config
- Add plan class support for WSL and Docker app versions
- client: query the libc version of WSL distros and report it in scheduler requests.
The plan class entry for a WSL app version can specify a min libc version.
- wsl_wrapper: add --min_libc_version cmdline arg (should match plan class spec)
> Extend support for WSL and Docker apps

- samples/vboxwrapper/vboxwrapper.cpp
When time leaps happen (e.g. switching between normal time and DST) vboxwrapper still falsely cancels tasks reporting "missing heartbeat".
Instead of doing many complex date/time checks simply count back to back inconsistencies before cancelling a task.
> Heartbeat checks deal with time leaps

- html/inc/profile.inc
We were checking specifically for '2.0'.
If you had a later version (like 2.2) it would think you had an old version, and use an old image conversion function that produces wrong-colored results.
> web: parse gd version number correctly

- client/app.cpp
- lib/procinfo.cpp
- lib/procinfo.h
We were checking for VBoxSVC.exe and, if a VBox app is running, counting its CPU time as BOINC-related.
Should be 'VBoxHeadless.exe' on Win.
May be different on Mac/Linux, so use '*vbox*', case-insensitive
> client: measure CPU time of VBox apps correctly

- client/client_state.cpp
- client/client_state.h
- client/cs_apps.cpp
- client/hostinfo_linux.cpp
- lib/hostinfo.h
- lib/util.cpp
- lib/util.h
- lib/win_util.cpp
- lib/win_util.h
- samples/docker_wrapper/docker_wrapper.cpp
The names of images and containers created by docker_wrapper have a particular form:
boinc__<proj>__<wuname> and boinc__<proj>__<resultname>.
docker_wrapper normally cleans up after itself.
But if it crashes, these objects could hang around forever, taking up disk space.
So clean them up on client startup, as follows:
make lists of the image/container names for active Docker tasks.
Then go through the Docker images and containers.
Remove any that
- were created by Docker wrapper (i.e. have boinc__ names)
- aren't in the active-task lists
On Unix, do this on the host itself if it has Docker installed.
On Win, do it for every WSL distro that has Docker installed.
> client: remove unused Docker images and containers on startup

- html/user/forum_forum.php
- html/user/submit.php
> web: fix two undefined var bugs

- client/app_test.cpp
- client/cs_apps.cpp
- html/user/buda_submit.php
- samples/docker_wrapper/docker_wrapper.cpp
- samples/docker_wrapper/test/main.sh
To do this, put in your Dockerfile e.g.
ENV ARGS ""
CMD ./main.sh $(ARGS}
The args (any unparsed args on the docker_wrapper cmdline)
are then passed to the container in the ARGS environment variable.
Access them in main.sh e.g. with
./worker $ARGS
> docker_wrapper: allow passing args into container

- client/cs_platforms.cpp
- client/hostinfo_win.cpp
- lib/hostinfo.h
With this commit a new platform name 'windows_arm64' added. Also, according to the https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-x86-emulation, Windows 10 on ARM supports x86 applications, and Windows 11 on ARM supports x64 applications. That is why we will be checking what version of Windows we are running on, and adding 'windows_intelx86' on Windows 10 and later (I suppose, this is will set always) and 'windows_x86_64' on Windows 11 and later (nothing later at the moment, but we are looking into the future!).
This fixes #5934.
> [Windows] Set correct platform name when running BOINC client on Windows on ARM.

- client/app.h
- client/app_control.cpp
- client/app_start.cpp
- client/client_state.cpp
- client/client_state.h
- client/main.cpp
- samples/wrapper/wrapper.cpp
Fixes #5936
wrapper: unzip input files only first time we run
client: set up slot dir only at start of job.
This is a little tricky because of async file copy.
Deal with this by creating a 'boinc_setup_complete' file
after all files are copied.
These fixes address a problem where:
- wrapper job starts, unzips its output files, deletes the .zip
- job stops (e.g. client exits)
- job restarts; client sees that .zip file isn't in slot dir,
copies it again.
- wrapper starts, unzips .zip file again.
The fixes address both (new client, old wrapper) and (old client, new wrapper).
> fix problem where wrapper unzips input files each time it restarts

- installer/Control.cpp
- installer/Control.h
- installer/ControlTable.cpp
- installer/Installer.cpp
- installer/InstallerStrings.cpp
- installer/InstallerStrings.h
- installer/RadioButton.cpp
- installer/RadioButton.h
- installer/RadioButtonTable.cpp
- installer/RadioButtonTable.h
- installer/boinc.json
- installer/locale/en.json
- installer/main.cpp
- win_build/installer_setup.vcxproj
Moved RadioButton definitions closer to the relevant controls.
Locale files now should be defined in the main JSON file.
Add possibility to pass main JSON file as a parameter to the installer.exe.
> Refactor boinc.json structure a little bit.

- html/user/user_agreetermsofuse.php
Remove useless call to `redirect_to_secure_url`.
The call is already made in a file that is included:
https://github.com/BOINC/boinc/blob/c67393e6d11e4dafe11b54fd9470fa254f3b1c36/html/inc/util.inc#L1167
Also, the function `redirect_to_secure_url` requires 0 parameter, here we were providing one:
https://github.com/BOINC/boinc/blob/c67393e6d11e4dafe11b54fd9470fa254f3b1c36/html/inc/util.inc#L1156
N/A
> remove useless redirect

- html/inc/consent.inc
- html/inc/prefs_util.inc
- html/inc/user_util.inc
- html/inc/util.inc
- html/inc/util_basic.inc
- html/user/am_set_host_info.php
- html/user/buda.php
- html/user/manage_app.php
- html/user/manage_project.php
- html/user/sandbox.php
- html/user/team_forum.php
- html/user/team_founder_transfer_action.php
- Send all cookies as HttpOnly (don't let Javascript see them)
- If page sending cookie is HTTPS, make the cookie secure
- Often we have something like: $name = get_str('name'); if (!lookup($name)) { error_page("can't find $name"); } Can't do this; it can be exploited for XSS attacks. Just say 'Can't find file' or whatever
- Don't show database error messages
> web: fix various vulnerabilities

- html/inc/util_basic.inc
- html/user/get_output.php
- html/user/get_output3.php
- html/user/job_file.php
- html/user/openid_login.php
- html/user/prefs_edit.php
- html/user/submit_rpc_handler.php
Most of these involve putting user text in error messages. Use htmlspecialchars() for this.
filenames: require POSIX portable names
> web: fix various XSS vulnerabilities

- clientgui/ProjectInfoPage.cpp
- clientgui/ProjectInfoPage.h
Fixes #1552 
This PR adds a feature to the Add Project wizard that will change the text of a project to gray if the project is already added.  This is accomplished by storing a string array of all projects that are available in the wizard, another string array of all projects currently attached.  Each array is then canonicalized, then trimmed of "http", etc.  Arrays are then compared and if any match, the text is set to gray.  The ability to make the text gray was enabled by adding the property "wxLB_OWNERDRAW" to the wxListBox.
For a "simple" change, this is actually a bit more complicated.  A few design notes:
1. Adding the Ownerdraw property did more than provide the ability to change the text color.  The background color of the wxListBox, wherenever there …
> [Manager] Gray out projects in project wizard that are already attached

- api/gutil.cpp
Fixes a warning during compilation
```
gutil.cpp: In member function 'void STARFIELD::build_stars(int, float)':
gutil.cpp:473:27: warning: 'void* calloc(size_t, size_t)' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
473 |     stars = (STAR*)calloc(sizeof(STAR), (long unsigned int)nstars);
|                           ^~~~~~~~~~~~
gutil.cpp:473:27: note: earlier argument should specify number of elements, later size of each element
```
The calloc function takes two arguments: the number of elements and the size of each element. However, the arguments here are swapped.
> swap calloc arguments

- client/cs_files.cpp
If someone runs the client in a directory (e.g. their home directory) that happens to contain a directory projects/, it deletes everything there! I don't know what I was thinking.
Print a message instead.
Fixes #6000
BTW: maybe we should have called it boinc_projects/ instead of projects/.
For now let's not change this.
> client: don't delete unrecognized stuff in projects/

- client/scripts/boinc-client.service.in
- tests/linux_package_integration_tests.py
BOINC volunteers running VirtualBox tasks on Linux occasionally report errors like this if BOINC runs as a systemd service:
```
2024-12-28 01:20:15 (16867): Detected: VirtualBox VboxManage Interface (Version: 7.0.12)
2024-12-28 01:20:20 (16867): Error in host info for VM: -182
Command:
VBoxManage -q list hostinfo 
Output:
VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
2024-12-28 01:20:20 (16867): WARNING: Communication with VM Hypervisor failed.
2024-12-28 01:20:20 (16867): ERROR: VBoxManage list hostinfo failed
2024-12-28 01:20:20 (16867): called boinc_finish(1)
``` …
> Revert to 'ProtectSystem=strict' in boinc-client.service and make '/tmp' writable

- html/user/get_output.php
> get_output.php: send empty file if no files to send, rather then error messages

- sched/handle_request.cpp
> Rename 'Protected application execution' to 'Service Install'.

- client/client_state.cpp
- client/client_types.cpp
- client/cs_statefile.cpp
> client: fix bug where avg_ncpus for anonymous platform apps defaults to zero

- samples/vboxwrapper/vbox_vboxmanage.cpp
The VBox home dir (where it keeps its files) is
"/Library/Application Support/BOINC Data/.VirtualBox/",
not ~/.Virtualbox (the latter may be inaccessible)
Fixes #6015
> vboxwrapper (Mac): fix startup failure on Mac

- lib/crypt.cpp
- lib/crypt_prog.cpp
The ENGINE API is deprecated in OpenSSL 3.0; the intended replacement is the Provider API.
See also #5356, for which this addresses one (but not all) of the reported deprecation warnings.
This is also motivated by [F41 Change Proposal: OpenSSL Deprecate Engine (system-wide)](https://discussion.fedoraproject.org/t/f41-change-proposal-openssl-deprecate-engine-system-wide/111344). OpenSSL ENGINE API support has not been removed from Fedora, but there is an effort to identify packages that require it and gradually fix them. A similar change appears [in RHEL10](https://www.redhat.com/en/blog/openssl-3-providers-rhel-10).
This simply removes each instance of `#include <openssl/engine.h>` and the one function call to OpenSSL’s ENGINE API, …
> Remove OpenSSL engine support

- installer/installer_setup/main.cpp
> [windows] when running installer, search for DLLs in the system directory only since the installer itself doesn't rely on any custom DLLs.

- installer/boinc.json
I was not able to reproduce neither #1034 nor #1035, also it looks like the 'repair' option is not available anymore on Windows 11, and when selecting 'modify' it provides you two options: 'repair' and 'uninstall'. This looks valid to me, as if the user want to change something in the installation, it's always safer to uninstall and install again with the correct configuration, since it's a fast operation, and no user files are affected during it.
This fixes #1034 and #1035.
> [windows][installer] enable 'change'\'modify' and 'repair' options.

- lib/app_ipc.cpp
- lib/str_util.h
- lib/url.cpp
- lib/util.cpp
> client and docker_wrapper: lower-case image and container names

- html/inc/text_transform.inc
These probably don't need to exist but at least
they should point to the right place.
> web: the BBCode processor has [github] tags.

- html/inc/forum.inc
- html/user/forum_forum.php
- html/user/forum_post.php
Currently, if we direct someone to the "Questions and problems" forum,
and they're not logged in, it's a dead end;
they aren't told that they need to log in
(and/or create an account) in order to post a question. Add this.
> web: on forum page, tell user they have to log in to post

- html/user/forum_banishment_vote.php
- html/user/forum_banishment_vote_action.php
- html/user/forum_moderate_post.php
- html/user/forum_moderate_thread.php
- html/user/forum_post.php
- html/user/forum_rate.php
- html/user/forum_reply.php
- html/user/forum_subscribe.php
- html/user/forum_thread_vote.php
- html/user/forum_user_posts.php
don't just proceed with a null object
> web: in pages that take an ID as an arg, show error if not valid ID

- clientsetup/win/launcher.cpp
> [windows] Fix installer to start BOINC unelevated.

- client/app_start.cpp
- client/client_types.h
- client/result.h
... rather than 'docker'
Related to #6028
> client: in init_data.xml file for BUDA jobs, pass the BUDA variant as plan class

- samples/docker_wrapper/docker_wrapper.cpp
> docker wrapper: if image name specified in config file, use it and don't delete

- samples/vboxwrapper/vbox_vboxmanage.cpp
The 'VBox home directory' is where VBox writes log files
(which are read by vboxwrapper).
If this is not specified by the env var VBOX_USER_HOME,
we need to create it somewhere and set the env var to point there.
Previously we put it in <datadir>/projects.
That's no good because it's not a project, and the client erased it.
We also tried putting it in the (real) user's home dir.
That's no good because
1) we shouldn't mess with the home dir
2) in sandboxed configs we're running as user 'boinc_projects',
and don't have access to the home dir.
According to https://boinc.berkeley.edu/sandbox_design.php,
the only places 'boinc_projects' can write are
projects/, slots/, and their subdirectories.
So the logical places to put .VirtualBox are
this job's slot directory, or its project directory.
I …
> vboxwrapper: create the 'virtualbox home directory' in the project dir

- client/client_state.cpp
- client/cs_statefile.cpp
The BUDA changes copy resource usage (and cmdline) from either WU or APP_VERSION.
Need to do this after app_config files have been parsed, otherwise they'll have no effect.
Fixes #6072
> client: handle app_config.xml correctly

- client/cs_scheduler.cpp
When processing a scheduler reply, we were copying info (e.g. resource usage) from <app_version> elements
into the corresponding APP_VERSION objects.
This undoes any params specified in app_config.xml So I'm not sure that app_config.xml ever worked except initially.
The reason for this was in case projects tweaked app version parameters. But they're not supposed to do this.
App versions are immutable.
If you want to change something, make a new app version.
Fixes #6072 (hopefully)
> client: don't overwrite settings in app_config.xml

- client/main.cpp
Per Microsoft's notes on setvbuf:
> The setvbuf function allows the program to control both buffering and buffer size for stream. stream must refer to an open file that hasn't undergone an I/O operation since it was opened.
Source:  [https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setvbuf?view=msvc-170#remarks](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setvbuf?view=msvc-170#remarks)
If a user were to run the Client from the command line and use both --redirectio and --detach_console, the current code would create the output log files.  However, after the console is detached, this causes an I/O operation, and therefore nothing else can be written to the log files.  By detaching the console before the diagnotic logs are …
> [Client] [Windows]  Move location of FreeConsole within init_core_client

- clientgui/CompletionErrorPage.cpp
Fixes #3055 
In the add project wizard under the CompletionErrorPage, if a server message is provided it is wrapped to the width of the wizard page.
Example:
Please note, if the server sends a message that has a long word (such as an URL), the wrap function does not work beyond that word.  I believe this is a function of wxWidgets that we cannot bypass.
None considered.
[Manager] Under "Add project" wizard, message from server for a failed project attempt now wraps to the wizard window.
> [Manager] Add wrap function to server message

- samples/vboxwrapper/vbox_vboxmanage.cpp
- samples/vboxwrapper/vboxjob.cpp
- samples/vboxwrapper/vboxjob.h
VirtualBox manual suggests `virtio` network driver to be the best choice for (recent) Linux guests.
Nonetheless, when a Linux VM is created without a driver is explicitly set, it configures an `Intel Pro` emulation, most likely for maximum compatibility.
Further information can be found here:
https://www.virtualbox.org/manual/topics/networkingdetails.html
This PR sets `virtio` as default driver if a Linux guest can be assumed.
Otherwise it keeps the default `Intel Pro`.
In addition it allows to manually overrride the selection using `<vm_network_driver>custom_name</vm_network_driver>` in `vbox_job.xml`.
Also added to `vbox_job.xml`:
An option `enable_nat_dns_host_resolver` which specifies whether the VirtualBox NAT engine uses the host system's resolver mechanisms to handle DNS requests.
> improve vboxwrapper network setup

- clientgui/AdvancedFrame.cpp
- clientgui/BOINCBaseView.cpp
- clientgui/BOINCBaseView.h
- clientgui/ViewNotices.cpp
- clientgui/ViewNotices.h
- clientgui/ViewResources.cpp
- clientgui/ViewResources.h
- clientgui/ViewStatistics.cpp
- clientgui/ViewStatistics.h
Fixes #6098 (in part)
According to #6098, there is the following warning under the latest version of wxWidgets:
```
AdvancedFrame.cpp:1570:25: warning: ‘wxTimerEvent::wxTimerEvent()’ is deprecated: wxTimerEvent not supposed to be created by user code [-Wdeprecated-declarations]
1570 |         wxTimerEvent    timerEvent;
```
Upon studying the code, I found that _CBOINCBaseView::FireOnListRender()_, _CBOINCBaseView::OnListRender()_, _CViewNotices::OnListRender()_, _CViewResources::OnListRender()_ and _CViewStatistics::OnListRender()_ are never called directly from a wxTimer event and so do not need the wxTimerEvent argument. I removed that argument, which eliminated the need for the `wxTimerEvent    timerEvent;` declarations in _CAdvancedFrame::OnRefreshView()_ and …
> Fix deprecated warning about wxTimerEvent::wxTimerEvent()

- html/inc/forum_db.inc
- html/ops/delete_spammers.php
- add comments
- add --all option.  Recommended default for BOINC projects. Does --teams, --user_url, --profiles
- --teams: delete teams with no founder
Also fix a small bug in forum code: BoincDb::readonly no longer exists
> improvements to spam deletion script

- html/inc/boinc_db.inc
In `BoicDB::get()` if `self::$dbnum` is currently 0 or 1, it is handled as a boolean value and thus the comparison with the new `$dbnum` is a boolean comparison. This works for 0 or 1, but not for other values (like 2, which is also boolean `true`). Therefore numeric values need to be specified explicitly.
Fixes a problem in #5697 that slipped through during original review/testing. I had that in my MR (#5695), though, to fix  the same problem.
> html/inc/boinc_db.inc: fix $dbnum comparison in BoicDB::get()

- samples/vboxwrapper/vbox_common.cpp
- samples/vboxwrapper/vbox_common.h
- samples/vboxwrapper/vbox_vboxmanage.cpp
With PR #6119 `launch_vboxsvc()` has been removed from vboxwrapper.
As a result code snippets using `vboxsvc_pid_handle` and `vboxsvc_pid` (which were set in that function) can also be removed.
> Cleanup 'launch_vboxsvc' associated code

- samples/vboxwrapper/vboxwrapper.cpp
Compiling vboxwrapper with warnings enabled prints this:
```
vboxwrapper.cpp: In function ‘int main(int, char**)’:
vboxwrapper.cpp:511:11: warning: ignoring return value of ‘char* getcwd(char*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
511 |     getcwd(path, sizeof(path));
|     ~~~~~~^~~~~~~~~~~~~~~~~~~~
```
To get rid of the warning replace getcwd() with boinc_getcwd().
> Replace getcwd() with boinc_getcwd()

- db/boinc_db_types.h
- sched/sched_types.cpp
The client sends docker_type, not docker_available.
> scheduler: update parsing of host info.

- client/client_types.cpp
- html/user/buda.php
- lib/hostinfo.cpp
BUDA: the user file sandbox system doesn't know about executable flags.
This is OK on Win because everything is executable, but on Unix BUDA apps were failing.
Fix this by making all BUDA application files executable.
client: fix bug when changing file to executable
BUDA variant creation: mark all app files as executable.
docker_wrapper, Linux: fix parsing of Docker type
Fixes #6141 (and others not reported yet)
> debug BUDA on Unix

- samples/docker_wrapper/Makefile
- samples/docker_wrapper/docker_wrapper.cpp
- win_build/docker_wrapper.vcxproj
Add 'web_graphics_guest_port' option to job.toml config file. If set:
- allocate a host port
- tell Docker to map the guest port to host port
- tell the BOINC client to get HTML graphics at http:localhost:host_port
Fixes #6146
> docker_wrapper: support HTML graphics

- html/inc/db_ops.inc
- html/inc/result.inc
- html/inc/submit_util.inc
- html/inc/util_ops.inc
- html/user/server_status.php
Much of the db_ops code is substandard in various ways.
> web: use symbols rather than hardwired numbers for states in DB queries

- client/hostinfo_unix.cpp
podman build with a remote FS doesn't seem to work. For now, use docker instead of podman.
> client, Linux: don't check for podman

- samples/docker_wrapper/docker_wrapper.cpp
- samples/docker_wrapper/toml.h
Fixes warnings when DockerWrapper is compiled on Linux with gcc 14.2.1.
```
In file included from docker_wrapper.cpp:91:
toml.h: In function ‘toml::ParseResult toml::parse(std::istream&)’:
toml.h:390:47: warning: redundant move in initialization [-Wredundant-move]
390 |     return ParseResult(std::move(v), std::move(parser.errorReason()));
|                                      ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
toml.h:390:47: note: remove ‘std::move’ call
```
```
In function ‘fprintf’,
inlined from ‘create_container’ at docker_wrapper.cpp:432:20:
/usr/include/bits/stdio2.h:111:24: warning: ‘host_port’ may be used uninitialized [-Wmaybe-uninitialized]
111 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
|                        ^
docker_wrapper.cpp: In function …
```
> Fix DockerWrapper compiler warnings

- lib/hostinfo.cpp
- lib/util.cpp
- lib/util.h
Change timeout for Docker commands from 10s to 600s.  Build commands can take a while.
In parsing docker version, parse anything of the form '* version a.b.c*'
Fix bug in popen() error checking.  Set errno=0 first.
> client and docker_wrapper: bug fixes

- lib/url.cpp
- sched/handle_request.cpp
Fixes a bug where an account manager has an old URL with leading www;
causes duplicates of the project in the client.
> client: strip leading www. from master URLs

- sched/handle_request.cpp
This includes version and type,
and also whether WSL and/or docker use are banned by prefs. From this we can find the number of Docker-capable hosts.
> scheduler: add docker info to host.serialnum

- client/hostinfo_linux.cpp
- client/hostinfo_unix.cpp
- lib/hostinfo.h
If it's remote, podman doesn't work without complex config changes
> client (Linux): check for podman only if BOINC data dir is not remote

- client/hostinfo_unix.cpp
... which makes docker an alias of podman.
Note: there should be no reason to use podman-docker now that we allow podman if data dir is not remote.
Fixes #6141
> client (Linux): parse podman version if using podman-docker

- clientgui/BOINCGUIApp.cpp
- clientgui/BOINCGUIApp.h
- mac_installer/PostInstall.cpp
- mac_installer/finish_install.cpp
- mac_installer/uninstall.cpp
Mac installer, uninstaller:
* Whenever possible use login item launch agent instead of old-style login item
* Avoid  calling System Events so as not to display an alert "Installer wants to control your computer" that might alarm the user.
Previous versions of the Mac installer switched from the old style login items to using the newer launch agent method only for MacOS 13.0, when the old style ones stopped working. This version of the Mac installer uses the newer method for MacOS 10.13 or later.
If a previous BOINC install set a login item launch agent, it already removed the old style login item at that time, so we can avoid that alert.
> Mac tweaks to installer, uninstaller

- lib/util.cpp
We were doing this on Unix but not Win.
I think this affects only docker_wrapper.
Fixes #6190
> run_command(): return command output as \n-terminated lines

- clientgui/BOINCGUIApp.cpp
On the Mac, BOINC Manager's implementation of the -s or --systray argument was broken. This fixes it.
> Mac Manager: fix response to -s or --systray argument

- samples/docker_wrapper/docker_wrapper.xcodeproj/project.pbxproj
Allow building docker_wrapper on the Mac without providing a code signing identity so no signing certificate is required.
Fixes #6205
> Mac: build docker_wrapper without providing a code signing identity

- client/client_state.cpp
- client/hostinfo_unix.cpp
- samples/docker_wrapper/docker_wrapper.cpp
- client: fix lookup_project() bug. Note to self: don't use strcpy on overlapping areas! It works on some libc but not others
- client: don't show output of 'podman machine' commands
- docker_wrapper: for -v host:guest args, the 'host' part needs to be a full path with Mac/podman
> client and docker_wrapper: get it to work on MacOS/podman

- html/inc/util.inc
- html/inc/util_basic.inc
- html/user/buda.php
- html/user/sandbox.php
- user file sandbox: improve error messages if bad filename Note: we don't currently allow spaces in sandbox filenames. This restriction probably isn't necessary.
- support dark mode if browser settings request it
> web: minor fixes

- samples/wrapper/wrapper.cpp
Use vector<string> instead of argc/argv for passthrough args.
Pass extra cmdline to tasks only if --passthrough_child is present.
> wrapper: code cleanup; no functional change

- .github/workflows/linux.yml
Fixes #6219 
Sets arm64 as the `RELEASE_ARCH` under the workflow step "Build apps for arm64" in `linux.yml`.
This is a band-aid fix, imo, but reworking the workflow to explicitly set the arch for every build might be more extensible, as right now it's assumed it's x86_64 unless told otherwise, and we're only 'telling it otherwise' when it's arm64. Not risc-v, for example.
N/A - Developer-facing only
> Workflow: Set RELEASE_ARCH for arm64 build non-release

- html/inc/bootstrap.inc
- html/user/buda.php
- html/user/buda_submit.php
- html/user/get_output3.php
- html/user/sandbox.php
- BUDA: allow variants with no input files
- BUDA: make app files sticky to avoid repeated download (at somepoint we'll think about how to eventually delete them from client)
- BUDA: show text files correctly
- show Ctrl-click instructions for multi-select
- expand multi-file selection box to 12 lines
- output file display: show files correctly
- sandbox: striped table
> Web: Sandbox and job submission fixes (mostly for BUDA)

- linux/arm64/build_curl_arm64.sh
- linux/arm64/build_example_arm64.sh
- linux/arm64/build_openssl_arm64.sh
Fixes #6226
Removed libatomic from the aarch64 build of BOINC.
It's still left alone in the android builds, but if it's not needed there either we could also remove it there.
No real alternates are possible besides leaving libatomic referenced. 
Libatomic is no longer a requirement for running BOINC apps using aarch64 hardware on linux.
This would've mostly impacted people running builds of BOINC software that was built using the workflows in github. I'm not aware of how the publicly facing builds are handled, if it's any different to begin with, or if anyone ever noticed because it's possible a lot of distros come with libatomic pre-installed.
> Remove libatomic reference in linux aarch64 build

- client/mac_address.cpp
- lib/unix_util.cpp
PR #4864 introduced 4 erroneous changes of the form
sprintf(buf, sizeof(buf), ....)
where buf is a char*.
(Note: in this case sizeof(buf) is 8.
It is NOT the size of the memory area that buf points to).
One of these (in file_names.cpp) was fixed in a later PR. This PR fixes the other 3.
Hopefully we didn't miss any.
> Fix snprintf() errors introduced in PR #4864

- html/inc/bootstrap.inc
- html/inc/submit_util.inc
- html/user/buda.php
- html/user/buda_submit.php
- html/user/submit.php
- BUDA: add "min success instances" and "max total instances" to BUDA varian
ts.
e.g. min_success=1 and max_total=3 means send instances
until 1 succeeds, but don't send more than 3
Note: I made these a property of the variant because that's
where the input template is.
This is much simpler than making it a batch property, for example.
- BUDA: in displaying a variant, show
- Docker file
- app files
- auto-generated files
- input/output filenames
- replication params
In other words, all the info you'd need to make a new variant.
- job submission page: if app doesn't have a logo, show its name
- in batch status page, show job status correctly,
and with colors that match progress bar
- In BUDA variant page
- fix bug in form checkboxes
> web (job submission): big fixes and enhancements

- tools/update_versions
Sometimes (not sure why) it's not.
> update_versions: don't require that API_VERSION is at start of string.

- html/inc/bootstrap.inc
- html/inc/buda.inc
- html/inc/keywords.inc
- html/user/buda.php
- html/user/show_apps.php
- html/user/submit.php
General goal: provide volunteers with more information about apps, in particular BUDA science apps.
Terminology: 'remote apps' are those for which jobs are submitted via web RPCs, or web forms, or both.
We use user-level permissions for these apps.
- If a project has remote apps, it must create a PHP file html/project/remote_apps.inc
that creates a data structure $remote_apps describing these apps. In the case of non-BUDA apps, these include
long name, description text, URL, and science keywords. (This replaces $web_apps, which was in project.inc)
- BUDA apps now have a JSON description file containing
- short and long names
- description
- science keywords
- URL of a page describing the app
- user ID of creator
- create time
- Added web interface for creating/editing the above
- A new …
> web: web-based job submission changes

- client/client_types.cpp
- client/client_types.h
- clientgui/ViewWork.cpp
- html/user/buda_submit.php
- lib/gui_rpc_client.h
- lib/gui_rpc_client_ops.cpp
- samples/docker_wrapper/docker_wrapper.cpp
- tools/backend_lib.cpp
- tools/create_work.cpp
- client: include resource_usage in  WORKUNIT::write()
- docker_wrapper: on Mac need to use full paths for mounts.
But on Win, full path includes :, which breaks the -v command!
So use . for current dir
- client: add sub_appname to WORKUNIT.
This is the BUDA app long name.
- create_work: add --sub_appname arg; adds it to the <workunit>
- buda_submit.php: pass --sub_appname to create_work
- Manager: if job has sub_appname, show it
- create_work: handle sub_appname correctly
>  Various BUDA-related bugs and enhancements

- configure.ac
- m4/ax_check_glut.m4
- m4/boinc_gtk.m4
- samples/nvcuda/common.mk
- samples/nvcuda/common_mac.mk
- tools/check_project
- tools/update_versions
- tools/update_versions_v6
The build process prints a couple of warnings like this:
`egrep: warning: egrep is obsolescent; using grep -E`
Since `egrep` is deprecated for many years it should be replaced by `grep -E`.
> Replace egrep

- html/inc/boinc_db.inc
- html/inc/bootstrap.inc
- html/inc/submit_util.inc
- html/user/buda.php
- html/user/buda_submit.php
- html/user/manage_app.php
- html/user/manage_project.php
- html/user/submit.php
- html/user/submit_example.php
- Clarify access-control semantics
if you have submit access to BUDA, you can submit jobs to any app/variant
if you have manage access to BUDA, you can edit/create/delete
apps and variants
if you have manage access to an app,
you can view/abort/retire batches for that app
(even if they belong to someone else)
- Divide BUDA functions accordingly;
management functions are under the 'Manage apps' navbar item,
submission functions are under 'Submit jobs'
Don't mix the two.
Note: users without manage permissions can see app/variant details
but they don't get the edit/add/remove controls
- Change the default 'Job submission' menu to show
'Manage apps' if use has any manage access
'Manage permissions' if user has manage_all access
(grant/revoke permissions to other users)
- When showing lists of …
> Various improvements to web-based job submission and app management

- html/user/buda_submit.php
The default max was 1 GFLOPS day, or 7 hours on a typical computer. Some apps need more.
> BUDA: add 'max runtime' param for job submission

- html/inc/boinc_db.inc
- html/user/buda_submit.php
- html/user/get_output2.php
- html/user/get_output3.php
- html/user/submit.php
- html/user/workunit.php
- anything that enumerates the WUs or results in a batch
should fetch only the fields it needs.
Otherwise PHP runs out of memory with big batches and large stderr output.
- Add missing piece for BUDA job submission
- get_output2.php and get_output3.php: add comments
Scripts should document their GET arguments.
- workunit.php
show WU command line
show links to input files
> web: job submission enhancements

- html/user/buda.php
This lets you have multiple CPU variants.
If anyone wants multiple variants of a GPU plan class, we'll have to do something else.
> BUDA: treat variants as CPU (not plan class) if 'cpu' is in variant name

- html/project.sample/project.inc
It was hyperlinking the entire row, not just the image. Not sure why.  Fixed it by removing CSS incantations.
To use this, projects will need to check out html/project.sample/project.inc,
then merge it with their own project.inc
(the only change is in project_footer())
Fixes #6294
> web: fix 'powered by BOINC' behavior in footer

- client/hostinfo_unix.cpp
Replace fix size with `sizeof(buf)` in `fgets()` calls.
Avoid compiler warning:
```
hostinfo_unix.cpp: In member function ‘bool HOST_INFO::get_docker_compose_version_aux(DOCKER_TYPE)’:
hostinfo_unix.cpp:1327:14: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
1327 |         fgets(buf, 256, f);
|         ~~~~~^~~~~~~~~~~~~
```
> Fix compiler warning and avoid magic number in function call

- html/inc/submit.inc
use property_exists() instead of array_key_exists() for objects
Fixes #6316
> RPC-based job submission: make it work with PHP 8

- html/inc/host.inc
> web: use 'cores' instead of 'processors'

- client/check_security.cpp
- client/file_names.h
- client/hostinfo_unix.cpp
- clientgui/mac/SetupSecurity.cpp
- lib/hostinfo.cpp
- lib/hostinfo.h
- lib/util.cpp
- mac_build/Finish_Install-Info.plist
- mac_build/Mac_SA_Secure.sh
Podman on Mac was failing because it tried to store data in .config/ in the user's home dir.
Podman runs as boinc_master (in the client)
and boinc_projects (in the wrapper)
and neither account has access to this dir.
To fix this, we'll have the installer create an accessable dir 'podman' in the BOINC data dir.
This change prepends an 'env' directive to Podman commands on Mac, telling it to use this dir.
Fixes #6302
> client and docker_wrapper (Mac/podman): set env vars to use accessable dir

- client/check_security.cpp
Fixes printing of permissions error number (mainly in BOINC Manager's stdoutdae.txt.)
> Mac: fix small typo in error message

- py/Boinc/database.py
Replaced the `print` statement with the `print()` function and added `from __future__ import print_function` to ensure compatibility with Python 2.
No alternate designs were necessary, as replacing `print` with `print()` is a straightforward solution to the problem.
Replaced deprecated print syntax in `py/Boinc/database.py` to ensure compatibility with Python 3 (and Python 2 if needed).
> Fix print statements in database module

- api/graphics2_win.cpp
- api/windows_opengl.cpp
- client/hostinfo_win.cpp
- samples/gfx_html/browserctrl_win.cpp
Standardized the CPUInfo initializer in hostinfo_win.cpp to use spaced commas for readability
Added spaces after commas in assembly helper call for clarity
Ensured variables declared together are spaced correctly
Updated several Win32 API calls in windows_opengl.cpp to follow comma-spacing conventions
Applied the same formatting fixes in graphics2_win.cpp and sample HTML graphics code to keep style consistent
> Fix spacing after commas in Windows source files

- client/hostinfo_win.cpp
Cleaned up inconsistent spacing so every “if” statement now follows the “if (condition)” style
Used Coding style notes:
1411          - every fopen() MUST have a matching fclose() in same function
1412          - every malloc() MUST have a matching free() in same function
1413          - don't do a rewind() right after fopen()
1414          - write function calls as
1415              func(arg1, arg2);
1416              NOTE: there's a space after every comma, everywhere
**1417          - write "if" statements as
1418              if (condition) {
1419                  ...
1420              }**
> style: standardize if spacing

- client/client_msgs.h
- client/hostinfo_linux.cpp
- lib/app_ipc.cpp
- lib/common_defs.h
- lib/coproc.h
- lib/miofile.h
- lib/opencl_boinc.h
- lib/proxy_info.h
- lib/str_util.h
- lib/util.cpp
- lib/win_util.cpp
- tests/unit-tests/lib/test_parse.cpp
- tests/unit-tests/lib/test_str_util.cpp
We need to be able to compile with libboinc and libboinc_api without needing config.h.
To do this: avoid having .h files include other .h files
(in particular, avoid chains of includes that lead to str_replace.h,
which is what needs config.h).
Fixes #6271
> library interfaces: remove dependency on config.h

- client/app_config.cpp
- client/client_state.cpp
- client/client_state.h
Resource usage is now stored in RESULT,
and is copied either from the workunit (for BUDA-type jobs) or from the app version (for other jobs).
This is done at startup; we also need to do it after rereading app_config.xml since the app version resource usage may have changed.
Fixes #6334
> client: make resource usages take effect after reread app_config.xml

- client/client_types.cpp
- client/client_types.h
Don't write resource usage to <workunit> if it's not there; otherwise the client will print spurious error messages
Fixes #6342
> client: remove spurious error messages about WU FLOPS

- api/boinc_api.cpp
> Make `strftime()` format string compatible with old libraries

- client/cs_scheduler.cpp
- lib/cc_config.cpp
- lib/cc_config.h
This is an experiment to see if calculating disk usage is causing client performance problems.
Related to #6332
> Add a config option <no_disk_usage/> that skips disk usage in sched requests

- sched/feeder.cpp
Do retries of failed jobs before new jobs
Fixes #6386
> feeder: default order is by priority, then by increasing WU create time

- sched/sample_assimilator.cpp
Fixes #6357  (already did the same thing as script assim)
> sample assimilator: rename rather than copy output files

- client/client_state.cpp
- client/cs_benchmark.cpp
- client/cs_statefile.cpp
- lib/Makefile.linux
Previous: we ran benchmarks only after attaching to a project.
> client: run benchmarks on startup if new install or upgrade

- client/app.cpp
- client/client_types.cpp
- client/client_types.h
- lib/procinfo.cpp
- lib/procinfo_unix.cpp
Win: count 'vmmem' (WSL process) as BOINC
Others: get Docker app CPU time from the apps themselves
Fixes #6398 (not tested on linux/mac)
> client: avoid erroneous 'suspended - non-BOINC CPU' when running Docker apps

- client/client_msgs.cpp
- client/client_state.cpp
- client/client_state.h
- client/cs_statefile.cpp
- client/current_version.cpp
- client/current_version.h
- client/hostinfo_wsl.cpp
- lib/wslinfo.cpp
- lib/wslinfo.h
Fixes #6407
- BOINC WSL distro has version number in /home/boinc/version.txt:
version: 1
- client version RPC includes current BOINC WSL distro version
- check at startup and after RPC; show notice with link to wiki page
> client: notify user if there's a newer BOINC WSL distro

- html/user/submit.php
- show completion (or abort) time in batch lists
- allow ordering of batch lists by asc/desc submit time or completion time
> web (job submission): enhancements

- lib/hostinfo.cpp
- samples/docker_wrapper/docker_wrapper.cpp
If no Docker type is specified in app_init_data.xml, write a message to stderr and exit(1).
Before we were trying to run 'unknown' as the Docker CLI program.
> docker_wrapper (Mac/Linux): show appropriate error message if Docker not present

- .github/workflows/linux.yml
- deploy/prepare_deployment.py
- linux/arm64/ci_configure_apps.sh
- linux/arm64/ci_configure_libs.sh
- linux/arm64/update_vcpkg_apps.sh
- linux/arm64/update_vcpkg_libs.sh
- samples/openclapp/Makefile
- samples/openclapp/Makefile_AMD
- samples/openclapp/Makefile_NVIDIA
Add arm64 linux with vcpkg
Fix #4782
> [linux][apps][arm64] Add arm64 linux with vcpkg

- html/inc/bootstrap.inc
- html/user/submit.php
> web (job submission): enumerate and order batches correctly

- client/check_security.cpp
- client/switcher.cpp
- clientgui/mac/templates/Finish_Install-Info.plist
- clientgui/mac/templates/PostInstall-Info.plist
- clientgui/mac/templates/ScreenSaver-Info.plist
- clientscr/Mac_Saver_Module.h
- clientscr/Mac_Saver_ModuleView.h
- clientscr/Mac_Saver_ModuleView.m
- clientscr/gfx_cleanup.mm
- clientscr/gfx_switcher.cpp
- clientscr/mac_saver_module.cpp
- clientscr/screensaver.cpp
- mac_build/boinc.xcodeproj/project.pbxproj
- mac_build/boinc.xcodeproj/xcshareddata/xcschemes/boinc_finish_install.xcscheme
- mac_installer/PostInstall.cpp
- mac_installer/finish_install.cpp
- mac_installer/release_boinc.sh
- mac_installer/release_brand.sh
This PR updates 2 aspects of BOINC screensaver logic for MacOS 25:
- The BOINC screensaver coordinator runs properly under the legacy screensaver engine
-  MacOS 14 and MacOS 15 broke the ability select a screensaver programmatically, so the BOINC installer cold no longer offer the option to set BOINC as your screensaver. MacOS 26 restores that capability, but using a different API. Changes in this PR implement that capability, again offering the user the option to set BOINC as their screensaver.
This code is backward compatible with earlier versions of MacOS, so it can be merged into all new releases of BOINC.
> MacOS 26 Screensaver fixes

- lib/coproc.cpp
Fixes #6472
With CUDA 12.0, Blackwell is treated under the same default 8.0 special case as the A100 Tensor Core datacenter GPU.
https://developer.nvidia.com/cuda-gpus
Instead of relying on a lookup table, we could measure it through benchmarking (like CPU apps), though that would be a more significant change.
Fixed estimated flops calculation for NVidia Blackwell
> update NVidia flops calculation for Blackwell

- html/inc/news.inc
A project (e.g. the BOINC test project) can somehow get in a state where it has multiple forums called 'News',
including bogus ones that aren't linked to a category. If a bogus one is first in the enumeration,
the client won't see any Notices from the project.
Fix: have news_forum() skip forums with no category.
> web: make sure News forum is valid

- html/user/get_output3.php
- html/user/submit.php
In the scheme for downloading output files, we were passing a path in a URL.
We checked for '..' but there may be other vulnerabilities.
Instead, pass the result ID and file index, which are ints.
Don't pass paths in URLs.
> web (job submission): make output file download more secure

- html/user/buda_submit.php
- html/user/submit.php
- It's implemented by passing --target_user to create_work in the job submission script. This was being done for autodock, but not BUDA.
- It's enforced in the scheduler, but only if <enable_assignment/> is set in config.xml. If the user tries to set 'only my computers' and this is not enabled, show an error page.
Also: don't use <li> without enclosing </ul>;
it produces ugly flush-left layout.
> web (job submission): 'only own computers' fixes

- samples/docker_wrapper/docker_wrapper.cpp
The Mac version of Podman doesn't parse quoted args correctly :-( I already fixed this a couple of other places;
hopefully this one is the last
> docker wrapper (Mac): escape space in arg to 'stats' command
